### PR TITLE
add blog post announcing HSTS for website

### PR DESCRIPTION
**Pull request by Trott**
@nodejs/build I don't think we *need* this blog post, but if we *want* to put it out there, please approve this PR and we'll get it posted. Thanks.

### CODE REVIEW

**Comment by rvagg** [comment]
haha, that quote .. ok

so I don't think we need this post, as per the quote, but will defer to others

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
My take is lets just do it versus re-discussing if we need it or not, it will probably be faster.

**Review by willin — APPROVED** [review]

**Comment by Trott** [comment]
HSTS has been enabled so I think this can be closed.

**Pull request closed without merging**
