### PR TITLE
feat: adjust styles to match figmas and moved icons as react components

### PR DESCRIPTION
**Pull request by ovflowd**
## Description

This PR moves all our new SVG icons as React Components so they become directly part of the bundle.

This PR adjusts several styles and fixes a few Storybooks to match some styles that were not correctly defined as per Figma.

Finally this PR isolates global styles (`a, h1, h2, table,...`) as they're only used within Markdown content to be behind a pseudo `.mdxContent` class name.

## Validation

Chromatic should look as close a possible; Storybook should build and work.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
@ovflowd this story had issue with styling 
Capture d’écran 2023-11-25 à 13 49 18

**Comment by ovflowd** [comment]
> @ovflowd this story had issue with styling Capture d’écran 2023-11-25 à 13 49 18

I know...

**Comment by AugustinMauroy** [comment]
is it on purpose?

**Comment by AugustinMauroy** [comment]
also avatarGroups/avatar story "no-square" should be update

**Comment by ovflowd** [comment]
> also avatarGroups/avatar story "no-square" should be update

Can you please stop commenting while I'm self-reviewing the PR? Thanks!

**Comment by ovflowd** [comment]
> is it on purpose?

Nope. That's why I made a PR, to let Chromatic analyse the divergences. You don't need to comment on the PR with the divergences, because Chromatic will already do that.

**Comment by ovflowd** [comment]
@AugustinMauroy now you can review ;)

**Review by canerakdas — APPROVED** [review]
LGTM ✨

**Review by AugustinMauroy — APPROVED** [review]
Perfect ✨
_**NOTE**: assets will no longer be served in public_

**Comment by bmuenzenmeyer** [comment]
> Perfect ✨
> _**NOTE**: assets will no longer be served in public_

I can see this leading to 404s with the org and elsewhere... Maybe that's by design

**Comment by ovflowd** [comment]
> > Perfect ✨
> > _**NOTE**: assets will no longer be served in public_
> 
> I can see this leading to 404s with the org and elsewhere... Maybe that's by design

These assets were never used anywhere to begin with.

**Comment by bmuenzenmeyer** [comment]
> > > Perfect ✨
> > > _**NOTE**: assets will no longer be served in public_
> > 
> > 
> > I can see this leading to 404s with the org and elsewhere... Maybe that's by design
> 
> These assets were never used anywhere to begin with.

404 on https://github.com/nodejs/help

perhaps that's an antipattern we want to stamp out.

**Comment by ovflowd** [comment]
> > > > Perfect ✨
> > > > _**NOTE**: assets will no longer be served in public_
> > > 
> > > 
> > > I can see this leading to 404s with the org and elsewhere... Maybe that's by design
> > 
> > 
> > These assets were never used anywhere to begin with.
> 
> 404 on [nodejs/help](https://github.com/nodejs/help)
> 
> perhaps that's an antipattern we want to stamp out.

Well, these were added by us on the repo for redesign. They shouldn't have been used to begin with... You can use these: https://github.com/nodejs/nodejs.org/blob/main/README.md?plain=1#L8-L10

**Pull request merged**
