### PR TITLE
add Chinese i18n file

### PR DESCRIPTION
**Pull request by PolarisSdesu**
## Description

Translated `en.json` to provide Chinese lang support.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
Please read [this file](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md) about our translation Policy. We handle translation with tools named Crowdin, not with PR.

but thank you for your interest in the project.

**Comment by AugustinMauroy** [comment]
@ovflowd didn't we have a workflow that takes care of putting a message when someone does manual translation?

**Comment by PolarisSdesu** [comment]
lmao, i'm sorry for that😂

**Comment by AugustinMauroy** [comment]
No problem ! can't wait to see you on the Crowdin 😁

**Pull request closed without merging**
