### PR TITLE
Improvement banner#5510

### PR DESCRIPTION
**Pull request by BahugunaSaumya**
A Fix to Improvement: Banner issue [#5510](https://github.com/nodejs/nodejs.org/issues/5510) 
mostly all the changes are committed but changes are as follows:-
Added a div to the react component and added a class called banner content to make the div centred and add the banner background to it.

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing, and/or `npx turbo test:snapshot` to update snapshots if I created and/or updated React Components.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by ovflowd** [comment]
Hey there 👋 I've just looked through your changes and the Banner still doesn't look as expected on Figma.

The button size, background, border and fonts are incorrect, the same as the text. Not to mention that (as I said) the banner for text content should have 100% of the page width and no top-margin.

Pretty much please check the Figma and images on the original issue :)

**Comment by BahugunaSaumya** [comment]
Hey Thank you for the feedback I wasn't sure about changing colours and fonts, as changing fonts and colours will require me to remove those settings from default i.e. remove all the constants "--var" defined, will that be okay?

Edit:-  Just saw in Figma developer mode predefined colours are provided with my bad I'll go ahead and fix that

Thankyou

**Comment by ovflowd** [comment]
The font-family and colours are the same. And all the colours are available within the code. I recommend giving a read to the source code, first. You can find the CSS colours on `tokens.scss` (Just see how other Storybooks and Components are done)

**Comment by BahugunaSaumya** [comment]
Thank you for the advice, I am doing that right now, I had a few questions 
1:- should I handle overflow in the button? if yes should I increase the button size with relevance to the text i.e keep the proportion but increase the size
2:- The size values in Figma even with default values look too small or out of proportion should I change that (and you can review) or should I keep Figma values as they are 
3:- There is not really any colour for the hover as this button in Figma is not interactable 
should I make the brand colour as is on the website(on hover)

I am sorry for so many questions, it is my first contribution.

**Pull request closed without merging**
