### PR TITLE
feat: provided some file structural changes

### PR DESCRIPTION
**Pull request by ovflowd**
## Description

This PR does some minimal changes meant to improve the build experience and reduce the performance costs.

- This PR moves the shared `helpers.mjs` into `next.helpers.mjs` as they're not exclusive to `next-data`
- This PR moves the `next-data/index.mjs` to just `next.data.mjs`
- This PR enables exclusion of some hefty modules, such as `swc` from the output tracing
- This PR removes isomorphic dompurify as to be honest, it is not needed as all Markdown Pre/HTML code comes from our Markdown Pages (DOMPurify also had a significant impact on the final bundle)
- This PR removes all languages besides JavaScript from the Highlight.js bundle as it was gigantic (the "common" language set was extensive and unnecessary)
  - `highlight.js` is going to be removed once we get rid of the legacy pages
- This PR does some minor optimisations with the Next.js configuration and the `Theme` Component by disabling unnecessary re-renders
- This PR updates some packages
- This PR adopts ESM for the Storybook Test Runner
- This PR simplifies the `precommit` hook by simply using `git checkout`
- This PR updates the build scripts removing the repeated `prebuild`

### CODE REVIEW

**Review by Harkunwar — APPROVED** [review]
LGTM!

**Comment by ovflowd** [comment]
cc @nodejs/website requesting fast-tracking here as some of these changes would benefit from being deployed soonish.

**Comment by bmuenzenmeyer** [comment]
Read through it too, look good. 

The sanitization is a bit concerning for long term consideration, in case remote markdown is ever used.

**Comment by ovflowd** [comment]
> The sanitization is a bit concerning for long term consideration, in case remote markdown is ever used.

@bmuenzenmeyer agreed. But to be fair, all the Components with manual unsafe injection of HTML will be removed once we migrate to the new Components.

But I would probably also avoid at all costs on actually using remote markdown, even tho we do use `MDXRemote` as a component.

**Comment by bmuenzenmeyer** [comment]
> But to be fair, all the Components with manual unsafe injection of HTML will be removed once we migrate to the new Components.

apologies, I feel as if I keep bringing up things the team has already thought through 😄

**Pull request merged**
