### PR TITLE
[Fix] Add missing localizations to locale/uk/

### PR DESCRIPTION
**Pull request by vsemozhetbyt**
Refs: https://github.com/nodejs/nodejs.org/pull/1737

### CODE REVIEW

**Comment by ghost** [comment]
Suggestions：
After modification, please run：
```
1）npm run build
2）npm run test
3）npm run start
```
Then go to `http://localhost:8080/uk` and you'll see what you want by clicking pages.

**Comment by vsemozhetbyt** [comment]
I've added more missing localizations.

**Comment by vsemozhetbyt** [comment]
`npm run build` throws:

<details>
<summary>Output:</summary>

```sh
npm run build

> nodejs.org@ build J:\temp\_git\-etc\nodejs.org-fork
> node build.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'metalsmith'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (J:\temp\_git\-etc\nodejs.org-fork\build.js:7:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs.org@ build: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejs.org@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vmb\AppData\Roaming\npm-cache\_logs\2018-07-15T11_57_14_085Z-debug.log
```
</details><br>

**Comment by vsemozhetbyt** [comment]
http://localhost:8080/uk seems OK.

**Comment by ghost** [comment]
There seems to be ONLY ONE left for you to translate in this file:
/locale/uk/download/index.md
default

**Comment by vsemozhetbyt** [comment]
I've added some more translations in the `/locale/uk/download/index.md`.

**Comment by ghost** [comment]
Thanks anyway!

**Pull request merged**
