### PR TITLE
zh-TW：Add missing translation for 'Collab Summit'

### PR DESCRIPTION
**Pull request by ghost**
Add this missing Traditional Chinese for 'Collab Summit'.

### CODE REVIEW

**Review by osk2 — COMMENTED** [review]
I'm thinking that if it's necessary to translate "Collab Summit". if so, then we'll need to translate words in `collab-summit.md` too.

**Comment by ghost** [comment]
`collab-summit.md` has been translated into zh-TW as：https://nodejs.org/zh-tw/get-involved/collab-summit/.

You see that we've translated once about "Collab Submmit" as "協作者峰會". And for the rest, there's no need to translate because they are fixed special pharses.

**Comment by osk2** [comment]
I mean the word "Collab Summit" :P

I left them untranslated in `collab-summit.md`. If we decide to translate them to "協作者峰會", we should also replace "Collab Summit" with "協作者峰會" in `collab-summit.md`.

**Review by osk2 — APPROVED** [review]
Nice, looks much better now 👍

**Pull request merged**
