### PR TITLE
fix: lang box radius

### PR DESCRIPTION
**Pull request by araujogui**
## Description

Fix Codebox's lang box border radius.

## Validation

Before:
image

After: 
image

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing, and/or `npx turbo test:snapshot` to update snapshots if I created and/or updated React Components.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by ovflowd — APPROVED** [review]
Very interesting solution!

**Review by mikeesto — APPROVED** [review]

**Comment by bmuenzenmeyer** [comment]
I was hoping to test this across a bunch of browsers, but the storybook deployment failed. Any idea why?

**Review by bmuenzenmeyer — APPROVED** [review]
✅ Chrome
✅ Firefox
✅ Edge
✅ Mobile Chrome

**Review by aymen94 — APPROVED** [review]

**Review by shanpriyan — APPROVED** [review]
LGTM!

**Pull request merged**
