### PR TITLE
Georgian translation for index page of about section

### PR DESCRIPTION
**Pull request by davidkadaria**

### CODE REVIEW

**Comment by davidkadaria** [comment]
Some of the Build tests failed because there is no core files of Georgian locale (I have already created pull request for them).

**Comment by davidkadaria** [comment]
@Trott This page is ready to be merged.

**Comment by Trott** [comment]
@nodejs/website Does anyone either read Georgian or know someone who does? I'll rubber-stamp this if I have to, but I'd rather have a competent review of course.

**Comment by davidkadaria** [comment]
@Trott I guess no one is going to discuss it. Maybe it's time to merge my translations?

**Review by Trott — APPROVED** [review]

**Pull request merged**
