### PR TITLE
Add guides to docs

### PR DESCRIPTION
**Pull request by lpinca**
This reproposes #313 with additional changes to make the guides work.

### CODE REVIEW

**Comment by matthewloring** [comment]
What is the current state of this PR? I'd love to get the guides page set up and would be happy to help if there's more work to be done here.

**Comment by lpinca** [comment]
It needs a review.

**Comment by fhemberger** [comment]
LGTM, sorry you had to wait. Merged.

**Comment by lpinca** [comment]
@fhemberger no problem.

**Pull request merged**
