### PR TITLE
Working Group page grammar and style fixes

### PR DESCRIPTION
**Pull request by ryanmurakami**
I noticed some inconsistencies in the Working Group page and thought it would benefit from a cleanup. The focus was on making the document feel like a cohesive whole and remove discrepencies of style and structure between each section.

Here are some of the changes I made. Feedback around any of these is appreciated!

- Changed all bulleted responsibilities to start with a gerund
- Changed all references of "Node" to "Node.js"
- Capitalized all instances of "Working Group"
- Changed all instances of "WG" to "Working Group"
- Updated markdown syntax for bulleted lists to be consistent
- Language consistencies across each group
- Various grammar fixes

### CODE REVIEW

**Review by lpinca — APPROVED** [review]

**Review by williamkapke — CHANGES_REQUESTED** [review]
I _REALLY_ like this polishing!! however, this page (as the comment in there says):

> Information here should mostly mirror: https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md

So, that document should be changed first and get approved/PRd. Any chance you're up for doing a PR to that doc?

**Comment by ryanmurakami** [comment]
@williamkapke Ah, thanks for mentioning that. Looks like there are two separate documents for top-level and core working groups. I'll make PR's for both and reference this PR in them. Thanks!

**Comment by ryanmurakami** [comment]
@williamkapke PR's complete. Also, updated the diagnostics section to match the core WG document. Looks like it actually was updated, but the site didn't stay in sync.

**Comment by ryanmurakami** [comment]
@williamkapke Both PR's for the other working group documents have been merged. You good with merging this PR?

**Review by williamkapke — APPROVED** [review]

**Pull request merged**
