### PR TITLE
Fix the id search

### PR DESCRIPTION
**Pull request by yorkie**
Open the console in https://nodejs.org/en/#

### CODE REVIEW

**Comment by lpinca** [comment]
👍

**Comment by lpinca** [comment]
Offending commit is https://github.com/nodejs/nodejs.org/commit/2747f511b18d321556e88d8d95a044bc070ea6a2.

**Comment by ghost** [comment]
yep, wasn't sure where else that id would appear. sorry.

**Comment by lpinca** [comment]
@tentakel no need to apologize, it happens, and reviewers did not have a chance to see it as it wasn't shown in the diff I guess.

**Comment by yorkie** [comment]
Never mind @tentakel not a big problem :-)

**Comment by yorkie** [comment]
By the way, what's the plan to make this online @lpinca ?

**Comment by lpinca** [comment]
@yorkie should be already in production.

**Pull request merged**
