### PR TITLE
Add a Node.js certification page

### PR DESCRIPTION
**Pull request by brianwarner**
A few folks noted that there are no links to the Node.js certification programs on the site. I'm opening this PR to begin a discussion as to whether having a new menu item is a good way to raise awareness about the certifications.

The content of the page is effectively identical to that of openjsf.org/certification, with a few style and language tweaks.

This is meant to be a starting point. If there's a better way to do this, please let me know and I'd be happy to make changes.

Signed-off-by: Brian Warner <brian@bdwarner.com>

### CODE REVIEW

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
@nodejs/tsc , @nodejs/community-committee FYI, this adds links to the certification program which I think should be on the website.

**Review by joesepi — APPROVED** [review]
LGTM. Thanks!

**Review by mcollina — APPROVED** [review]
lgtm

**Review by BridgeAR — APPROVED** [review]

**Review by BethGriggs — APPROVED** [review]

**Review by ahmadawais — APPROVED** [review]
LGTM

**Review by willin — APPROVED** [review]
LGTM

**Review by Aissaoui-Ahmed — APPROVED** [review]

**Review by osk2 — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by MylesBorins** [comment]
@brianwarner is there a reason to not make the link in the menu bar forward to the external cert page?

**Comment by brianwarner** [comment]
@mylesborins No particular reason, aside from maintaining consistency with the other items. If that makes more sense to folks, I can update it. It does make long term maintenance easier...

**Comment by MylesBorins** [comment]
@brianwarner I don't have strong feelings... but was thinking that forwarding would be better from a maintenance stand point and avoid the possibility of divergence

**Comment by bnb** [comment]
It would also reduce the eventual workload on the Website Redesign - instead of having to duplicate a page, we can include a link or some kind of banner / CTA on the Learn page.

**Comment by mhdawson** [comment]
@MylesBorins do you have any option to this landing and then Brian submitting a PR to update as you suggested? Just thinking it would be good to have the certification visible on the site sooner than later.

**Comment by brianwarner** [comment]
I'll update my branch and push a revision later this evening so you can see how it would look.

**Comment by brianwarner** [comment]
Ok folks, the separate cert page is removed, and now the menu item points to the upstream page on openjsf.org.

Also, merged in the latest changes from the current site to verify the new menu item doesn't create layout issues.

**Comment by MylesBorins** [comment]
@brianwarner we probably want to remove the new layout if we are only including the link correct?

Also, do we want to include it on any of the INTL landing pages?

**Comment by brianwarner** [comment]
Good call, just pushed.

I was wondering about other languages as well, as it would be good to include it on the landing pages for languages other than English. What is the usual practice for finding the right translation?

**Comment by MylesBorins** [comment]
@brianwarner sorry for being an it, but we likely want to remove the image from this PR as well, it isn't being used anywhere is it?

The locale folder has all the translations. you edited `locale/en/index.md`, you can find all the other languages in the `locale/` folder

**Review by mhdawson — APPROVED** [review]
LGTM again

**Comment by brianwarner** [comment]
No worries, thanks for catching the image. I'll remove it now.

On the translations, I guess my question was more about finding the right translation for the word "Certification". I can try Google Translate for each of the support languages, but I'm hesitant to lean too heavily on that being accurate... thoughts?

**Comment by nschonni** [comment]
Translations are (theoretically) handled on Crowdin once English content is pushed. It's up to the localization teams to suggest the translations over there

**Comment by brianwarner** [comment]
Thanks @nschonni, that is helpful to know.

**Pull request merged**
