### PR TITLE
ko: translate get-involved/index.md

### LINKED ISSUE #2251: 404 error with "Edit on Github" link on https://nodejs.org/ko/get-involved/
* **URL**: https://nodejs.org/ko/get-involved/
* **Browser version**: - 
* **Operating system**: -

"Edit on Github" throws 404 error page. it is linked to the page: https://github.com/nodejs/nodejs.org/edit/master/locale/ko/get-involved/index.md  

it looks like the url has to be modified. 
screenshot-nodejs

### PR DESCRIPTION
**Pull request by yous**
Fix #2251.

@nodejs/nodejs-ko: Review please.

### CODE REVIEW

**Review by marocchino — APPROVED** [review]

**Review by alexandrtovmach — CHANGES_REQUESTED** [review]
Could you remove all commented text, because it's unusable. Thanks

**Comment by yous** [comment]
@alexandrtovmach Comments are for translators. We can't track all changes under locale/en, so we diff the comments of locale/ko and locale/en. Then it's way easier to know what's out-of-date, and update translations.

**Comment by alexandrtovmach** [comment]
I see, okay let's merge it. Hope to make translation process easier soon.

**Review by alexandrtovmach — APPROVED** [review]

**Comment by yous** [comment]
Thank you!

**Pull request merged**
