### PR TITLE
nl：Add New Dutch Translations

### PR DESCRIPTION
**Pull request by hursittarcan**
## Description

Hey, I'm Hursit Tarcan. I'm an open-source developer and I'm willing to help translate the nodejs website in Dutch. I have a lot of experience in translating and I would love to make this website available in Dutch. I'm willing to translate the complete website if I'm allowed to do so. I already added a new folder with some files.

## Changes 
* Added new nl [dutch] folder to locale. 
* Added Dutch index.md.
* Added Dutch 404.md.
* Added Dutch site.json.

### CODE REVIEW

**Comment by ghost** [comment]
@nodejs/nodejs-nl ：Any help to this guy by reviewing his translations so as to merge it quickly？

@hursittarcan：Thank you for your 1st contribution to the translation of Nodejs doc.

**Comment by Trott** [comment]
@nodejs/website Is anyone able to review this? Or should I rubber-stamp it and deploy it?

**Review by davidkadaria — COMMENTED** [review]
Looks good to me.

**Comment by hursittarcan** [comment]
Hey @Trott, I understand you guys need a review, especially for a stranger's first PR. I'm not sure if you guys have Dutch translators in the team, but I can assure you it's a legit translation. I'm willing to help translate the complete page to Dutch if I'm allowed to. 

I have degrees in many languages and work on open-source translating and developing in my spare time (I'm still a student developer). 

Here is a link to my Crowdin profile: https://crowdin.com/profile/tarcanhursit

**Review by Trott — APPROVED** [review]

**Comment by Trott** [comment]
@hursittarcan Is it OK if I add you to the @nodejs/nodejs-nl team so that folks can ping you in the event that we want a review for Dutch translations submitted by others?

**Comment by hursittarcan** [comment]
@Trott yes you can add me to the team 👍

**Comment by AdriVanHoudt** [comment]
Just to give you a heads up, @nodejs/nodejs-nl is an old (in times of when it was set up) team.
If I recall correctly we kinda stopped doing translations in Dutch as it is a massive effort with not enough people and most (if not all) Dutch speaking people will end up using the EN version regardless.
But I'm glad someone is willing to do some translations 💪 , it def can't hurt :P
I know I'm a bit late but the translations LGTM

**Pull request merged**
