### PR TITLE
Add GitHub issue template

### PR DESCRIPTION
**Pull request by fhemberger**
As general questions about Node.js and issues regarding the API docs often land here instead, I created a GitHub issue template based on the template in `nodejs/node`.

### CODE REVIEW

**Comment by hiroppy** [comment]
LGTM 👍

**Comment by lpinca** [comment]
LGTM.

**Comment by lpinca** [comment]
Maybe add something like "Steps to reproduce the issue"?

**Comment by fhemberger** [comment]
@lpinca Added field "URL" instead. I guess there aren't many cases where there are multiple steps necessary to re-create an issue.

**Comment by lpinca** [comment]
Yeah it makes sense.

**Comment by mikeal** [comment]
I'm a little troubled by this template. Do we have a problem with bad issues that we're trying to solve? I can't recall a ton of erroneous issues we've had to deal with and I don't know if it's worth putting up a barrier to entry to solve a concern we don't have.

**Comment by ghost** [comment]
@mikeal if it helps users to find the right repo to open an issue in, therefore reducing unnecessary noise, i'd say it's justified

**Comment by fhemberger** [comment]
I don't see it as a barrier: You still can totally ignore the template content and post your stuff anyway. I took the general wording from node core.

We had some tickets in the past that were doc issues or general questions unrelated to the website. That's why I added links to both repositories, to help people find the right spot for their questions (which IMHO is better than closing tickets with "wrong repo" right away).

Affected URL and browser also helps us to reproduce issues – again, this is totally optional.

**Comment by mikeal** [comment]
> You still can totally ignore the template content and post your stuff anyway.

_I_ can certainly do that (and do often) but new users, especially people new to contributing to Node.js i any way, will read all of this and try to tailor their comment to it and if they can't fit it into the box of the template they will probably just not log an issue at all.

At the very least I think that we can cut this way down.

**Comment by fhemberger** [comment]
The main idea was to point people to the right place, if it's not about the website and they followed the link by accident (e.g instead of reporting an issue with Node instead).

If you have an idea for a better, more approachable template text, please go ahead! This was just a first draft.

**Pull request merged**
