### PR TITLE
ci: only run linting on Ubuntu

### PR DESCRIPTION
**Pull request by nschonni**
The linting tools like ESLint are well tested for cross-platform issues, so it doesn't really need to be run in a matrix build.

### CODE REVIEW

**Comment by tniessen** [comment]
Following that argument, is there a reason for the `build` job to run on more than one platform?

**Comment by ovflowd** [comment]
+1 we probably could limit the build to Ubuntu only. I doubt we would face x-platform issues by running a framework tested to work on many platforms (we don't use anything fancy/custom). We could maybe make the windows build only for the `main` branch or run on a schedule (like daily on `main`) just to ensure that we might not occasionally break people doing builds on Windows.

**Review by manishprivet — APPROVED** [review]

**Comment by ovflowd** [comment]
@nschonni would you like to make the build step ubuntu-only?

**Review by AugustinMauroy — APPROVED** [review]
Not bad I find it simpler

**Review by rodion-arr — APPROVED** [review]

**Comment by nschonni** [comment]
> @nschonni would you like to make the build step ubuntu-only?

I'm pretty confident that this change isn't going to miss anything, but I've got now idea if that's the case for the site build, so I think someone else can do that

**Comment by ovflowd** [comment]
Alright, merging the PR as it is then 🙃

**Comment by bnb** [comment]
+1 for lint, -1 for test if that were a thing to come up in the future.

Specifically, it's good to ensure that it still works on Windows so people who use the website as an entry point to contributing are not facing additional issues if they're on Windows.

**Comment by ovflowd** [comment]
> Specifically, it's good to ensure that it still works on Windows so people who use the website as an entry point to contributing are not facing additional issues if they're on Windows.

That makes sense. The test job is separated from the lining one, so that should not affect us here. (Testing jobs are only available on branch `major/website-redesign`) for now, as the branch introduces unit testing.

**Pull request merged**
