### PR TITLE
fix: main download button for linux incorrect

### LINKED ISSUE #5610: Big green download button on nodejs.org from Linux/x64 gives source archive
### URL:

https://nodejs.org

### Browser Name:

Firefox

### Browser Version:

101.0

### Operating System:

Fedora Silverblue 37

### How to reproduce the issue:

Go to nodejs.org and try to click the download button for 18 or 20. The URLs point to the source archive e.g. https://nodejs.org/dist/v18.17.0/node-v18.17.0.tar.gz at present, instead of the node-v18.17.0-linux-x64.tar.xz build that I would expect. From the screnshot you can see that it has correctly detected what platform I'm using.

image

### PR DESCRIPTION
**Pull request by sxa**
## Description

Fixes https://github.com/nodejs/nodejs.org/issues/5610 - the download button for Linux on the front page of the website links to the source tar archive, not the built node.js for that platform as it should.

## Validation

Main download link is for the binary, not the source, when connecting from a Linux web browser.

### Check List

- [ ] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing, and/or `npx turbo test:snapshot` to update snapshots if I created and/or updated React Components.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by ovflowd — APPROVED** [review]
Looks legit to me :) (Feel free to test on the Deployment Preview URL)

**Comment by sxa** [comment]
Preview looks good. Note that this is currently hard coded to provide the Linux/x64 download when a Linux web browser is detected, however this is consistent with the label displayed above the buttons which will always display (X64) for the architecture as per https://github.com/nodejs/nodejs.org/blob/562ed48c4c4f1fe6921a1327bff795f0b0a2eced/layouts/IndexLayout.tsx#L17

The architecture detection would require more work so this should be considered a first phase of the solution.

**Comment by ovflowd** [comment]
> The architecture detection would require more work so this should be considered a first phase of the solution.

Yeah, we have plans of better arch detection, the main reason it is the way it is is because in the past only these 3 platforms were considered. On the redesigns we're aiming for a broader range.

**Comment by ovflowd** [comment]
I'm fast-tracking this due to the nature of being a super simple change.

**Pull request merged**
