### PR TITLE
meta: enable french translations

### PR DESCRIPTION
**Pull request by ovflowd**
Let's see what happens when we enable the French language :)

### CODE REVIEW

**Review by AugustinMauroy — APPROVED** [review]
Woooooowwww

**Comment by ovflowd** [comment]
Well, it gives Error 5XX

**Comment by AugustinMauroy** [comment]
I had push hot fix on this pr. That same issue that transparent bg for header/footer

**before:**

Capture d’écran 2024-03-05 à 16 38 27

**After:**

Capture d’écran 2024-03-05 à 16 40 19

**Comment by ovflowd** [comment]
> I had push hot fix on this pr. That same issue that transparent bg for header/footer
> 
> **before:**
> 
> Capture d’écran 2024-03-05 à 16 38 27
> **After:**
> 
> Capture d’écran 2024-03-05 à 16 40 19

Please make this in another PR, not this one.

**Comment by AugustinMauroy** [comment]
> Please make this in another PR, not this one.

Ok.
 I had done this to reduce the number of pr. And that it's activating another language that creates this.
 Sorry ;)

**Comment by ovflowd** [comment]
> > Please make this in another PR, not this one.
> 
> Ok. I had done this to reduce the number of pr. And that it's activating another language that creates this. Sorry ;)

It's just unrelated hehe, all good!

**Comment by ovflowd** [comment]
Closing for now due to Crowdin issues.

**Pull request closed without merging**
