### PR TITLE
Sync: merge `major/website-redesign` into `main`

### PR DESCRIPTION
**Pull request by ovflowd**
This will keep the branch synced and reduce the amount of merge conflicts from going-on as it's always good to sync the base branch and feature branch from time-to-time.

This PR does not affect on anything and the Website should still work 100% as it is on current infra. These changes also have 0 effect on the current layout of the website.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
One problem with this is crowdin, we will start translating `react-intl` translation key. So I thinks we should put crowdin on pause.

**Comment by ovflowd** [comment]
> One problem with this is crowdin, we will start translating react-intl translation key. So I thinks we should put crowdin on pause.

Why? It's completely fine for translators to start translating the translation keys. That's intended.

**Comment by AugustinMauroy** [comment]
If it's not a problem let's go

**Comment by ovflowd** [comment]
Since this PR contains only already reviewed and merged codebase, I'm proceeding with the merge.

cc @nodejs/website

**Pull request merged**
