### PR TITLE
doc: change some URLs from 'http' to https'

### PR DESCRIPTION
**Pull request by ghost**
There're some URLs that starts with 'https', change them together.

1. http://c-ares.haxx.se/docs.html => https://c-ares.haxx.se/docs.html.
2. http://ibm.biz/ibmi-rpms => https://ibm.biz/ibmi-rpms.

### CODE REVIEW

**Review by XhmikosR — APPROVED** [review]
There are a lot more but we'll be able to fix them later when we have automated testing in place :)

**Review by celyes — APPROVED** [review]
LGTM
thank you for your contribution.

**Comment by rokaslit6** [comment]
@XhmikosR would you be so kind to share anything on how to automate the change from http to https throughout the whole website? Redirects are annoying..

**Comment by XhmikosR** [comment]
@rokaslit6 I'm not done yet, I still need to first have a working patch for 404 pages.

I just need to figure out a way to make the check not take 2 hours, and it's not easy so far :P

**Pull request merged**
