### PR TITLE
Added NodeConf Argentina to the events list

### PR DESCRIPTION
**Pull request by glennschler**
There is no pull script for conferences, so manually updated the markdown.

@bevacqua @a0viedo I hope it's ok to add your event.

### CODE REVIEW

**Comment by bevacqua** [comment]
Most definitely. Thanks!

**Comment by ghost** [comment]
LGTM! thanks for contributing!

**Comment by gaboesquivel** [comment]
👍

**Comment by a0viedo** [comment]
@glennschler thanks! Actually none of the events taking place in Latin America were added to the site. Also we should change the description since our friends at Sao Paulo are organising the first of latam :)

**Comment by glennschler** [comment]
Oh, I copied description from NodeConfAr page. Both should be changed.

For Meetups and Nodeschool events, pull scripts exist to parse and add to
this list. If those are not working, there should be a new issue, instead
of manually editing.

**Comment by glennschler** [comment]
I should have created an issue first to initiate the discussing on the proper NodeConfAr description, before submitting my pull request. So now the new issue to add the [Sao Paulo NodeConf](https://github.com/nodeconf/brazil) event

**Pull request merged**
