### PR TITLE
Add meta doc summarizing dependencies

### PR DESCRIPTION
**Pull request by Qard**
Note: This is part of the migration of content files from https://github.com/nodejs/docs, see: https://github.com/nodejs/docs/issues/44

This doc explains the high-level purpose of the various dependencies and provides links to documentation for each.

### CODE REVIEW

**Comment by Qard** [comment]
@nodejs/documentation @nodejs/website Can I get a LGTM, just for good measure? :)

**Comment by phillipj** [comment]
Should it be linked to from the docs section right away?

**Comment by fhemberger** [comment]
Now we have PRs for adding pages as docs, meta docs, guides, topics and knowledge base. This is confusing for the users (at least it is for me now). I think having less categories (and/or a clearer structure) would be a better approach.

Otherwise LGTM.

**Comment by Qard** [comment]
The intent is for there to be separate sections for different types of docs: reference, guides, topics and meta (which is about developing node itself). This was what the Docs WG had decided on back at NodeConf. Do you feel differently? We're always open to feedback. :smiley_cat:

**Comment by fhemberger** [comment]
Sorry, didn't get the Docs WG memo. Is there a doc/issue on this topic you can point me to? It's hard to trace back decisions that were made at a conference. :wink:

How is this related to the Knowledge Base discussed in #211? I know this is content originally coming from Nodejitsu, but as a new user coming to the website I would probably have a hard time to decide what the difference between "Knowledge Base", "Guides" and "Topics" is.

**Comment by Qard** [comment]
The original idea is mapped out in the trello board linked in https://github.com/nodejs/docs/issues/1.

**Comment by Qard** [comment]
As for the Knowledge Base stuff, that hasn't really been discussed yet, but I agree that it overlaps a lot. I suspect the articles from it might get divided up into our topics and guides sections eventually.

**Comment by fhemberger** [comment]
@Qard Thanks for the link!

**Comment by fhemberger** [comment]
@Qard I'd like to merge this. Can someone please add a link to the website? @bnb offered to take care of this (https://github.com/nodejs/new.nodejs.org/pull/254#issuecomment-149642697).

**Comment by bnb** [comment]
@fhemberger I'll do it. Just add the link in the other issue?

**Comment by Qard** [comment]
It should be fine to just merge this and leave linking to it to another PR.

**Pull request merged**
