### PR TITLE
fix: add redirection from /dist to /dist/

### PR DESCRIPTION
**Pull request by UlisesGascon**
## Description

This is a simple redirection from `/dist` to `/dist/`.

## Related Issues

Full context in https://github.com/nodejs/docker-node/issues/1945. 

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [ ] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [ ] I have run `npx turbo format` to ensure the code follows the style guide.
- [ ] I have run `npx turbo test` to check if all tests are passing, and/or `npx turbo test:snapshot` to update snapshots if I created and/or updated React Components.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by targos — CHANGES_REQUESTED** [review]
I changed the CF rule's regex to remove the trailing slash:

image


https://dash.cloudflare.com/07be8d2fbc940503ca1be344714cb0d1/nodejs.org/rules/origin-rules/2b2bcc23b9e143dfa3c10164d89465e9

**Comment by ovflowd** [comment]
@targos I assume Caching Rules also need to be updated then? https://dash.cloudflare.com/07be8d2fbc940503ca1be344714cb0d1/nodejs.org/caching/cache-rules

**Comment by targos** [comment]
@ovflowd Updated as well.

**Comment by ovflowd** [comment]
@targos also this rule https://dash.cloudflare.com/07be8d2fbc940503ca1be344714cb0d1/nodejs.org/caching/cache-rules/fc349b6ef0c64f2db0474a5fe418bd26 I assume?

**Comment by targos** [comment]
aaaargh, done :D

**Comment by UlisesGascon** [comment]
thanks @targos and @ovflowd! I will close this PR then :)

**Pull request closed without merging**
