### PR TITLE
add webinar to top of page

### PR DESCRIPTION
**Pull request by gtewallace**
we are holding a webinar July 12 and would like to add description and registration link to the top of the page. Pretty sure I got everything right and certainly appreciate a review.

thank you.

### CODE REVIEW

**Review by MylesBorins — APPROVED** [review]
LGTM

**Comment by fhemberger** [comment]
@gtewallace Please don't forget to remove the link again, once the webinar is over. Thx.

**Comment by gtewallace** [comment]
@fhemberger  I'll put a reminder in my calendar now. ty

**Comment by gtewallace** [comment]
@fhemberger  In looking at the addition, I think it could use a header like ## Join our upcoming webinar. I feel confident I can make this change without breaking anything. OK with you if I go ahead and do it?  lmk and thanks again

**Comment by fhemberger** [comment]
@gtewallace Sure.

**Pull request merged**
