### PR TITLE
updated scroll-to-top button

### PR DESCRIPTION
**Pull request by emirgoren**
### Updating scroll-to-top button

> It looked very old and when using Google Chrome it completely stuck to the right side, creating an ugly image.

**Before**
image

**After**
image

### CODE REVIEW

**Comment by emirgoren** [comment]
To see images, create a new page and paste the url. GitHub is not sending you to another url.

**Comment by ghost** [comment]
> To see images, create a new page and paste the url. GitHub is not sending you to another url.



> To see images, create a new page and paste the url. GitHub is not sending you to another url.

In fact you can directly paste the img by either "Ctrl+C" or directly dragging and dropping into the GitHub's comment dialog.
Thank you for your 1st contribution to it.

**Comment by emirgoren** [comment]
> > To see images, create a new page and paste the url. GitHub is not sending you to another url.
> 
> > To see images, create a new page and paste the url. GitHub is not sending you to another url.
> 
> In fact you can directly paste the img by either "Ctrl+C" or directly dragging and dropping into the GitHub's comment dialog. Thank you for your 1st contribution to it.

That hurts haha. Thank you for your edits by the way!

**Comment by ghost** [comment]
@emirgoren: IMO：Maybe you can just take the green color of the image, and then make then original one into the green color instead of nesting an image as a handler？

**Comment by ovflowd** [comment]
I'm not sure we really need a Node.js logo on the scroll to top button 🤔

**Comment by emirgoren** [comment]
> I'm not sure we really need a Node.js logo on the scroll to top button 🤔

And now I'm thinking it was odd.
Screenshot at Dec 14 00-30-08

@ovflowd @MaledongGit

**Review by ghost — APPROVED** [review]
> > I'm not sure we really need a Node.js logo on the scroll to top button 🤔
> 
> And now I'm thinking it was odd. Screenshot at Dec 14 00-30-08
> 
> @ovflowd @MaledongGit

LGTM. 

IMO：It's just a tag, no need to make it too big or with a sign.

**Comment by ghost** [comment]
@emirgoren ：I wonder why you say "It's a bit odd without a sign?"
I just want to know your idea about your design :)

**Pull request merged**
