### PR TITLE
chore: Add date range for banner expiry

### PR DESCRIPTION
**Pull request by nschonni**
Didn't add any GitHub Action to support this, as the `.org` would need a cron on the build server since the deployment is done by webhook there right now

### CODE REVIEW

**Review by Trott — APPROVED** [review]

**Comment by Trott** [comment]
> Didn't add any GitHub Action to support this, as the `.org` would need a cron on the build server since the deployment is done by webhook there right now

It will at least remove the banner when something else lands, rather than requiring a specific PR to remove it.

Might be a bit kludgy...er, ambitious, but I suppose we could add a scheduled GitHub Action that opens a PR when the banner is expired, and maybe even lands it too.

**Comment by nschonni** [comment]
Think there is an issue around moving from the webhook to GitHub Actions for the deploy, but not sure how much work is involved in changing that. If that happens, the cron GitHub Action should be doable

**Review by ghost — COMMENTED** [review]
Feel great

**Review by ghost — APPROVED** [review]

**Review by lancemccluskey — APPROVED** [review]
Thanks for adding this in! I know my approvals dont count, but here ya go lol

**Comment by ghost** [comment]
@nodejs/translators: Here comes a new improvement——We can now localize our own banner.

**Pull request merged**
