### PR TITLE
code typo fix

### PR DESCRIPTION
**Pull request by Olympicene**
added missing comma to myOptions object value

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
Have you looked at the translated files? (There are other folders containing the same file)

<sup>edited by @ovflowd</sup>

**Comment by ovflowd** [comment]
> Have you looked at the translated files?

This has nothing to do with translations.

**Comment by AugustinMauroy** [comment]
> This has nothing to do with translations.

My comment is about if the error is in other file

**Comment by ovflowd** [comment]
> My comment is about if the error is in other file

What error? There's no error.

**Comment by ovflowd** [comment]
I think I got what you meant, if you're talking about the knowledgebase in other translations, there are 4 translations with knowledgebase, and yes, they could check those.

**Comment by AugustinMauroy** [comment]
> What error? There's no error.

It's not an error but a missing comma. And I just say that you have to be careful if the comma is not missing in other languages.

**Review by ItaloPussi — CHANGES_REQUESTED** [review]
After checking other locales, I found out that `FR` and `PT-BR` has the same mistake in the same file. Could you fix it to centralize these corrections in this pull request?

**Comment by Olympicene** [comment]
Got it. Added missing commas to `FR` and `PT-BR`.

**Review by ItaloPussi — APPROVED** [review]
Looks OK to me :)

**Review by ItaloPussi — APPROVED** [review]
Looks OK to me :)

**Review by AugustinMauroy — APPROVED** [review]
Thanks for your first contribution!!!!

**Review by shanpriyan — APPROVED** [review]
LGTM. Thanks!

**Review by aymen94 — APPROVED** [review]

**Comment by nschonni** [comment]
Thanks for the fix. Closing because https://github.com/nodejs/nodejs.org/pull/4999 was landed and removed these files

**Pull request closed without merging**
