### PR TITLE
update: Remove node-speakers

### PR DESCRIPTION
**Pull request by Trott**
The node-speakers page is problematic for several reasons. Remove it.

### CODE REVIEW

**Review by Aissaoui-Ahmed — APPROVED** [review]

**Comment by Aissaoui-Ahmed** [comment]
it's working !

**Comment by ghost** [comment]
@Trott：Why? Do you mean we don't need to translate this topic and its content?

**Comment by Trott** [comment]
> @Trott：Why? Do you mean we don't need to translate this topic and its content?

I mean the page is one that can and should be removed from the website. It is not well-maintained. Speakers are not vetted. Listing here implies endorsement by the project and/or foundation but neither of those things are true. There's no reason to believe that this list of speakers contains only the best speakers. There's no reason for us to even have a list of speakers. It's one more piece of content that is not well-curated and thus damages the credibility of the website.

**Review by ZYSzys — APPROVED** [review]

**Comment by ZYSzys** [comment]
Maybe /cc @ladyleet who added this originally. Are you ok if we remove this from our website ?

**Review by aymen94 — APPROVED** [review]

**Review by WaleedAshraf — COMMENTED** [review]
LGTM, but I'd still like @ladyleet review on this. I'm not sure what was the main purpose and benefit of this list.
There is this listing also: https://foundation.nodejs.org/news/speakers-bureau

**Comment by aymen94** [comment]
I don't see any usefulness, @ladyleet what do you think?

**Comment by ghost** [comment]
@Trott：Sorry but there are some conflicts meeting me, and I cannot help to solve... :(
image

**Comment by Trott** [comment]
> @Trott：Sorry but there are some conflicts meeting me, and I cannot help to solve... :(


@MaledongGit Resolved.

**Comment by bnb** [comment]
>Speakers are not vetted. 

@Trott For context, this was a Node.js Foundation effort to build a speaker's bureau that was entirely maintained by the foundation. AFAIK Zibby Keaton did a lot of work on this but I could be mistaken.

**Comment by WaleedAshraf** [comment]
@bnb but that still exists here https://foundation.nodejs.org/news/speakers-bureau
I'm not sure how this was different from that?

**Pull request merged**
