### PR TITLE
chore: reorder real-time chat spaces by seniority

### PR DESCRIPTION
**Pull request by mmarchini**
Reordering real-time chat spaces list by when they were created/added to
the list. Also pulled Node Slackers to real-time chat lists and added a
note to both Slacks mentioning WG channels.

### CODE REVIEW

**Comment by mmarchini** [comment]
cc @nodejs/tsc @nodejs/community-committee @ljharb @joepie91

**Review by MylesBorins — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
lgtm

**Review by BethGriggs — APPROVED** [review]

**Review by ljharb — COMMENTED** [review]
LGTM <sub>(not approving since it'd incorrectly show up as green)</sub>

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by 3imed-jaberi — APPROVED** [review]
lgtm

**Review by codebytere — APPROVED** [review]

**Pull request merged**
