### PR TITLE
doc: Fix for some statements

### PR DESCRIPTION
**Pull request by ghost**
1. 'trace-gc' can be also 'trace_gc'. However if you see 'node
   --v8-options' the standard should be '--trace-gc', and this is the
   fix to make them in union.
2. 'flags' isn't timestamps but additional information about GC (Refs: https://github.com/nodejs/nodejs.org/pull/4775)

### CODE REVIEW

**Comment by ghost** [comment]
@tony-go and @RafaelGSS ：There're things not right in the doc and here's the fix, hope you can have a review of them :)

**Review by ovflowd — APPROVED** [review]

**Review by tony-go — APPROVED** [review]
Thanks a lot, @MaledongGit - I saw your comment a few days ago, and I planned to open a PR today, but I was busy before that. Thanks again 🙌

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Comment by ghost** [comment]
Thanks to all of you here.

**Comment by MaledongGit** [comment]
Thank you all!

**Pull request merged**
