### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by piperchester**

### CODE REVIEW

**Comment by lpinca** [comment]
Not a native speaker but I think the original is also ok?
Anyway I'm fine with the change.

**Comment by ryanmurakami** [comment]
The original was not correct grammatically, but using a semi colon instead just makes the sentence kind of difficult to read. Maybe a transition word like 'and' could be added to make it smoother?

**Comment by piperchester** [comment]
Reading it over, I feel like even a period would be best for flow. Thoughts?

**Comment by ryanmurakami** [comment]
@piperchester Yeah, I think that would be better.

**Comment by piperchester** [comment]
@ryanmurakami made the change 😄

**Review by lpinca — APPROVED** [review]

**Comment by ryanmurakami** [comment]
@piperchester Awesome! Thanks!

**Pull request merged**
