### PR TITLE
chore(i18n): add Mongolian locale in config

### PR DESCRIPTION
**Pull request by zolbooo**
Hi there! 👋

## Description

Added Mongolian (mn) locale in i18n config.

## Validation

Git diff shows changes in `i18n/config.json`

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by zolbooo** [comment]
Hey guys, is it possible to get this PR merged anytime soon?

**Comment by AugustinMauroy** [comment]
Unfortunately not. Because crowdin has an MDX parsing problem, the whole translation process is blocked until a solution is found.

**Comment by avivkeller** [comment]
> Unfortunately not. Because crowdin has an MDX parsing problem, the whole translation process is blocked until a solution is found.

Just curiuos, where is this parsing issue occuring, are there any docs on a planned fix, I'd love to see where the magic is happening :-)

**Comment by ovflowd** [comment]
> > Unfortunately not. Because crowdin has an MDX parsing problem, the whole translation process is blocked until a solution is found.
> 
> 
> 
> Just curiuos, where is this parsing issue occuring, are there any docs on a planned fix, I'd love to see where the magic is happening :-)

The parsing happens on the Crowdin platform. The issue is that their current MDX parser doesn't support correctly (or doesn't preserve) existing styles/formatting rules. So there's no much to see as it "happens behind the scenes"

We are already in contact with Crowdin and they are working on a solution. I asked them yesterday for an update and they are on the final stages of releasing the fix, which is awesome!

Appreciate the ping, Ive forgot to update folks on the matter in a while 😄

**Comment by avivkeller** [comment]
Great! Thanks for the info!

**Review by bmuenzenmeyer — APPROVED** [review]
This is now unblocked!
Alphabetized this by `code` , as it was conflicting.

**Comment by bmuenzenmeyer** [comment]
added in crowdin

**Pull request merged**
