### PR TITLE
Add weekly posts from 21st August to 4th September.

### PR DESCRIPTION
**Pull request by yosuke-furukawa**
We have 3 weekly updates.
If these updates don't have problems, please merge.

### CODE REVIEW

**Comment by rvagg** [comment]
@mikeal @fhemberger what are your thoughts on giving one or more people on @nodejs/evangelism commit rights to this repo so they can post updates without having to wait for a website team member? They have a great process in place for review and collection already and it'd be great to have these be more timely.

**Comment by fhemberger** [comment]
Yes, please! :100: (@bnb and @snostorm and already have, adding @yosuke-furukawa – anyone else?)

**Comment by mikeal** [comment]
This week we should round up all the contributions and onboard a ton of new committers, including people that have been contributing blog posts.

**Comment by yosuke-furukawa** [comment]
@fhemberger Thank you. currently, it is OK. If I would like to add any other member, I will ask you.

**Pull request merged**
