### PR TITLE
foundation: update sauce logo

### PR DESCRIPTION
**Pull request by MylesBorins**
Closes: https://github.com/nodejs/nodejs.org/issues/750

Logo is kind of blury though :s

edit: hold off on landing this until we verify this is the best quality logo we can get

### CODE REVIEW

**Comment by lpinca** [comment]
Can you optimize it with zopflipng? See #746.
@PeterDaveHello can you share the flags used there?

**Comment by lpinca** [comment]
Can we find a better logo? As you said in #750 the quality is pretty bad.

**Comment by lpinca** [comment]
This is better https://saucelabs.com/home/++theme++saucelabs_new/static/images/logo-mark-red.png but has no text :/

**Comment by gtewallace** [comment]
I'll ask for a higher res version - stand by - and thanks

**Comment by gtewallace** [comment]
from Sauce Labs: "There's a ton of padding so please trim to the appropriate size."

thanks again all!

[020101_LOGO_Sauce-Labs_Vert_Red-Grey_RGB.zip](https://github.com/nodejs/nodejs.org/files/271310/020101_LOGO_Sauce-Labs_Vert_Red-Grey_RGB.zip)

**Comment by PeterDaveHello** [comment]
@lpinca sure, see this:

```
zopflipng --keepchunks=iCCP --iterations=500 --lossy_transparent -m filename.png filaneme.png
```

**Comment by lpinca** [comment]
@PeterDaveHello Thank you.

@TheAlphaNerd I see you have updated the pr with the new logo. I've also created a png from that ai but also cropped the image, compressed it and used a slightly bigger resolution.

Here it is:

saucelabslogo3

If you want to go with you version please use this compressed version:

saucelabslogo

**Comment by MylesBorins** [comment]
@lpinca @lpinca I went with the smaller one to save some bytes... thanks

**Comment by MylesBorins** [comment]
@nodejs/website can we get some LGTM's on this :smile:

**Comment by lpinca** [comment]
Maybe it can be cropped but LGTM.

**Comment by ghost** [comment]
LGTM!

**Comment by gtewallace** [comment]
LGR8TM

**Pull request merged**
