### PR TITLE
remove FAQ

### PR DESCRIPTION
**Pull request by Trott**
Fixes: https://github.com/nodejs/nodejs.org/issues/1249

### CODE REVIEW

**Comment by lpinca** [comment]
It should also be removed from other locales.

**Comment by sotayamashita** [comment]
@lpinca I will create a pull request for other locales FAQ so please merge it.

**Comment by lpinca** [comment]
@sotayamashita we should see if there is consensus for this. I'm fine with removing the FAQ but I would like to know what other collaborators think.

**Review by fhemberger — APPROVED** [review]

**Comment by fhemberger** [comment]
LGTM, let's remove it.

**Pull request merged**
