### PR TITLE
explain the lts naming scheme

### PR DESCRIPTION
**Pull request by Fishrock123**
s/simple/actual description/ :)

cc @jasnell & @nodejs/website

### CODE REVIEW

**Comment by phillipj** [comment]
LGTM

**Comment by jasnell** [comment]
Picky picky picky...:-) LGTM

**Comment by csabapalfi** [comment]
LGTM. Merging now that 2 owners and 2 collaborators saw it. :)

**Comment by mikeal** [comment]
Is there a good document that describes LTS and the difference between v4 and v5?

**Comment by narqo** [comment]
@mikeal I believe nodejs/LTS#44 is the right place from where such document should appear.

BTW, if anyone interested, for me personally, [this article by @rvagg](https://nodesource.com/blog/essential-steps-long-term-support-for-nodejs) is an example of what this document should describe.

**Comment by zeke** [comment]
aside: https://www.npmjs.com/package/periodic-table

**Pull request merged**
