### PR TITLE
Translate knowledge/other-resources into portuguese (pt-br)

### PR DESCRIPTION
**Pull request by ftonato**
Hello,

I have finished the `knowledge/other-resources` section, can you validate and approve this one?

/cc @nodejs/nodejs-pt
/cco @glaucia86 @khaosdoctor

### CODE REVIEW

**Review by TiagoDanin — APPROVED** [review]

**Review by khaosdoctor — APPROVED** [review]

**Comment by khaosdoctor** [comment]
LGTM 👍 

cc: @Maledong @Trott @fhemberger @MylesBorins

**Review by glaucia86 — APPROVED** [review]
LGTM 👍 
Thanks for your contribution @ftonato

**Comment by fhemberger** [comment]
Please also see #2278

**Comment by ghost** [comment]
@ftonato：This doesn't need translating. So if you don't have other suggestions, I'll close it?

**Comment by khaosdoctor** [comment]
@fhemberger yeah I think this is a bit outdated. +1 for closing this PR and marking it as completed

**Pull request closed without merging**
