### PR TITLE
Guide: Anatomy of an http…: Echo Server

### PR DESCRIPTION
**Pull request by bneevan**
Towards [#1480](https://github.com/nodejs/nodejs.org/issues/1480)

Changes:
* Updated GET to POST method… in echo server code and related comments.
* Guide versions of `en` and `uk` - changes at 4 places.
* Guide version of `ko` - changes at 8 places (including 4 commented `en` code used for reference).

### CODE REVIEW

**Review by lpinca — APPROVED** [review]
A GET request can have a body but yes, using POST makes more sense.

**Comment by bneevan** [comment]
@lpinca, thanks for that insight. I didn't know about GET requests having a body being valid. `curl` command allowed creating such a GET request and the Echo server did echo 😊.

Did some more search and found [this interesting comment](https://groups.yahoo.com/neo/groups/rest-discuss/conversations/messages/9962) from Roy Fielding on GET requests:

> any HTTP request message is allowed to contain a message body, and thus must parse messages with that in mind. Server semantics for GET, however, are restricted such that a body, if any, has no semantic meaning to the request. The requirements on parsing are separate from the requirements on method semantics.
>
>So, yes, you can send a body with GET, and no, it is never useful to do so.

[https://groups.yahoo.com/neo/groups/rest-discuss/conversations/messages/9962](https://groups.yahoo.com/neo/groups/rest-discuss/conversations/messages/9962)

**Comment by bneevan** [comment]
Sorry, closed it accidentally.

**Comment by lpinca** [comment]
@bneevan thank you!

**Pull request merged**
