### PR TITLE
Feature / Improve Spanish Translation

### PR DESCRIPTION
**Pull request by JoseJPR**
The main tasks:

1. Update severals texts into the "Home" section.
2. Update severals texts into the subsections "About Node.js", "Project Governance", "Resources", "Releases" and "Trademark Policy" of the "About" section.
3. Creation of the subsections "Community Committee", "Working Groups" and "Privacy Policy" into the "About" section.
4. Update options of main menu website.

### CODE REVIEW

**Comment by nschonni** [comment]
Ping @nodejs/nodejs-es

**Comment by JoseJPR** [comment]
@alexandrtovmach, do you think it is better to close this pull request? I can rewrite these translations into Crowdin. If you think it is the best way, I will do it. :)

**Comment by alexandrtovmach** [comment]
@JoseJPR Huh, I'm not sure that's easy, so let's merge. But please do all new translations on Crowdin side

**Comment by alexandrtovmach** [comment]
@nodejs/nodejs-es Please take a look on this PR

**Comment by alexandrtovmach** [comment]
@nodejs/nodejs-es any chance?

**Review by alexandrtovmach — APPROVED** [review]

**Comment by alexandrtovmach** [comment]
@JoseJPR Thanks for contribution. Please do all next translations through Crowdin

**Comment by JoseJPR** [comment]
Thanks @alexandrtovmach, the following are already for Crowdin! Thanks for the support. :)

**Pull request merged**
