### PR TITLE
chore(site): update website badge + banner

### PR DESCRIPTION
**Pull request by AugustinMauroy**
## Description

Add badge for next-10
Fix banner type

### Check List

- [X] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [X] I have run `npm run format` to ensure the code follows the style guide.
- [X] I have run `npm run test` to check if all tests are passing.
- [X] I have run `npx turbo build` to check if the website builds without errors.

### CODE REVIEW

**Comment by MattIPv4** [comment]
> Add badge for next-10

The badge still seems to be the collab blog?

**Comment by AugustinMauroy** [comment]
@MattIPv4 fails with git 😅

**Comment by MattIPv4** [comment]
Your force push still hasn't changed the link?

**Comment by AugustinMauroy** [comment]
Now it's good 😄
Pff there are times when you do everything backwards

**Review by MattIPv4 — APPROVED** [review]

**Review by richardlau — APPROVED** [review]

**Review by sheplu — APPROVED** [review]
LGTM

**Comment by ovflowd** [comment]
image

I don't think the average user will understand what this badge means.

I'd suggest changing to something like this:

image

**Comment by richardlau** [comment]
They're not results, the link goes to the live survey form. Agree though that maybe the wording could be improved for those less familiar with the project.

**Comment by ovflowd** [comment]
Oh gotcha! WDYT?

image

**Comment by richardlau** [comment]
> Oh gotcha! WDYT?
> 
> image

+1

**Review by aymen94 — APPROVED** [review]

**Review by canerakdas — APPROVED** [review]

**Review by richardlau — APPROVED** [review]

**Pull request merged**
