### PR TITLE
main.js: consistency changes

### PR DESCRIPTION
**Pull request by XhmikosR**
Later, we should enforce const/let properly. This patch just streamlines the code with what we are currently using.

### CODE REVIEW

**Comment by KenG-pro** [comment]
Thanks hope things work out

**Review by aymen94 — APPROVED** [review]

**Comment by Trott** [comment]
@XhmikosR Do you want to rebase so this can be landed?

**Comment by XhmikosR** [comment]
I'm not sure this PR makes sense anymore... I mean, I see pretty modern features being used like `??` which contradicts with the browsers in .browserslistrc.

**Comment by aymen94** [comment]
@XhmikosR I think not make sense.

**Comment by XhmikosR** [comment]
Either way, .browserslistrc should be updated and `var` should be removed.

**Comment by aymen94** [comment]
@XhmikosR yes, we can update it by making a new PR.

**Pull request closed without merging**
