### PR TITLE
chore(next/link): do not use link for external links

### PR DESCRIPTION
**Pull request by ovflowd**
This PR removes `next/link` from external links as it has no advantage here. It also messes up with event listeners for "dynamically" changed URLs from the `legacyMain` script.

### CODE REVIEW

**Comment by ovflowd** [comment]
@MaledongGit, this fixes your "async/defer" change. Your change would "work" because the `legacyMain` script would be called **after** Next.js made its initial render and changes on the `next/link` with its custom event listeners. The solution is not to use `next/link` on dynamically changed URLs + external URLs.

Also, a note that in the future the `legacyMain` script will be removed.

**Comment by ghost** [comment]
> @MaledongGit, this fixes your "async/defer" change. Your change would "work" because the `legacyMain` script would be called **after** Next.js made its initial render and changes on the `next/link` with its custom event listeners. The solution is not to use `next/link` on dynamically changed URLs + external URLs.
> 
> Also, a note that in the future the `legacyMain` script will be removed.

Thanks! That's what I did yesterday later and since you're going to submit this PR, I've closed mine.
It seems you got my point, and actually yours is the best way here.

I just found "async/defer" and noticed the custom event linsters' orders and that's why I changed to "async" / "defer"   XD XD XD.

**Comment by ghost** [comment]
There're some conflicts on your PR, and I've helped to change them together.

**Comment by ovflowd** [comment]
> Thanks! That's what I did yesterday later and since you're going to submit this PR, I've closed mine.
It seems you got my point, and actually yours is the best way here.

No worries, there's no such thing as best or worst point here, you did what you believed would solve the issue, but you were almost there :)

**Comment by ovflowd** [comment]
> There're some conflicts on your PR, and I've helped to change them together.

Thanks! Could you also review/approve the PR?

**Review by ghost — APPROVED** [review]

**Pull request merged**
