### PR TITLE
build.js: don't copy `site.json` files in the output dir

### LINKED ISSUE #2617: Stop outputting site.json in the build dir
It seems currently each locale's site.json file is output in the build dir. For example https://nodejs.org/en/site.json

Is this intentional? If not we should ignore them.

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #2617

Preview: <https://dazzling-minsky-3c0d14.netlify.com/en/>

### CODE REVIEW

**Comment by XhmikosR** [comment]
Can someone confirm that the json files are not needed on the live site?

**Comment by Aissaoui-Ahmed** [comment]
when change language news (blog) not redirect to EN

**Comment by Aissaoui-Ahmed** [comment]
NEWS link on other languages not rending blog(EN)

**Comment by XhmikosR** [comment]
Where is that code? AFAICT everything is built on build time. I added a live Preview with this patch: https://dazzling-minsky-3c0d14.netlify.com/en/

Give it some time to go live

**Comment by XhmikosR** [comment]
Also, note that this only removes site.json from the build dir, not the source dir.

**Review by Aissaoui-Ahmed — APPROVED** [review]
confirmed ! not necessary file site.json in Build dir

**Pull request merged**
