### PR TITLE
Blog: v22.0.0 release post

### PR DESCRIPTION
**Pull request by RafaelGSS**
Refs: https://github.com/nodejs/node/pull/52505

### CODE REVIEW

**Review by marco-ippolito — APPROVED** [review]

**Comment by ovflowd** [comment]
🎉

**Comment by ovflowd** [comment]
FYI @RafaelGSS should we add a badge on the home page?

**Comment by ovflowd** [comment]
(https://github.com/nodejs/nodejs.org/blob/main/site.json#L38-L46)

**Comment by RafaelGSS** [comment]
> FYI @RafaelGSS should we add a badge on the home page?

I think we should do it for https://github.com/nodejs/nodejs.org/pull/6661

**Review by anonrig — APPROVED** [review]

**Review by richardlau — APPROVED** [review]

**Pull request merged**
