### PR TITLE
Update language consistency in About

### PR DESCRIPTION
**Pull request by Fishrock123**
Updated to follow https://github.com/nodejs/docs/blob/master/STYLE-GUIDE.md a bit more, and also add consistency that this is a "javascript runtime" not a "framework" (which doesn't make much sense). This brings more consistency with the main page.

Also adds links to some our excellent new Blocking and Event Loop topic docs.

**ATTENTION**: I am also testing the bot (per usual lol) and so please don't merge it right away. :)

### CODE REVIEW

**Comment by fhemberger** [comment]
LGTM, this can land as soon as you're done testing the bot. ;)

**Comment by phillipj** [comment]
@Fishrock123 could you push an update here? https://github.com/nodejs-github-bot/github-bot/pull/21 has been deployed for testing

**Comment by Fishrock123** [comment]
Updated, fixed some formatting things I noticed when actually testing it myself.

@phillipj The status updated instantly to pass, I think It used the original CI run?

**Comment by Fishrock123** [comment]
>  about 18 hours ago

yup, looks like the run hadn't started up yet and it saw the old one. :S

**Comment by Fishrock123** [comment]
Hmm looks like this run is working correctly.

**Comment by phillipj** [comment]
@Fishrock123 a new commit would be awesome. The bot has been deployed which checks the committed date as well as sha/PR.. *fingers crossed*

**Comment by Fishrock123** [comment]
Looks like it's working here still.

**Comment by phillipj** [comment]
@Fishrock123 thanks! I'm tempted to say we've got a polling and statuses up and running now, meaning this test PR could be closed, agreed?

**Comment by Fishrock123** [comment]
Seems like it. Merging.

**Pull request merged**
