### PR TITLE
Remove code+learn

### PR DESCRIPTION
**Pull request by HassanBahati**
This is in reference to #4874 . @nschonni @Trott kindly review.

- [x] Remove all links to [https://nodejs.org/en/get-involved/code-and-learn/ ](https://nodejs.org/en/get-involved/code-and-learn/)
- [x] Remove `code-and-learn.md` file from all translations

### CODE REVIEW

**Review by nschonni — APPROVED** [review]
LGTM, I'm pretty sure that the side bar is generated off those JSON files, so this should do it

**Comment by Trott** [comment]
This looks good to me. Thinking about this more, though, I wonder if the thing to do is to remove it from the navigation (the `.json` files here) but leave the `.md` file so that people reaching it from elsewhere still get the content? Otherwise, we'd probably want to figure out a redirect.

**Comment by nschonni** [comment]
Some of the other stuff I think needed a redirect, but since this appears to be a list of old conference/meetup events that hasn't been updated since 2019 I think it's OK. If someone really wants to see it, they're probably OK to check it out on Archive.org

**Comment by HassanBahati** [comment]
> 

@nschonni @Trott does this mean we should put back the `.md` files and only maintain removal from the `.json` files ?

**Review by AugustinMauroy — APPROVED** [review]
LGTM

**Pull request merged**
