### PR TITLE
Update fedora

### PR DESCRIPTION
**Pull request by kasicka**
Update guidelines for installing from Fedora repositories

### CODE REVIEW

**Comment by jbergstroem** [comment]
We have a testing gap for fedora25 in CI and still support fedora22 (which probs should be dropped) -- not sure how to handle this but otherwise LGTM.

**Comment by kasicka** [comment]
I thought that was more about what is available from Fedora repositories, which is responsibility of Fedora packagers.

**Comment by jbergstroem** [comment]
Upon reading the full page, the responsibility is pushed back to package maintainers but the word "supported" is ambiguous. Anyway, don't let me hold up progress.

**Comment by fhemberger** [comment]
@kasicka @jbergstroem Sorry for the long delay: Can this be merged? If the range of supported versions/platforms is managed by the Fedora package maintainers, should we remove the list entirely?

**Comment by fhemberger** [comment]
Merging this now … if the supported Fedora version range changes (or should be removed entirely), please open a new PR.

**Pull request merged**
