### PR TITLE
Feature/UI small improvements

### PR DESCRIPTION
**Pull request by thomscoder**
On big screens there is a portion of the screen which is empty. The small UI improvement was to center the content on big monitors. (margin or paddings of the writings can be changed to better fit the space)
Issue: Immagine 2021-11-11 173530
Link: [nodejs.org/](url)
UI change: Immagine 2021-11-11 174818

### CODE REVIEW

**Review by humble-barnacle001 — CHANGES_REQUESTED** [review]
@thomscoder

- [x] Add a newline in `layouts/css/layout/_main.scss` on line 13
- In `layouts/css/page-modules/_home.scss`
  - [x] on line 194 correct tab/spaces indentation issue
  - [x] on line 205, add a new line

Always run `npm run test` before committing so that tests may pass

**Comment by thomscoder** [comment]
> @thomscoder
> 
> * [x]  Add a newline in `layouts/css/layout/_main.scss` on line 13
> * In `layouts/css/page-modules/_home.scss`
>   
>   * [x]  on line 194 correct tab/spaces indentation issue
>   * [x]  on line 205, add a new line
> 
> Always run `npm run test` before committing so that tests may pass

thank you very much for your help. Fixing right away

**Comment by jonymusky** [comment]
Hi @thomscoder can you explain how a `max-width: 780px` is affecting bigger screens?

**Comment by thomscoder** [comment]
> Hi @thomscoder can you explain how a `max-width: 780px` is affecting bigger screens?

that media query was for vertical displays iirc. it's max-width && min-height

**Review by benhalverson — APPROVED** [review]

**Review by aymen94 — APPROVED** [review]

**Comment by thomscoder** [comment]
Thanks, I will resolve conflicts and update the pr

**Review by jonymusky — APPROVED** [review]
LGTM

**Review by WaleedAshraf — COMMENTED** [review]
Is it possible to have this CSS in one common place and be used in both areas?

**Comment by thomscoder** [comment]
> Is it possible to have this CSS in one common place and be used in both areas?

should I unify the files?

**Review by AugustinMauroy — APPROVED** [review]

**Comment by WaleedAshraf** [comment]
> > Is it possible to have this CSS in one common place and be used in both areas?
> 
> should I unify the files?

I think yes. So it stays consistent in both places.

**Review by aymen94 — APPROVED** [review]

**Comment by ovflowd** [comment]
I'm closing this PR as the current layout will soon be abandoned. Thank you anyway for your contribution!

**Pull request closed without merging**
