### PR TITLE
fix: remove privacy page

### PR DESCRIPTION
**Pull request by Trott**
The privacy policy for the OpenJS Foundation is linked in the footer.
We do not need to maintain a separate privacy page.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by nschonni** [comment]
/Is it worth doing a redirect in the build repo?

**Comment by ovflowd** [comment]
> The privacy policy for the OpenJS Foundation is linked in the footer.
We do not need to maintain a separate privacy page.

Should we do the same for nodejs.dev?

**Comment by Trott** [comment]
> /Is it worth doing a redirect in the build repo?

Ideally, yes!

**Comment by Trott** [comment]
> Should we do the same for nodejs.dev?

I would say yes.

**Comment by nschonni** [comment]
Think the redirects go in https://github.com/nodejs/build/blob/bfdea82300d635fcac681656885d7b7736ee62a3/ansible/www-standalone/resources/config/nodejs.org, although that page seems to confuse the GitHub previewer 😆

**Pull request merged**
