### PR TITLE
CI: Orama cloud sync

### PR DESCRIPTION
**Pull request by canerakdas**
## Description

With this PR, we aim to solve the Orama cloud sync issue mentioned in #6719 

## Related Issues

Related to #6719

### CODE REVIEW

**Comment by ovflowd** [comment]
Is it still a WIP?

**Comment by ovflowd** [comment]
@canerakdas can you make the changes to the GitHub Action Workflow on a separate PR so I can merge it first?

**Comment by canerakdas** [comment]
> Is it still a WIP?

The [last build](https://github.com/nodejs/nodejs.org/actions/runs/9354034372/job/25745929053?pr=6806) failed, so I marked it as WIP. I'm trying to understand the problem 🤔 

> @canerakdas can you make the changes to the GitHub Action Workflow on a separate PR so I can merge it first?

Sure, I will open it as a separate PR after solving this problem 👍

**Comment by ovflowd** [comment]
> > Is it still a WIP?
> 
> 
> 
> The [last build](https://github.com/nodejs/nodejs.org/actions/runs/9354034372/job/25745929053?pr=6806) failed, so I marked it as WIP. I'm trying to understand the problem 🤔 
> 
> 
> 
> > @canerakdas can you make the changes to the GitHub Action Workflow on a separate PR so I can merge it first?
> 
> 
> 
> Sure, I will open it as a separate PR after solving this problem 👍 

After solving what problem? You know changes to the workflow only take effect after merging.

So Imo the workflow change should fix this, but we can only test that after you merge the workflow changes 😅

**Comment by canerakdas** [comment]
> After solving what problem? You know changes to the workflow only take effect after merging.
> 
> So Imo the workflow change should fix this, but we can only test that after you merge the workflow changes 😅

Updated :smile: I'd better get some rest, I'm starting to see non-existent issues 👻

**Review by ovflowd — APPROVED** [review]

**Comment by ovflowd** [comment]
Fast-tracking this to see if it fixes the upload!

**Pull request merged**
