### PR TITLE
Use the same style for all links

### LINKED ISSUE #652: UI - Lines appear on top of the commit links on hover in the release notes
It's a minor issue, but I'm pretty sure you'd want to underline the link instead when I hover over it.

The below image shows the line when hovering over the first link.
screen shot 2016-04-15 at 10 10 45 am

Screenshot taken here: https://nodejs.org/en/blog/release/v4.3.1/

### PR DESCRIPTION
**Pull request by lpinca**
Fixes #652.

As usual here are some screenshots (Firefox):

screen shot 2016-04-21 at 12 08 39
screen shot 2016-04-21 at 12 07 54

screen shot 2016-04-21 at 12 08 18
screen shot 2016-04-21 at 12 07 15

### CODE REVIEW

**Comment by fhemberger** [comment]
Can you please drop the colons and semi-colons in Stylus? Otherwise, LGTM. 👍

**Comment by lpinca** [comment]
WOPS, sure on my way.

**Comment by lpinca** [comment]
Done.

**Comment by fhemberger** [comment]
Great, thanks!

**Pull request merged**
