### PR TITLE
fix: Removed misleading info

### LINKED ISSUE #6853: Misleading debugging information: "Node.js and the Chrome need to be run on the same platform"
### URL:

https://nodejs.org/en/learn/getting-started/debugging

### Browser Name:

Chrome

### Browser Version:

126.0.6478.62

### Operating System:

Windows

### How to reproduce the issue:

Screenshot 2024-06-20 154224

Since when has this been the case?!

The requirement that Node.js and Chrome need to be run on the same platform is not accurate in the context of debugging. Cross-platform debugging using Chrome DevTools is a standard practice and works seamlessly due to the underlying network and WebSocket protocols that facilitate communication between Node.js and DevTools. The documentation should ideally clarify this to avoid confusion.

I have no idea why this was added in the first place...
https://github.com/nodejs/nodejs.org/commit/15774e7744da60bb418aa1ee14f5d88b7b9cda1e

### PR DESCRIPTION
**Pull request by Wellitsabhi**
## Description

Removed the misleading info as mentioned in issue #6853 

## Validation

image

## Related Issues

Fixes: #6853 

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by TenzDelek** [comment]
@Wellitsabhi   I think reverting the changes directly from the merged PR page will be a better choice for clarity and consistency rather than merging a new PR with a manual revert might create unnecessary changes.

**Comment by Wellitsabhi** [comment]
I agree but I don't have access to perform reverts, also @ovflowd might have put some thought before allowing to raise PR.

**Comment by bmuenzenmeyer** [comment]
I don't follow why this approach would be bad.  Don't worry about it. Clean git history is overrated. 

That said,  we're not meeting anything until monorepo conversion stabilizes.

**Comment by TenzDelek** [comment]
> I don't follow why this approach would be bad. Don't worry about it. Clean git history is overrated.
> 
> That said, we're not meeting anything until monorepo conversion stabilizes.

Can't agree more on this, :)

**Comment by bmuenzenmeyer** [comment]
This PR will need to be rebased or recreated now that https://github.com/nodejs/nodejs.org/pull/6850 merged.

**Comment by Wellitsabhi** [comment]
I really don't understand how it got closed, i shall be adding new PR again.

**Comment by Wellitsabhi** [comment]
@bmuenzenmeyer  i recreated this PR as #6924 
and would like to request review on it.

**Pull request closed without merging**
