### PR TITLE
add Google as a node.js foundation member

### PR DESCRIPTION
**Pull request by JustinBeckwith**

### CODE REVIEW

**Comment by ghost** [comment]
[Travis build passed](https://travis-ci.org/nodejs/nodejs.org/builds/120234257) :+1:

**Comment by jasnell** [comment]
Since it's specifically Google Cloud Platform (https://cloud.google.com/) that joined, is the general google logo the one they want displayed? /cc @mikeal

**Comment by JustinBeckwith** [comment]
I don't want to give the impression this is a cloud-only thing at Google - right now it's a joint effort between us and the v8/blink folks.  I'd very much prefer to use the general Google logo :)

**Comment by jasnell** [comment]
Yeah, I definitely get that :-) just need to double check that we've got the proper permissions to use this particular logo :-)

**Comment by lpinca** [comment]
:+1:

**Comment by fhemberger** [comment]
@JustinBeckwith Can you please use ImageAlpha/ImageOptim to reduce the file size of the logo? (This would roughly save 75% of the file's size). Also, for easier merging it would be cool if you could add a desktop size/mobile size screenshot of the logo cluster afterwards, just to be sure the layout doesn't break.

@jasnell Can you please give a :+1: if we're good to use the logo?

**Comment by JustinBeckwith** [comment]
No problem!  Here's the screenshots:

Desktop:

image

Mobile: 

image

**Comment by jasnell** [comment]
I don't have the info to say whether we're good to use it or not. ping @mikeal

**Comment by fhemberger** [comment]
@JustinBeckwith Great, thank you. As soon as we have green light for the logo, this change can be merged.

**Comment by Knighton910** [comment]
LGTM 👍

**Comment by JustinBeckwith** [comment]
Thanks!

**Pull request merged**
