### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by nodejs-crowdin-zz**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Err, this adds untranslated pages too...

**Comment by alexandrtovmach** [comment]
@XhmikosR Yep, that's expected result. English language is like a fallback

**Review by alexandrtovmach — APPROVED** [review]

**Comment by alexandrtovmach** [comment]
Seems like CI/CD can't handle this PR =(
Let's merge it, because it's blocking me with configuration process

**Comment by XhmikosR** [comment]
It's quite redundant because in production the English pages will be used
anyway. This is so much bloat.

**Comment by alexandrtovmach** [comment]
After this PR, please also take a look https://github.com/nodejs/nodejs.org/pull/3052

**Comment by nschonni** [comment]
Is there an option not to copy the file till a translation is made? as @XhmikosR we cleaned out the old english copies of files from the locale folders because they nginx rules redirect to the english version if the translation is missing

**Comment by alexandrtovmach** [comment]
@XhmikosR It's not just a question about build, it's also about localization process and comfortable way for translators.
Just to make sure that everything is clear, we wouldn't translate website through GitHub in a near future, so you'll never open `locale` directory.

**Comment by alexandrtovmach** [comment]
It's a main problem of translation strategy, if we decide to not pull content until it's fully translated, we will never translate the website =/
1. In open source world really hard to find teams that going to translate everything completely. Somebody started, somebody corrected, somebody added, somebody completed, and in that way we will wait for `index.md` a month. But if we going with proposed strategy, we can have at least partially translated content as soon as it's done.
2. Another case: I've fully translated `index.md`, it's published and everyone happy to see this page live in Russian (for example). Then, in english version changed one line, and with your way we need hide the whole page, instead of one line, because it's not completely translated

**Review by alexandrtovmach — CHANGES_REQUESTED** [review]
NOT READY TO MERGE!

**Comment by Aissaoui-Ahmed** [comment]
Problem on CI/CD is limit  [Job matrix - A job matrix can generate a maximum of 256 jobs per workflow run. This limit also applies to self-hosted runners.](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions)

**Comment by XhmikosR** [comment]
IMHO this should **not** land. It's useless and bloat.

The build process generates the English fallbacks in production. Adding 2.5 million lines will make development super slow.

**Review by XhmikosR — CHANGES_REQUESTED** [review]
Too much bloat

**Comment by alexandrtovmach** [comment]
Closed to remove /blog directory

**Comment by alexandrtovmach** [comment]
> Adding 2.5 million lines will make development super slow.

@XhmikosR Could you explain why?

**Comment by alexandrtovmach** [comment]
@XhmikosR Please read this https://github.com/nodejs/nodejs.org/pull/3050#issuecomment-606853490, and let me know about your alternatives for strategy

**Comment by XhmikosR** [comment]
What's there to explain? The site is built and adding so many lines will literally make this take more than 2 minutes which is a no go for development.

**Comment by alexandrtovmach** [comment]
@XhmikosR As I said, it's not a build issue, it's more about localization process. We can't avoid this for localization, so probably we need to think about optimization of our build (crazy idea, but why not).

**Comment by alexandrtovmach** [comment]
For example, we can improve build scripts to use only English content for development, or give possibility to provide a list of locales to build

**Comment by XhmikosR** [comment]
>We can't avoid this for localization, so probably we need to think about optimization of our build (crazy idea, but why not).

I don't see why we can't avoid it. As far as I can tell, we can definitely avoid this kind of bloat.

**Comment by alexandrtovmach** [comment]
@XhmikosR Did you check this https://github.com/nodejs/nodejs.org/pull/3050#issuecomment-606853490 ? We can't avoid it

**Comment by XhmikosR** [comment]
Well, that's not a viable solution for me, sorry.

**Pull request closed without merging**
