### PR TITLE
nodejs-zh-CN: Add files - site.json, index.md, 404.md and a part of download/ .

### PR DESCRIPTION
**Pull request by laosb**
If I didn't finish the whole site, should I submit all files in `en/`? Or the site will deal with the fallback?

If it does, I will remove all untranslated files for now.

Any way, it's just a beginning. I didn't see any controls on the website for switching language.

@nodejs/iojs-cn

### CODE REVIEW

**Comment by fhemberger** [comment]
@laosb No, there is no automatic fallback to `en`. Also there isn't a language switch yet, because besides the Korean index page, there wasn't anything to switch to. :smile:

**Comment by laosb** [comment]
@fhemberger So that means we will have a switch after we have a complete translation? 

Waiting for +1s :smiley:

**Comment by fhemberger** [comment]
@nodejs/iojs-cn Can you please review this?

**Comment by laosb** [comment]
Seems that GitHub didn't redirect nodejs/iojs-cn to nodejs/nodejs-cn.

Waiting for reviews. @nodejs/nodejs-cn

**Comment by stevemao** [comment]
@laosb it redirects from nodejs/iojs-cn to nodejs/nodejs-zh-CN

**Comment by laosb** [comment]
@stevemao Aha, I'm talking about **teams**, not **repos**.

Repo: nodejs/iojs-cn -> nodejs/nodejs-zh-CN

Team: nodejs/iojs-cn -> nodejs/nodejs-cn

**Comment by fengmk2** [comment]
zh-CN and zh-TW are different. Why I can't see any tanslation?

**Comment by lzxb** [comment]
全是英文的，中文的路过

**Comment by laosb** [comment]
@fengmk2 It might because I submitted all files including many untranslated ones. `site.json`, `index.md`, `404.md` and a part of `download/` was translated. Sorry for the inconvenience.

**Comment by zanjs** [comment]
小学生路过

**Comment by laosb** [comment]
Because there are no further updates, I'm closing this and will open another one when the whole translation is ready.

**Pull request closed without merging**
