### PR TITLE
Fix: render HTML tables in md files (#6002)

### PR DESCRIPTION
**Pull request by victorsptt**
## Description

Added the `rehype-raw` plugin to preserve HTML tables in md files. By default `@mdx-js/mdx` removes HTML from `md` files.

## Validation

I checked that the pages are rendering properly.

Screenshot from 2023-10-19 02-29-34

## Related Issues

#6002 

### Check List

- [ x ] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [ x ] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [ x ] I have run `npx turbo format` to ensure the code follows the style guide.
- [ x ] I have run `npx turbo test` to check if all tests are passing.
- [ x ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by ovflowd** [comment]
I'm not sure this is a good idea. By adding `rehype-raw` you're making the each document be parsed twice. That is horrible for memory.

HTML is not Markdown-compliant, and we shouldn't have raw HTML within our Markdown files. There's a a reason MDX is not parsing those, and that's because they're HTML.

MDX explicitly on their documentation state that mixing HTML is not recommended. (Of course there are some exceptions, but it's not recommended).

If you could just simply do what I've asked, which is transforming the HTML tables into Markdown ones, that'd be great :)

**Comment by ovflowd** [comment]
But this might be the only solution, @victorspt can you provide some benchmarks?

**Comment by ovflowd** [comment]
This PR breaks the website. Check the errors,  @victorspt. I feel that you should only add `rehype-raw` if the file extension is `md`. Can you update the `next.dynamic.mjs` with such logic? It should be simple as we already know the extension.

**Comment by victorsptt** [comment]
> But this might be the only solution, @victorspt can you provide some benchmarks?

Yes, I will emit the benchmark.

**Comment by ovflowd** [comment]
Hey @victorspt I'm going to make a PR to fix plain Markdown tables not being rendered/etc (adding the remark-gfm plugin for tables), then you can update this PR updating the HTML tables into plain ones. Does that sound good?

**Comment by ovflowd** [comment]
Okay, this PR now is superseeded by https://github.com/nodejs/nodejs.org/pull/6039

**Comment by victorsptt** [comment]
Thank you for fixing it Claudio, it looks great! 🎉

Em ter., 24 de out. de 2023 08:38, Claudio W ***@***.***>
escreveu:

**Pull request closed without merging**
