### PR TITLE
chore: update nvm to v0.40.0

### PR DESCRIPTION
**Pull request by avivkeller**
This PR updates the nvm install script to v0.40.0.

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by mikeesto — COMMENTED** [review]
Hmm, not sure why the preview deploy is failing here - seems unrelated to the diff

**Review by ljharb — APPROVED** [review]

**Comment by AugustinMauroy** [comment]
we should do something like we had done on nodejs.dev
https://github.com/nodejs/nodejs.dev/blob/main/util-node/getNvmData.js

**Comment by ovflowd** [comment]
Random Vercel failure, redeploying.

**Comment by ovflowd** [comment]
> we should do something like we had done on nodejs.dev [nodejs/nodejs.dev@`main`/util-node/getNvmData.js](https://github.com/nodejs/nodejs.dev/blob/main/util-node/getNvmData.js?rgh-link-date=2024-08-09T09%3A44%3A05Z)

What are you talking about? We use NVM only for Husky to install Node on the environment.

**Comment by AugustinMauroy** [comment]
> What are you talking about? We use NVM only for Husky to install Node on the environment.

No no no, if you go on shared code you I'll see how on nodejs.dev we did to get the dynamic version of NVM

**Comment by ovflowd** [comment]
> > What are you talking about? We use NVM only for Husky to install Node on the environment.
> 
> No no no, if you go on shared code you I'll see how on nodejs.dev we did to get the dynamic version of NVM

Again, this is completely unrelated to this PR and that was used to render NVM version in a specific component. This has no use over here. Please avoid off-topic.

**Review by ovflowd — APPROVED** [review]

**Pull request merged**
