### PR TITLE
fix: Consistent emphasis and strong

### PR DESCRIPTION
**Pull request by nschonni**
- Some had a space in the emphasis marker
- Escape some elements in the changelogs
- remove double asterisks order list style

### CODE REVIEW

**Comment by XhmikosR** [comment]
The thing is that the changelog files aren't supposed to change, that's what I was told :P

So, if we go with this we'll need to make these changes upstream too maybe?

**Comment by nschonni** [comment]
Most of these fixes appear to have been made in the upstream repo, but I did see one or 2 where they used backticks instead of escaping

**Comment by XhmikosR** [comment]
Let's make it consistent with upstream, otherwise LGTM.

**Comment by XhmikosR** [comment]
I think markdowlint has some related rules, which I thought were enabled by default. Maybe enable them so that we are safe until the remark-lint change happens. Note that this comment applies for all of your PRs; just enable any related markdownlint rules.

**Review by Aissaoui-Ahmed — APPROVED** [review]

**Comment by XhmikosR** [comment]
@nschonni I assume markdowlint doesn't have rules for these?

**Comment by nschonni** [comment]
Not that I'm aware of

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
