### PR TITLE
Blog: v22.4.0 release post

### PR DESCRIPTION
**Pull request by targos**
Refs: https://github.com/nodejs/node/pull/53583

### CODE REVIEW

**Comment by targos** [comment]
Vercel error:

```
Running "[[ "$VERCEL_GIT_COMMIT_REF" =~ dependabot* || "$VERCEL_GIT_COMMIT_REF" =~ gh-readonly* ]]"
Error: The specified Root Directory "apps/site" does not exist. Please update your Project Settings. Learn More: https://vercel.com/docs/build-step#root-directory
The specified Root Directory "apps/site" does not exist. Please update your Project Settings.
```

I have no idea what to do here.

**Comment by AugustinMauroy** [comment]
@ovflowd I thinks you change something on Vercel config to allow monorepo ?

**Review by mikeesto — APPROVED** [review]
LGTM. With the push to a monorepo CI isn't aligned correctly right now, this should still be fine to merge as we have done for other recent blog posts.

**Review by RafaelGSS — APPROVED** [review]

**Comment by targos** [comment]
I don't know how to go forward with the two failed checks

**Pull request merged**
