### PR TITLE
improve Dark Mode

### PR DESCRIPTION
**Pull request by ghost**
Ref: #4139.

1. Change the header's background color to make it more light so as to
   be enhanced according to @Trott's idea.
2. Fix the blog's "code" part and its font color to make it more
   visible.

****
FixMe

Blog

### CODE REVIEW

**Comment by ghost** [comment]
@NriotHrreion, @Trott. Plz have a review, thanks!

**Review by NriotHrreion — CHANGES_REQUESTED** [review]
The switcher's position is not suitable for the mobile client. 
It's better to move it to the center.

image

**Comment by Trott** [comment]
I've never noticed it until this PR, but the highlighting in the docs vs. the rest of the website is very different.

About page:

image

Docs:

image

**Comment by Trott** [comment]
Doesn't necessarily need to be fixed in this PR because it's already a problem on the main branch so could be fixed separately, but at certain viewport widths, the dark mode/light mode toggle sits on top of the News nav item:

image

**Review by Trott — APPROVED** [review]

**Comment by ghost** [comment]
@Trott: Here's my fix for the background color of code...ect (The same color as what we in in the doc).

About
Blog

@NriotHrreion: The problem you've mentioned above doesn't only appear in the dark mode, but in the light mode (Not only for your icon, but the language picker as well). I'll create another Bug issue to re-produce it in detail. So please cancel your reject request here because it doesn't belong to this fix ;)

**Comment by ghost** [comment]
Related Issue: https://github.com/nodejs/nodejs.org/issues/4166

**Review by NriotHrreion — APPROVED** [review]
That's OK, LGTM

**Comment by NriotHrreion** [comment]
@MaledongGit: The switcher is still have a problem. I fixed that. See: #4174

**Pull request merged**
