### PR TITLE
Update contributor-list/package-lock.json.

### PR DESCRIPTION
**Pull request by Trott**
This updates hoek@2 to hoek@4.2.1.

I wasn't able to test the relevant script because it didn't work for me even with no changes. So, maybe someone else can confirm that it's still in use and that it works? (Maybe GitHub was having issues when I tried? I'm pretty sure my API token would have the needed permissions.)

### CODE REVIEW

**Comment by WaleedAshraf** [comment]
I just ran the script without any error with these steps.
- Pulled latest
- `npm install`
- `GITHUB_API_TOKEN=<your token> node index.js <since date: YYYY-MM-DD>`

**Comment by WaleedAshraf** [comment]
+ I don't see **hoek** in package.json here. Why do we need to update?
And also in other PR https://github.com/nodejs/nodejs.org/pull/1638

**Review by WaleedAshraf — COMMENTED** [review]
I just ran the script without any error with these steps.

- Pulled latest
- `npm install`
- `GITHUB_API_TOKEN=<your token> node index.js <since date: YYYY-MM-DD>`

**Comment by Trott** [comment]
@WaleedAshraf It's in package-lock.json, not package.json, because it's a dependency of a dependency.

**Comment by Trott** [comment]
> I just ran the script without any error with these steps.

:+1: Thanks!

**Comment by Trott** [comment]
(For what it's worth, those are the steps I took and it seemed to take a looooong time. Maybe I just wasn't patient enough? I think I waited a minute or two.)

**Comment by WaleedAshraf** [comment]
Maybe something with the date. What date you used? 
For me with 2018-01-01, it took few seconds.

**Comment by fhemberger** [comment]
@Trott Yes, it's still in use and it should work. ;)

**Comment by Trott** [comment]
I'm going to guess it's my API token/account permissions. Regardless, as long as it is working, great.

**Comment by fhemberger** [comment]
@Trott Why are there two PRs for this change? 🤔

**Comment by WaleedAshraf** [comment]
@fhemberger  One is for `nodejs.org/package-lock.json` and other for `nodejs.org/scripts/contributor-list/package-lock.json`

I think both can be closed?

**Comment by Trott** [comment]
> I think both can be closed?

No, they should not be closed. `hoek` should be updated.

**Review by lpinca — APPROVED** [review]

**Review by WaleedAshraf — APPROVED** [review]
LGTM

**Review by ghost — APPROVED** [review]

**Review by marswong — APPROVED** [review]

**Review by daxlab — APPROVED** [review]

**Pull request merged**
