### PR TITLE
Polish Translations Setup

### PR DESCRIPTION
**Pull request by edicik**
### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by ovflowd** [comment]
Pleae read the TRANSLATION.md file. Translations are only done via Crowdin. Thank you.

**Comment by ovflowd** [comment]
Hey there 👋 translations should only be done via Crowdin. Can you remove the pl.json file? And only keep the changes to the config.json?

**Comment by edicik** [comment]
> Hey there 👋 translations should only be done via Crowdin. Can you remove the pl.json file? And only keep the changes to the config.json?

removed pl.json

**Review by ovflowd — APPROVED** [review]
LGTM! Thank you for the contribution :) Hope to see you on Crowdin!

**Comment by edicik** [comment]
When will it be available on crowdin?

**Comment by ovflowd** [comment]
> When will it be available on crowdin?

It's already there. You can request to join Crowdin for Polish already :)

**Comment by edicik** [comment]
image
@ovflowd

**Comment by edicik** [comment]
@ovflowd translations are still not at crowdin

**Comment by ovflowd** [comment]
> @ovflowd translations are still not at crowdin
> 
> 

What do you mean by this statement?

**Comment by edicik** [comment]
> > @ovflowd translations are still not at crowdin
> 
> What do you mean by this statement?

You cant choose polish language in crowdin

**Comment by ovflowd** [comment]
Alright, I forgot to add. Done!

**Comment by edicik** [comment]
> Alright, I forgot to add. Done!

All working, thanks

**Pull request merged**
