### PR TITLE
Added New Language Indonesian - Bahasa Indonesia

### PR DESCRIPTION
**Pull request by Mr7Gabriel**
I did the translation from En to Id with translation standards like any other language.

### CODE REVIEW

**Comment by ghost** [comment]
@Mr7Gabriel ：Maybe you can run `npm run test:lint:js` before submit. This will help you to find out all the syntax errors and you can either use `--fix` or fix them manually.

**Comment by Mr7Gabriel** [comment]
@MaledongGit :: Thanks for the advice and I have checked using `npm run test:lint:js` but no problem with it when I do `npm run test:lint:md` came out some problems and almost all of them related to the following warning
`1:1 warning Missing newline character at end of file` `final-newline`  `remark-lint`
how to fix this?

**Comment by ghost** [comment]
> @MaledongGit :: Thanks for the advice and I have checked using `npm run test:lint:js` but no problem with it when I do `npm run test:lint:md` came out some problems and almost all of them related to the following warning `1:1 warning Missing newline character at end of file` `final-newline` `remark-lint` how to fix this?

Then please run `npm run test:lint:md`  :)

**Comment by Mr7Gabriel** [comment]
> > @MaledongGit :: Thanks for the advice and I have checked using `npm run test:lint:js` but no problem with it when I do `npm run test:lint:md` came out some problems and almost all of them related to the following warning `1:1 warning Missing newline character at end of file` `final-newline` `remark-lint` how to fix this?
> 
> Then please run `npm run test:lint:md` :)

Okay, I'll try to fix it and update it as soon as possible.

**Comment by ghost** [comment]
@nodejs/nodejs-id : Please help the 1st contributor to review these translations.

@Mr7Gabriel : Many thanks for your support of Nodejs, and I've pinged your localization group to review your translations and you can wait for their replies, during the process your can have discussions with them if you disagree their suggestions or even you have better ideas.

Happy translating!

**Comment by Mr7Gabriel** [comment]
> @nodejs/nodejs-id : Please help the 1st contributor to review these translations.
> 
> @Mr7Gabriel : Many thanks for your support of Nodejs, and I've pinged your localization group to review your translations and you can wait for their replies, during the process your can have discussions with them if you disagree their suggestionsor even you have better ideas.
> 
> Happy translating!

Okay, I will wait for a reply from the ID Localization Group within 7×24 hours, if there is no reply, is there anyone who can help up?

**Comment by ghost** [comment]
> Okay, I will wait for a reply from the ID Localization Group within 7×24 hours, if there is no reply, is there anyone who can help up?

Maybe you have to wait until someone who is familiar with Indonesia that approves your translations (If I knew, I would be glad to have a review of yours :). But once yours is approved, I'll merge it quickly.

**Comment by Mr7Gabriel** [comment]
@MaledongGit Ok thanks I'll try that later and make changes as soon as
possible.

**Comment by ovflowd** [comment]
Hey y'all, as we moved all translation efforts to Crowdin, we're closing this PR.

Please feel free to add your translations on Crowdin :)

Guide available on the repository `TRANSLATION.md`.

**Comment by Mr7Gabriel** [comment]
> Hey y'all, as we moved all translation efforts to Crowdin, we're closing this PR.
> 
> Please feel free to add your translations on Crowdin :)
> 
> Guide available on the repository `TRANSLATION.md`.

@ovflowd At first I wanted to do a translation in Crowdin on `nodejs-website` but unfortunately ID/Indonesian localization is not yet available, can you add it in Crowdin?

**Comment by ovflowd** [comment]
Sure thing! Let me do that! Also please request to be added to the project there so I can approve you :)

**Comment by Mr7Gabriel** [comment]
I've submitted a join request and am waiting for it to be accepted and is @nodejs/nodejs-id still being used for review?

Thanks for the reply.

**Comment by ovflowd** [comment]
Nope, review is not done through GitHub teams anymore. So we're planning in Crowdin (I'm going to make a post soon) of how we're going to coordinate proofreading.

**Comment by Mr7Gabriel** [comment]
@ovflowd The ID translation is already 100, it just needs to be corrected by the proofreader or approved directly,
I hope Crowdin doesn't do a New String if that happens then I have to do another re-edit from 0% :>

**Comment by ovflowd** [comment]
We had a sync issue with Crowdin, so we had to reset the sources, so we apologise for that. But new strings should not cause re-edit from 0% 🙇 (in the future)

**Comment by Mr7Gabriel** [comment]
Yeah it's not a big deal for me but just in case I'll always download the translation memory after doing translation for a few months now. :)

**Pull request closed without merging**
