### PR TITLE
chore: Change the title from 'TL;DR' to 'Summary'

### PR DESCRIPTION
**Pull request by ghost**
In order to give a good understanding of 'TL;DR', change it to 'Summary' to make it more proper.
Ref: https://github.com/nodejs/nodejs.org/issues/2210.

### CODE REVIEW

**Comment by davisjam** [comment]
Do you have a reason to think that "Abstract" is more understandable than "TL;DR" to the average reader?

**Comment by stevemao** [comment]
I support this change. It makes the title more formal.

**Comment by ghost** [comment]
@davisjam：I don't think 'TL;DR' is more formal than 'Abstract', if in a scientific article.

On the other hand, 'TL;DR' may have two meanings:

1) Too Long Don't Read.
2) Too Long Didn't Read.

This will make it too puzzled, so to make it "Abstract" just as your suggestion to make it more clear to understand (https://github.com/nodejs/nodejs.org/issues/2210#issuecomment-487388123). I think yours is better to understand.

**Comment by zeke** [comment]
👍 I'm in favor of this change. TLDR is widely known among English-speaking developers, but it's not very accessible to international audiences.

I think "Abstract" is an improvement on TLDR, but "Abstract" is more likely to be recognizable to people with academic backgrounds, and could be confusing to people who don't read research papers.

I would suggest "Summary" as a more universally accessible term.

**Comment by davisjam** [comment]
I like "Summary" more as well, for the reasons @zeke outlined.

**Comment by ghost** [comment]
@davisjam：OK. Follow your suggestion :)

**Review by zeke — APPROVED** [review]
💯

**Review by davisjam — APPROVED** [review]
LGTM

**Review by ZYSzys — APPROVED** [review]

**Pull request merged**
