### PR TITLE
Switch to GitHub Actions CI.

### PR DESCRIPTION
**Pull request by XhmikosR**
I noticed GitHub Actions are enabled for this repo and thought I'd give this a go.

EDIT: It seems CI isn't enabled for the repo yet.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@Trott: do you know if the nodejs organization has registered for GitHub Actions yet? If yes, can you check if it's enabled for this repo in the repo options?

**Review by Aissaoui-Ahmed — APPROVED** [review]

**Comment by XhmikosR** [comment]
Here's a preview of this on my fork:

Screenshot_2019-09-20 XhmikosR nodejs org

**Comment by Trott** [comment]
> @Trott: do you know if the nodejs organization has registered for GitHub Actions yet? If yes, can you check if it's enabled for this repo in the repo options?

Confirmed that it is enabled in the repo settings.

**Comment by XhmikosR** [comment]
I think we need to contact GitHub support. It's the same issue we have with https://github.com/nodejs/remark-preset-lint-node/pull/24.

**Comment by Trott** [comment]
@XhmikosR Maybe to get this landed, change it to adding the GitHub Actions but get rid of the changes that remove Travis? Then we can be running both until any problems with GitHub Actions or whatever are sorted. At a later date, we can remove Travis (or GitHub Actions).

**Comment by XhmikosR** [comment]
@Trott It makes more sense to have everything in one patch. I just need someone to push to a branch to this repo to see if it works. My guess is it won't, because I'm hitting this issue in repos where I have push rights like https://github.com/errorception/staticify/pull/39

So, let's try pushing this to a branch here manually and see how it goes. If it doesn't work, someone will need to contact GitHub support on behalf of the `nodejs` org.

**Comment by phillipj** [comment]
Here's your changes pushed to a branch in this repo: [introduce-gh-actions](https://github.com/nodejs/nodejs.org/tree/introduce-gh-actions)

**Comment by XhmikosR** [comment]
Perfect then it works fine. :)

It should work fine on https://github.com/nodejs/remark-preset-lint-node/pull/24 too.

Let me know if you need me to make any changes, I mostly used boilerplate code from my other projects.

**Review by phillipj — APPROVED** [review]
LGTM

Haven't had any trouble with GitHub Actions, so for me it's okey to remove Travis immediately. In worst case, we could also consider re-introduce Travis until sorted out 🤷‍♂ 

Still on the fence about this @Trott?

**Comment by Trott** [comment]
> Still on the fence about this @Trott?

Nah, I'm fine with whatever.

**Comment by XhmikosR** [comment]
BTW later we could split the tests so that they run in parallel, add more actions and so on.

The only things that are missing IMO are:

1. no ability to restart the build if it's successful; one has to push something to achieve this
2. there's no button to restart a failed workflow when there are multiple workflow, so one needs to restart all workflows (doesn't affect us here)
3. no cache - this is coming in the next few months
4. low prio - no aliases when specifying Node.js versions, but this will be probably fixed soon

Just remember if you merge this to remove any Travis CI leftovers from the repo integrations/apps/hooks

**Comment by phillipj** [comment]
I don't have privileges to remove the Travis CI service/integration from repository Settings.. To me it seems like all build status indicators are now updated to only reflect last GitHub Actions build, so maybe not too important to get rid of the said service from Settings.

@XhmikosR maybe you know of some other downsides I haven't considered by leaving it as is?

**Comment by XhmikosR** [comment]
It's a security precaution. IMO any unused hooks/apps/integrations should be removed. Better be safe than sorry.

**Comment by phillipj** [comment]
Ahhh, good point 👍 

@Trott any chance you've got privileges to uninstall Travis CI from organisation Settings or similar? This is what I see from this repo' Settings, with no action buttons available:

Screenshot 2019-09-29 at 12 22 56

**Comment by XhmikosR** [comment]
Just make sure you only remove it from this repo, not the org :P

There might be extra stuff in apps settings BTW.

**Comment by Trott** [comment]
I removed it from this repo.

**Comment by nschonni** [comment]
I can't seem to push to my fork anymore now that this is enabled
```
To https://github.com/nschonni/nodejs.org.git
 ! [remote rejected]   master -> master (refusing to allow an integration to create or update .github/workflows/test.yml)
error: failed to push some refs to 'https://github.com/nschonni/nodejs.org.git'
```

**Comment by XhmikosR** [comment]
Try a google search https://github.com/desktop/desktop/issues/6526

Never seen such error personally.

**Comment by nschonni** [comment]
I did search around first, but nothing useful is coming up around the errror.
Your thread lead me to this https://github.com/zkSNACKs/WalletWasabi/issues/2329 which indicates this might not support HTTPS cloning urls anymore

**Comment by XhmikosR** [comment]
I don't know how you clone but I don't see how this is can be related to
this patch. Either way, you are better off contacting GitHub support.

I know for sure I don't have this issue with CLI git on Windows and Linux.

**Comment by nschonni** [comment]
It's related to the patch, because unlike Travis CI, GitHub Actions are allowed to blocking pushes to forks. This no longer allows push or force push on Windows or OSX

**Comment by XhmikosR** [comment]
And like I said you only seem to have this issue.

Please contact GitHub support.

**Comment by nschonni** [comment]
I get you like it @XhmikosR but I'm trying to see if anyone else tried to rebase their fork since this landed all of 10 hours ago and is having the same issue here?

PS: I'm also getting the same error on the remark-preset-lint-node since that switch as well

**Comment by XhmikosR** [comment]
You don't even mention what tool you are using. Just bashing a patch isn't
helping.

This could easily be a bug in the gui git client one might be using.

It's not that I like it. I love it and as far as I'm concerned I wouldn't
revert it. I would contact github support.

**Comment by Trott** [comment]
> I get you like it @XhmikosR but I'm trying to see if anyone else tried to rebase their fork since this landed all of 10 hours ago and is having the same issue here?
> 
> PS: I'm also getting the same error on the remark-preset-lint-node since that switch as well

@nschonni Are you able to switch to SSH instead of HTTPS? I strongly suspect (as you seem to indicate above, IIUC) that will fix the problem. I think running this command should do it:

```console
git remote set-url origin git@github.com:nschonni/nodejs.org.git
```

**Comment by nschonni** [comment]
No, different error then, but going by a few things I came across like https://github.com/desktop/desktop/pull/8340 it's more that users need to regenerate new PATs used by any .gitconfig or Git Credential Helpers.

FYI, turning off Actions in a fork's Settings does not allow pushing either. The server error applies to any repo with Actions enabled, and not just this repo.

**Comment by Trott** [comment]
> No, different error then, but going by a few things I came across like [desktop/desktop#8340](https://github.com/desktop/desktop/pull/8340) it's more that users need to regenerate new PATs used by any .gitconfig or Git Credential Helpers.
> 
> FYI, turning off Actions in a fork's Settings does not allow pushing either. The server error applies to any repo with Actions enabled, and not just this repo.

Hmm...OK, in that case, I'll let you sort this out (and please report back what finally fixes it for you!), but if I'm interpreting that wrong and you need me to either do something or provide some information, just ask!

**Comment by nschonni** [comment]
Don't think there is anything to be done here, the tooling just generally needs to catch up. Reverting wouldn't help anyone because it would still reject the push on that commit. New people forking shouldn't see any issues, it might just be existing collaborators that might run into the issue.

**Comment by sleepdefic1t** [comment]
Came across this issue trying to solve my own.

I was able to push to my own projects after setting up a [Personal Access Token](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line).

**Pull request merged**
