### PR TITLE
chore(internationalization): Add Russian language to Home page

### PR DESCRIPTION
**Pull request by mirasayon**
## Description

Add Russian language to home page.

## Validation

I dont know what is that. This is my first pull request 🤷‍♂️

### Check List

- [X] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [X] I have run `npm run format` to ensure the code follows the style guide.
- [X] I have run `npm run test` to check if all tests are passing.
- [X] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by mikeesto** [comment]
Thanks for your first PR. The translation effort happens on Crownin, please have a look [here](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md) if you would like to contribute

**Comment by mirasayon** [comment]
> Thanks for your first PR. The translation effort happens on Crownin, please have a look [here](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md) if you would like to contribute

What? I didn't want to wait for the moderators to take me there. And what about this PR. Well, I tried my best. Can't you just merge this? Then I will do it on the Crowdin platform.

**Comment by ovflowd** [comment]
> > Thanks for your first PR. The translation effort happens on Crownin, please have a look [here](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md) if you would like to contribute
> 
> 
> 
> What? I didn't want to wait for the moderators to take me there. And what about this PR. Well, I tried my best. Can't you just merge this? Then I will do it on the Crowdin platform.

No, we can't just merge this. There are processes for translating the website and certain triggers that are generated by Crowdin. Not to mention there are proofreaders who validate the translations.

Apologies for the wasted effort, but we have it written within the README the translation guidelines 👀 and a dedicated file named TRANSLATING.md

**Comment by mirasayon** [comment]
> > > Thanks for your first PR. The translation effort happens on Crownin, please have a look [here](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md) if you would like to contribute
> > 
> > 
> > What? I didn't want to wait for the moderators to take me there. And what about this PR. Well, I tried my best. Can't you just merge this? Then I will do it on the Crowdin platform.
> 
> No, we can't just merge this. There are processes for translating the website and certain triggers that are generated by Crowdin. Not to mention there are proofreaders who validate the translations.
> 
> Apologies for the wasted effort, but we have it written within the README the translation guidelines 👀 and a dedicated file named TRANSLATING.md

Okay, okay. But bro, I’ve been waiting for 2 days already, I haven’t been accepted onto that platform yet. 🤷‍♂️

**Comment by ovflowd** [comment]
> > > > Thanks for your first PR. The translation effort happens on Crownin, please have a look [here](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md) if you would like to contribute
> 
> > > 
> 
> > > 
> 
> > > What? I didn't want to wait for the moderators to take me there. And what about this PR. Well, I tried my best. Can't you just merge this? Then I will do it on the Crowdin platform.
> 
> > 
> 
> > No, we can't just merge this. There are processes for translating the website and certain triggers that are generated by Crowdin. Not to mention there are proofreaders who validate the translations.
> 
> > 
> 
> > Apologies for the wasted effort, but we have it written within the README the translation guidelines 👀 and a dedicated file named TRANSLATING.md
> 
> 
> 
> Okay, okay. But bro, I’ve been waiting for 2 days already, I haven’t been accepted onto that platform yet. 🤷‍♂️

So you sent a request to be added there already? Let me check on that. Unfortunately we don't get notifications when someone requests to join.

**Comment by mirasayon** [comment]
> > > > > Thanks for your first PR. The translation effort happens on Crownin, please have a look [here](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md) if you would like to contribute
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > What? I didn't want to wait for the moderators to take me there. And what about this PR. Well, I tried my best. Can't you just merge this? Then I will do it on the Crowdin platform.
> > 
> > 
> > > 
> > 
> > 
> > > No, we can't just merge this. There are processes for translating the website and certain triggers that are generated by Crowdin. Not to mention there are proofreaders who validate the translations.
> > 
> > 
> > > 
> > 
> > 
> > > Apologies for the wasted effort, but we have it written within the README the translation guidelines 👀 and a dedicated file named TRANSLATING.md
> > 
> > 
> > Okay, okay. But bro, I’ve been waiting for 2 days already, I haven’t been accepted onto that platform yet. 🤷‍♂️
> 
> So you sent a request to be added there already? Let me check on that. Unfortunately we don't get notifications when someone requests to join.

Yes. Ok

**Comment by bmuenzenmeyer** [comment]
sorry - i check crowdin nearly every day and missed those notifications coming in

**Comment by mirasayon** [comment]
> sorry - i check crowdin nearly every day and missed those notifications coming in

No problem, bro, better tell me when my translation will be approved and Russian will be added to the pages.

**Comment by bmuenzenmeyer** [comment]
russian is 100% translated but requires proofreading. no crowdin members currently have that role - though one person expressed some interest in tag teaming it. can you help out with proofreading?

**Comment by mirasayon** [comment]
> russian is 100% translated but requires proofreading. no crowdin members currently have that role - though one person expressed some interest in tag teaming it. can you help out with proofreading?

Yes, sure. But I can't check all the translations at once. Is it possible to do this step by step? And gradually add Russian to the pages, starting from the home page, and not all at once?

**Pull request closed without merging**
