### PR TITLE
Update knowledge/how to use nodejs repl

### PR DESCRIPTION
**Pull request by jonchurch**
Updates to the knowledge article **[how to use nodejs repl](https://nodejs.org/en/knowledge/REPL/how-to-create-a-custom-repl/)**. 

This is the first of several articles I will be editing https://github.com/nodejs/nodejs.org/issues/1977#issuecomment-472619855. Any feedback is welcome. 

And to jumpstart that: 
**Is it acceptable that I added sectional headers?**

I think it helps the reader survey the content quicker, but very few of these knowledge articles use headers at all currently. My inclination is to add them to articles I edit. Please let me know if I shouldn't bother for any reason.

**Edit**: Also, any guidance on how I should handle linking between these articles? I wanted to link to the next article, "how to create a custom repl" from this one, but wasn't sure the convention. So I linked to the Node API docs instead.

* Updated code blocks to fences, added `shell` syntax.
* Added headers to sections
* Added "Special Commands" section, from the Node API docs
* Mention the existence of built in REPL module and standalone executable

cc @fhemberger @keywordnew

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM, thanks!
waiting others' suggestions :)

**Comment by Yash-Handa** [comment]
LGTM, 🙌
To link to the article you should use: `/en/knowledge/REPL/how-to-create-a-custom-repl/` so that the link [https://nodejs.org/en/knowledge/REPL/how-to-create-a-custom-repl/](https://nodejs.org/en/knowledge/REPL/how-to-create-a-custom-repl/) is opened.

**Comment by Maledong** [comment]
@Yash-Handa：Helped to fix the link in the dialog, it should be "https://nodejs.org/en/knowledge/REPL/how-to-use-nodejs-repl/", please confirm :)

**Comment by Yash-Handa** [comment]
> @Yash-Handa：Helped to fix the link in the dialog, it should be "https://nodejs.org/en/knowledge/REPL/how-to-use-nodejs-repl/", please confirm :)

I think it should be `/en/knowledge/REPL/how-to-create-a-custom-repl/` the domain is added automatically (relative to the root path maybe). Refer this [comment](https://github.com/nodejs/nodejs.org/pull/2064#discussion_r256704491) : )

**Pull request merged**
