### PR TITLE
Update index.md Issue #3875

### PR DESCRIPTION
**Pull request by InigoRomero**
Update Blocking vs Non-Blocking url in index.md
Issue: https://github.com/nodejs/nodejs.org/issues/3875

### CODE REVIEW

**Review by Trott — APPROVED** [review]
LGTM. The URL also needs to be updated in locale/ca/about/index.md if you want to update it there as well.

**Comment by InigoRomero** [comment]
> LGTM. The URL also needs to be updated in locale/ca/about/index.md if you want to update it there as well.

Done!

**Comment by MrJithil** [comment]
@InigoRomero I think the latest changes not pushed yet.

**Comment by ghost** [comment]
This is fixed at https://github.com/nodejs/nodejs.org/pull/3877,  I will close It for duplication. Any feedback is welcome.

**Comment by MrJithil** [comment]
@MaledongGit  This issue has unresolved suggestions. Please see the comment from @Trott 

I have created a separate PR to add that changes since this is closed.

**Comment by MrJithil** [comment]
#3882

**Pull request closed without merging**
