### PR TITLE
fix(grammar): LocalisedLink -> LocalizedLink

### PR DESCRIPTION
**Pull request by AugustinMauroy**

### CODE REVIEW

**Comment by ovflowd** [comment]
This is not a grammar issue. LocalisedLink is correct in the USA. LocalizedLink would be correct in the UK. Both are valid English.

**Comment by nschonni** [comment]
@ovflowd you've got it reversed, this is changing it to the US spelling https://multilingual.com/differences-us-uk-english/. "s" is UK version

**Comment by ovflowd** [comment]
Oh, _ahem_ my bad. @nschonni I supposed we should follow US-alike naming, right? If, so, @AugustinMauroy feel free to reopen the PR :)

**Comment by nschonni** [comment]
Looked it up again, and the styleguide says to stick with US spelling https://github.com/nodejs/node/blob/main/doc/README.md

**Comment by AugustinMauroy** [comment]
> so, @AugustinMauroy feel free to reopen the PR :)

I can't 🤔 ??

Capture d’écran 2023-03-14 à 17 29 05

**Review by ovflowd — APPROVED** [review]
LGTM!

**Pull request merged**
