### PR TITLE
Fixed broken links on "The built-in globals in Node.js"

### PR DESCRIPTION
**Pull request by godcrampy**
#2322 
Updated the [globals-in-node-js.md](https://github.com/nodejs/nodejs.org/blob/master/locale/en/knowledge/getting-started/globals-in-node-js.md) file with correct links.

### CODE REVIEW

**Comment by Trott** [comment]
Can you also fix it in the translation docs where it also appears?

locale/fa/knowledge/getting-started/globals-in-node-js.md
locale/ru/knowledge/getting-started/globals-in-node-js.md
locale/uk/knowledge/getting-started/globals-in-node-js.md

**Review by Trott — APPROVED** [review]
LGTM although better if it also fixes it in the translations too!

**Comment by godcrampy** [comment]
Yea sure I'll try doing that

**Comment by godcrampy** [comment]
Fixed the docs for uk, fa, ru versions.

**Review by Trott — APPROVED** [review]

**Comment by Trott** [comment]
For another PR for anyone that wants to do it: I think there are other broken links that can be found with `grep -rl /articles/ locale`.

**Comment by godcrampy** [comment]
I've fixed all the broken links as pointed out by ```grep -rl /articles/ locale``` and a few markdown errors for en, uk, ru, fa and pt-br docs.

**Review by Trott — APPROVED** [review]
Thanks for this!

**Review by alexandrtovmach — APPROVED** [review]

**Pull request merged**
