### PR TITLE
Banner: add link to Unhandled Rejections survey

### PR DESCRIPTION
**Pull request by mmarchini**
We're seeking input from the community on the longstanding unhandled
rejections deprecation. The survey will run for ~2 weeks

Ref: https://github.com/nodejs/TSC/issues/902

### CODE REVIEW

**Comment by mmarchini** [comment]
@nodejs/website pinging since this is time-sensitive.

Also cc @nodejs/tsc for awareness

**Comment by mmarchini** [comment]
Happy to hear suggestions for the text. An alternative I've considered was `Unhandled Promise Rejections survey now available` (both use about the same space on the banner)

**Review by codebytere — APPROVED** [review]

**Review by lpinca — APPROVED** [review]

**Review by evanlucas — APPROVED** [review]

**Review by MylesBorins — APPROVED** [review]
LGTM

**Comment by MylesBorins** [comment]
Based on multiple reviews and time sensitivity I'm going to land this, if we want to bikeshed text lets open another PR

**Pull request merged**
