### PR TITLE
infra: add `@oramacloud/*` to dependabot

### PR DESCRIPTION
**Pull request by avivkeller**
## Description

Add `@oramacloud/*` to the dependabot config, as we use deps from both `@orama/` and `@oramacloud/`

## Validation

**N/A**

### Check List

**N/A**

### CODE REVIEW

**Review by AugustinMauroy — APPROVED** [review]

**Review by bmuenzenmeyer — APPROVED** [review]

**Comment by ovflowd** [comment]
@RedYetiDev would you mind making a PR updating the GitHub Workflows so that the Lighthouse doesn't run when Vercel gets skipped?

**Comment by avivkeller** [comment]
> @RedYetiDev would you mind making a PR updating the GitHub Workflows so that the Lighthouse doesn't run when Vercel gets skipped?

Sure thing! I'll make one later today.

**Comment by bmuenzenmeyer** [comment]
Why are these prs being merged without the 48 hour policy being honored?

**Comment by ovflowd** [comment]
I used the good judgment/fast track policy but realised I forgot to actually request for fast track... My bad!

**Pull request merged**
