### PR TITLE
chore: remove express example

### PR DESCRIPTION
**Pull request by ovflowd**
It feels weird to provide an example of one specific framework so in-depth. So this PR removes that example. Note that I'm fine keeping it, but this page was originally migrated from one of the very old guides, and the content wasn't updated.

### CODE REVIEW

**Review by Harkunwar — APPROVED** [review]

**Review by AugustinMauroy — APPROVED** [review]
LGTM ! but why we still need this ressource ? Because `NODE_ENV` isn't node core related.

**Comment by ovflowd** [comment]
I don't know, @nodejs/collaborators should we have a guide about NODE_ENV or not?

**Review by anonrig — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by ovflowd** [comment]
Merging this for now, and we can revisit the NODE_ENV in the future.

**Pull request merged**
