### PR TITLE
docs: modernize classes in code snippets

### PR DESCRIPTION
**Pull request by GeorgeSapkin**
I've changed a few code snippets in the docs to use the modern class syntax. I've only touched the English bits for now.

### CODE REVIEW

**Comment by Trott** [comment]
@nodejs/documentation

**Review by benhalverson — APPROVED** [review]

**Comment by Trott** [comment]
I know this unfortunately got ignored for a long time, but any chance it can be rebased to resolve the conflicts?

@nodejs/website Reviews for this would be good.

**Comment by Trott** [comment]
@nodejs/domains @nodejs/website This could use a few more reviews.

**Review by ghost — APPROVED** [review]

**Review by Trott — COMMENTED** [review]
I don't have an opinion on this. I'm just leaving this comment so no one holds this up awaiting my review as it seems that it was requested in the GitHub interface. Thanks.

**Review by aymen94 — APPROVED** [review]

**Pull request merged**
