### PR TITLE
Translate knowledge/errors into portuguese (pt-br)

### PR DESCRIPTION
**Pull request by ftonato**
Hello,

I have finished the `knowledge/errors` section, can you validate and approve this one?

/cc @nodejs/nodejs-pt
/cco @glaucia86 @khaosdoctor

### CODE REVIEW

**Comment by khaosdoctor** [comment]
Hey man! Can you please put the original version in comments in the file? This way we can check the translation faster!

Example: https://github.com/nodejs/nodejs.org/blob/7f31f2fd492175da5bf077b246ae939a2a4576d6/locale/pt-br/docs/guides/abi-stability.md#L10-L25

**Review by khaosdoctor — APPROVED** [review]
This looks fine to me 👍

**Comment by khaosdoctor** [comment]
Thanks!

I think we're ready to merge

cc: @Maledong @Trott @fhemberger @MylesBorins

**Comment by fhemberger** [comment]
Great, thanks everyone!

**Pull request merged**
