### PR TITLE
Update Board Directors

### PR DESCRIPTION
**Pull request by dshaw**
Put Gold listing between Platinum and Silver director listings.

### CODE REVIEW

**Review by lpinca — APPROVED** [review]

**Comment by lpinca** [comment]
Question: should the directors above the gold-level-director be listed as platinum-level-director?

**Comment by mikeal** [comment]
We call out the Gold/Silver seats because they are elected by the class and represent the class. The platinum directors represent their company directly, which is already listed.

**Review by williamkapke — APPROVED** [review]

**Comment by williamkapke** [comment]
Added @williamkapke and @sethgaurav (Microsoft)

Used "Individual Director" for @ad_dubs and myself to align with the term used in the By-Laws.

**Comment by sethgaurav** [comment]
Thanks @williamkapke!

**Comment by williamkapke** [comment]
Also noticed that Mark Skarpness was added at the last meeting. Just added to this PR.

**Pull request merged**
