### PR TITLE
[automated]: crowdin sync

### PR DESCRIPTION
**Pull request by nodejs-crowdin**

### CODE REVIEW

**Review by AugustinMauroy — APPROVED** [review]
Oh it's work

**Comment by AugustinMauroy** [comment]
@ovflowd  why did you close it ?

**Comment by ovflowd** [comment]
Because this was a test PR triggered by Crowdin team.

**Comment by ovflowd** [comment]
Please do not approve such large PRs without context 😅

**Comment by ovflowd** [comment]
FYI @nodejs/nodejs-website the Crowdin team is using this PR as a reference for debugging purposes.

**Pull request closed without merging**
