### PR TITLE
Extending the noted time for Interactive to include collab summit.

### PR DESCRIPTION
**Pull request by mikeal**

### CODE REVIEW

**Comment by MylesBorins** [comment]
LGTM

**Comment by ghost** [comment]
LGTM

**Comment by MylesBorins** [comment]
So I was just looking at the site, and it now makes it look like the events are twice as long. Should we perhaps be explicit about the dates for the summit? It would not be great if people end up booking longer trips and don't have a need for the summit

**Comment by MylesBorins** [comment]
Also I just realized that the US dates should be to Dec 2 and the graphic says Dec 1

**Pull request merged**
