### PR TITLE
meta: removed old deps, updated deps, added shiki

### PR DESCRIPTION
**Pull request by ovflowd**
## Description

This PR introduces the [Rehype Pretty Code](https://rehype-pretty-code.netlify.app/) featurette (with [Shiki](https://github.com/shikijs/shiki)).

Pretty much we're moving on from the very-old Highlight.js and the non-React-friendly PrismJS towards Shiki (the same syntax highlighter of VS Code) and a Rehype Plugin, which means the Codeboxes are syntax-highlighted at the time of compilation of our MDX transpilation.

This ensures that:

- We have a smaller bundle footprint in general (client-side)
- Pages will already be pre-highlighted from the server-side (never client-side)
- Faster installation times (npm ci/i) due to less packages
- Futureproof to whatever Frontend Framework we use as long as it is MDX compatible

This PR also updates related packages, fixes a `js-dom` issue with Jest, removes unnecessary and old packages, and removes old styles.

## Validation

Validation is done by acknowledging that Syntax Highlighting is still working on web pages.

## Related Issues

No Related Issue but this is part of the Website Redesign

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by ovflowd** [comment]
Hey @styfle, sorry for pinging you here. It seems that on Vercel, we're getting 5XX Errors because the `node_modules/shiki` package is not being bundled/deployed to the Edge Runtimes:

```
[Error: [next-mdx-remote] error compiling MDX:
ENOENT: no such file or directory, open '/var/task/node_modules/shiki/languages/abap.tmLanguage.json'

More information: https://mdxjs.com/docs/troubleshooting-mdx] {
  page: '/en'
}
[Error: [next-mdx-remote] error compiling MDX:
ENOENT: no such file or directory, open '/var/task/node_modules/shiki/languages/abap.tmLanguage.json'

More information: https://mdxjs.com/docs/troubleshooting-mdx] {
  page: '/en'
}
RequestId: 267411e5-2092-4749-99ac-6ca62412b684 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

I've tried to search on Google some workarounds, but no luck. Is there any way to tell Vercel/Next.js that this package (shiki) should be included?

**Comment by ovflowd** [comment]
> ## 📦 Next.js Bundle Analysis for nodejs.org
> This analysis was generated by the [Next.js Bundle Analysis action](https://github.com/hashicorp/nextjs-bundle-analysis). 🤖
> 
> This PR introduced no changes to the JavaScript bundle! 🙌

I... doubt. I'm starting to wonder how useful this is... @bmuenzenmeyer

**Comment by bmuenzenmeyer** [comment]
I've wondered too. Do you know if we've ever made a change to the prod bundle size since introducing it? I suppose dependencies could... But nodes.dev work would not have.

Either way, I would be fine with removing. The Lighthouse work will be nice to land in it's place.

**Comment by ovflowd** [comment]
> I've wondered too. Do you know if we've ever made a change to the prod bundle size since introducing it? I suppose dependencies could... But nodes.dev work would not have.
> 
> Either way, I would be fine with removing. The Lighthouse work will be nice to land in it's place.

My concern here is that the changes here definitely change the bundle, even if a slightliest bit. If this Bundle Analyzer cannot calculate changes done on the ISR-side of things, then this bundle analyzer is pretty useless.

Even more because all our pages are dynamic. I'm +1 removing it. I prefer that we integrate our custom solution that you've been working for (I dm'd you on Slack)

**Comment by ovflowd** [comment]
Hey @shuding or @styfle sorry for the bump. Just curious if we could get help with this or if we should create a ticket somewhere?

**Comment by ovflowd** [comment]
@bmuenzenmeyer after a lot of digging on Shiki's source and hitting my mind to almost desperation... I was able to make this work out 🤓 

I've added some inline docs on how this works.

cc @nodejs/website ready for review

**Comment by rluvaton** [comment]
FYI shiki seems to have a memory leak:

Ref: [Fixing a Memory Leak in a Production Node.js App](https://kentcdodds.com/blog/fixing-a-memory-leak-in-a-production-node-js-app) - @kentcdodds blog

**Comment by ovflowd** [comment]
> FYI shiki seems to have a memory leak:
> 
> Ref: [Fixing a Memory Leak in a Production Node.js App](https://kentcdodds.com/blog/fixing-a-memory-leak-in-a-production-node-js-app) - @kentcdodds blog

That's OK and probably would not affect us, as:

We use Shiki within Server-Side-Rendering on a Serverless Function that caches each route after one render. Meaning that Shiki's lifecycle pretty much is unable to cause these said memory leaks. Also this leak would never affect the end-user. Since Shiki is not bundled nor available on the client-side, as we do direct MDX transpilation to Shiki's resulting highlighted content with a Rehype Plugin.

**Review by rodion-arr — COMMENTED** [review]
Hey, just to validate:
I see empty code block in blog, looks like we need to adjust config to cover this case also

https://nodejs-org-git-feat-rehype-pretty-code-openjs.vercel.app/en/blog/release/v20.5.1

image

**Comment by ovflowd** [comment]
> Hey, just to validate: I see empty code block in blog, looks like we need to adjust config to cover this case also
> 
> [nodejs-org-git-feat-rehype-pretty-code-openjs.vercel.app/en/blog/release/v20.5.1](https://nodejs-org-git-feat-rehype-pretty-code-openjs.vercel.app/en/blog/release/v20.5.1)
> 
> image

It's not empty, I think during rebases the font colour got overridden lol. (Because it's text/plain) and by default Shiki does nothing with plain text :P

**Comment by ovflowd** [comment]
> > Hey, just to validate: I see empty code block in blog, looks like we need to adjust config to cover this case also
> > [nodejs-org-git-feat-rehype-pretty-code-openjs.vercel.app/en/blog/release/v20.5.1](https://nodejs-org-git-feat-rehype-pretty-code-openjs.vercel.app/en/blog/release/v20.5.1)
> > image
> 
> It's not empty, I think during rebases the font colour got overridden lol. (Because it's text/plain) and by default Shiki does nothing with plain text :P

**Update:** Fixed

**Comment by rodion-arr** [comment]
> **Update:** Fixed

Text is still invisible in latest preview:
https://nodejs-25o56h2j3-openjs.vercel.app/en/blog/release/v20.5.1

image

**Comment by ovflowd** [comment]
@mikeesto you don't need to keep rebasing branches. Also, a note to @nodejs/website we use "Merge Queues" here, meaning you don't need to constantly keep "rebasing"/"update branch".

The Merge Queues do that for you.

**Comment by ovflowd** [comment]
> > **Update:** Fixed
> 
> Text is still invisible in latest preview: [nodejs-25o56h2j3-openjs.vercel.app/en/blog/release/v20.5.1](https://nodejs-25o56h2j3-openjs.vercel.app/en/blog/release/v20.5.1)
> 
> image

This is a dark mode issue.

**Comment by ovflowd** [comment]
> > > **Update:** Fixed
> > 
> > 
> > Text is still invisible in latest preview: [nodejs-25o56h2j3-openjs.vercel.app/en/blog/release/v20.5.1](https://nodejs-25o56h2j3-openjs.vercel.app/en/blog/release/v20.5.1)
> > image
> 
> This is a dark mode issue.

**Update:** styles updated

**Comment by mikeesto** [comment]
> @mikeesto you don't need to keep rebasing branches. Also, a note to @nodejs/website we use "Merge Queues" here, meaning you don't need to constantly keep "rebasing"/"update branch".
> 
> The Merge Queues do that for you.

Sorry I did it to trigger a new preview. I understand how the merge queue works

**Comment by ovflowd** [comment]
> > @mikeesto you don't need to keep rebasing branches. Also, a note to @nodejs/website we use "Merge Queues" here, meaning you don't need to constantly keep "rebasing"/"update branch".
> > The Merge Queues do that for you.
> 
> Sorry I did it to trigger a new preview. I understand how the merge queue works

New Previews for Rebase are pointless IMO, but all good.

**Review by rodion-arr — APPROVED** [review]

**Review by araujogui — APPROVED** [review]

**Pull request merged**
