### PR TITLE
[Localization] Add modification styles onto the `md` files, fix typo error.

### PR DESCRIPTION
**Pull request by ghost**
1) Fix a typo.
2) Modify styles onto codes.

### CODE REVIEW

**Review by fhemberger — APPROVED** [review]
@Maledong Could you please pull again and resolve the conflict?

Otherwise LGTM.

**Review by fhemberger — CHANGES_REQUESTED** [review]
@Maledong Could you please pull again and resolve the conflict?

Otherwise LGTM.

**Review by fhemberger — CHANGES_REQUESTED** [review]
@Maledong Could you please pull again and resolve the conflict?

Otherwise LGTM.

**Review by fhemberger — CHANGES_REQUESTED** [review]
@Maledong Could you please pull again and resolve the conflict?

Otherwise LGTM.

**Comment by fhemberger** [comment]
Waaaah! 😱

**Comment by ghost** [comment]
OK. For the 1st time I don't have authority to access the write of the file. Now I've submitted this :)

**Comment by fhemberger** [comment]
Sorry, `locale/en/blog/vulnerability/june-2018-security-releases.md` is still an older version, I'll change `locale/uk/blog/advisory-board/advisory-board-update.md` by hand.

Landed in 1d9dd3a041021eb5815b83c948d54c458d68278f.

**Pull request closed without merging**
