### PR TITLE
Blog: v20.1.0 release post

### PR DESCRIPTION
**Pull request by targos**
Refs: https://github.com/nodejs/node/pull/47820

### CODE REVIEW

**Review by BethGriggs — APPROVED** [review]

**Review by ovflowd — APPROVED** [review]

**Comment by targos** [comment]
Needs two approving reviews? That may be a problem sometimes (blog post should be published ASAP after the release is promoted).

**Comment by ovflowd** [comment]
@targos we can create bypass rules for releasers.

**Comment by targos** [comment]
Can we bypass only this rule? I don't want to bypass CI workflows.

**Comment by ovflowd** [comment]
Which rule? (Amount of reviewers?)

**Comment by targos** [comment]
Yes, amount of reviewers.

**Comment by ovflowd** [comment]
I don't think there's bypass for an individual requirement. Let me check on OpenJS Slack.

**Comment by targos** [comment]
If necessary, we can create a separate ruleset for this requirement. btw GitHub deployed a new way to define rules recently: https://github.com/nodejs/nodejs.org/settings/rules

**Comment by ovflowd** [comment]
I applied a few rules, @targos! Let's check if next time they work well!

**Pull request merged**
