### PR TITLE
fa: Create Nodejs Doc files in Persian

### PR DESCRIPTION
**Pull request by ghost**
Ref: https://github.com/nodejs/nodejs.org/pull/1844

### CODE REVIEW

**Comment by AliSawari** [comment]
this could be helpful, as there is a growing up Persian-speaking community for Nodejs in Iran.
@fhemberger any plans on adding this?

**Comment by fhemberger** [comment]
@AliSawari As far as I've seen, the pages are still all in English. A good starting point are the `index.md` and `site.json` files, from there you could gradually move on translating other parts.

I'd be happy to have a Persian version of the website as well to support the growing community.

**Comment by AliSawari** [comment]
@fhemberger thanks for the reply :)
I will share this in the community of developers for further translation. I'll take a look at the files and will add some more translations too.

**Comment by m-esm** [comment]
@AliSawari count me in.

**Comment by ghost** [comment]
@AliSawari & @m-esm & @armanatory：The page's index and site.json have both been in Persian. So I've submitted this PR and you all can continue your translations in Persian by forking and downloading, based on them.

For details when submitting, you can still see the last reply by me at top of this PR, now here's the actual look in `index` with `site.json`:

image

**Comment by m-esm** [comment]
@Maledong what we can do about website direction ( RTL for Persian ) and the font? this 2 item caused poor UX for Persian users.

P.s. navigation menu items lead users to the English version

**Comment by fhemberger** [comment]
Set "rtl" to "true" in `site.json`, see https://github.com/nodejs/nodejs.org/blob/master/locale/ar/site.json#L6

**Comment by anio** [comment]
About your P.S. @Maledong, you should set "locale" to "fa" in site.json.

**Comment by Maledong** [comment]
@fhemberger & @anio :  These fixes will be merged from https://github.com/nodejs/nodejs.org/pull/1865/commits/88481f7ed0edf986fde7adfa3f19ff6d641b9172#diff-6a66020b6a49bfa6ecf62c7ee634fef4

**Comment by ghost** [comment]
@anio , @m-esm : Fixed and you can continue your contributions:)
image

**Comment by ghost** [comment]
@AliSawari & @m-esm & @armanatory,@anio：Your friends are waiting for you at https://github.com/orgs/nodejs/teams/nodejs-fa, please switch to "Members" and "Request to Join in". This is a translation group in Persian. You can cooperate together. 

For more: https://help.github.com/articles/adding-organization-members-to-a-team/

**Comment by armanatory** [comment]
@Maledong With sincere thanks, I'm not a member of Nodejs organization. How could I do this?

**Comment by ghost** [comment]
@AliSawari & @m-esm & @armanatory：

Hummm……, you need to write a request to be the collabrator of Nodejs, see this related and similar post: https://github.com/nodejs/nodejs.org/issues/1867. Perhaps you have to wait for a while because people are added batchly.

PS：This WON'T effect your contributions to the docs in Persian, you can still submit them and let others help to submit for you.

/cc：@fhemberger

**Comment by fhemberger** [comment]
> Hummm……, you need to write a request to be the collabrator of Nodejs

No, you don't. You'll be added automatically once you contributed. But I can't add users myself, so we're doing this in batches and then pinging the Admins of the GitHub org to add you. Sorry it's that complicated. 🤷‍♂️

I was planning to do this shortly, so please just bear with me. 🙏

**Comment by fhemberger** [comment]
Ref: #1872

**Pull request merged**
