### PR TITLE
es6 function edits

### PR DESCRIPTION
**Pull request by ericmoore123**
updated several modules to utilize variable based arrow functions

### CODE REVIEW

**Comment by Trott** [comment]
Welcome, @ericmoore123, and thanks for the pull request. This change seems cosmetic. Is there a reason to make this change?

**Comment by ericmoore123** [comment]
Hi @Trott. The main goal was to update some out of date code and uniformly get the js up to es6 standards. Though yes, at this time it is mainly cosmetic and functionality will remain the same.

**Comment by Arifan998** [comment]
Welcome, @ericmoore123, and thanks for the pull request. This change seems cosmetic. Is there a reason to make this change?

**Comment by ericmoore123** [comment]
Hi @Arifan998 . The main goal was to update some out of date code and uniformly get the js up to es6 standards. Though yes, at this time it is mainly cosmetic and functionality will remain the same.

**Comment by Arifan998** [comment]
Range

**Pull request closed without merging**
