### PR TITLE
update node.js community

### PR DESCRIPTION
**Pull request by tungtouch**
Hi,

My name is Tung, i'm founder https://nodejs.vn (Facebook fanpage https://fb.com/nodejs.vn) from 2012 to present. We're a node.js community at vietnam, we have 4k members follow.
So i want ask about our community add to https://nodejs.org/en/get-involved/#international-community-sites-and-projects

Our vision wants bring node.js to vietnam developers. We want node.js common at vietnam.

Thanks !
Tung

### CODE REVIEW

**Comment by fhemberger** [comment]
Hi Tung,

great to hear! The list is sorted alphabetically, so could you please add your link below "Chinese community" instead? Thanks!

**Comment by tungtouch** [comment]
Yes, i had update. thanks!

**Comment by hiroppy** [comment]
LGTM 👍

**Comment by ghost** [comment]
LGTM! thanks for contributing! ✨

**Pull request merged**
