### PR TITLE
fix table markup in branding pages

### PR DESCRIPTION
**Pull request by aquibbaig**
## Description
This PR fixes the following hydration error:
```
In HTML, <tr> cannot be a child of <table>.
This will cause a hydration error.
```

The browser expects `<tr>` tags to be wrapped in `<tbody>...</tbody>` tags but our server generated markup is missing this -- Hence the error arises.

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by mikeesto** [comment]
Nice catch, no need to update the translation files

**Comment by aquibbaig** [comment]
@mikeesto thanks! done

**Review by mikeesto — APPROVED** [review]
LGTM, thanks @aquibbaig

**Comment by mikeesto** [comment]
The CI failing here is unrelated, I will open an issue

**Pull request merged**
