### PR TITLE
nodejs-zh-TW: Add/Improve some translations

### PR DESCRIPTION
**Pull request by osk2**
1. Improve current translation of index:
  - index.md
  - site.json

2. Complete translation of download section:
  - current.md
  - index.md
  - package-manager.md
  - release.md

### CODE REVIEW

**Comment by dca** [comment]
👍

**Comment by siygle** [comment]
LGTM

**Review by PeterDaveHello — APPROVED** [review]
LGTM

**Review by jihchi — APPROVED** [review]
LGTM

**Comment by osk2** [comment]
Can we merge this yet?

**Pull request merged**
