### PR TITLE
Resolved grammatical error in privacy.md doc

### LINKED ISSUE #3752: Grammatical error in privacy.md doc
There is a grammatical error in privacy.md. ```Below, we provide a brief summary these activities.``` it should be "Below, we provide a brief summary  **of** these activities."

Screenshot
img1

### PR DESCRIPTION
**Pull request by av1shek**
Issue #3752 resolved

### CODE REVIEW

**Review by nschonni — APPROVED** [review]

**Review by benjamingr — APPROVED** [review]

**Comment by benjamingr** [comment]
Thank you for your first(?) contribution to Node.js!

**Comment by benjamingr** [comment]
Collaborators, 👍  to fast track

**Comment by benjamingr** [comment]
I, in my sleep-deprived new-baby glory for some odd reason missed this isn't nodejs/node and stared at node-core-utils trying to figure out why PR 3753 isn't this 😅 

Apologies for the mishap. Since I am not a website maintainer I'll dismiss my review and let you proceed as usual <3

**Comment by ghost** [comment]
@benjamingr: Waiting for your review and merge...
image

**Review by benjamingr — APPROVED** [review]

**Comment by nschonni** [comment]
@av1shek sorry, I tried to close and re-open to get around the "stuck" check from above, but it won't let me re-open. Can you please resubmit this one?

**Comment by nschonni** [comment]
Ah, hovering over the button "The repository that submitted this pull request has been deleted". And since this repo requires the branch to be up-to-date, as soon as you deleted your fork, it couldn't be landed

**Pull request closed without merging**
