### PR TITLE
Node.js Interactive 2016 banner

### PR DESCRIPTION
**Pull request by mikeal**
Here's a banner for Node.js Interactive 2016.

It scales with various widths and changes to a single column on mobile, as you can see through the various screenshots.

screen shot 2016-03-21 at 4 55 47 pm
screen shot 2016-03-21 at 4 55 54 pm
screen shot 2016-03-21 at 4 56 08 pm

### CODE REVIEW

**Comment by mikeal** [comment]
Oh, and I ran the images through ImageOptim before committing them this time ;)

**Comment by ghost** [comment]
[Travis build passed](https://travis-ci.org/nodejs/nodejs.org/builds/117598707) :+1:

**Comment by lpinca** [comment]
Looks great.

**Comment by benjamingr** [comment]
Looks very nice. I'm wondering @mikeal - is there any discount for org members in either of these events?

**Comment by mikeal** [comment]
@benjamingr I'll check with people about getting a discount out to the foundation individual members and send that out to them via email, but it'll end up being a discount on a standard reg price, so the current $250 price is probably the best you're going to get :)

**Comment by benjamingr** [comment]
Thanks for checking :)

**Pull request merged**
