### PR TITLE
fix: 404 generation and circular dependencies

### PR DESCRIPTION
**Pull request by ovflowd**
## Description

This PR fixes the 404 generation for our Statically Exported Website, as NGINX loads the /{locale}/404.html file, but that was not being generated anymore.

Besides that, for pages that import the `Theme` component and have `children` we should only compare the `content` and `frontmatter` as Stringifying `children` will cause circular dependencies within the JSON lookup.

Finally, we fixed the server-side and client-side mismatch of the default Next.js 404's page (which is used on our SSR server, differently from the statically generated 404 pages (which should eventually be removed) as Next.js (for some reason) will always tell to the server that the URL when on a 404 page is `/404` even tho the server has the context of the actual URL/route. Causing server/client render mismatch.

## Validation

- 404 files should be generated statically with `npm run deploy`
- Custom `404.tsx` page (SSR) should be rendered without errors

### CODE REVIEW

**Comment by ovflowd** [comment]
cc @nodejs/website requesting a fast track here!

**Review by bmuenzenmeyer — APPROVED** [review]
code looks good. I was trying to use the preview to validate this. best i could imagine was

- before: ❌ https://nodejs.org/en/not-a-real-route - nginx 404
- after: ✅ https://nodejs-org-git-fork-ovflowd-fix-404-routing-openjs.vercel.app/en/not-a-real-route - controlled 404

**Comment by ovflowd** [comment]
FYI previews should not be used for validating this PR as the Next.js 404 page is used (404.tsx)

Only way to validate is that the /locale/404.html file exists on the static build.

**Comment by bmuenzenmeyer** [comment]
> Only way to validate is that the /locale/404.html file exists on the static build.

another thing for me to look into then, as `npm run deploy` fails on Windows

**Pull request merged**
