### PR TITLE
Refactor/fix: attempt at making notificationProvider only render on client efficiently

### LINKED ISSUE #6629: Optimization Suggestions for NotificationProvider Component in Next.js Project
## Environment
- **Path:** `./providers/notificationProvider.tsx`

## Description
During a code review of the `NotificationProvider` component, two primary concerns were identified that may impact performance and client-side rendering behavior. Addressing these concerns could **_potentially_** enhance the component's efficiency

#### 1. Lack of Client-Side Rendering Indication
The component manages state and side effects, which are relevant primarily to client-side execution. However, there's no explicit indication or control to ensure that this code executes only on the client side. This absence could lead to unnecessary execution paths or errors during server-side rendering processes in Next.js. 

#### 2. UseEffect Dependency on Object State
The implementation uses `notification`, an object, as a dependency in a `useEffect` hook. Given that objects in JavaScript are reference types, this setup can lead to unnecessary executions of the effect. The effect, which clears a timeout based on `notification?.duration`, will re-run on any change to `notification` — even if the actual content remains unchanged. This behavior can introduce performance inefficiencies.

#### 1. Implement Explicit Client-Side Execution Control
To ensure that the component's logic executes only in environments where it's applicable, consider utilizing Next.js's client-side rendering capabilities more explicitly. This control could be achieved through dynamic imports with `{ ssr: false }` or by using client-side hooks that defer rendering until the client environment is confirmed.

#### 2. Optimize `useEffect` Dependencies
To mitigate unnecessary effect executions tied to the `notification` state, it may be beneficial to:
- Decompose the state and use a more primitive aspect (like `notification?.duration`) as the dependency.
see - [react docs](https://react.dev/reference/react/useEffect#removing-unnecessary-object-dependencies)
```typescript
  useEffect(() => {
    const timeoutId = setTimeout(() => dispatch(null), notification?.duration);

    return () => clearTimeout(timeoutId);
  }, [notification?.duration]);
```
- Implement a custom hook for deep comparison of the relevant parts of `notification`, or memoize the state where applicable to prevent the effect from running more than necessary.

### PR DESCRIPTION
**Pull request by mAmineChniti**
## Description

Making sure this componenet Effect is only running on client by checking if notification && typeof window !== 'undefined', this is more of a hacky solution i'm open to request of changes and more guidance
## Related Issues

Fixes #6629 
### Check List

- [X] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [X] I have run `npx turbo format` to ensure the code follows the style guide.
- [X] I have run `npx turbo test` to check if all tests are passing.
- [X] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by mAmineChniti** [comment]
hey @ra2u18 is this in line with what you were thinking about and if not how can i improve it?

**Comment by ovflowd** [comment]
Sorry for being the bringer of bad news, but effects by definition only run within the client side, these changes are unnecessary.

**Comment by mAmineChniti** [comment]
@ovflowd hey thanks for the feedback, i'm still just a beginner to frontend.
would checking if notfication exists and that its duration > 0 optimize this component rendering a bit?

**Comment by ovflowd** [comment]
No worries! I don't think any optimisation is needed. Afaik the component is already working as expected, and it has no performance issues or anything of sort.

Or have you noticed something? 🤔

**Comment by mAmineChniti** [comment]
Not really i haven't noticed anything again thank you for the feedback again.

**Comment by ovflowd** [comment]
No worries! I appreciate the time you've put into this 🙇

**Pull request closed without merging**
