### PR TITLE
add SVG version of new logo

### PR DESCRIPTION
**Pull request by silverwind**
My attempt at converting https://github.com/nodejs/nodejs.org/blob/master/static/images/logos/nodejs-new-pantone-white.ai to a small size SVG. I suspect the colors in the source file are off a bit (they are pretty dull on the 'o'), so I went ahead and manually rewrote the gradient `<stop>`s. Note that the gradients are a approximation. Also, I cropped the viewBox.

### CODE REVIEW

**Comment by silverwind** [comment]
also compare with the .png:
- [png](https://github.com/nodejs/nodejs.org/blob/master/static/images/logos/nodejs-new-white-pantone.png)
- [svg](https://github.com/silverwind/nodejs.org/blob/new-logo-svg/static/images/logo-new.svg)

**Comment by silverwind** [comment]
The gradients need some slight tuning, will follow up.

**Comment by lpinca** [comment]
Colors are only slightly different, I had to check with a color picker, can't see the difference with my eyes so looks good to me.

**Comment by silverwind** [comment]
Did a few minor tweaks. I'd say it's pretty flawless now. Merge at will.

**Comment by lpinca** [comment]
Can someone weigh in? The gradient difference is negligible imho, LGTM.

**Comment by fhemberger** [comment]
FYI: I just merged #880 to get the logo issue fixed while you're fine-tuning the svg version. As soon as it's ready, please go for it!

**Comment by silverwind** [comment]
I'll do one more pass on tuning the gradients.

**Comment by lpinca** [comment]
I really appreciate the effort here, but can't we ask whoever designed the logo to give us the updated `.ai` or `.svg`?

**Comment by fhemberger** [comment]
If you can find out who did it …

It's the same with #600 (or #870). We **know** the AI file is incorrect, but it's hard to get someone from the Foundation (or anybody else involved) to reply.

**Comment by lpinca** [comment]
@fhemberger gotcha, ignore my previous comment then.
Ping @gtewallace.

**Comment by zeke** [comment]
Thanks for making this, @silverwind. I was surprised to find that only AI files are available for download on the website.

It would be great to also link to this new SVG file from the https://nodejs.org/en/about/resources/ page.

**Comment by zeke** [comment]
cc @mikeal, who said on https://github.com/nodejs/nodejs.org/issues/526#issuecomment-192488194

> I have a zip file with a bunch of the noted variants in different formats.

**Review by zeke — APPROVED** [review]

**Comment by silverwind** [comment]
Did a few very minor tweaks to the main gradient before the merge. I'll go ahead and replace the old PNG in another PR.

**Pull request merged**
