### PR TITLE
Update nodejs-docker-webapp.md with shut down section

### PR DESCRIPTION
**Pull request by cdehaan**
Explain how to kill the container we made in the "_Dockerizing a Node.js web app_" documentation.

### CODE REVIEW

**Comment by Trott** [comment]
@nodejs/docker In addition to reviewing the material added in this PR, I'd be interested to know if the information in the file in general isn't done somewhere else better or more canonically. (Maybe a file in the nodejs/docker-node repo?) I wouldn't be surprised at all if a lot of the information in this file is out of date and rather than try in vain to keep it updated, we might be better referring people elsewhere.

**Comment by cdehaan** [comment]
Although not directly answering your question, this page served as one of the more accessible Node.js+Docker introduction documentation pages, and it would be a shame to see it gone in favour of links.

**Review by Gemk83 — APPROVED** [review]

**Comment by Trott** [comment]
@nodejs/website

**Review by ovflowd — APPROVED** [review]
LGTM 👀

**Review by osk2 — APPROVED** [review]

**Pull request merged**
