### PR TITLE
Add Node Knockout to the events page

### PR DESCRIPTION
**Pull request by lpinca**
This adds the Node Knockout event as requested in #311.

### CODE REVIEW

**Comment by lpinca** [comment]
Unrelated but I wonder if it's better to change the intro text:

```
The Node.js community is committed to bringing you events from around the world, currently spanning the US, Europe and Japan.
```

to just:

```
The Node.js community is committed to bringing you events from around the world.
```

**Comment by rnsloan** [comment]
:+1:  to changing the intro text and the PR

**Comment by bnb** [comment]
+1 to the PR and making that change.

**Comment by lpinca** [comment]
Updated to also change that sentence.

**Pull request merged**
