### PR TITLE
Update Interactive US banner with Dec 2nd date

### LINKED ISSUE #870: Wrong interactive US end date?
@mikeal what's the correct end date for interactive US? You changed it in https://github.com/nodejs/nodejs.org/commit/b185dfe917dbcfa80d32acabe727fef439ba9fd2 but the alt-text and text in the image isn't the same...

Refs https://twitter.com/wa7son/status/766633689220546560

### PR DESCRIPTION
**Pull request by williamkapke**
Fixes #870

### CODE REVIEW

**Comment by williamkapke** [comment]
Hm, looks like the current one has some transparency and the new one doesn't. I'll see if I can modify it.

**Comment by williamkapke** [comment]
I couldn't modify it myself. Cassandra has asked for an updated one- which she'll relay to me.

**Comment by williamkapke** [comment]
Ok- pushed the latest they sent me. It seems a bit different...? The color is off :/

With @phillipj 's #909 this might not make a difference. Some please tell me if I need to go back and ask for another version or merge it!

**Review by phillipj — APPROVED** [review]
LGTM, as you said the slight brightness difference will not be an issue with the EU banner removed

**Review by lpinca — APPROVED** [review]
LGTM once #909 is merged.

**Comment by phillipj** [comment]
Thanks for pinging the right people and fixing this  @williamkapke 👌

**Pull request merged**
