### PR TITLE
Remove outdated 'get-involved/development' page

### PR DESCRIPTION
**Pull request by fhemberger**
The content of the 'development' page was outdated and written in a way too long
and complex manner. Currently, there are two documents, explaining the
overall governance and contribution process in detail:

- https://github.com/nodejs/node/blob/master/GOVERNANCE.md
- https://github.com/nodejs/node/blob/master/CONTRIBUTING.md

Both documents go into a level of detail that IMHO aren't suitable for a general
"get involved" text like on the website, so only the following sections were added:

- Where to get general help (linking Node.js help repository)
- Code contribution guidelines (CONTRIBUTING.md#pull-requests)
- What are 'Collaborators', who appoints them and how can I become one

Other changes:

- Removes menu item from all translations
- Fix links and minor layout issues in 'get-involved/index' (ca, en, es, uk)
- Remove note about last Fall's collab summit's Code + Learn (en)

Fixes: #758

### CODE REVIEW

**Comment by fhemberger** [comment]
@nodejs/nodejs-uk `get-involved/contribute.md` must be updated to match the latest changes. For the moment, I commented out a section of the page. Would be great if you could help translating it.

**Review by Trott — APPROVED** [review]
LGTM. Am I mistaken or does this not really remove the page? It removes links to it but it will still exist? (Fine by me either way.)

**Comment by fhemberger** [comment]
@Trott Whoops, you're right. Forgot to delete the page … fixed!

**Comment by Trott** [comment]
+26 −812   🎉

**Review by lpinca — APPROVED** [review]

**Pull request merged**
