### PR TITLE
Style tweak for download buttons

### PR DESCRIPTION
**Pull request by refack**
Fixes: #1232

image

Please, please, please review this, as I have been told many times that I'm design blind.

/cc @nodejs/website

### CODE REVIEW

**Comment by gibfahn** [comment]
I think this looks nice, but I'm not sure it looks more like a button...

**Comment by silverwind** [comment]
It's better than before, but I think styling them as tabs (so they're above the OS download buttons) may be even better.

**Comment by lpinca** [comment]
Refs: https://github.com/nodejs/nodejs.org/issues/947

**Comment by refack** [comment]
New version

image

**Comment by jrit** [comment]
New design looks a lot better/clearer. It looks like the tabs may not be the same width in your screenshot though.

**Comment by refack** [comment]
I'd like to shrink then both down to a fixed 260px width, but had trouble with all the flex-boxes. I wanted some preliminary feedback before I start fighting...

**Comment by jseijas** [comment]
I like it :+1: But I'm also design blind :cold_sweat:

**Comment by silverwind** [comment]
Looking good. I think you could also experiment with adding the border around the whole box and maybe removing the background from the inactive tab.

**Comment by refack** [comment]
Thank for the +1, so I dug and got to where I wanted:

---

image

**Comment by iliakan** [comment]
That's better (5 cents)

**Comment by lpinca** [comment]
Looks good on tablet/desktop, not so good on mobile :)

**Comment by refack** [comment]
Any ideas what to do for `@media (max-width: 700px)`
image

**Comment by silverwind** [comment]
> Any ideas what to do for @media (max-width: 700px)

Hide the subtitle.

**Comment by silverwind** [comment]
BTW, I think having full-width tabs in all resolution might look better. Maybe try what I suggested in https://github.com/nodejs/nodejs.org/pull/1233#issuecomment-303194611.

**Comment by refack** [comment]
I found an option (I shrank the subtitle a bit)
image
But on mobile we don't have hover, so it this enough?

**Comment by refack** [comment]
Let's vote:
## 👍 for fixed-width with tabs

image
image

##   ❤️  &nbsp;for full-width tabs
image
image

**Comment by refack** [comment]
@pierreneter thanks.

**Comment by pierreneter** [comment]
I think we should choose `fixed-width with tabs` style. Look good!

**Comment by lpinca** [comment]
@pierreneter I prefer full-width tabs especially on mobile. If I'm not wrong there is an ongoing? vote. Let's wait for more feedbacks.

cc: @nodejs/website

**Comment by silverwind** [comment]
FWIW, my attempt below, might not look as great as I thought it would:



BTW you can remove the `width` hacks on the `.download-hero .download-version-toggle` and `.download-hero ul` rules, flexbox already takes care of that.

**Comment by refack** [comment]
> BTW you can remove the width hacks on the .download-hero .download-version-toggle and .download-hero ul rules, flexbox already takes care of that.

Ack.
But I had to add `padding-right 4px` to the `@media (max-width: 700px)`. Don't know where those 4px come from...

**Comment by silverwind** [comment]
> Don't know where those 4px come from

Could be some border. Hopefully `box-sizing: border-box` is active.

**Comment by refack** [comment]
@nodejs/website I think we have a majority for the stretched width (that's the current state in the PR)...

**Comment by lpinca** [comment]
@refack at 320px there is a small issue, see the screenshot.

screenshot at 2017-05-30 15-43-31

**Comment by fhemberger** [comment]
@refack I'd like to get this change merged, could you please have a look at the small issue @lpinca mentioned?

**Comment by refack** [comment]
> @refack I'd like to get this change merged, could you please have a look at the small issue @lpinca mentioned?

Slipped under my radar. Will do first thing in the morning.

**Comment by refack** [comment]
>> @refack I'd like to get this change merged, could you please have a look at the small issue @lpinca mentioned?
>
> Slipped under my radar. Will do first thing in the morning.

Well no time like the present so; Fixed. (Added a 320px breakpoint with smaller fonts)
(BTW: who uses a 320px wide screen to download node?)

**Comment by refack** [comment]
Ping @fhemberger

**Comment by lpinca** [comment]
It's very to hard to read the text at 320px now but as you said I think no one uses a screen with that resolution.

**Review by lpinca — APPROVED** [review]

**Comment by refack** [comment]
@fhemberger anything I need to do?

**Comment by fhemberger** [comment]
Sorry, missed the last comment. I'll have a look over the weekend.

**Comment by fhemberger** [comment]
Awesome, thank you! If we come up with a better idea for the 320px text, we can do so in a separate PR. But that button style was bugging a lot of people. 😀

**Pull request merged**
