### PR TITLE
feat: merge and improve codebox and shellbox

### PR DESCRIPTION
**Pull request by araujogui**
## Description

Merge Codebox and Shellbox components.

### Check List

- [ ] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [ ] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [ ] I have run `npx turbo format` to ensure the code follows the style guide.
- [ ] I have run `npx turbo test` to check if all tests are passing, and/or `npx turbo test:snapshot` to update snapshots if I created and/or updated React Components.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
Please don't touch to shellbox I have correct on installTabs

**Comment by ovflowd** [comment]
@AugustinMauroy I have asked @araujogui to make this PR.

I mentioned a long while ago I wanted the two components to become one.

**Comment by AugustinMauroy** [comment]
I thinks you can add copyToClipord in props and use the logic of shellBox.
And what do you thinks about a possibility to disable the hightlight ?

**Comment by ovflowd** [comment]
**FYI:** We deleted the `major/website-redesign` branch to simplify our release and rollout process. Please feel free to recreate this PR or reopen it with the `main` branch as a target.

Thank you, and we apologise for the inconvenience!

**Pull request closed without merging**
