### PR TITLE
Update 2 links: safe-regex & rxxr2

### PR DESCRIPTION
**Pull request by ghost**
In: "Don't Block the Event Loop (or the Worker Pool)" there are two broken links/404s. 

Under sub-heading: "Anti-REDOS Resources", I updated them to (what I think are) their current GitHub repos.

safe-regex - https://github.com/davisjam/safe-regex

rxxr2 - https://github.com/superhuman/rxxr2

I could do the same in the other languages too. Not sure how that works.

### CODE REVIEW

**Review by aymen94 — APPROVED** [review]

**Comment by aymen94** [comment]
Thanks for your first contribution! 🙂

**Review by Trott — APPROVED** [review]

**Comment by ghost** [comment]
Ok, I think I finally got the signing key thing figured out :)

Should I push another commit to my branch or is there a way to update this commit here?

I found another a dead link, and I can't find what it pointed to. It's the link on line 375 with the text: "these slides"

**Review by AugustinMauroy — APPROVED** [review]

**Comment by ovflowd** [comment]
> Ok, I think I finally got the signing key thing figured out :)

Yeah, you still have the first commit marked as unsigned. But that's fine, we can make an exception. But if you want to have all commits signed, you can read this: https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits

Your PR is fine, I'm only going to merge it after the code freeze that we're having right now.

**Comment by ovflowd** [comment]
@beeburrt I think you need to rebase this PR :)

**Comment by ghost** [comment]
> @beeburrt I think you need to rebase this PR :)

ok. I appreciate your help by the way. Sorry to have bungled this, I'm still pretty new.

So my fork is now 35 commits behind and 4 commits ahead. Would it leave a total mess behind if I sync my repo first? Essentially ditching my four commits.

Is a rebase something I can do here on GitHub UI?

Or maybe I just close this PR, sync my fork, and then redo the changes?

**Comment by ovflowd** [comment]
For the changes you've made it's easier to reclone the repository and make your changes again.

**Comment by ghost** [comment]
> For the changes you've made it's easier to reclone the repository and make your changes again.

Ok. Thank you for your time :)

**Pull request closed without merging**
