### PR TITLE
Adds WG membership section to the README. For #13

### PR DESCRIPTION
**Pull request by snostorm**
Other members, please add yourself to the list :)

### CODE REVIEW

**Comment by snostorm** [comment]
I was assuming alphabetical by first name, so that's why (for now) I'm at the top of the list.

**Comment by snostorm** [comment]
Ping @nodejs/website : if you're a WG member or collaborator, please add your name to this PR

**Comment by Fishrock123** [comment]
cc @indexzero (Since I know he still wants to be involved.)

**Comment by fhemberger** [comment]
@snostorm Can we merge this into master? So far we have six people on board, further members can just go ahead and add themselves later.

**Comment by fhemberger** [comment]
@nodejs/website Any objections about merging this?

**Comment by fhemberger** [comment]
Rebased via 101aa109f54ee09d1ed7f314ce66b3f10434802e and following.

**Pull request closed without merging**
