### PR TITLE
fix: align mdx

### PR DESCRIPTION
**Pull request by ovflowd**
This PR realigns all `index.mdx` files from all languages. Note that there might be other MDX files with discrepancies too 🤷

### CODE REVIEW

**Comment by ovflowd** [comment]
Requesting fast-tracking! cc @nodejs/nodejs-website

**Comment by bmuenzenmeyer** [comment]
@ovflowd if these were passing lint before, is that indicative that we were not linting/formatting them, or ???

i dont want another crowdin sync to clobber all this, or rather, if the whitespace is unimportant, why fix it

**Comment by ovflowd** [comment]
> @ovflowd if these were passing lint before, is that indicative that we were not linting/formatting them, or ???
> 
> i dont want another crowdin sync to clobber all this, or rather, if the whitespace is unimportant, why fix it

This has nothing to do with linting. It is a prettier bug. Linting-wise both are valid.

**Comment by ovflowd** [comment]
> i dont want another crowdin sync to clobber all this, or rather, if the whitespace is unimportant, why fix it

🤷 -- afaik my changes will override that.

**Comment by bmuenzenmeyer** [comment]
interesting, we call prettier directly within https://github.com/nodejs/nodejs.org/blob/main/.github/workflows/translations-pr.yml#L116-L119 instead of using our `lint:fix` script.

**Review by AugustinMauroy — APPROVED** [review]

**Review by bmuenzenmeyer — APPROVED** [review]

**Comment by ovflowd** [comment]
> interesting, we call prettier directly within [`main`/.github/workflows/translations-pr.yml#L116-L119](https://github.com/nodejs/nodejs.org/blob/main/.github/workflows/translations-pr.yml?rgh-link-date=2024-11-22T16%3A13%3A37Z#L116-L119) instead of using our `lint:fix` script.

Follow-up issue to investigate that?

**Comment by ovflowd** [comment]
FYI here's the master issue for MDXv3 for prettier: https://github.com/prettier/prettier/issues/12209

**Pull request merged**
