### PR TITLE
Change 'library' translation

### PR DESCRIPTION
**Pull request by nhsz**
- 'librería' is a bad translation when we are talking about code in Spanish. We use the word 'biblioteca' instead, which refers to the place were we store, catalog and go to request/consult books.

### CODE REVIEW

**Review by zlatanvasovic — APPROVED** [review]

**Comment by zlatanvasovic** [comment]
Agreed. *biblioteca* is an usual Spanish word for library. I've never heard of *libreria* used in that context.

**Comment by pin3da** [comment]
Hi @nhquiroz in Colombia we use "librería" when we talk about code. Other countries (like Mexico, also use that word), I don't think that is a bad translation. 

If you prefer we can put both (librerías/bibliotecas de código abierto).

¡ saludos :smile: !

**Comment by lpinca** [comment]
@nhquiroz this is kinda funny, we have the same words in Italian and "biblioteca" is also used to refer to places where book are stored and can be rent like a university library but when we talk about code we use "libreria".

**Comment by nhsz** [comment]
Ok, maybe this becomes `undefined` :stuck_out_tongue:

I think we tend to use _librería_ in Spanish because it sounds very similar to _library_, but _librería_ means _book shop_ and that's not the intended use in the programming metaphor.

**Comment by edsadr** [comment]
this basically a regional problem, but I found that many official translations use *librería*, so that's what I used, a couple of examples here (warning... obviously is Spanish): 

* https://msdn.microsoft.com/es-es/library/hh875057.aspx
* https://developer.mozilla.org/es/docs/Gecko_SDK

we can vote anyway...

**Comment by nhsz** [comment]
@edsadr I agree with that.

**Comment by edsadr** [comment]
@nhquiroz so ... safe to close this one?

**Comment by nhsz** [comment]
Yes.

**Pull request closed without merging**
