### PR TITLE
Update HomeDownloadButton.tsx

### PR DESCRIPTION
**Pull request by CodingRule**
make the component more reusable isLts coul;d have a better meaning  => isLatestLtsVersion URLs and labels to constants at the top of the file annotations for the props and state

### CODE REVIEW

**Review by CodingRule — COMMENTED** [review]
Like I said I made the components more reusebel and other lil changes!

**Comment by ovflowd** [comment]
I appreciate the effort, but this code is going to be trashed and discarded pretty soon, so... I would rather not attempt to make changes here :)

**Comment by CodingRule** [comment]
Ohh ok! Where should I do some changes ?

**Comment by mikeesto** [comment]
@SpriteyOnTheDraconic There's some discussion here that may help you get up to speed on what the current goals for the website are: https://github.com/nodejs/nodejs.org/discussions/5131 , https://github.com/nodejs/nodejs.org/issues/5242

**Pull request closed without merging**
