### PR TITLE
Adds LICENSE

### PR DESCRIPTION
**Pull request by snostorm**
This was copied from the https://github.com/nodejs/iojs.org repo as-is (with a slight modification to the first line to mention "original contents".)
## Open Question(s):
- [ ] MIT as previously determined for the last project? See https://github.com/nodejs/iojs.org/issues/1
- [ ] Given we do not have ownership of some of the assets which may be bundled (namely logos), do we need to modify the license to reflect this? For now this is why I used the phrasing "original contents" in the opening line.

### CODE REVIEW

**Comment by snostorm** [comment]
_I wonder how long we can keep the trend going of our Issue #s in this project matching the same Issues in the iojs.org project ... So far we're 1 for 1!_

**Comment by bnb** [comment]
I think we need to talk to whatever lawyers the Node Foundation has about the licensing/logos deal. I assume the repo will bit MIT, but the logos will probably have to live with a WG. Website/Evangelism are the obvious ones. However, I know jack sh*t about law, so we need to consult someone who knows. Is there someone from the foundation that can direct us to the right place?

**Comment by bnb** [comment]
@therebelrobot I hate to keep bothering @rvagg with this stuff, but he seems to know what's going on with the Foundation and where to go/who to talk to about this stuff. 

Rod: Do you have an idea of where we can go for this? Also, is there someone else that we can/should have as a point of contact/information about the Foundation?

**Comment by rvagg** [comment]
Yes, I've started discussing some of this with them but will not likely connect the dots until next week. I'm going to try and connect some of the website & evangelism teams with appropriate people in LF so they can be used as a resource, at the moment there's a bit of a barrier between the community and the formal side of the foundation that we need to work on breaking down simply by connecting people together.

**Pull request merged**
