### PR TITLE
Update site.json of zh-cn locale

### PR DESCRIPTION
**Pull request by ovo4096**

### CODE REVIEW

**Comment by lpinca** [comment]
Can you please revert the changes applied to `package-lock.json`?

**Comment by ovo4096** [comment]
I can, but why revert it?

**Comment by lpinca** [comment]
@ovo4096 I think they are a mistake as I see no changes in `package.json`. Am I wrong?

**Comment by ovo4096** [comment]
@lpinca I noticed that the **fsevents** that were deleted in `package-lock.json` are optionalDependencies of **chokidar**, and when i execute `npm install` it is not installed.

So that **fsevents** is require?

**Comment by lpinca** [comment]
@ovo4096 I guess this is the result of running `npm install` in two different systems.

**Comment by ovo4096** [comment]
@lpinca The problem should be this: https://github.com/npm/npm/issues/17722

My system is Linux.

**Comment by lpinca** [comment]
Ping @nodejs/nodejs-cn.

**Comment by terry-fei** [comment]
👍

**Review by lpinca — APPROVED** [review]

**Comment by lpinca** [comment]
@ovo4096 Thank you!

**Pull request merged**
