### PR TITLE
fix: open external link in new tab for navbar items

### PR DESCRIPTION
**Pull request by hisamafahri**
## Description

Open external navigation bar's link in new tab

## Validation

If clicked in the `Certification` and `Docs` in the navbar, should open it in the new tab.

## Related Issues

None

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
Honestly, I'm not in favour of this change, because if a user wants to go to the docs and goes through nodejs.org, they'll end up with two tabs open, which will "take time" to close. I think that opening a new tab should only be done when the user needs to keep the source page open, which isn't the case here.

**Comment by hisamafahri** [comment]
@AugustinMauroy That's a good point. However, I believe the expectations for most users are to open the clicked link in a new tab whenever they see a top-right arrow (↗) since it is mostly used as an indicator for a link from another site.

Either way, whatever decision will be made (open in a new tab, remove the arrow, or even keep the current behaviour), I am all for it 🙆‍♂️ .

**Review by bmuenzenmeyer — APPROVED** [review]
I'm 👍 on this UX behavior

**Review by aymen94 — APPROVED** [review]

**Comment by bmuenzenmeyer** [comment]
@AugustinMauroy are you okay with moving this forward?

**Comment by AugustinMauroy** [comment]
> @AugustinMauroy are you okay with moving this forward?

I'm in favor of keeping this behavior. But modifying api docs link to not have icons and blank page.

**Comment by bmuenzenmeyer** [comment]
@AugustinMauroy i appreciate your thoughts but am going to merge this. it's generally common consensus that 

- the arrow means you are leaving the site
- its a courteous gesture in today's tab based browsing to open blank

if you feel strongly, please block it in future discussions

**Comment by bmuenzenmeyer** [comment]
that being said, some of the usage here is probably wrong (credit @ovflowd for mentioning this)
image

**Pull request merged**
