### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by lpinca**
- [`html-to-text@3.2.0`](https://github.com/werk85/node-html-to-text/blob/master/CHANGELOG.md#version-320)
- [`htmllint-cli@0.0.6`](https://github.com/htmllint/htmllint-cli/compare/v0.0.5...v0.0.6)
- [`js-yaml@3.8.3`](https://github.com/nodeca/js-yaml/blob/master/CHANGELOG.md#383--2017-04-05)
- [`junk@2.1.0`](https://github.com/sindresorhus/junk/compare/v2.0.0...v2.1.0)
- [`metalsmith-layouts@1.8.0`](https://github.com/superwolff/metalsmith-layouts/blob/master/History.md#180---february-3-2017)
- [`metalsmith-stylus@3.0.0`](https://github.com/esundahl/metalsmith-stylus/compare/d3bd869...9c222b3)
- [`node-geocoder@3.16.0`](https://github.com/nchaulet/node-geocoder/blob/master/CHANGELOG.md#3160)
- [`octonode@0.7.11`](https://github.com/pksunkara/octonode/compare/v0.7.7...v0.7.11)
- [`request@2.81.0`](https://github.com/request/request/blob/master/CHANGELOG.md#v2810-20170309)
- [`snyk@1.28.1`](https://github.com/snyk/snyk/releases)
- [`standard@10.0.2`](https://github.com/feross/standard/blob/master/CHANGELOG.md#1002---2017-04-14)

### CODE REVIEW

**Comment by lpinca** [comment]
Can we use Node.js >= 4.5.0 on Travis CI?

**Comment by fhemberger** [comment]
@lpinca They have all the current versions:
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions

**Comment by lpinca** [comment]
Yes, I got confused with the bot. Realized only after writing that comment that the version is actually pulled by Travis CI from `.travis.yml` :)

**Comment by lpinca** [comment]
Ping @nodejs/website.

**Review by silverwind — APPROVED** [review]

**Pull request merged**
