### PR TITLE
WIP: support multiple projects

### PR DESCRIPTION
**Pull request by phillipj**
Working on getting _both_ io.js and node supported, mainly related to downloads and versions. So far its been brute force just to get it up-n-running.

As we dont have a unified `versions.json` yet, as @mikeal mentioned in nodejs/build#163, I've just created a simple `unified_versions.json` for mocking purposes in the meantime.

Just duplicating _everything_ doesnt make sense and obviously doesnt look that great either. The frontpage didnt get too bad though, but the downloads page with its matrix and previous released versions is a whoooole different story.

image

Any thoughts about how this?

### CODE REVIEW

**Comment by fhemberger** [comment]
There's no need to support multiple projects. From version 4 on, there will be only Node.js.
Older versions of node/io.js will only be shown in the overall release list, which will by then become a separate page (with a looooong list).

**Comment by phillipj** [comment]
Ahh, so when you said

> Both. There still needs to be some work done to integrate the builds automatically into the site.

in issue #20 you only meant the previous release list?

**Comment by fhemberger** [comment]
Yes. The list should not only the converged release (starting with 4.0.0), but all io.js and node.js releases in a single spot. Sorry, if this caused a misunderstanding.

**Comment by phillipj** [comment]
Np, created a WIP to find out what needed to be done - great success in other words :tada:

Sounds alot simpler than what I had in mind. Closing this PR as it sounds trivial enough to fix quickly after build has a unified versions in `versions.json` ready.

**Comment by mikeal** [comment]
This came up in the TSC meeting a bit as well, we want to have a merged/complete Changelog as well and I want to try and create automated release posts from the Changelog+versions.js

**Pull request closed without merging**
