### PR TITLE
Add gzip task for production, fixes #712

### LINKED ISSUE #712: Store gzip representations of common files on deploy
Since we're using `gzip_static on` in the server we could shave off an considerable amount of cpu power by storing a gzip representation of each file we deploy (for instance `index.html` would be accompanied by `index.html.gz`). Additionally, since we default to `-6` in nginx, we'd likely make each file a bit smaller by using `-9` on deploy.

### PR DESCRIPTION
**Pull request by fhemberger**
Ref: #712
/cc @jbergstroem

### CODE REVIEW

**Comment by jbergstroem** [comment]
That was quick! LGTM (haven't tested but flags and formats looks good to me); here are the content types we (would) gzip, so it should match well: `gzip_types text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript;`

**Comment by fhemberger** [comment]
@jbergstroem You don't gzip `text/html`?

**Comment by jbergstroem** [comment]
@fhemberger from nginx manual: "Responses with the “text/html” type are always compressed."

**Comment by fhemberger** [comment]
@jbergstroem Ah, ok. Merging this now.

**Comment by jbergstroem** [comment]
Cool. Does this mean that it'll be shipped with next version of docs/website?

**Comment by fhemberger** [comment]
I guess all that's left to do is replacing the line here (https://github.com/nodejs/build/blob/master/setup/www/resources/scripts/build-site.sh#L28):

``` diff
-  build_cmd="npm run build"
+  build_cmd="npm run build; npm run gzip"
```

**Comment by jbergstroem** [comment]
Ok. Want to PR?

**Comment by fhemberger** [comment]
@jbergstroem https://github.com/nodejs/build/pull/405

**Pull request merged**
