### PR TITLE
Reformat of blog posts

### PR DESCRIPTION
**Pull request by elinnet**
A 5 line summary of the blog post has been created to help users navigate useful blogposts.  A 'read more' link has also been added

### CODE REVIEW

**Comment by rvagg** [comment]
would you mind posting a screenshot of what's changed?

**Comment by elinnet** [comment]
Sure - no problem - I've attached to this message.

**Comment by rvagg** [comment]
didn't come through, if you go to github you can do it in the comment box and they'll appear inline

**Comment by elinnet** [comment]
Hi - I've attached the screnshot below

screen shot 2015-09-15 at 07 59 16

**Comment by rvagg** [comment]
That's much nicer than the current simple list, good work!

A couple of suggestions from me (I'm not on the website team so will defer to them, perhaps they don't agree):
- let's remove the `<ul>` completely, the dots seem pointless now
- Include the date in the link or switch them so the date comes second, there's something that feels odd about the dates leading

**Comment by iancrowther** [comment]
+1 to remove bullets, the heading styling is enough to imply a new article.

{{title}} - {{date}} makes sense to me as the title is the primary information.

**Comment by fhemberger** [comment]
Looks really sweet!

For semantics, we should stick to `<ul>` (because it's a list of items), but we can remove the bullet.

We should also find a way to break the blog index list down into one page per year. Otherwise the list will be way too long. I don't have much time right now, so if anybody has a good idea how to handle this …

**Comment by mikeal** [comment]
Love it.

**Comment by Fishrock123** [comment]
Does this always guarantee to split on whitespace for where it ends the summary?

Also could we add an ellipsis character to the end of the summary, before the link? (`…`)

**Comment by fhemberger** [comment]
@elinnet I'd love to merge your PR. Can you please have a quick look at the merge conflicts?

**Comment by phillipj** [comment]
I'm inclined to resolving the merge conflict manually, as this looks so much better than what we've got on nodejs.org atm :smile:

**Comment by fhemberger** [comment]
@phillipj Knock yourself out. :smile:

**Comment by phillipj** [comment]
These changes, with some additions, just landed in cbeb2a099c51f4f0a2778aa3f0482626215fc2fa, thanks @elinnet and @xicombd!

**Pull request closed without merging**
