### PR TITLE
zh-CN：Trans for 'diagnostics-flamegraph.md'

### PR DESCRIPTION
**Pull request by ghost**
1) Trans for Chinese of the file：'diagnostics-flamegraph.md'.
2) Fix some typo errors in the related English version.

Ref：https://github.com/nodejs/nodejs.org/pull/1444

### CODE REVIEW

**Comment by ghost** [comment]
@naugtur：Please have a review, there're some changes in the English version.

**Comment by ghost** [comment]
@nodejs/nodejs-cn：Please have a review of translation, thanks!

**Review by willin — APPROVED** [review]

**Review by ZYSzys — APPROVED** [review]
LGTM

BTW, maybe it’s a good time to update all node or Node to Node.js for consistency  :)

**Review by Lellansin — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
@ZYSzys：Thanks and I've unioned all in both English and Chinese.

**Comment by ZYSzys** [comment]
Cool ! Thank you~ 👍

**Comment by naugtur** [comment]
Great work, sorry I was not available earlier.

**Pull request merged**
