### PR TITLE
Revert "meta: switch v6.x to LTS (#973)"

### PR DESCRIPTION
**Pull request by MylesBorins**
For the release of v7.0 we should revert commit 8c53b4b0a0a

This can be trumped by #990 if it is ready for release before v7 is cut

### CODE REVIEW

**Comment by phillipj** [comment]
@TheAlphaNerd I took the liberty of pushing a commit needed for the navigation links on the Docs page, as they were hard coded to v4.x and v6.x, which would be an issue whenever v7 get released.

screen shot 2016-10-25 at 09 18 23

**Comment by MylesBorins** [comment]
thanks @phillipj 

@jasnell this is ready to land when the v7 release is promoted

**Comment by jasnell** [comment]
Landed

**Comment by MylesBorins** [comment]
landed in 0a5d54210e7170d9690383fc992114fcf432a51e...55012f3df52586dcba8e0bf5938caeb2e543991b

**Pull request closed without merging**
