### PR TITLE
Update index.mdx

### PR DESCRIPTION
**Pull request by TheTempest76**
Updated link to '/pages/en/learn/asynchronous-work/overview-of-blocking-vs-non-blocking.md' to reflect correct location

## Description

This pull request updates the [blocking vs non-blocking] link to /pages/en/learn/asynchronous-work/overview-of-blocking-vs-non-blocking.md.

### CODE REVIEW

**Review by mikeesto — CHANGES_REQUESTED** [review]
Hi. We don't want to link to a markdown file here... are you getting a 404 with the current link? (I'm not)

**Comment by TheTempest76** [comment]
hi, yes when i am on [this ](https://github.com/nodejs/nodejs.org/blob/main/pages/en/about/index.mdx )page and click on the blocking vs non blocking link i get a [404](https://github.com/nodejs/nodejs.org/blob/main/learn/asynchronous-work/overview-of-blocking-vs-non-blocking)  page

**Comment by mikeesto** [comment]
> hi, yes when i am on [this ](https://github.com/nodejs/nodejs.org/blob/main/pages/en/about/index.mdx)page and click on the blocking vs non blocking link i get a [404](https://github.com/nodejs/nodejs.org/blob/main/learn/asynchronous-work/overview-of-blocking-vs-non-blocking) page

You can see the rendered page here: https://nodejs.org/en/about . When viewing the MDX file directly, the links may not work as expected because the file is not being served by a web server and does not have access to the same routing and navigation as the live website.

**Comment by TheTempest76** [comment]
ok, thanks for clarifying. I didn't know that's how it worked.

**Pull request closed without merging**
