### PR TITLE
feat: add metalsmith-one-replace plugin for dynamic contents

### PR DESCRIPTION
**Pull request by MrJithil**
We have added a new metalsmith plugin `metalsmith-one-replace`.

The major intention I added here to replace the `Built-in Debugger` URL was too old and needs to be pointed to the `LTS` version.
Now, we don't want to change the URLs each time we released a new `LTS`. The plugin will dynamically generate the URLs.

Evidence:
NodeJsLatestDebuggerUrl

### CODE REVIEW

**Comment by Trott** [comment]
I think we're better off pointing at https://nodejs.org/docs/latest/api/debugger.html. I don't know why we'd have to point at LTS. Either way, the docs are going to be wrong when 16.x becomes LTS in October because 16.x does not have `node debug script.js` as described in that document. It needs to be updated to use `node inspect script.js` instead.

**Comment by MrJithil** [comment]
> I think we're better off pointing at https://nodejs.org/docs/latest/api/debugger.html. I don't know why we'd have to point at LTS. Either way, the docs are going to be wrong when 16.x becomes LTS in October because 16.x does not have `node debug script.js` as described in that document. It needs to be updated to use `node inspect script.js` instead.

Since the LTS is recommended for most users, who are more new to the NodeJS sometimes, in my opinion, we should point to LTS rather than the current version.

Anyway, this plugin can dynamically replace the versions. So, in that case, whenever we change an LTS version, it will reflect after a build and deployment. 

For eg: if we want to switch to the current version, we can change the code as below:
```
varValues: {
    currentVersion: `latest-${latestVersionInfo.current.nodeMajor}`
}
```

So, we can merge this pull request, and open a discussion if we need to finalize the version later. In the future, it will be a single-line change. 
CC: @Trott

**Comment by Trott** [comment]
> Since the LTS is recommended for most users, who are more new to the NodeJS sometimes, in my opinion, we should point to LTS rather than the current version.

Sure, I'm good with that.

**Comment by MrJithil** [comment]
> > Since the LTS is recommended for most users, who are more new to the NodeJS sometimes, in my opinion, we should point to LTS rather than the current version.
> 
> Sure, I'm good with that.

Thanks @Trott

**Comment by MrJithil** [comment]
> > Since the LTS is recommended for most users, who are more new to the NodeJS sometimes, in my opinion, we should point to LTS rather than the current version.
> 
> Sure, I'm good with that.

@Trott  Could you please review these changes?

**Comment by Trott** [comment]
@XhmikosR Is this something you're comfortable reviewing?

**Review by Trott — APPROVED** [review]
LGTM

**Comment by XhmikosR** [comment]
> 
> 
> @XhmikosR Is this something you're comfortable reviewing?

Not thoroughly, but perhaps we don't need the plugin at all. We already parse and modify the content in the other custom plugins and this seems to be redundant, let alone it might slow things down (again, I haven't tested the patch).

I'd do this with a custom plugin like we do for anchor links, github links, and so on. Alternatively, I'd look into what else from the custom code could be done with the plugin so that things are more streamlined.

**Comment by MrJithil** [comment]
> > @XhmikosR Is this something you're comfortable reviewing?
> 
> Not thoroughly, but perhaps we don't need the plugin at all. We already parse and modify the content in the other custom plugins and this seems to be redundant, let alone it might slow things down (again, I haven't tested the patch).
> 
> I'd do this with a custom plugin like we do for anchor links, github links, and so on. Alternatively, I'd look into what else from the custom code could be done with the plugin so that things are more streamlined.

It's a built time plugin. So it won't slow down things as it's a one-time activity. Could you please provide the sample where we use the  `anchor links` replacements? So that I can refer and use it here too.

**Comment by MrJithil** [comment]
Can I close this pr? @Trott

**Comment by Trott** [comment]
@nodejs/website This looks OK to me, but I'd really like to get a more informed set of eyes on it. I don't pay that close attention to the website build process. Anyone able to look at this and give it a reasonably confident 👍  or 👎 ?

**Review by aymen94 — APPROVED** [review]

**Comment by Trott** [comment]
Thanks for your patience, @MrJithil!

**Comment by MrJithil** [comment]
Thanks @Trott

**Pull request merged**
