### PR TITLE
Revert "feat: minify HTML on build (#2537)"

### PR DESCRIPTION
**Pull request by tniessen**
This reverts commit 0cc3648df2741afbfdc29e43247e3dc0e6e44b66. Based on my estimations and calculations, the benefit is minimal, while making our build pipeline more complex, more time consuming, adding a dependency and making the output less readable. Contrary to assumptions in the original PR, the patch does not affect the docs.

(Also, @XhmikosR suggested that there might be a better alternative provided by Cloudflare.)

Refs: https://github.com/nodejs/nodejs.org/pull/2537

cc @nschonni @MylesBorins @aymen94 @bnb @Trott

### CODE REVIEW

**Comment by tniessen** [comment]
And to be clear, I am fine with closing this and leaving the commit as it is if that is what people want, but I believe that the original PR was landed prematurely.

**Comment by XhmikosR** [comment]
I agree, this should be reverted.

Now, I understand if we don't want to do this via Cloudflare, but the slowdown from this isn't justified by the gains IMHO.

**Review by MylesBorins — APPROVED** [review]
RSLGTM, we should turn it on with cloudflare imho

**Review by XhmikosR — APPROVED** [review]

**Comment by bnb** [comment]
SGTM. +1 to turning it on through CloudFlare, since that’s where the majority of our traffic is served from anyway AFAIK.

**Review by aymen94 — APPROVED** [review]

**Comment by aymen94** [comment]
if there is a better alternative, then so be it.

**Pull request merged**
