### PR TITLE
remove about/working-groups

### PR DESCRIPTION
**Pull request by Trott**
The working groups page is not needed, probably out of place under
"about", and (most importantly) duplicates material in the TSC repo but
is out of date. (The Undici WG is not in the page, for example.) Let
there be just one source of truth, which is the TSC repo.

### CODE REVIEW

**Review by AugustinMauroy — APPROVED** [review]

**Comment by ovflowd** [comment]
@Trott shouldn't we then redirect users to the proper page on TSC? How will they get to know about the current working groups otherwise? 🤔

**Comment by Trott** [comment]
> @Trott shouldn't we then redirect users to the proper page on TSC? How will they get to know about the current working groups otherwise? 🤔

I think it would be better to have (at most) a single page about getting involved. That can have links to working groups and whatnot. Right now, we have "Working Group" and "Governance" under "About", five separate things under "Get Involved" and (until recently) other things under About concerning the Community Committee (which was retired some time ago) and so on.

Rather than try to keep the website up to date with the repository, yes, link to the repository as the single source of truth.

But also: Rather than have links to the repository scattered all over the web page, choose a small number of focused/well-chosen links.

Working Groups are a bit of an anachronism anyway, if you ask me. Many of the most active teams that serve the function of a working group are not chartered working groups. And many of the chartered working groups are not active. So I think de-emphasizing them is probably a good idea.

**Comment by ovflowd** [comment]
> Rather than try to keep the website up to date with the repository, yes, link to the repository as the single source of truth.

Agreed.

> But also: Rather than have links to the repository scattered all over the web page, choose a small number of focused/well-chosen links.

Agreed.

> Working Groups are a bit of an anachronism anyway, if you ask me. Many of the most active teams that serve the function of a working group are not chartered working groups. And many of the chartered working groups are not active. So I think de-emphasizing them is probably a good idea.

Interesting! I had no idea. I'll also create an issue on the .dev repository to think about this and figure it out.

**Review by joesepi — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
