### PR TITLE
d/l: 32bit linux is experimental

### PR DESCRIPTION
**Pull request by refack**
Refs: https://github.com/nodejs/build/issues/885

### CODE REVIEW

**Comment by seishun** [comment]
What about when 32-bit builds stop being built?

**Comment by refack** [comment]
> What about when 32-bit builds stop being built?

IMHO new box should be removed.

**Comment by seishun** [comment]
Which new box?

**Comment by refack** [comment]
> Which new box?

The new link in `secondary-download-matrix.hbs`
image

**Comment by refack** [comment]
Cross-ref: https://github.com/nodejs/node/pull/16723

**Comment by seishun** [comment]
Ah, agree.

**Review by gibfahn — DISMISSED** [review]
Blocking so this doesn't get landed accidentally before https://github.com/nodejs/node/pull/16723 is resolved.

**Comment by gibfahn** [comment]
I think we should call out that it's experimental, I'm not even sure that it should continue to be on the main downloads page. I think we want to make sure people who are automatically downloading 32-bit builds notice the change (and come tell us that they still use 32-bit).

**Comment by refack** [comment]
I completely removed the listing of the 32 bit linux binary. If people will come looking for it hope they will raise an issue that it is missing.

**Comment by seishun** [comment]
@gibfahn unless it's required that Tier 1 and Tier 2 platforms must have public builds, I think this can be unblocked now.

**Comment by gibfahn** [comment]
>@gibfahn unless it's required that Tier 1 and Tier 2 platforms must have public builds, I think this can be unblocked now.

I think it's reasonable to say Tier 1 platforms should have public builds where possible.

**Comment by fhemberger** [comment]
Just merge it whenever you're ready.

**Pull request merged**
