### PR TITLE
asynchronously loading the webfont + caching it

### LINKED ISSUE #108: Font glitches while clicking around
Am I the only one seeing this on page load while clicking around? The text seems slightly bigger for the first few 100 milliseconds, before suddenly changing. Must be recent change as I havent noticed this before.

Chrome v45.

nodejs font glitch

### PR DESCRIPTION
**Pull request by fabiosantoscode**
Since #69 by @ddprrt had some conflicts, I rebased it and am pushing again.

This should close #108.

### CODE REVIEW

**Comment by mikeal** [comment]
@fhemberger this was rebased I think to resolve the merge conflicts. you had reviewed the prior patch, does this one look ok?

**Comment by fhemberger** [comment]
I only had a quick glance at the original patch (looked okay to me so far). Still, I'd like to have a closer look and reserve some time for testing.

**Comment by silverwind** [comment]
This whole XHR + localStorage stuff seems a bit excessive to me. Can't we just rely on native browser caching?

**Comment by silverwind** [comment]
Opened https://github.com/nodejs/new.nodejs.org/pull/178 for my attempt at this.

**Comment by silverwind** [comment]
Guess this one is kind of obsolete now with https://github.com/nodejs/nodejs.org/commit/aa4b373526fd3feb2c30bd6271e2872001e56c05.

**Pull request closed without merging**
