### PR TITLE
Arabic translations "get-involved"

### PR DESCRIPTION
**Pull request by Aissaoui-Ahmed**
for Arabic translate "get-involved" 
files : `index.md` `contribute.md` `collab-summit.md` `code-and-learn.md`
thank you @celyes !

@nodejs/nodejs-ar @InterstellarClub

### CODE REVIEW

**Comment by ghost** [comment]
@nodejs/nodejs-ar：Please have a review, thanks!

**Comment by celyes** [comment]
@Aissaoui-Ahmed @Maledong Any review?

**Comment by ghost** [comment]
@celyes：Not yet, but if you are free you can review and I'll help to merge :)

**Comment by Aissaoui-Ahmed** [comment]
@Maledong the code has been reviewed by @celyes before pushing to github

**Review by celyes — APPROVED** [review]
@Maledong Seems good to me

**Comment by ghost** [comment]
Thanks!

**Pull request merged**
