### PR TITLE
feat: added white hex svg logo

### PR DESCRIPTION
**Pull request by vaqueraoscar0**
## Description issue #5899 
Added white hex logo.

## Validation
Previewed changes using storyboard 

Screenshot 2023-09-27 at 9 01 21 AM

### Check List

- [X] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by AugustinMauroy — APPROVED** [review]
LGMT !

**Review by mikeesto — APPROVED** [review]
Thanks for your first contribution

**Review by aymen94 — APPROVED** [review]

**Comment by vaqueraoscar0** [comment]
@mikeesto @AugustinMauroy Thank you guys for the opportunity!

**Comment by AugustinMauroy** [comment]
We'd love to! Maybe we'll see you on another issue.

**Comment by vaqueraoscar0** [comment]
@AugustinMauroy Absolutely! if i see something that am able to do, i’ll definitely contribute.

**Comment by AugustinMauroy** [comment]
if you have any questions, don't hesitate. There's sure to be someone who can help.

**Pull request merged**
