### PR TITLE
Express Annoucement

### PR DESCRIPTION
**Pull request by mikeal**
This should have gone up a while ago.

### CODE REVIEW

**Comment by Fishrock123** [comment]
Looks like the date formatting is incorrect? https://github.com/nodejs/nodejs.org/issues/531

**Comment by rvagg** [comment]
americans and their weird dates

perhaps this would be a good addition to the precommit hook? check date is valid and not too far in the future

**Comment by stevemao** [comment]
@rvagg oh well `02-10-2016` would be Americans. I'd like to see how to write a hook for that :)

**Comment by rvagg** [comment]
`2016-10-02` > `2016-02-24`, that's a pretty easy hook

**Comment by stevemao** [comment]
Oh I thought you'd find all dates in the page. If just the header one its easy.

**Pull request merged**
