### PR TITLE
meta: switch to shikiji and updated packages

### PR DESCRIPTION
**Pull request by ovflowd**
## Description

Since Shiki is written in CJS and requires Node.js file APIs and other shenanigans, it is a problematic dependency that we've had to deal a few times already. With Next.js 14, Shiki breaks completely.

Our package `rehype-pretty-code` is also switching to `shikiji` as we speak, but since `shikiji` exposes a nice compatibility layer called `shikiji-compat` I've went ahead and upgraded.

This makes our website finally be compatible with Server Components if we ever need (this was the last big dependency that was incompatible afaik) and also removes the need of using file APIs for Shiki...

## Validation

All syntax highlighters should work as expected.

### CODE REVIEW

**Comment by ovflowd** [comment]
@bmuenzenmeyer this switches to `type: module` and fixes the build failure

**Comment by ovflowd** [comment]
cc @nodejs/nodejs-website and @nodejs/web-infra to fast-track so that we unblock migrating to Next.js 14 and Turbopack.

**Comment by ovflowd** [comment]
cc @devjvao you will need to rebase your PR after this gets merged. But will remove the need of you to see `setCDN` for Shiki :)

**Comment by bmuenzenmeyer** [comment]
> @bmuenzenmeyer this switches to `type: module` and fixes the build failure

thanks! I'd made the same changes in my fork this AM but hadn't yet pushed. this will be cleaner

**Review by bmuenzenmeyer — APPROVED** [review]

**Pull request merged**
