### PR TITLE
Improve Japanese translation on top page

### PR DESCRIPTION
**Pull request by sotayamashita**
It is very small PR. In Japanese translation, there is a space between English and Japanese
word but I found a sentence which do not follow the rule so I fix it.

ping @watilde
please review this! 🙇

Thanks in advance.

### CODE REVIEW

**Comment by lpinca** [comment]
cc: @nodejs/nodejs-ja

**Comment by hiroppy** [comment]
LGTM.

**Comment by okuryu** [comment]
looks good. 👍

**Comment by lpinca** [comment]
Thank you.

**Pull request merged**
