### PR TITLE
Anatomy of an HTTP Transaction - Fix typo

### PR DESCRIPTION
**Pull request by taueres**

### CODE REVIEW

**Comment by Trott** [comment]
LGTM

**Comment by ghost** [comment]
LGTM!

**Comment by Trott** [comment]
Actually, one nit: The line that's edited is now 81 chars long, but the file is wrapped at 80 chars. Can you wrap the last word to the next line?

**Comment by ghost** [comment]
should i revert the merge, @Trott?

**Comment by Trott** [comment]
Nah, it's a nit. You can leave it. (In my opinion anyway.) If someone wants to fix it in another PR, that would be fine by me. Or not. Whatever. Someone else may care more about the 80-char wrap than me. @bengl maybe?

**Comment by ghost** [comment]
i'll do it real quick

**Comment by ghost** [comment]
#393

**Pull request merged**
