### PR TITLE
fix: Change link to point to npm release notes

### PR DESCRIPTION
**Pull request by styfle**
## Description

Previously, this link was pointing to the npm registry which looks nearly the same for every release.

This PR changes the link to point to the release notes for the given version of npm.

## Validation

Click on "Node.js includes npm (10.2.4)" here:

image

## Related Issues

None

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [ ] I have run `npx turbo format` to ensure the code follows the style guide.
- [ ] I have run `npx turbo test` to check if all tests are passing.
- [ ] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
@ovflowd it was you who put this link up, any reason? 

I'm fine with the GitHub release too.

**Review by ovflowd — APPROVED** [review]
LGTM! Can you double check, @styfle that this link works for every version from our Dropdown selector?

**Review by AugustinMauroy — APPROVED** [review]
LGTM ! on my manual test it's work fine

**Review by aymen94 — APPROVED** [review]

**Comment by styfle** [comment]
> Can you double check, @styfle that this link works for every version from our Dropdown selector?

@ovflowd I confirmed that all links work 👍

However, a few old releases don't have notes (its just the tag) such as https://github.com/npm/cli/releases/tag/v2.15.11

I think that is an acceptable trade off.

**Comment by ovflowd** [comment]
@styfle could you run prettier locally? Apparently it is not happy

**Pull request merged**
