### PR TITLE
Added integration for OneSignal.push

### PR DESCRIPTION
**Pull request by ColinMoulds**
OneSignal is a high volume and reliable push notification service for websites and mobile applications.

Added base integration as an option to use OneSignal.push

### CODE REVIEW

**Comment by fhemberger** [comment]
Hmm, not sure we need push notifications (someone has to trigger them as well).

Opinions, @nodejs/website?

**Comment by ColinMoulds** [comment]
Yes, i thought it would be useful when announcing updated version of node directly through webpush.

**Comment by MylesBorins** [comment]
I'm not seeing value in this. We don't release often enough / have enough engagement to introduce web push imho

**Comment by sotayamashita** [comment]
I agree with @MylesBorins. 

I would like to know why @ColinMoulds create this issue because ColinMoulds just describes what OneSignal is. Thanks in advance.

**Comment by lpinca** [comment]
I'm also -1 on this unless it is really needed.

**Pull request closed without merging**
