### PR TITLE
feat: enabled git lfs

### LINKED ISSUE #5501: Enable Git LFS on the repository
For a long period, we have had a lot of assets on our repository, (including the Survey Report) but we never used Git LFS.

By using Git LFS we can reduce the overall repository size, and commit-to-commit size.

I'm making a PR already, but wanted to open an issue to keep track of this, and allow discussions to happen.

### PR DESCRIPTION
**Pull request by ovflowd**
This PR simply enables Git LFS and enables tracking of LFS for the following file formats:

- `*.png`
- `*.jpg`
- `*.gif`
- `*.eps`
- `*.pdf`

Closes https://github.com/nodejs/nodejs.org/issues/5501

### CODE REVIEW

**Review by bmuenzenmeyer — APPROVED** [review]
This worked for me with a test commit, and I already have git LFS enabled. Someone should test it WITHOUT too.

**Comment by ovflowd** [comment]
> This worked for me with a test commit, and I already have git LFS enabled. Someone should test it WITHOUT too.

We probably need to update docs mandating `git lfs` to be installed. Yet, afaik if you don't have, you will see an error asking you to install git lfs and pointing to docs as far as I remember.

**Comment by bmuenzenmeyer** [comment]
> We probably need to update docs mandating `git lfs` to be installed. Yet, afaik if you don't have, you will see an error asking you to install git lfs and pointing to docs as far as I remember.

that's gonna be a pretty terrible developer experience, especially for newcomers and one-of contributions. considering that... and conversation in #5501 I think we should close this

**Comment by ovflowd** [comment]
> that's gonna be a pretty terrible developer experience, especially for newcomers and one-of contributions. considering that... and conversation in https://github.com/nodejs/nodejs.org/issues/5501 I think we should close this

Let's close this for now, kinda shame-ish, but it is what it is.

**Pull request closed without merging**
