### PR TITLE
Add weekly update 2015-10-30

### PR DESCRIPTION
**Pull request by JungMinu**
Please review this post. :heart:,@nodejs/evangelism

### CODE REVIEW

**Comment by yosuke-furukawa** [comment]
I would like to add Node v5.0 release. is that too late??

**Comment by JungMinu** [comment]
@yosuke-furukawa Thanks, I'd love to :heart:

**Comment by JungMinu** [comment]
@yosuke-furukawa Thanks, I've updated :smile:

**Comment by yosuke-furukawa** [comment]
@JungMinu I think we should update Notable Changes for v5.0.0

**Comment by JungMinu** [comment]
@yosuke-furukawa Yup, I will

**Comment by JungMinu** [comment]
@yosuke-furukawa Thanks, I've done

**Comment by Trott** [comment]
In general, I'd be inclined to not list release proposals and just list actual releases. So this would mean:
- Remove the word `proposal`
- Remove the 4.2.2 stuff and leave that for next week. (Maybe include an item indicating that LTS 4.2.2 is coming soon.)

That's all just my opinion, though.

**Comment by Trott** [comment]
For the summary of 5.0, I think the breaking changes are actually not that interesting or notable for a news item. I would much rather emphasize exciting (or exciting-ish anyway) new features like the ES 2015 spread operator.

**Comment by JungMinu** [comment]
@Trott Thanks, I've updated

**Comment by Trott** [comment]
Cool. If you want something to replace the other breaking change item, maybe mention that 5.0.0 ships with npm v3!

Either way, :+1: and thanks for putting it together!

**Comment by JungMinu** [comment]
@Trott Thanks, I added npm v3

**Comment by Trott** [comment]
:+1:

**Comment by yosuke-furukawa** [comment]
LGTM

**Pull request merged**
