### PR TITLE
chore(remove): nodeFeatures

### LINKED ISSUE #5684: Delete NodeFeatures Component
The NodeFeatures component is not being ported to the new website design.

Remove all references to it within the current codebase. This includes:

- [ ] all files within [components/Home/NodeFeatures ](https://github.com/nodejs/nodejs.org/tree/main/components/Home/NodeFeatures )
   - [ ] if this is the last work within a higher directory, delete that too
   - [ ] perform a global search for the component. If found elsewhere, remove its usage
- [ ] all references to the component within [internationalization files](https://github.com/nodejs/nodejs.org/tree/main/i18n/locales).
   - [ ] look for `components.home.nodeFeatures.*` keys within `i18n/locales/{locale}.json` files
   - [ ] ensure these files remain valid JSON by being mindful of commas when deleting lines

As with all contributions, run local commands to ensure the deletion was cleanly executed:
- [ ] `npx turbo lint`
- [ ] `npx turbo format`
- [ ] `npx turbo test`
- [ ] `npx turbo build`
- [ ] `npx turbo serve`

### PR DESCRIPTION
**Pull request by AugustinMauroy**
## Description

Removing #5684 

## Related Issues

Close: #5684

### Check List

- [X] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [X] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [X] I have run `npx turbo format` to ensure the code follows the style guide.
- [X] I have run `npx turbo test` to check if all tests are passing, and/or `npx turbo test:snapshot` to update snapshots if I created and/or updated React Components.
- **NA** I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by ovflowd** [comment]
@AugustinMauroy I feel that the git hooks are not being respected as you've committed files that should not be committed xD

**Comment by AugustinMauroy** [comment]
@ovflowd it's because I'm using GitHub desktop (visual interface for git) so when I use husky it's doesn't work because he try to use `git` command but it's not usable (I don't have `git` command on my machine).

**Comment by ovflowd** [comment]
> @ovflowd it's because I'm using GitHub desktop (visual interface for git) so when I use husky it's doesn't work because he try to use git command but it's not usable (I don't have git command on my machine).

GitHub Desktop should still respect Git Hooks if they got installed when you ran `npm ci` 🤔

**Comment by AugustinMauroy** [comment]
```bash
 npm ci

> nodejs.org@1.0.0 postinstall
> npx next telemetry disable

Next.js' telemetry collection is already disabled.

Status: Disabled

You have opted-out of Next.js' anonymous telemetry program.
No data will be collected from your machine.
Learn more: https://nextjs.org/telemetry


> nodejs.org@1.0.0 prepare
> husky install

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
husky - git command not found, skipping install

added 2010 packages, and audited 2011 packages in 17s

491 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
machine@user nodejs.org % 
```

**Comment by ovflowd** [comment]
See:

```
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
husky - git command not found, skipping install
```

You have missing MacOS Developer Tools.

Can you please run: `xcode-select --install`

**Comment by AugustinMauroy** [comment]
That a solution. But if I doesn't want to have `git` installed on my machin I'm stuck. But thanks I will do that
BTW, I don't understand why visual regression fails ?

**Comment by ovflowd** [comment]
> That a solution. But if I doesn't want to have git installed on my machin I'm stuck. But thanks I will do that
BTW, I don't understand why visual regression fails ?

Well, it is a requirement to have git installed in your machine lol.

**Comment by bmuenzenmeyer** [comment]
> @ovflowd it's because I'm using GitHub desktop (visual interface for git) so when I use husky it's doesn't work because he try to use `git` command but it's not usable (I don't have `git` command on my machine).

thats an interesting turn of events. I hadn't considered how GitHub Desktop would work with this, if true. I've seen it behave strangely like this in the past too.

@AugustinMauroy do you think you could take some time and try to install https://git-scm.com/ directly?

**Comment by ovflowd** [comment]
> thats an interesting turn of events. I hadn't considered how GitHub Desktop would work with this, if true. I've seen it behave strangely like this in the past too.

It should work as normal. The issue is that Husky failed to install the Hooks as you can see on his `npm ci` command. Due to missing `git` package. And having git on the system is a pre-requisite. No matter what IDE or Application you use for actually creating and pushing commits. Git Hooks will always be respected on these tools. (In this case the hooks were not configured due to missing git)

GitHub Desktop has a bundled git within its Application (standalone), but the Git hooks get installed within the repository `.git` folder, so it doesn't matter in the end xD

**Comment by bmuenzenmeyer** [comment]
> It should work as normal. The issue is that Husky failed to install the Hooks as you can see on his `npm ci` command.

gotcha. my github issue UI was out of date again and I ended up "double-helping"

**Review by rodion-arr — APPROVED** [review]
Looks OK now, no unneeded files seen committed

**Review by mikeesto — APPROVED** [review]

**Review by shanpriyan — APPROVED** [review]

**Pull request merged**
