### PR TITLE
Remove unused layouts and their CSS.

### PR DESCRIPTION
**Pull request by XhmikosR**
* announcements.hbs
* in-the-news.hbs

I left the `blogAnnounce` collection as is, although it probably is redundant too, so must be its feed

### CODE REVIEW

**Comment by XhmikosR** [comment]
Actually now that I see [site.json](https://github.com/nodejs/nodejs.org/blob/master/locale/en/site.json) it seems the feed is also unused. Let me know how to proceed.

https://github.com/nodejs/nodejs.org/blob/ceaa1c09dd5fdd28c20b2a73ef5d795cc73e8a15/locale/en/site.json#L19-L32

**Comment by XhmikosR** [comment]
@Trott should I also remove completely announcements?

**Comment by Trott** [comment]
> @Trott should I also remove completely announcements?

I'm not sure. I don't know the ramifications. We can ping more widely for review or I can be educated.

**Comment by XhmikosR** [comment]
Let's ask more people. I added the complete removal of announcements. Not sure if we should add any redirections or not.

**Comment by Trott** [comment]
@nodejs/website

**Comment by XhmikosR** [comment]
@nodejs/build should we redirect the announcements index file or their feed? Note that this actually only removes the `/announcements/index.html/` file and `announcements.xml`

Otherwise, I will split this patch so that we can merge the first one which is safe.

**Comment by XhmikosR** [comment]
Since I'm not getting any reviews, I dropped the second patch from this PR.

Now the patch just removes unused layouts and their CSS.

**Review by rvagg — APPROVED** [review]
This seems fine to me.
I'm a little shocked that we have nobody showing up to review though? what happened to our website team and where is our shiny new website that we've had a whole team pouring over?

**Comment by alexandrtovmach** [comment]
I think we haven't somebody who can give an answer about removed layouts, so let's merge PR and take a look on any issues that can be produced

**Review by alexandrtovmach — APPROVED** [review]

**Comment by XhmikosR** [comment]
This shouldn't affect anything. I moved the other patch to separate PRs.

**Review by nschonni — APPROVED** [review]
Not sure about removing the content (now in other PR), but these do look unreferenced anyway so 👍

**Comment by bnb** [comment]
>I'm a little shocked that we have nobody showing up to review though? what happened to our website team and where is our shiny new website that we've had a whole team pouring over?

@rvagg you can find that work in [nodejs/nodejs.dev](https://github.com/nodejs/nodejs.dev).

**Comment by rvagg** [comment]
@bnb thanks, so when do we get to replace nodejs.org?

**Comment by bnb** [comment]
That's a great question. I'm not involved to the point to be able to assert an answer to it. Perhaps @amiller-gh could give some insight on, though I don't necessarily think this PR is the correct venue for that.

**Pull request merged**
