### PR TITLE
Fix IE and minor tweaks

### PR DESCRIPTION
**Pull request by XhmikosR**
Before:

1-before

After:

2-after

### CODE REVIEW

**Comment by XhmikosR** [comment]
BTW I can always rebase and generally make any needed changes. I just happened to notice the IE issues and maybe the last patch could be split to a separate PR.

**Comment by MaledongGit** [comment]
Any special changes？I don't see anything perticular……？

**Review by ghost — COMMENTED** [review]
Any special changes？I don't see anything perticular……？

**Review by alexandrtovmach — COMMENTED** [review]
Looks good for me, but I haven't sure about these changes. I can't believe that is some developer using old version of IE. In the same time you refactored JS code to ES5 style, that's not very readable (especially `Array.prototype` stuff).

**Comment by alexandrtovmach** [comment]
> Any special changes？I don't see anything perticular……？

@MaledongGit 
Take a look on language switcher, it wasn't show before in IE

**Comment by XhmikosR** [comment]
>Looks good for me, but I haven't sure about these changes. I can't believe that is some developer using ol version of IE. In the same time you refactored JS code to ES5 style, that's not very readable (especially Array.prototype stuff).

Well, this is the only place in frontend that ES6 was used. And that's just one line, we can all live with it or with `[].slice.call` :)

**Comment by ghost** [comment]
> > Any special changes？I don't see anything perticular……？
> 
> @MaledongGit
> Take a look on language switcher, it wasn't show before in IE

Thanks for telling me, it's right.
I've no doubt about this change, but I'll see others' opinions about this change. I'm OK with it.

**Review by ghost — APPROVED** [review]

**Comment by silverwind** [comment]
That `var` change is kind of pointless thought. IE11 supports `const` and supporting anything older is also pointless.

**Comment by XhmikosR** [comment]
@silverwind: it's the only place ES6 is used. And IE doesn't support arrow functions. I went with consistency here, which is better in the long-term IMO.

**Review by silverwind — APPROVED** [review]

**Comment by silverwind** [comment]
Ok, whatever. Would prefer we stop supporting IE11 soon and compile to ES6.

**Comment by XhmikosR** [comment]
Fine by me but it should be done properly is all I'm saying. And this was easier for me at the time :P

**Pull request merged**
