### PR TITLE
chore: added platform-nvm.svg and storybook, #issue 34

### PR DESCRIPTION
**Pull request by niyashiyas**
### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by niyashiyas** [comment]
Removed the storybook file components/__design__/platform-logos.stories.tsx because it was already added.

**Comment by joycexfang** [comment]
@niyashiyas it's important that you still add the `div` and `Image` components to the `platform-logos.stories.tsx`

**Comment by joycexfang** [comment]
may you also add the issue as a link in your PR description? see this PR as an example for reference: https://github.com/nodejs/nodejs.org/pull/5887

**Review by Gdakgdak22 — COMMENTED** [review]
Ich bin  batman

**Comment by bmuenzenmeyer** [comment]
@niyashiyas please take a look at the comments here - we need to add the `Image` to the existing storybook file. 

if this doesn't get picked back up in a few more days, I will ask someone else to do so

**Comment by bmuenzenmeyer** [comment]
closes https://github.com/bmuenzenmeyer/nodejs.org/issues/34

**Comment by bmuenzenmeyer** [comment]
this PR looks abandoned and the underlying approach has changed. I will recreate the scope as a new issue

**Pull request closed without merging**
