### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by lpinca**
- [`cheerio@0.22.0`](https://github.com/cheeriojs/cheerio/blob/master/History.md#0220--2016-08-23)
- `lodash.defaultsdeep@4.6.0`
- [`metalsmith@2.2.0`](https://github.com/metalsmith/metalsmith/blob/master/CHANGELOG.md#220---august-11-2016)
- [`node-geocoder@3.14.0`](https://github.com/nchaulet/node-geocoder/blob/master/CHANGELOG.md#3140)
- [`snyk@1.18.1`](https://github.com/Snyk/snyk/compare/v1.17.2...v1.18.1)
- `standard@8.0.0`

### CODE REVIEW

**Comment by ghost** [comment]
what changed in `standard@8.0.0`?

**Comment by saadq** [comment]
Taken from the first comment [here](https://github.com/feross/standard/issues/564):
<details>

## New features
- [x] Upgrade to ESLint v3 (http://eslint.org/docs/user-guide/migrating-to-3.0.0) (feross/standard#565)
  - **BREAKING**: Drop support for node < 4 (this was a decision made by the ESLint team)
- [x] Expose ESLint's `--fix` command line flag (feross/standard#540) (Flet/standard-engine#107)
  - Lightweight, no additional dependencies, fixes dozens of rules automatically

## New rules

(Estimated % of affected standard users, based on test suite in parens)
- [x] Enforce placing object properties on separate lines (object-property-newline) (feross/standard#524) (2%)
- [x] Require block comments to be balanced (spaced-comment "balanced") (feross/standard#572) (2%)
- [x] Disallow constant expressions in conditions (no-constant-condition) (feross/standard#563) (1%)
- [x] Disallow renaming import, export, and destructured assignments to the same name (no-useless-rename) (feross/standard#537) (0%)
- [x] Disallow spacing between rest and spread operators and their expressions (rest-spread-spacing) (feross/standard#567) (0%)
- [x] Disallow the Unicode Byte Order Mark (BOM) (unicode-bom) (feross/standard#538) (0%)
- [x] Disallow assignment to native objects/global variables (no-global-assign) (feross/standard#596) (0%)
- [x] Disallow negating the left operand of relational operators (no-unsafe-negation) (feross/standard#595) (0%)
- [x] Disallow template literal placeholder syntax in regular strings (no-template-curly-in-string) (feross/standard#594) (0%)
- [x] Disallow tabs in file (no-tabs) (feross/standard#593) (0%)

## Changed rules
- [x] ~~Enforce use of double quotes in JSX attributes (jsx-quotes) (1%, but likely more in private repos)~~
  - ~~**BREAKING**: This rule was changed to reflect the way the vast majority of developers quote HTML attributes (both in plain HTML and in the React community) (feross/eslint-config-standard#27)~~
  - This rule was re-evaluated. See (feross/standard#564)
- [x] Relax rule: Allow template literal strings (backtick strings) to avoid escaping (feross/standard#421)
- [x] Relax rule: Do not enforce spacing around \* in generator functions (feross/standard#564)
  - This is a temporary workaround for babel users who use async generator functions.

## Internal changes
- [x] Migrate to new ESLint rule format for plugins (xjamundx/eslint-plugin-standard#11) (xjamundx/eslint-plugin-promise#19)
  </details>

**Comment by ghost** [comment]
okay, looks good

**Comment by lpinca** [comment]
Thank you @saadq.

**Pull request merged**
