### PR TITLE
Remove announcements collection and feed

### PR DESCRIPTION
**Pull request by XhmikosR**
Should we redirect these in nodejs/build?

### CODE REVIEW

**Comment by XhmikosR** [comment]
@Trott any suggestions how to proceed with this? This basically just removes the blog Announcement feed: https://nodejs.org/en/feed/announce.xml

**Comment by Trott** [comment]
> @Trott any suggestions how to proceed with this? This basically just removes the blog Announcement feed: https://nodejs.org/en/feed/announce.xml

First new entry in that feed in a long time showed up this month....

**Comment by Trott** [comment]
I'm not sure how to proceed here, to be honest.

**Comment by XhmikosR** [comment]
>First new entry in that feed in a long time showed up this month....

I don't quite follow you there... Note that this just removes the feed which I assume it's unused because it's not linked in the HTML:

```html
<link rel="alternate" href="/en/feed/blog.xml" title="Node.js Blog" type="application/rss+xml">
<link rel="alternate" href="/en/feed/releases.xml" title="Node.js Blog: Releases" type="application/rss+xml">
<link rel="alternate" href="/en/feed/vulnerability.xml" title="Node.js Blog: Vulnerability Reports" type="application/rss+xml">
```

**Comment by Trott** [comment]
> > First new entry in that feed in a long time showed up this month....
> 
> I don't quite follow you there... Note that this just removes the feed which I assume it's unused because it's not linked in the HTML:
> 
> ```
> <link rel="alternate" href="/en/feed/blog.xml" title="Node.js Blog" type="application/rss+xml">
> <link rel="alternate" href="/en/feed/releases.xml" title="Node.js Blog: Releases" type="application/rss+xml">
> <link rel="alternate" href="/en/feed/vulnerability.xml" title="Node.js Blog: Vulnerability Reports" type="application/rss+xml">
> ```

I assumed (wrongly?) that these were RSS/Atom feeds or something and that they might be used by others even if we don't link to them.

**Comment by XhmikosR** [comment]
I'm not sure if this feed was ever linked in the HTML TBH.

**Comment by XhmikosR** [comment]
But either way this feed hasn't been updated for years.

**Comment by Trott** [comment]
> But either way this feed hasn't been updated for years.

By "this feed", do you mean https://nodejs.org/en/feed/announce.xml? If so, it was updated this month for the first time in almost two years.

**Comment by Trott** [comment]
> > But either way this feed hasn't been updated for years.
> 
> By "this feed", do you mean https://nodejs.org/en/feed/announce.xml? If so, it was updated this month for the first time in almost two years.

Oh, wait, except no it wasn't. I was looking at the feed generation date, not the item publication date. &lt;facepalm&gt;

**Comment by XhmikosR** [comment]
I don't see how it was updated when the last post is from `January 26, 2017, 2:00 PM`.

**Review by Trott — APPROVED** [review]

**Comment by XhmikosR** [comment]
>Oh, wait, except no it wasn't. I was looking at the feed generation date, not the item publication date. <facepalm>

Ah that changes if the post date changes which is normal since we still make changes to old content...

**Review by nschonni — APPROVED** [review]

**Pull request merged**
