### PR TITLE
Added Austin MEAN Stack to North American events list

### PR DESCRIPTION
**Pull request by cdnadmin**
Hey, y'all, simply wanted to add the [Austin MEAN Stack Dev meetup](http://www.meetup.com/Austin-MEAN-Stack-Development/) in the North American list of meetups.

### CODE REVIEW

**Comment by ghost** [comment]
LGTM. thanks for contributing!

**Comment by stevemao** [comment]
I thought those were automatically generated?

**Comment by ghost** [comment]
@stevemao what do you mean? is there a script for it somewhere?

**Comment by ghost** [comment]
oh wait, do you mean `pull-meetup.js`?

**Comment by stevemao** [comment]
I think so.

**Comment by tentakel** [comment]
do we have a process that runs this regularly? i almost think that it might be better to manage it through pull requests

**Comment by ghost** [comment]
actually, i retract that statement. the `get-involved/events.md` file doesn't look like it belongs in version control at all, it's way too big.

**Comment by lpinca** [comment]
@tentakel yes, that is the script to pull the events. That one and `pull-nodeschool.js` populate `get-involved/events.md`. It was way bigger than it is now 😄 . See https://github.com/nodejs/nodejs.org/pull/625.

**Comment by cdnadmin** [comment]
Sweet!  Thx, everyone!  

Why my approach?  --> First, I just wanted to get our meetup in here ASAP.  :-) 

I did try using pull-meetup.js, but I noticed that when I ran it locally (used my own meetup API key of course), it firstly ran into an issue with MK not being in the country-map.js export object .  i.e. new data from meeetup.com's API.  Then, when I added MK (locally, just to test), pull-meetup.js added a whole bunch of other meetups, and other data, that I didn't want to muck around with, because I'm not sure what policy there is for this.  So, I added our data directly, and PR'd it here. 

Also, I know pull-meetup.js triggers off of meetups' having "nodeJs" as one of their configured topics, so I added it to ours, but, again, other data was being pulled in.

So, I opted for adding our meetup's data directly and submitting this PR.  

Question, when do these pull files get executed to update the respective *.md files? 

Thx again, y'all!

**Comment by lpinca** [comment]
> Question, when do these pull files get executed to update the respective *.md files?

Not sure, I think it's done manually now, pull request to add MK to the map is welcome :)

**Comment by cdnadmin** [comment]
> ...pull request to add MK to the map is welcome :)

#762

**Pull request merged**
