### PR TITLE
update v20.8.0 blog post

### PR DESCRIPTION
**Pull request by joyeecheung**
Refs: https://github.com/nodejs/node/pull/49932#issuecomment-1740542932

### CODE REVIEW

**Comment by ovflowd** [comment]
cc @nodejs/releasers

**Review by richardlau — APPROVED** [review]

**Comment by richardlau** [comment]
@joyeecheung will you be mirroring the change to the [changelog in nodejs/node](https://github.com/nodejs/node/blob/1dc0667aa6096f10c5f95471dfe27e78db1dafd5/doc/changelogs/CHANGELOG_V20.md?plain=1#L74)?

**Comment by joyeecheung** [comment]
Oh I forgot about that one. Thanks for the reminder. Opened https://github.com/nodejs/node/pull/49951

**Comment by joyeecheung** [comment]
Can I just push the "Merge when ready" button?

**Comment by ovflowd** [comment]
> Can I just push the "Merge when ready" button?

Yes :)

**Comment by ruyadorno** [comment]
Thanks @joyeecheung !

**Pull request merged**
