### PR TITLE
Spanish translation for `dependencies` page

### PR DESCRIPTION
**Pull request by joseluisq**
This PR just translates the missing [Dependencies | Node.js](https://nodejs.org/es/docs/meta/topics/dependencies/) page currently in English to Spanish.

Just let me know if you need further changes.

### CODE REVIEW

**Comment by joseluisq** [comment]
Looks like `remark -qf` fails on warnings because of the table of contents was using hyphens instead of asterisks.
Fixed now.

**Comment by ghost** [comment]
Ping @nodejs/nodejs-es

**Review by DerekNonGeneric — APPROVED** [review]
LGTM

Also, thank you so much for doing this &mdash; it looks great!

**Comment by DerekNonGeneric** [comment]
@joseluisq, it would be great to get this merged, but I am getting the following when trying to merge:

> This branch is out-of-date with the base branch

Would you be able to rebase your changes on top of the latest `main` branch? That should take care of this&hellip;

**Comment by joseluisq** [comment]
@DerekNonGeneric rebased

**Pull request merged**
