### PR TITLE
meta: some component cleanups and design fixes

### PR DESCRIPTION
**Pull request by ovflowd**
## Description

This PR does a few component normalisation and design fixes:

- Fixes the LanguageDropdown as it was slightly deviating from Figmas
- Updated Props from LanguageDropdown to reflect on agreements (see #6007)
- Updated some components that were exporting types and use `ComponentProps` instead
- Normalised Component imports to use absolute imports `@`
- Updated a few components to only import `formattedMessage` from intl Hook

## Validation

All Storybooks should be the same, besides the LanguageDropdown one and all Storybooks should be working.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
> Normalised Component imports to use absolute imports @

Don't my to specify on Callab guide how imports are made.

**Review by shanpriyan — APPROVED** [review]
LGTM!

**Comment by ovflowd** [comment]
> > Normalised Component imports to use absolute imports @
> 
> Don't my to specify on Callab guide how imports are made.

What?

**Comment by ovflowd** [comment]
cc @nodejs/nodejs-website can we fast-track this as these are simply changes?

**Review by canerakdas — APPROVED** [review]
LGTM, I have only a tiny comment, we need to update this line to avoid misunderstandings;

https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md?plain=1#L290

**Comment by AugustinMauroy** [comment]
I mean we need to update the [collaborateor guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#how-a-new-component-should-look-like-when-freshly-created)

**Pull request merged**
