### PR TITLE
Blog: v19.8.0 release post

### PR DESCRIPTION
**Pull request by targos**
Refs: https://github.com/nodejs/node/pull/47087

### CODE REVIEW

**Review by BethGriggs — APPROVED** [review]

**Review by tniessen — APPROVED** [review]

**Comment by nschonni** [comment]
@nodejs/website this isn't showing up on https://nodejs.org/en/blog/ or the RSS feed, so either CDN caching or something else has gone wrong.
Oddly not showing up on the gh-pages deployment either http://nodejs.github.io/nodejs.org/en/blog/

**Comment by ovflowd** [comment]
@nschonni we are aware of this already, and talking inside the OpenJS Foundation slack. For all it looks, Cloudflare strikes again. There's nothing much I can do as I have no Cloudflare access.

**Comment by ovflowd** [comment]
This _probably_ would be fixed once we trigger a next build, but who knows 🤷

**Comment by nschonni** [comment]
sorry, edited my comment afterwards, but it's also missing from the github pages, so it's not a Cloudflare thing this time

**Comment by ovflowd** [comment]
Hmmm, also not on the GitHub pages one? 🤔 that is utmost confusing... Spinning up a local instance works fine. Let me trigger another GitHub pages build.

**Comment by nschonni** [comment]
Looks like it's live again. Noticed an unrelated RSS thing, but I'll create a separate issue

**Comment by ovflowd** [comment]
I'm starting to feel that something is a little bit broken on the build script inside our live server. And yes, also see that SSR (not RSS) is having some troubles on nodejs.org, while when running local prod builds, not. It's utmost... weird.

**Comment by nschonni** [comment]
No, I meant RSS, but I've filed the issue for that now

**Comment by ovflowd** [comment]
I know you meant RSS, hence why I said (not RSS) (I was talking about something completely different...)

**Pull request merged**
