### PR TITLE
remove resources page

### PR DESCRIPTION
**Pull request by Trott**
The site is not the place to make Illustrator files of the logo
available.

### CODE REVIEW

**Comment by nschonni** [comment]
Are these available somewhere else, like the foundation site?

**Comment by Trott** [comment]
> Are these available somewhere else, like the foundation site?

Open to reasons why I'm wrong about this, but I think as long as the marketing folks etc. at the Foundation have the files, I'm not sure other people should be messing with the logos. @rginn

**Comment by rginn** [comment]
All OpenJS project logos are kept up-to-date in our foundation artwork repo https://github.com/openjs-foundation/artwork, including Node.js.

**Review by joesepi — APPROVED** [review]
LGTM!

**Review by ghost — COMMENTED** [review]
Do we need to refer the link in detail somewhere in our project?
https://github.com/openjs-foundation/artwork/tree/main/projects/nodejs#nodejs-artwork

**Comment by Trott** [comment]
> Do we need to refer the link in detail somewhere in our project? https://github.com/openjs-foundation/artwork/tree/main/projects/nodejs#nodejs-artwork

I'm not opposed, but I don't know that we need it, to be honest. I know Python has it on their site, but I'm just not really sure who it's for, to be honest.

**Comment by Trott** [comment]
Landing. We can always revert if it turns out this is needed. I doubt it is, though.

**Pull request merged**
