### PR TITLE
doc: update oct DOS security vulnerability post

### PR DESCRIPTION
**Pull request by MylesBorins**
Fixes spelling error and adds notice to front page

### CODE REVIEW

**Review by refack — APPROVED** [review]
+1 Fast track

**Review by bengl — APPROVED** [review]

**Review by addaleax — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
Landed as 178a3c641465e432bd4c96d301094a1413520583

**Pull request closed without merging**
