### PR TITLE
Lossy compress PNG files

### PR DESCRIPTION
**Pull request by XhmikosR**
Before: 1,55 MB (1.627.160 bytes)
After:   720 KB (737.908 bytes)

### CODE REVIEW

**Comment by nschonni** [comment]
I'm not sure if these are updated during the deploy or not from https://github.com/nodejs/nodejs.org/blob/9239c9eb30ed78b58722ef111179f55eb687d366/package.json#L10

**Comment by XhmikosR** [comment]
The external ones are probably not updated indeed. I plan to drop those from this patch, I just opened the PR with all the changes first.

**Comment by bnb** [comment]
might be worth also documenting how you did this so we can reproduce it in the future :)

**Review by bnb — APPROVED** [review]
LGTM, would love to see the approach documented in a reproducible way though.

**Comment by XhmikosR** [comment]
I use plenty of tools and custom scripts, but here it is:

1. https://kraken.io/web-interface lossy
2. `optipng -o7`
3. pngout with various blocksizes
3. `zopflipng -lossy_transparent -y --iterations=500`

**Pull request merged**
