### PR TITLE
Compress SVGs with svgo 1.3.0.

### PR DESCRIPTION
**Pull request by XhmikosR**
The config used can be found on https://gist.github.com/XhmikosR/f0ead200a2006e6924998e664ead3663

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
Hello, thanks for contributing.

What is the functional reason of this changes?

**Comment by XhmikosR** [comment]
Smaller size :P

The output should be the same.

**Comment by silverwind** [comment]
Did you compare the rendering? GitHub does not seem to want to show a rendered diff here.

Also, I'd check what `--precision` argument was used, would suggest at least `3`. Can't seem to find what the default value is in SVGO's docs.

**Comment by XhmikosR** [comment]
Yeah, it looks fine AFAICT. Default is 3, I can change it, but I didn't notice any issues visually.

The only SVG file that seems to have been using a different precision is lfcp.svg, which BTW seems to be unused currently.

**Review by alexandrtovmach — APPROVED** [review]

**Comment by XhmikosR** [comment]
For transformations it seems precision is 5, in the rest of the cases it's 3. I had to search their codebase for this.

**Review by silverwind — APPROVED** [review]

**Review by Trott — APPROVED** [review]

**Pull request merged**
