### PR TITLE
Update nodejs-docker-webapp.md

### PR DESCRIPTION
**Pull request by Durairaj**
Modified Docs to run as non-root user and with NODE_ENV set to production as part of docker best pratices

### CODE REVIEW

**Comment by Trott** [comment]
@nodejs/docker 

Should this file even exist on the website? Would users be better off if we referred them to some other resource?

**Comment by Durairaj** [comment]
> @nodejs/docker
> 
> Should this file even exist on the website? Would users be better off if we referred them to some other resource?

I personally have this file that will be helpful to a lot of devs who are coming to Nodejs for the first time or trying to get a quick play around. 

Referring to another document link might be outdated or a few things can be deprecated in long run.

**Comment by SimenB** [comment]
We have https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md FWIW. Both `NODE_ENV` and the user is mentioned there. Can link to it?

**Comment by Durairaj** [comment]
> We have https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md FWIW. Both `NODE_ENV` and the user is mentioned there. Can link to it?

Its already linked

**Comment by SimenB** [comment]
Ok, then I'm not sure why we're duplicating information from it?

To answer the original "Should this file even exist on the website? Would users be better off if we referred them to some other resource?" I think probably just pointing to the docker-node repo makes sense? If there's any info missing we can add it.

**Comment by Trott** [comment]
Yeah, what I'm suggesting is that we do something more like https://github.com/nodejs/nodejs.org/blob/0206636c47e19b4bed7cc635f400678d46298919/locale/en/knowledge/javascript-conventions/what-is-the-arguments-object.md (or for the web page version:  https://nodejs.org/en/knowledge/javascript-conventions/what-is-the-arguments-object/)

**Comment by ovflowd** [comment]
Closing this PR as it has been stale for 1 year. @Durairaj feel free to reopen and work on it if you're still interested :)

**Pull request closed without merging**
