### PR TITLE
blog: add pos announcement sec release

### PR DESCRIPTION
**Pull request by RafaelGSS**

### CODE REVIEW

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
lgtm

**Review by ruyadorno — APPROVED** [review]

**Review by richardlau — APPROVED** [review]

**Review by Trott — APPROVED** [review]

**Comment by ovflowd** [comment]
Note that since we're merging so many things concurrently, the WebHook on our server will ignore all consecutive merges if a build is already happening. It is a known bug.

After the build finishes (10m maybe?) I'm going to retrigger the WebHook.

**Comment by Trott** [comment]
> Note that since we're merging so many things concurrently, the WebHook on our server will ignore all consecutive merges if a build is already happening. It is a known bug.
> 
> After the build finishes (10m maybe?) I'm going to retrigger the WebHook.

I just pressed the `Redelivery` button for it.

**Comment by Trott** [comment]
> I just pressed the `Redelivery` button for it.

Still not showing up, though, so maybe I did it wrong? @ovflowd

**Comment by ovflowd** [comment]
As I mentioned we need to wait enough tike for any running build inside the server to finish. It ignores new deliveries until the currently running one hasn't finished.

**Comment by ovflowd** [comment]
Deployed with success!

**Comment by Trott** [comment]
> As I mentioned we need to wait enough tike for any running build inside the server to finish. It ignores new deliveries until the currently running one hasn't finished.

I thought it had finished, but I guess I was wrong. Ah well. Thank you for making it happen!

**Comment by ovflowd** [comment]
No worries!! 🙇

**Pull request merged**
