### PR TITLE
blog: v13.11.0 release post

### PR DESCRIPTION
**Pull request by MylesBorins**
Refs: https://github.com/nodejs/node/pull/32185

### CODE REVIEW

**Comment by XhmikosR** [comment]
@MylesBorins @Trott it seems deployments are broken :/

Last commit I see in https://nodejs.org/github-webhook.log is `HEAD is now at df6f178... fix(docs): fix wrong translations in zh-cn`

BTW perhaps we should look into switching to GitHub Actions for deploys?

**Comment by MylesBorins** [comment]
I've pinged build about this on a couple channels. Unfortunately I don't
think we could use actions for deployment here without major changes to how
the website is hosted. not that we shouldn't consider it, but the change is
non trivial.

**Comment by Trott** [comment]
> I've pinged build about this on a couple channels.

I don't think Build WG generalists like me have the access to remove that log file. I'd be interested to know who does. Is it @nodejs/build-infra folks? I would love to have that ability.

**Comment by XhmikosR** [comment]
Your call, but it shouldn't be too hard to switch to GitHub Actions and rsync deployments, at least in theory :)

**Comment by rvagg** [comment]
@XhmikosR want to draft up a GitHub Action for this? If I can encrypt and store a secret that has an SSH key then we could isolate it to a single user account on the server and push content up directly. It'll need to be two step - 1) rsync content and 2) run an ssh command on the server to queue an invalidation of our cloudflare cached content. As long as we have strong assurance of the secret content not getting leaked then it could be a good way of pulling back control of this process into this repo rather than relying so much on build-infra to support when things go wrong.

**Pull request merged**
