### PR TITLE
docs: add docs for Proto package manager

### PR DESCRIPTION
**Pull request by ImBIOS**
## Description

This commit adds support for the Proto package manager in the site/types/release.ts, site/util/downloadUtils.ts, components/Downloads/Release/PlatformDropdown.tsx, and components/Icons/Platform/Proto.tsx files. The Proto package manager is now included as an option in the PackageManager enum and the platformItems array. The PlatformDropdown component has been updated to display the Proto icon. Additionally, the en.json file has been updated to include instructions for installing Proto.

## Validation

image
image
image
image

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
https://github.com/nodejs/nodejs.org/issues/7037 will supersede this

**Review by ovflowd — CHANGES_REQUESTED** [review]
Hey, unfortunately, we are not accepting changes to the current Downloads page Codebox component. Read more here: https://github.com/nodejs/nodejs.org/issues/7037

Could you remove those changes from this PR? Thanks 🙏 (The i18n translation change is fine tho)

**Review by avivkeller — CHANGES_REQUESTED** [review]
Along with that @ovflowd said, I feel that this PR changes several different parts of the code. IMHO, each part should be split into a different PR, or at least a different commit (w/ drebase), to make understanding the file history easier.

**Comment by avivkeller** [comment]
Also, there hasn't been any activity from the author in a little bit. If there's no activity in the next week (~4 months since open), I'm going to assume this stale-d and close it.

**Pull request closed without merging**
