### PR TITLE
Adding Secretary Member to Board.md

### PR DESCRIPTION
**Pull request by ryanmurakami**
Adding Dan Shaw as the Board Secretary.

I put it at the bottom of the Board list. Let me know if a different placement or wording is better.

Note: We may need translation in Ukranian for this change as well, since it is the only localized site that currently has a board page. Not sure how this is handled best.

### CODE REVIEW

**Comment by ryanmurakami** [comment]
Fixes #1005

**Comment by hackygolucky** [comment]
@ryanmurakami Can you place him right below Scott Hammond? We try to keep the officers together.

As a separate ask(may need to be a separate PR I can do), Charlie Robbins' title should be changed from 'Gold-level Director' to just 'Director' for now. I was just filing this PR myself and caught that you'd already posted.

**Comment by ryanmurakami** [comment]
@hackygolucky No problem. I just pushed the change. Is there a Gold-Level Director now? Or just two silvers?

**Review by lpinca — APPROVED** [review]

**Comment by mikeal** [comment]
No Gold members right now so no Gold director. Silver hit 20+ members so they have two seats now.

**Pull request merged**
