### PR TITLE
meta: add banner for 6 February 2024 security releases

### PR DESCRIPTION
**Pull request by richardlau**
## Description

Adds a banner for 6 February security releases. 
Also corrects timestamp on blog post.

## Validation

Banner should appear on the homepage:

image

## Related Issues

Refs: https://github.com/nodejs/nodejs.org/pull/6268

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [ ] I have run `npx turbo test` to check if all tests are passing.
- ~[ ] I've covered new added functionality with unit tests if necessary.~

### CODE REVIEW

**Review by AugustinMauroy — APPROVED** [review]
Lgtm

**Comment by richardlau** [comment]
Anyone have any ideas re. the test failure? I'm seeing the test fail with `main` without any of these changes. AFAICT it's a mismatch in date formatting.

**Comment by richardlau** [comment]
> Anyone have any ideas re. the test failure? I'm seeing the test fail with `main` without any of these changes. AFAICT it's a mismatch in date formatting.

Attempt to fix: https://github.com/nodejs/nodejs.org/pull/6271

**Comment by ovflowd** [comment]
I guess after rebasing and adding the CI label again, things should be 👌

**Comment by richardlau** [comment]
Rebased 🤞

**Review by anonrig — APPROVED** [review]

**Review by bmuenzenmeyer — APPROVED** [review]

**Comment by bmuenzenmeyer** [comment]
i am a a bit curious if we have new web design visual styles leaking into the old here, but I opted to get the word out over fretting about it - we are 3 or 4 days out from the content at this point

**Pull request merged**
