### PR TITLE
Add 2017 NI CfP banner

### PR DESCRIPTION
**Pull request by hackygolucky**
Per Zibby's request #1174, this adds the Node Interactive 2017 CfP banner, with styles echoing prior banners above the fold on the homepage.

### CODE REVIEW

**Comment by lpinca** [comment]
There is one link in the banner which should be made clickable or removed imho.
Apart from this LGTM.

**Review by lpinca — APPROVED** [review]

**Comment by lpinca** [comment]
Hmm, it doesn't look very good live. Maybe we should separate the two layers of the image.
One layer can be used as `background-image` of the `#interactive` `div` and the other as src of the `` tag inside the same `div`.

**Comment by lpinca** [comment]
@hackygolucky is it possible to have the original image without the layers flattened?

**Comment by hackygolucky** [comment]
@lpinca ah shoot, let me ask creative services. I requested the assets without them being flattened and I was handed a pdf :-/

**Comment by lpinca** [comment]
Thanks.

**Comment by hackygolucky** [comment]
@lpinca 
https://www.dropbox.com/s/qbustyrjynonhsu/banners_node_eps.eps?dl=0

**Comment by lpinca** [comment]
Saved, thanks @hackygolucky.

**Pull request merged**
