### PR TITLE
add link to installation instructions for Linux

### PR DESCRIPTION
**Pull request by ZYSzys**
Fix: #1926

### CODE REVIEW

**Comment by ZYSzys** [comment]
@fhemberger BTW, do we need to `/cc` some teams to translate the link text ?

**Comment by fhemberger** [comment]
@ZYSzys Awesome, thank you!

Regarding translation, we could either cc every translation team or active translators will pick up the change on their own. We need to come up with a better way to handle website updates for translators anyway (possibly even before the relaunch).

/cc @nodejs/i18n

**Comment by ZYSzys** [comment]
@fhemberger Hi, because of the nonactive at present, I just make the text keep in English if it's not translated.

**Review by fhemberger — CHANGES_REQUESTED** [review]
Please just add

```
    "install-on-linux": {
      "text": "Installing Node.js via binary archive on Linux"
    }
```

to all `locale/*/site.json` instead.

**Comment by ZYSzys** [comment]
@fhemberger Done :)

**Comment by fhemberger** [comment]
Awesome, thank you!

**Review by fhemberger — APPROVED** [review]

**Pull request merged**
