### PR TITLE
blog: fix indentation

### PR DESCRIPTION
**Pull request by maclover7**
cc @cjihrig

### CODE REVIEW

**Review by cjihrig — APPROVED** [review]
LGTM, but isn't all of this auto generated?

**Comment by maclover7** [comment]
Welp, turns out the issue is that the changelog in nodejs/node for v8.8.1 is indented more than it should be... who knew two spaces could cause so much trouble... This should go in, but also looks the changelog will need to be fixed as well.

**Comment by cjihrig** [comment]
Ah, my bad. I'm going to land this.

**Comment by maclover7** [comment]
no worries :) opened https://github.com/nodejs/node/pull/16507 to fix this in nodejs/node

**Pull request merged**
