### PR TITLE
refactor: updated release script and updated shiki

### PR DESCRIPTION
**Pull request by ovflowd**
## Description

This PR cleans up and refactors the Node.js Release Blog Post generation script.

- Modernizes the code a little bit
- Cleanses the code
- Updates the code by removing a few outdated things (regex replacements, version checks, and other things)
- Fixes occasional "Coming Soon" due to using "direct.nodejs.org"
- More obvious promisification of pieces of the code
- Already transforms the `*` lists into `-` lists (sadly prettier does not allow this to be changed)
- Adds ShellScript and ShellSession Shiki Languages

## Validation

Generating the Blog Posts should still work (for latest version, specific version, and forced generation)

### CODE REVIEW

**Comment by ovflowd** [comment]
cc @tniessen @nodejs/web-infra

**Review by tniessen — APPROVED** [review]
RSLGTM :)

**Review by bmuenzenmeyer — APPROVED** [review]
read through it - also ran the current release post again

✅

**Comment by richardlau** [comment]
The preview link is showing a 500 error?

**Comment by richardlau** [comment]
>     * Fixes occasional "Coming Soon" due to using "direct.nodejs.org"

History is that we switched to using direct _because_ of "Coming Soon"'s occurring: https://github.com/nodejs/nodejs.org/pull/4136
This will be very hard to validate/test outside of a release.

**Comment by bmuenzenmeyer** [comment]
> The preview link is showing a 500 error?

I'm guessing that's a hiccup - local and CI `deploy` and `serve` scripts run fine and this changeset doesn't appear to have anything related to next deployment. 🤞 

@ovflowd or someone else with Vercel access can look into it (I still do not)

**Comment by ovflowd** [comment]
> > ```
> > * Fixes occasional "Coming Soon" due to using "direct.nodejs.org"
> > ```
> 
> History is that we switched to using direct _because_ of "Coming Soon"'s occurring: #4136 This will be very hard to validate/test outside of a release.

Right. But that's the source of flakiness. The thing is that `direct.nodejs.org` is less reliable, as it is a non-cached origin. Not to mention once we move to R2, `direct.nodejs.org` is not an endpoint we want to hit.

**Comment by ovflowd** [comment]
> > The preview link is showing a 500 error?
> 
> I'm guessing that's a hiccup - local and CI `deploy` and `serve` scripts run fine and this changeset doesn't appear to have anything related to next deployment. 🤞
> 
> @ovflowd or someone else with Vercel access can look into it (I still do not)

Yea, I fixed the issue. It was `shiki's` `embeddedLangs`. Apparently it completely ignores the language grammar I am providing and tries to use its "built-in" resolution.

Removing `embeddedLangs` surprisingly doesn't break the highlighting, and apparently it is only used to pre-load other languages before the one you're currently loading. But since our `shiki.config.mjs` is already ordered, all fine. I swear, I hate when popular libraries depend on filesystem or other internals and give little to none control to end-users (I had to dig deep in order to make this `shiki.config.mjs` to work to begin with.

**Review by araujogui — APPROVED** [review]

**Review by RafaelGSS — APPROVED** [review]
LGTM

**Comment by richardlau** [comment]
> > > ```
> > > * Fixes occasional "Coming Soon" due to using "direct.nodejs.org"
> > > ```
> > 
> > 
> > History is that we switched to using direct _because_ of "Coming Soon"'s occurring: #4136 This will be very hard to validate/test outside of a release.
> 
> Right. But that's the source of flakiness. The thing is that `direct.nodejs.org` is less reliable, as it is a non-cached origin. Not to mention once we move to R2, `direct.nodejs.org` is not an endpoint we want to hit.

Yes, being non-cached was the point behind the original switch. Maybe it's not an issue now with the tweaks that were made to avoid caching 404's.

**Comment by ovflowd** [comment]
> > > > ```
> > > > * Fixes occasional "Coming Soon" due to using "direct.nodejs.org"
> > > > ```
> > > 
> > > 
> > > History is that we switched to using direct _because_ of "Coming Soon"'s occurring: #4136 This will be very hard to validate/test outside of a release.
> > 
> > 
> > Right. But that's the source of flakiness. The thing is that `direct.nodejs.org` is less reliable, as it is a non-cached origin. Not to mention once we move to R2, `direct.nodejs.org` is not an endpoint we want to hit.
> 
> Yes, being non-cached was the point behind the original switch. Maybe it's not an issue now with the tweaks that were made to avoid caching 404's.

Right. I'll keep an eye on that once a next release is done!

**Comment by targos** [comment]
I'm releasing v21.1.0 and hit two "coming soon" links and no shasums in the generated changelog.

**Comment by targos** [comment]
Rerunning a couple times fixed it, but it seems that the warning that used to be printed is no longer here so this is prone to errors if the generated file is not verified.

**Comment by ovflowd** [comment]
> Rerunning a couple times fixed it, but it seems that the warning that used to be printed is no longer here so this is prone to errors if the generated file is not verified.

Heyo, 👋 which warnings? 

The rerunning is due to Cloudflare giving errors probably a cache purge happened recently.

**Comment by targos** [comment]
> which warnings?

The script used to print warnings to the console when there were lines with "coming soon".

**Comment by ovflowd** [comment]
> > which warnings?
> 
> The script used to print warnings to the console when there were lines with "coming soon".

It should still be doing that if the request failed. But I can double-check. Afaik if the request failed (i.e. it will trigger a coming soon) it should console.warn that it failed. Will give a double check over here.

**Comment by targos** [comment]
@richardlau also had two "coming soon" links. Did you see a warning?

**Comment by richardlau** [comment]
> @richardlau also had two "coming soon" links. Did you see a warning?

No, no warnings.

**Pull request merged**
