### PR TITLE
fix: Certain languages break the max height of the search bar #6841

### LINKED ISSUE #6841: Certain languages break the max height of the search bar
### URL:

https://nodejs.org/pt or https://nodejs.org/fr

### Browser Name:

Chrome

### Browser Version:

N/A

### Operating System:

N/A

### How to reproduce the issue:

1. Switch to a Localized Language
2. You'll notice that the search bar height is not respected

### PR DESCRIPTION
**Pull request by nilkhankari**
## Description

Increased width of search button from 13rem to 15rem

## Validation

image

image

image

## Related Issues

Fixes: https://github.com/nodejs/nodejs.org/issues/6841

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by joesepi — APPROVED** [review]
LGTM but I'll leave it to the maintainers to full approve. :) Thank you!

**Comment by bmuenzenmeyer** [comment]
Two things

The keyboard shortcut still wraps. This is perhaps a separate issue, but we are in this section of the codebase here and it seems relevant to improve.
image

There is a viewport range (for me, on WIndows, Chrome, default zoom, `fr` locale) between1024px and 1114px where the site has a horizontal scrollbar.

image

I'd imagine we want to avoid that.

**Comment by nilkhankari** [comment]
Hi @bmuenzenmeyer ,
Thanks for the review. 
I am thinking of setting the width of the search button to 16rem. This will resolve the first issue. 
Regarding the second issue, I am considering reducing the gap and padding to 1rem. 
Do you have any suggestions on this proposed solution?

**Comment by ovflowd** [comment]
> Hi @bmuenzenmeyer , Thanks for the review. I am thinking of setting the width of the search button to 16rem. This will resolve the first issue. Regarding the second issue, I am considering reducing the gap and padding to 1rem. Do you have any suggestions on this proposed solution?

I think this is fine. Can you go ahead with it? (Dont forget to test different viewports, including mobile ones)

**Comment by nilkhankari** [comment]
Validation with new changes

For French language
image

image

image

image

For Portuguese
image

image

image

image

For English
image

image

image

image

**Comment by nilkhankari** [comment]
@bmuenzenmeyer @ovflowd Could you please review this.

**Review by aymen94 — APPROVED** [review]

**Review by nazarepiedady — COMMENTED** [review]
Since I did not know about this pull request, I neglected the searching work we should do before to do something on the project.

But I would like to contribute as a person dealing with front-end and accessibility problems for over than 8 years, saying that it is not recommended to explicitly set the `width` nor `height` to markup components because they should be dynamic in what concerned to their size.

We should use `padding` properties to set dynamic `width` and `height` to the component that should fit themselves to the content of the component.

**Comment by nilkhankari** [comment]
@ovflowd Could you please suggest what we should do with this PR?

**Comment by ovflowd** [comment]
> @ovflowd Could you please suggest what we should do with this PR?

Sorry for the delay! I did not get pinged here. Let's try @nazarepiedady's approach, as that makes sense. I'm worried with the tablet/small screen breakpoints, but we could add a max-width as a last resort and use padding here instead of setting widths.

Could you try that?

**Comment by ovflowd** [comment]
It looks like @nazarepiedady made a PR already https://github.com/nodejs/nodejs.org/pull/6904

**Comment by nilkhankari** [comment]
> It looks like @nazarepiedady made a PR already #6904

@ovflowd okay. Please suggest now what to do with this PR.

**Comment by ovflowd** [comment]
> > It looks like @nazarepiedady made a PR already #6904
> 
> @ovflowd okay. Please suggest now what to do with this PR.

I assume we'd proceed with Nazare's PR, but I'd keep this PR open until that gets merged. But feel free to close it, also.

**Comment by nazarepiedady** [comment]
@ovflowd, @bmuenzenmeyer, I believe we can close this pull request since the pull request I did is already merged.

I also would like to thank you, @nilkhankari, for your contribution because some of the updates that I did on my pull request were based on your pull request and ideas.

**Comment by mikeesto** [comment]
Closing as https://github.com/nodejs/nodejs.org/pull/6904 landed. Thanks everyone

**Pull request closed without merging**
