### PR TITLE
fix: layout shift on blogs due to i18n comps

### PR DESCRIPTION
**Pull request by Kinfe123**
- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
Could you give more information about this change. Because now it's just change the render of blog page. too keep footer visible.

**Comment by ovflowd** [comment]
I don't understand what the issue is. Could you attach a screenshot, reproduction steps or a video?

**Comment by Kinfe123** [comment]
sorrry for not being in touch

**Comment by Kinfe123** [comment]
[Screencast from 2024-03-24 11-42-50.webm](https://github.com/nodejs/nodejs.org/assets/65047246/34494af4-8794-4b62-8e9e-fc3eb4d0e5e1)

**Comment by AugustinMauroy** [comment]
@Kinfe123 which browser do you use?
'cause I can't reproduce your behaviour on safari or Chrome.

Also you solution change the design of page. I mean `NavBar` and `Footer` become sticky

**Comment by Kinfe123** [comment]
yeah i thought that would be a good thing ...making a sticky for the constant page layouts

**Comment by Kinfe123** [comment]
lemme reproduce if i can

**Comment by ovflowd** [comment]
Any luck reproducing the issue?

**Comment by ovflowd** [comment]
Closing for now, if the author still wishes to proceed with the PR, feel free to reopen.

**Pull request closed without merging**
