### PR TITLE
fix: legacy - use Buffer.from() instead of btoa()

### PR DESCRIPTION
**Pull request by shi-gg**
## Description
Fix homepage example for "Work with Threads":
`btoa("")` is a legacy function, `Buffer.from("").toString("base64")` should be used instead.

image

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by ovflowd** [comment]
The reason why we're using `btoa` here is for simplicity, by adding imports to `Buffer` the snippet becomes even more convoluted.

**Comment by shi-gg** [comment]
I understand that, though it’s awkward if the official homepage shows deprecated/legacy examples

**Comment by ovflowd** [comment]
> I understand that, though it’s awkward if the official homepage shows deprecated/legacy examples

Maybe, but it's just a _silly_ example. The important part is the worker communication. For all intends and purposes we can remove btoa and simply do .toUppercase()

The intent was just to show that a separate worker would handle the "work" and that it can work on the "data" you've initially sent.

**Comment by ovflowd** [comment]
@Luna-devv do you want to make amends to this PR?

**Pull request closed without merging**
