### PR TITLE
Map distance+position fix for mapbox/leaflet

### PR DESCRIPTION
**Pull request by justsml**
@mikeal

### CODE REVIEW

**Comment by mikeal** [comment]
Sorry that I missed this, can we re-target to master to get this in?

**Comment by mikeal** [comment]
I pulled this in locally and fixed the merge conflict but the behavior isn't ideal.

This ends up zooming way too far in, showing only the closes point. The code I had written was attempting to show at least 10 points on the map.

**Comment by justsml** [comment]
Ok, I understand. I can adjust the code pretty quickly. I've got something to try on the sort as well.

**Comment by justsml** [comment]
hey @mikeal  when you say retarget to master, do you mean rebase? Or ..?

**Comment by justsml** [comment]
How do i reposition my git at `justsml/events` over to origin/master & merge just my updates and then force update over my justsml/events?

**Comment by justsml** [comment]
Sorry for the dumb git questions... I'm trying.

Should I just do a fresh pull? :confounded:

**Comment by stevemao** [comment]
I think @mikeal means PR against master. The only way to retarget is to create a new PR :)

**Comment by justsml** [comment]
Thx @stevemao I have a new PR at #389

**Pull request closed without merging**
