### PR TITLE
outreachy: add citgm

### PR DESCRIPTION
**Pull request by MylesBorins**
here is an extra project for students to apply to.

I think project one is a bit more approachable and malleable, which
should make for a wider audience.

/cc @hackygolucky

### CODE REVIEW

**Comment by Trott** [comment]
LGTM.

Nit: Might want to define "smoke testing" (or omit/replace the term).

**Comment by MylesBorins** [comment]
@Trott updated PTAL

**Comment by zlatanvasovic** [comment]
LGTM :shipit:

**Comment by Trott** [comment]
LGTM.

Micro-nits:
- period after `'testing utility` rather than a comma (and capitalize the next word, so `it` -> `It`)
- `node` -> `Node.js`
- `other peoples code` -> `other people's code`

**Review by fhinkel — APPROVED** [review]

**Comment by fhemberger** [comment]
Thanks!

**Pull request merged**
