### PR TITLE
chore: reduce requirement from 2 approvals to 1

### PR DESCRIPTION
**Pull request by ovflowd**
Hey @nodejs/website I'm proposing we change the minimum amount of approvals for having a PR getting merged from 2 to 1.

This is due to not so many people being active on the Website Team. And often I cannot get reviews for PRs for long periods of time.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
If we reduce number of approvals we need to increase the time without objection/request change ?
Also should we ping TSC (website team is TSC recharged) ?

**Comment by Trott** [comment]
> Also should we ping TSC (website team is TSC recharged) ?

I appreciate the cautious consideration, but there's no need to ping TSC on minutiae like how many approvals are needed to land something. That's for the website group to decide.

**Review by Trott — APPROVED** [review]

**Comment by HinataKah0** [comment]
+1, I think it's reasonable to reduce it to 1 for now since we are in the middle of migrating things...

For worries on Stability, I believe the migration hardly touches legacy things... So, simple sanity check is sufficient (e.g. our checks are green)

**Review by HinataKah0 — APPROVED** [review]

**Comment by ovflowd** [comment]
> If we reduce number of approvals we need to increase the time without objection/request change ?

Nope. Current time is more than enough.

**Review by AugustinMauroy — APPROVED** [review]

**Review by mikeesto — APPROVED** [review]

**Review by manishprivet — APPROVED** [review]
Agreed with the change. I myself have been extremely busy due to the last year of my uni 😞 Would be back soon though on contributing. Thanks @ovflowd

**Review by bmuenzenmeyer — APPROVED** [review]
I find this to be one of GitHub's current shortfalls, and hope someday for the PR author to define the [review scrutiny](https://tech.target.com/blog/review-scrutiny) required. I'm currently a Node.js triager but am thinking my time could be better served reviewing PRs here too. 🤞

**Comment by ovflowd** [comment]
Hey, @bmuenzenmeyer thanks for the feedback! I'm curious about what "review scrutiny" is, so I'm going to read your blog post :)

**Comment by bmuenzenmeyer** [comment]
It's really a prioritization of trust in people vs adhering to the rigidity of the tooling. Functionally, it's just a PR template entry. On a small team it has worked really well, by putting the responsibility of the number of reviews required on the pull request author. I don't know how well it would translate to a global, open source project.

**Review by ghost — APPROVED** [review]
https://github.com/nodejs/nodejs.org/blob/9a41ee51dea2ca45d4e908f164cae5ac55f76c7e/CONTRIBUTING.md?plain=1#L150-L151

General speaking, +1 for this Approval suggestion bcoz we're volunteering to work here and many a time we are so busy to see what's happening by accident or bcoz of the diff timezones.

But what about this senario **if we have both agreements and objections**? 
1. Wait until he/she changes his/her idea to agree?
2. Dismiss him/her if more agree? (Depending on what number of people agree/disagree....)
3. Any other better suggestions?

Maybe for L150 and L151, there's something we should make up to make it more clear?

**Comment by ovflowd** [comment]
> But what about this senario if we have both agreements and objections?

The contributing guidelines are clear if objections arise the PR cannot be merged until all objections are cleared.

**Comment by ovflowd** [comment]
2 days have passed (not exact 48 hours but it's very unlikely we're getting a rejection at this point in time) so I'm merging this :)

**Pull request merged**
