### PR TITLE
Add a PR Template to this repo

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
Working on this

### CODE REVIEW

**Comment by XhmikosR** [comment]
Closing since the fork is gone.

**Comment by KendallDoesCoding** [comment]
Oh gosh, Sorry I forgot I deleted the fork.

Will you merge it if I restore the fork @XhmikosR?

**Comment by XhmikosR** [comment]
Not my decision only, so I'd say just make a new PR and someone will have a look when they have time.

**Comment by KendallDoesCoding** [comment]
> Not my decision only, so I'd say just make a new PR and someone will have a look when they have time.

Ok, will do that.

**Comment by KendallDoesCoding** [comment]
REPLACEMENT PR #4334

**Pull request closed without merging**
