### PR TITLE
New Persian translations

### PR DESCRIPTION
**Pull request by ebraminio**
Applied #2775 and #2835 plus minor fixes and more translations.

Closes #2835
Closes #2775

### CODE REVIEW

**Comment by ebraminio** [comment]
@nodejs/nodejs-fa have a look please.

**Comment by alexandrtovmach** [comment]
@nodejs/nodejs-fa Friendly reminder

**Comment by alexandrtovmach** [comment]
@nodejs/nodejs-fa

**Comment by ebraminio** [comment]
All are now moved to https://crowdin.com/project/nodejs-website/fa

@nodejs/nodejs-fa feel free to replace any of my translations there. Thanks!

**Comment by alexandrtovmach** [comment]
@ebraminio Thank you for moving translations to Crowdin, and sorry for this uncomfortable way

**Pull request closed without merging**
