### PR TITLE
Add vnu.jar support

### LINKED ISSUE #2398: Fix HTML validation errors
It seems there are plenty of errors, with some of them important IMO.

For example https://validator.w3.org/nu/?doc=https%3A%2F%2Fnodejs.org%2Fen%2Fblog%2F

We could automate the checks if you agree, most should be easy to fix. Here's a first attempt to use the official HTML validator: https://travis-ci.org/XhmikosR/nodejs.org/builds/572662096

### PR DESCRIPTION
**Pull request by XhmikosR**
This is WIP because there are some things that need to be addressed:

1. #2441 needs to be merged
2. #2437 probably needs to be merged too
3. There's a bug in vnu.jar, I have already discussed with sideshowbarker (not CC'ing right now), that causes the build to exit with non-zero.
4. I'd prefer it if we could actually fix the table errors, because these are real issues:
    ```
    "file:/home/travis/build/XhmikosR/nodejs.org/build/en/download/index.html":276.50-277.32: error: Table column 3 established by element "td" has no cells beginning in it.
    "file:/home/travis/build/XhmikosR/nodejs.org/build/en/download/index.html":277.113-278.32: error: Table column 7 established by element "td" has no cells beginning in it.
    ```
5. The license of the new file might need to be adapted for this repo. It's just a simple script so it's OK to change it, especially since I also adapted it to fit our needs

Note that this is how I noticed and fixed many of the issues so far, like https://github.com/nodejs/nodejs.org/commit/bae664a98a772781314b05eae4cdcc57efafd2b0, https://github.com/nodejs/nodejs.org/commit/b533fcddc0deffbf086d229b5f79155d8a21868d, https://github.com/nodejs/nodejs.org/commit/a714afcc90df0283d0cd9006d049a78ce60361fc, https://github.com/nodejs/nodejs.org/commit/ceee600686ae067f439a7ad9230499c442081e12 etc.

IMO this should definitely land as soon as we sort out the above points. Personally I'd remove htmllint too; I'm [having issues with it on Windows](#2459) and it just doesn't seem to catch any real issues.

Marking it as draft for further discussion and tweaks.

vnu.jar: <https://github.com/validator/validator>

Closes #2398

### CODE REVIEW

**Comment by XhmikosR** [comment]
I think we should try fixing the table errors. I'm gonna revert the ignore so that we see the errors, and someone might be able to help fix those. I believe the wrong exit code comes from this for some reason.

**Comment by XhmikosR** [comment]
Alright, I don't know how to fix the table errors, so I have them ignored for now.

This is ready for review. Note that on Windows there will be a failure due to #2422. This isn't triggered on nix, but I've yet to figure out the root cause (like I never managed to figure it out for the slashes, hence the workaround we have).

**Comment by XhmikosR** [comment]
After #2511 CI will be green. Generally that is why I insist that branches need to be up to date and we have the button.

**Comment by XhmikosR** [comment]
Can we move with this?

**Comment by XhmikosR** [comment]
Can I get some reviews please?

This is the only proper way to make sure we are valid and we don't have issues like duplicate IDs and so on. Note that I intentionally skip the test if Java isn't available, and that I haven't added the script in `npm t` like I haven't done it with linkinator, because these tests are a little slow.

On CI Java is present so this will run there.

**Comment by Trott** [comment]
@nodejs/website

**Review by phillipj — APPROVED** [review]
LGTM

**Pull request merged**
