### PR TITLE
Add version toggle to download page

### LINKED ISSUE #321: More descriptive buttons for LTS and Stable in the download tab.
We should have more descriptive tabs, similar to what we have on the front page, for the corner LTS and Stable tabs.

### PR DESCRIPTION
**Pull request by rnsloan**
Fixes #321 
- Add toggle
- remove top-right menu 

---

---

### CODE REVIEW

**Comment by fhemberger** [comment]
Wow, awesome! :+1:

**Comment by bnb** [comment]
Rally rad! :+1:

**Comment by lpinca** [comment]
It looks great.

**Comment by phillipj** [comment]
+:100:

**Comment by stevemao** [comment]
The images look awesome :) has anyone else tested this yet?

**Comment by diagramatics** [comment]
How about a different active color for LTS and stable, just to indicate which version the user is going to download easier?

**Comment by bnb** [comment]
@diagramatics I was looking at the gif, and noticed that the Windows/OS X/Source parts have a dark gray background on hover. Maybe that could be used?

**Comment by rnsloan** [comment]
@bnb like this?

full

black

**Comment by bnb** [comment]
@rnsloan Yes, except keep the bright green (from the previous version) for the active state. 

Notice how the gray background is only visible on hover for the Windows/Mac/Source buttons. Like that, except with the green background as an active state.

**Comment by rnsloan** [comment]
Colors updated. Merging.

**Comment by phillipj** [comment]
:dancers: nice work!

**Comment by bnb** [comment]
Good job. Looks awesome live!

**Comment by stevemao** [comment]
Perfect, Thanks @rnsloan :)

**Pull request merged**
