### PR TITLE
Ru: translation of simple-profiling.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@nodejs/nodejs-ru , Please have a review, thanks!

**Comment by XhmikosR** [comment]
This should be rebased since we don't have the Update branch button.

**Review by alexandrtovmach — APPROVED** [review]

**Comment by ghost** [comment]
@vasbaz : It seems for another half of the article isn't translated yet (Since L126). Maybe you can submit another PR.

**Comment by ghost** [comment]
@MaledongGit I'll do it in a week

**Pull request merged**
