### PR TITLE
test: increase test coverage

### PR DESCRIPTION
**Pull request by AugustinMauroy**
## Description

GOAL 🎯: increase unit test coverage

I don't have test all things depend of `next-data`.

- removing flag `passWithNoTests` because we have test and if there test found it's an error.
- Moving test for hook in specific dir to have strict separation of server and client

Test yet to be created:

- `getBitness`

## Validation

- test should pass 
- build mustn't change

## Related Issues

No related Issues

### Check List

- [X] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [X] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [X] I have run `npx turbo format` to ensure the code follows the style guide.
- [X] I have run `npx turbo test` to check if all tests are passing.
- **NA** I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by ovflowd** [comment]
I think we should also add tests for these two hooks:

image

(but directly on the `./hooks/__tests__` folder)

**Comment by ovflowd** [comment]
To test the functionalities of `next-data` I assume somehow you'll need to spyOn `writeFile`

**Comment by AugustinMauroy** [comment]
@ovflowd  ok i will take a look into that 👍

**Comment by ovflowd** [comment]
@AugustinMauroy I can merge these tests for now and then we add more, ok?

**Review by ovflowd — APPROVED** [review]
Awesome work. Thank you, Augustin!

**Comment by AugustinMauroy** [comment]
ok go ahead ! 🚀

**Pull request merged**
