### PR TITLE
chore: remove github pages

### PR DESCRIPTION
**Pull request by ovflowd**
This PR simply removes the support to GitHub Pages, as we use Vercel Deployments now (Previews and "Production" builds) and there seems to be no reason, to use extra CI on the `main` branch for GitHub Pages.

### CODE REVIEW

**Comment by ovflowd** [comment]
cc @nodejs/website if anyone has an opinion here. And requesting fast-tracking of this, as this seems like a no-brainer IMHO.

**Comment by bmuenzenmeyer** [comment]
LGTM - aside from the `public/` thrashing which IIRC we are fixing elsewhere

**Comment by ovflowd** [comment]
> aside from the public/ thrashing which IIRC we are fixing elsewhere

Oh these files got committed T.T

**Review by Harkunwar — APPROVED** [review]
LGTM!

**Review by shanpriyan — APPROVED** [review]
LGTM!

**Pull request merged**
