### PR TITLE
locale: add Ukrainian language

### PR DESCRIPTION
**Pull request by ghaiklor**
Thanks to @denysdovhan we have Ukrainian language for NodeJS website.
/cc @nodejs/nodejs-uk

### CODE REVIEW

**Comment by Fishrock123** [comment]
also cc @nodejs/website -- I don't think some of the pages here are necessary anymore and can probably also be removed from the english version, e.g. `/advisory-board/`.

**Comment by listochkin** [comment]
Adding +1 as a @nodejs/nodejs-uk member.

**Comment by ghost** [comment]
@Fishrock123 yeah, we can definitely remove `advisory-board` and translations. i'll open a separate issue for that

otherwise, LGTM from me ✨

**Comment by ghost** [comment]
@nodejs/nodejs-uk do you need one more LGTM from your group or can i merge this?

**Comment by sejoker** [comment]
One more LGTM from me as a @nodejs/nodejs-uk member.

**Comment by denysdovhan** [comment]
@Lac this translation is already checked by Ukrainian philologist, so we sure that everything is OK.

**Comment by fhemberger** [comment]
Thank you!

**Comment by phillipj** [comment]
Very nice work! :+1:

P.S. when new locales gets added, atm we have to manually enable english fallback (https://github.com/nodejs/nodejs.org/pull/490, https://github.com/nodejs/build/pull/316) in the nginx config as done in https://github.com/nodejs/build/pull/458.

**Comment by denysdovhan** [comment]
I've noticed a few small mistakes on the website. Gonna send pr with fixes.

And it seems like font doesn't support cyrillic characters and therefore it brakes layout. Take a look at https://github.com/nodejs/nodejs-uk/issues/88.

**Pull request merged**
