### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by lpinca**
- [`autoprefixer-stylus@0.13.0`](https://github.com/jescalan/autoprefixer-stylus/compare/v0.11.0...v0.13.0)
- [`html-to-text@3.0.0`](https://github.com/werk85/node-html-to-text/compare/66cb9506d7dac8fc922981ab8a85e400bc828aec...master) 
- [`metalsmith-prism@3.0.2`](https://github.com/Availity/metalsmith-prism/releases/tag/v3.0.2)
- [`node-geocoder@3.15.2`](https://github.com/nchaulet/node-geocoder/compare/8c0d4cc...11a6c55)
- [`snyk@1.23.2`](https://github.com/Snyk/snyk/releases)
- [`strftime@0.10.0`](https://github.com/samsonjs/strftime/blob/master/Changelog.md#v0100-on-2016-12-28)

### CODE REVIEW

**Comment by yorkie** [comment]
@lpinca html-to-text is a semver-major upgrade, a simple description about why we need this patch and risks?

**Comment by lpinca** [comment]
@yorkie AFAIK the only breaking change there is the switch to htmlparser2. It should have no side effects for us.

**Comment by lpinca** [comment]
`html-to-text` is only used in the [`event-geo.js`](https://github.com/nodejs/nodejs.org/blob/6be0db3b6d0762d6bd4da6223e1c61bd159ac9be/scripts/event-geo.js#L46) script to have a "text" description of the events in the map of the events page.

**Review by ryanmurakami — APPROVED** [review]
LGTM

**Pull request merged**
