### PR TITLE
Update code-and-learn.md

### PR DESCRIPTION
**Pull request by jvelezpo**
NodeConfCo, code and learn added to upcoming events

### CODE REVIEW

**Review by edsadr — APPROVED** [review]

**Review by julianduque — APPROVED** [review]
💃

**Review by ZYSzys — APPROVED** [review]
Cool!

**Comment by Maledong** [comment]
@nodejs/nodejs-pt：Maybe you can translate your language for this submit, continue to my work :)

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
@jvelezpo：Thanks for your nice contribution!

**Pull request merged**
