### PR TITLE
fix(docs): remove deprecated usage of npm ci --only

### PR DESCRIPTION
**Pull request by erfanium**
this is the npm output when you using `npm ci --only=production` 

npm version: 8.19.0

```
Step 4/7 : RUN npm ci --only=production
 ---> Running in bfc1319afc62
npm WARN config only Use `--omit=dev` to omit dev dependencies from the install.

```

### CODE REVIEW

**Review by ovflowd — APPROVED** [review]
Thank you for your contribution! LGTM!

**Review by AugustinMauroy — APPROVED** [review]
Thank you for your contribution (thanks for looking at the different languages)

**Comment by Trott** [comment]
@nodejs/docker

**Comment by ovflowd** [comment]
Hey @erfanium could you rebase this PR? (I'm going to merge after rebase as the @nodejs/docker WG hasn't said anything)

**Review by aymen94 — APPROVED** [review]

**Comment by erfanium** [comment]
@ovflowd sorry for my late reply. i'll do it today

**Comment by ghost** [comment]
@erfanium：Thanks for your 1st contribution to Nodejs.org and if you are free, please solve the conflict problems so as to make your changes get merged :)

**Comment by erfanium** [comment]
@MaledongGit @ovflowd 
Sorry all, we are in new year holidays in Iran. I have fixed all conflicts

**Review by mikeesto — APPROVED** [review]

**Review by PeterDaveHello — APPROVED** [review]

**Review by manishprivet — APPROVED** [review]

**Pull request merged**
