### PR TITLE
Use stream/promises on home

### PR DESCRIPTION
**Pull request by Joabesv**
## Description

Remove promisify to use the pipeline from `node:stream/promises`

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by AugustinMauroy — APPROVED** [review]
LGTM !

**Review by ovflowd — APPROVED** [review]
This change makes a lot of sense, but could you somehow add an extra line? We want to ensure all snippets have exactly 14 lines 😅 

Yes it's a weird requirement, but to ensure the codebox size is always the same

**Review by aymen94 — APPROVED** [review]

**Comment by Joabesv** [comment]
@ovflowd i can do it, just adding an extra space before the comment line. Will make the change and wait for feedback.

**Comment by lmammino** [comment]
I have already seen a few conversations with folks wondering why do we suggest to manually promisify `pipeline` rather than using the already promisified one in `stream/promises`.

I'd say, it would be nice to ship this one ASAP :)

Refs:

- https://twitter.com/maksimsinik/status/1771639350914167106
- https://www.linkedin.com/feed/update/urn:li:activity:7177282688326750208?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7177282688326750208%2C7177488964210053120%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287177488964210053120%2Curn%3Ali%3Aactivity%3A7177282688326750208%29

**Comment by lmammino** [comment]
Made a PR to, hopefully, help speeding things up a little :)

Let me know if it's easy to review/merge: https://github.com/Joabesv/nodejs.org/pull/1/

**Comment by ovflowd** [comment]
I checked your PR and it is not even opened against this repository + it has unrelated changes, I believe you did something wrong during the rebase.

**Comment by ovflowd** [comment]
I'd recommend just making a fresh new branch based out of main and applying the changes from this PR

**Comment by lmammino** [comment]
It's possible I did something wrong, since I also rebased off of current main. I didn't do a fresh PR because I didn't want to take over all the changes and take all the credit.

I believe that if @Joabesv merges that PR, this PR would be updated correctly.... Or at least that was my original intent 😅

But at this point I suspect it's probably easier/safer for @joabesv to do the changes by himself

**Comment by ovflowd** [comment]
I did the changes myself directly here, and I'm merging asap.

**Comment by lmammino** [comment]
Thanks @ovflowd 🙏😊

**Pull request merged**
