### PR TITLE
feat: introduced generic time component

### LINKED ISSUE #5481: Create <Time/> component
Create a generic `Time` cimponent that displays date info in the curent locale.

The component should have two props: `date`, which should be a string or `Date` object and the second one. corresponding to the shape of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#options

The component should return a `time` element, with the DateTime formatted on the currently applied locale (so the component must use `useLocale` hook).

See the repeated usage of a workaround from https://github.com/nodejs/nodejs.org/pull/5479. The new component would replace these.

```jsx
<time dateTime={post.date}>
  {new Date(post.date).toLocaleString('en-GB', {
    timeZone: 'UTC',
    month: 'short',
    day: '2-digit',
  })}
</time>
```

### PR DESCRIPTION
**Pull request by ovflowd**
## Description

This PR introduces a simple `Time` component that fulfils the specification presented on the issue.

It also updates the `en` locale to use `en-GB`

## Related Issues

Fixes #5481

### CODE REVIEW

**Comment by ovflowd** [comment]
@mikeesto I've made a clean PR (just because I accidentally deleted the branch on upstream)

(Actually, this branch should have been done on the fork to begin with... but hey, Codespaces default remote was set to upstream)

**Review by mikeesto — APPROVED** [review]
Not sure why there is a diff for `package-lock`? Otherwise LGTM.

**Review by bmuenzenmeyer — APPROVED** [review]
LGTM

**Review by shanpriyan — APPROVED** [review]
LGTM!

**Review by aymen94 — APPROVED** [review]

**Comment by ovflowd** [comment]
> Not sure why there is a diff for package-lock? Otherwise LGTM.

A little audit fix

**Pull request merged**
