### PR TITLE
doc: note JavaScript is not single threaded

### PR DESCRIPTION
**Pull request by benjamingr**
Honestly I appreciate the effort and don't have time to go over the whole thing but there are plenty of inaccuracies in this document.

This PR fixes the first one I noticed - JavaScript as a language is _not_ single threaded. Nor has it ever been, and multithreaded JavaScript execution dates back at least 10-20 years

### Check List

- [ ] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [ ] I have run `npm run format` to ensure the code follows the style guide.
- [ ] I have run `npm run test` to check if all tests are passing.
- [ ] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by ovflowd** [comment]
If I recall this document was a port of the original guide written many years ago, so not sure who even wrote this initially.

**Review by canerakdas — APPROVED** [review]
LGTM

**Comment by joyeecheung** [comment]
I wonder if there's a better way to describe this. What happens in Node.js currently is:

1. In general, each libuv event loop pairs with one JS execution thread. There are 7 threads in total by default: 1 main thread (which executes JS and runs the event loop), 4 V8 task runner threads, 1 V8 delayed task runner thread, 1 inspector I/O thread; If any async operations are initiated, 4 more threads will be spawn by the libuv thread pool, and there will be 11 threads in total. (Sometimes additional threads & event loops are spawned for e.g. watchdog for Ctrl+C signals, but those are on-demand)
2. When we are talking about a single Node.js instance (instances = main instance or Worker thread instances), each of them has 1 JS thread which runs one event loop. Every Worker spawn adds one more thread into the process (e.g. if the application does some async operation in the main thread, spawns a worker, and then also does some async operation in the worker, there would be 12 threads in total)

To emphasize that one can spawn threads from JS, maybe it's clearer to just mention Workers. But when we are talking about event loops, they do have a 1-1 correspondance with JS threads (each worker gets their own event loop). Or we can just drop "despite the fact that JavaScript is single-threaded" completely since it's not exactly clear what this is talking about in this context.

**Review by aymen94 — APPROVED** [review]

**Comment by nazarepiedady** [comment]
@benjamingr, you are correct because the language itself can not be described as single nor multi-thread because these specifications have to do with its interpreters and runners.

But I think the usage in this document could be because currently, many programmers associate the language to its interpreter.

To me, it would be better if we say that *Node.js* not *JavaScript* is single-thread.

**Comment by bmuenzenmeyer** [comment]
This PR will need to be rebased or recreated now that https://github.com/nodejs/nodejs.org/pull/6850 merged.

**Comment by benjamingr** [comment]
> To me, it would be better if we say that Node.js not JavaScript is single-thread.

That's also not true (e.g. https://nodejs.org/api/worker_threads.html :D ). We can add Node.js executes a single thread of user JavaScript unless other threads are explicitly created by the user or libraries, not sure that helps.

@bmuenzenmeyer I'm not sure what that means feel free to edit this branch

**Review by AugustinMauroy — COMMENTED** [review]
LGTM as it is, I think this resource could do with a little cleaning.

**Review by AugustinMauroy — APPROVED** [review]
LGTM as it is, I think this resource could do with a little cleaning.

**Review by mikeesto — APPROVED** [review]

**Pull request merged**
