### PR TITLE
zh-CN: improve Translation

### PR DESCRIPTION
**Pull request by Jarvan-via**
### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing, and/or `npx turbo test:snapshot` to update snapshots if I created and/or updated React Components.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by Jarvan-via** [comment]
Fix some incorrect translations

**Comment by AugustinMauroy** [comment]
Hey thanks for your help. But now we use crowdin you can take look to [translation guideline](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md)

**Comment by Jarvan-via** [comment]
> Hey thanks for your help. But now we use crowdin you can take look to [translation guideline](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md)

I have applied to join the translation team，At present, all Chinese articles look like machine translation

**Comment by AugustinMauroy** [comment]
@MaledongGit Can you take a look to this? I thinks it's your language

**Comment by ovflowd** [comment]
@Jarvan-via I'm adding you to the team and closing this issue :)

**Comment by ghost** [comment]
@Jarvan-via ：Sorry for the late reply bcoz of my busy work these days...

In fact these files are already translated well, and when I import the translated files into the Crowdin, sometimes the translated snippets of texts don't match where it exists in English, and when it cannot find accurately, it will make a "machine translation".

I've changed these translated texts these days and thanks for your pointing at me :)

**Comment by Jarvan-via** [comment]
> 



> @Jarvan-via ：Sorry for the late reply bcoz of my busy work these days...
> 
> In fact these files are already translated well, and when I import the translated files into the Crowdin, sometimes the translated snippets of texts don't match where it exists in English, and when it cannot find accurately, it will make a "machine translation".
> 
> I've changed these translated texts these days and thanks for your pointing at me :)


I am also the one who raised issue and suggest on crowdin recently 😄

**Pull request closed without merging**
