### PR TITLE
chore: remove performance section of ES6 page

### LINKED ISSUE #3176: doc: refer to not-up-to-date website: six-speed
https://nodejs.org/en/docs/es6/

In the link above there is a refrence to websit: six-speed. About performance of EcmaScript features. The website is so outdated.

### PR DESCRIPTION
**Pull request by Trott**
Information linked is out of date. Including an ES6 page is probably
something that needs to be re-thought entirely.

Fixes: https://github.com/nodejs/nodejs.org/issues/3176

@fhinkel

### CODE REVIEW

**Comment by Trott** [comment]
@alexandrtovmach Am I doing this right? Or do these changes need to go through Crowdin somehow?

**Comment by Trott** [comment]
> @alexandrtovmach Am I doing this right? Or do these changes need to go through Crowdin somehow?

@zeke

**Comment by Trott** [comment]
@nodejs/website

**Review by nschonni — APPROVED** [review]
Not sure if the ro and fr pages should just be removed since they appear to be only English

**Review by LinusU — APPROVED** [review]
Nice 👍

**Review by 3imed-jaberi — APPROVED** [review]

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
