### PR TITLE
revert "remove entire sentence in http anatomy" and replace it?

### PR DESCRIPTION
**Pull request by ghost**
i've accidentally directly pushed to master and deleted a sentence in a guide. i'm reverting that, but maybe we can also discuss if we should readd that sentence? @Trott made a valid complaint in https://github.com/nodejs/nodejs.org/pull/498#discussion_r51367974
#498, cc @Trott

### CODE REVIEW

**Comment by stevemao** [comment]
@nodejs/documentation

**Comment by Trott** [comment]
I'm fine with either omitting the sentence entirely or leaving the sentence there but omitting `such as other abstractions and tools,`. I guess it comes down mostly to how valuable the information in the linked text is.

**Comment by eljefedelrodeodeljefe** [comment]
I am indifferent on this. Rather have it shorter and link to something like "error handling" general guide in the future https://github.com/nodejs/docs/issues/82

**Comment by ghost** [comment]
i'm going to merge this for now.

**Pull request merged**
