### PR TITLE
ru：replace jargon in Russian text (#5027)Co-authored-by: Claudio Wunder <cwunder@gnome.org>

### PR DESCRIPTION
**Pull request by gurugray**
Replace `функционал` to `функциональность` this is a slang term, it is better to use the literary form.
https://ru.wiktionary.org/wiki/%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB

### CODE REVIEW

**Comment by ghost** [comment]
@nodejs/nodejs-ru：Please have a review, thanks!

**Comment by superioreturns** [comment]
gh pr checkout 5027

**Review by superioreturns — APPROVED** [review]
locale/ru/docs/es6.md

**Comment by gurugray** [comment]
Hello, is there any additional action I need to take?

**Comment by ovflowd** [comment]
Hey @gurugray, not really. As stated in some places, the repository is on a code freeze right now as we're waiting for #4991 to get merged.

**Review by alexandrtovmach — APPROVED** [review]
lgtm
btw: thanks, never thought that's jargon, that means a bit different things

**Review by ovflowd — APPROVED** [review]

**Pull request merged**
