### PR TITLE
The back to top button at the bottom of the page does not appear properly in mobile responsive

### PR DESCRIPTION
**Pull request by benveo**
incorrect
Screenshot_1

improved
Screenshot_2

### CODE REVIEW

**Comment by emirgoren** [comment]
It may be better not to appear because scrolling is much easier on mobile. But it should be fixed either way.

**Comment by ovflowd** [comment]
I'm also inclined to hide this on mobile screens. (You can use CSS rule for if the device has touch capabilities)

**Comment by satoshinakamotoVoltage** [comment]
Hi. I came to start.
wwww.mehdimehrabi40277@gmail.com

**Comment by ovflowd** [comment]
Closing as https://github.com/nodejs/nodejs.org/pull/5098 fixed this issue.

**Pull request closed without merging**
