### PR TITLE
Fixed typo (bug in code example)

### PR DESCRIPTION
**Pull request by ackinc**

### CODE REVIEW

**Comment by Trott** [comment]
@nodejs/diagnostics

**Review by RafaelGSS — CHANGES_REQUESTED** [review]
The current code is correct. It aims to return `400` if the user already exists, otherwise, it creates.

**Comment by nschonni** [comment]
I think this has come up and reverted back and forth a few times. It might be worth having a code comment in the sample to clear up the confusion

**Comment by ackinc** [comment]
> The current code is correct. It aims to return `400` if the user already exists, otherwise, it creates.

Not sure I agree, @RafaelGSS . Why would the handler of the `/auth` route, whose goal is to check whether a supplied password belongs to the specified user or not, return a 400 if the user exists?

In fact, just a few lines below my change, the handler refers to `user[username]`. This is unreachable code if the handler returns 400 if `user[username]` already exists.

Perhaps you're thinking of the `/newUser` route, which is defined elsewhere in the same file.

**Review by RafaelGSS — APPROVED** [review]
LGTM

**Comment by RafaelGSS** [comment]
> In fact, just a few lines below my change, the handler refers to user[username]. This is unreachable code if the handler returns 400 if user[username] already exists.

You right. I was seeing another handler.

**Review by benjamingr — DISMISSED** [review]

**Review by Trott — APPROVED** [review]

**Pull request merged**
