### PR TITLE
clarify that the board meeting is a remote call

### PR DESCRIPTION
**Pull request by Fishrock123**
A concern was brought to me that people elected form the community board elections would have to fly to these meetings in-person.

cc @mikeal

### CODE REVIEW

**Comment by mikeal** [comment]
There are occasional in-person meetings and there is budget allocated for
board member travel if their company doesn't cover it.

**Comment by Fishrock123** [comment]
Hmmm, noted.

**Comment by ghost** [comment]
still, it does sound a bit misleading IMO. maybe change it to `remote and sometimes in-person`?

**Comment by williamkapke** [comment]
@Fishrock123 do you mind revising? It would be a nice addition.

**Comment by stevemao** [comment]
ping @Fishrock123

**Comment by Fishrock123** [comment]
closing since it may not be remote, if somoene else feels strongly about the wording feel free to take it up

**Pull request closed without merging**
