### PR TITLE
Remove no longer used logos

### PR DESCRIPTION
**Pull request by lpinca**
This removes foundation members logos that are no longer used, see https://github.com/nodejs/nodejs.org/commit/6d2f3ef862639ef628bfaf5e966b0808a38eb5c2#commitcomment-17850513.

### CODE REVIEW

**Comment by ghost** [comment]
why would stylint be failing the tests even though the stylus files weren't touched? whatever, LGTM

**Comment by lpinca** [comment]
@ore yes I guess there is something wrong in stylint, the failure looks totally unrelated.

**Comment by lpinca** [comment]
@ore https://github.com/rossPatton/stylint/issues/324

**Comment by ghost** [comment]
@lpinca alright! we should maybe ping @nodejs/tsc before though, just to be sure

**Comment by Fishrock123** [comment]
Seems fine to me if it looks good to @mikeal

**Comment by mikeal** [comment]
Why did Travis fail?

**Comment by ghost** [comment]
@mikeal unrelated issue with stylint, see further up the thread

**Pull request merged**
