### PR TITLE
Add guide: "Working with Different Filesystems"

### PR DESCRIPTION
**Pull request by jorangreef**
This was suggested by @silverwind in https://github.com/nodejs/docs/issues/42

### CODE REVIEW

**Comment by fhemberger** [comment]
Aren't you linking your docs on the website somewhere?

**Comment by jorangreef** [comment]
@fhemberger The plan was to make it part of a new guides section which does not yet exist.

**Comment by silverwind** [comment]
@fhemberger what do you think about adding a 'Guides' section right here:

screen shot 2015-10-18 at 6 47 23 am

**Comment by fhemberger** [comment]
@silverwind Perfect fit, and we could merge the other guides as well. :+1:

**Comment by fhemberger** [comment]
Merged, although it's not linked on the site yet.

**Pull request merged**
