### PR TITLE
New Announcement - Node Interactive N.A. Schedule

### PR DESCRIPTION
**Pull request by gtewallace**
Hi,

We'd like this to be added today at 12 Noon Eastern.

I _tried_ to copy the formatting from another recent announcement, but my js and markdown are not very good.

Thank you very much!

Greg

### CODE REVIEW

**Comment by lpinca** [comment]
@gtewallace I added a commit to your branch to fix the filename. I also updated the document to make it use bulleted lists for the highlights.

This is how it looks https://stackedit.io/viewer#!url=http://hastebin.com/raw/lijejijizo

**Comment by gtewallace** [comment]
@lpinca awesome! thank you

**Comment by lpinca** [comment]
@nodejs/website LGTY?

**Comment by ghost** [comment]
yep

**Comment by lpinca** [comment]
From #891:

> There seems to be a missing link towards the bottom with Visit here to register. I'm assuming 'here' should be actually be a link to somewhere?

@gtewallace do you know what the link is?

**Comment by gtewallace** [comment]
Gah, my bad. Thanks so much for catching

http://events.linuxfoundation.org/events/node-interactive

**Pull request merged**
