### PR TITLE
docs: fixing typos in zh-cn event loop page

### PR DESCRIPTION
**Pull request by nnsay**
1. fix the typos `setEffite` and `setFidate`
2. `check` translates as `检查` better
3. `poll` translates as `轮询` better

note: `2` and `3` comes from the history commits, I think the history is better.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
Thanks for your contribution. But we use Crowdin. Take a look to this [translation guide](https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md)

**Comment by ovflowd** [comment]
Closing as translations are only accepted over Crowdin.

**Comment by ovflowd** [comment]
@AugustinMauroy I guess we need a PR template similar to nodejs.dev and with a message on Top "TRANSLATIONS ON CROWDINW" (just kidding, something in line with "If you're doing a translation contribution please read the TRANSLATION guidelines first."

**Comment by nnsay** [comment]
@AugustinMauroy Crowdin is a good helper, but Chinese translation does translate incorrectly, e.g. `setEffite` `setFidate`, which is an obvious error. I feel like this  should be fixed via Crowdin or some others.

**Comment by AugustinMauroy** [comment]
Translation errors should be corrected on crowdin. And for your information there is a discussion section on crowdin. You can create a discussion there by saying "hey this translation doesn't look good to me".

**Pull request closed without merging**
