### PR TITLE
update: Remove node-events page

### PR DESCRIPTION
**Pull request by Trott**
The page is undermaintained and not very visible anyway. It currently
contains one past event, two upcoming events, and one event that is not
actually happening in 2019. It does not containt the Foundation's own
December conference. We could update it now, but it will simply
immediately go back to being neglected. This is not great content for
the website anyway, in my opinion. If we can get the Get Involved
section slimmed down a fair amount, it might make sense to include a
link or two to external well-maintained sources of information, whether
it be a community-maintained page somewhere or a search on Lanyrd or
similar service. But for now, let's remove this largely unused and
unmaintained page.

### CODE REVIEW

**Comment by ghost** [comment]
I agree, the file is frequently updated and changed, maybe we need something outside the website, and then refer the link....

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
@fhemberger Any other clues or ideas?

**Comment by fhemberger** [comment]
I think you made some valid points. Do what you think is best. 😉

Maybe someone else from the website team has some input. If there are objections, discuss the pros and cons. If there's no feedback after 1-2 days, proceed.

**Comment by alexandrtovmach** [comment]
We can make some public Google Calendar, and provide link to it on the website:
Advantages:
- easy to manage
- no more frequent updates in this repository
- we also can try to use Calendar API to show events near current date on the website

Disadvantages:
- require the Google account to create and manage this calendar
- require Google accounts to make request to add/modify event 
- localization: we should use universal (English) language to describe event details

**Pull request merged**
