### PR TITLE
Adding Sorocaba Node.js User Group to the Meetups list

### PR DESCRIPTION
**Pull request by pablos4nt0s**

### CODE REVIEW

**Comment by pin3da** [comment]
Hello @rectius I think that it will be overwritten when the  `pull-meetup.js` script is run. I will try to verify that in my locale to be sure. 

If you want to keep the data **exactly** like your in pull request, you will need to add the field `source_of_truth: true`

**Comment by pablos4nt0s** [comment]
Hey @pin3da, so let's wait for the script. Thank you!

**Comment by pin3da** [comment]
@rectius I just submitted a [PR](https://github.com/nodejs/nodejs.org/pull/998) updating the event.md using the script.

Could you double-check that your meetup was correctly added please ?

Thank you :smile:

**Comment by pablos4nt0s** [comment]
@pin3da All is ok! Thank you very much!

**Comment by pin3da** [comment]
You're welcome !

**Pull request closed without merging**
