### PR TITLE
Correct grammar and improve clarity

### PR DESCRIPTION
**Pull request by asdacosta**
## Description

Correct grammar and improve clarity

## Validation

Confirmed

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
While I appreciate the eye for detail, this is a low-quality PR to me that doesn't accomplish much other than what a grammar tool might suggest. I am 👎 but want other opinions.

**Comment by asdacosta** [comment]
> While I appreciate the eye for detail, this is a low-quality PR to me that doesn't accomplish much other than what a grammar tool might suggest. I am 👎 but want other opinions.

If it’s even a subtle part of the phrase that is wrong, I think it’s worth correcting as it can change the whole meaning of what is being conveyed. Hence, it might seem like a ‘low-quality’ when it’s impact in the whole text is actually significant. We’re weighing between wrong grammar and correct one, which option is best…

**Review by AugustinMauroy — APPROVED** [review]
LGTM !

**Comment by AugustinMauroy** [comment]
@bmuenzenmeyer I think it makes the text clearer

**Review by aymen94 — APPROVED** [review]

**Comment by aymen94** [comment]
@asdacosta thanks for contributing 🎉

**Pull request merged**
