### PR TITLE
chore: remove reference to outdated examples

### PR DESCRIPTION
**Pull request by avivkeller**
## Description

This PR removes the reference to the outdated example repository, as in its current state, it may confuse users more than help them.

## Related Issues

https://github.com/nodejs/admin/issues/883 discusses archiving the repository, and this is the only actively maintained link to the repository.

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [ ] I have run `npm run format` to ensure the code follows the style guide.
- [ ] I have run `npm run test` to check if all tests are passing.
- [ ] I have run `npx turbo build` to check if the website builds without errors.

### CODE REVIEW

**Comment by avivkeller** [comment]
https://nodejs-org-git-fork-redyetidev-patch-1-openjs.vercel.app/en/learn/getting-started/introduction-to-nodejs

**Review by bmuenzenmeyer — CHANGES_REQUESTED** [review]
blocking until https://github.com/nodejs/admin/issues/883 is resolved

**Comment by avivkeller** [comment]
> blocking until https://github.com/nodejs/admin/issues/883 is resolved

Thanks! I wanted this blocked until that's resolved anyway, but I wanted to put it in the works to make sure it's okay dev-wise

**Review by bmuenzenmeyer — APPROVED** [review]
this is now unblocked due to the resolution of the other issue - but we wont merge until we solidify monorepo work

**Comment by bmuenzenmeyer** [comment]
This PR will need to be rebased or recreated now that https://github.com/nodejs/nodejs.org/pull/6850 merged.

**Comment by avivkeller** [comment]
Done!

**Review by mikeesto — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
