### PR TITLE
feat(download): Add APT and YUM package manager

### PR DESCRIPTION
**Pull request by riosje**
# Add APT and YUM package manager

Hello Node.js Team,

I hope this message finds you well. This PR is to propose the inclusion of APT and YUM installation instructions for Node.js on the official [Node.js Downloads page](https://nodejs.org/en/download/).
These package managers are the default for Debian/Ubuntu and RHEL-based systems and are familiar to a vast number of users.

Why should nodejs.org need those?
- Improves accessibility and user experience for Linux users.
- Encourages best practices through trusted and maintained channels.
- Aligns with community usage patterns and expectations.
- Nodesource APT and RPM packages are widely used by the community and we have millions of downloads per month.

I am ready to contribute the necessary instructions and collaborate on refining the content to meet the Node.js website standards.

## Validation

You can visit the repo where this is maintained, the installation instructions are really straight forward.
https://github.com/nodesource/distributions

### Check List
- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by ovflowd — CHANGES_REQUESTED** [review]
APT and YUM are not Node package managers.

**Comment by ovflowd** [comment]
To make this clear, we are not going to land this. Sorry.

We already limited the amount of package managers to a very subset of things we can somewhat have control or influence over.

Adding Distribution package managers here is a no go and are not official ways of installing Node.js and often the biggest source of issues for Node.js installations.

**Comment by ovflowd** [comment]
I appreciate the time you spend into this, and Im sorry to see your time going in vain, I understand this must be frustrating. I appreciate and welcome you for future contributions here 🙏

**Comment by riosje** [comment]
I understand, well... nothing to do about it then.
Thanks for reviewing this.

**Comment by ovflowd** [comment]
> I understand, well... nothing to do about it then. Thanks for reviewing this.

I understand the feeling, and I do see value on your points, it's just unfortunately not something we can officially support. Yet, we do have a page containing APT/YUM https://nodejs.org/en/download/package-manager/all

**Pull request closed without merging**
