### PR TITLE
Improve the korean docs

### PR DESCRIPTION
**Pull request by preco21**
- Add missing fields to the `site.json`
- Add missing labels to the `index.md`
- Improve grammar summary of `index.md`
- Add 404 page

/cc @nodejs/nodejs-ko

### CODE REVIEW

**Comment by ghost** [comment]
[Travis build passed](https://travis-ci.org/nodejs/nodejs.org/builds/120415902) :+1:

**Comment by ghost** [comment]
LGTM @preco21 do you wanna wait for someone of your team to review this or should i merge?

**Comment by preco21** [comment]
@hg I think it would be safe to merge. :)

**Comment by ghost** [comment]
merged! thanks!

**Pull request merged**
