### PR TITLE
border-radius increase

### PR DESCRIPTION
**Pull request by AugustinMauroy**
# border-radius increase
border-radius increase for more modern

### CODE REVIEW

**Review by ovflowd — COMMENTED** [review]
Ehi, I'm not sure this change is really necessary. What do you mean by "more modern"? Could you attach an image of how it looks after your changes?

**Comment by Trott** [comment]
I am not enthusiastic about this kind of extremely-subjective cosmetic change. I won't block it, but I'm sure not going to approve/endorse it.

Before:

image


After:

image

**Comment by AugustinMauroy** [comment]
@Trott
If we look at nodejs.dev we see that it is much more rounded. I think (and that's why I opened this PR) that it would look better with more rounding.
I could be wrong.

**Comment by AugustinMauroy** [comment]
@ovflowd 
as said just above, this allows a rapprochement on the style of nodejs.org and nodejs.dev

**Comment by ovflowd** [comment]
I understand your statements, but I don't think we should make design changes on nodejs.org as nodejs.dev is supposed to replace it in the future. Design changes here to foster a seamless visual identity between both websites aren't something we want to spend time on.

Adding this simple change would break the current design language of nodejs.org. Sorry, @AugustinMauroy, I'm not going to approve these changes, but I thank you for the PR.

Let's keep our focus for design changes on the other repository :)

**Comment by AugustinMauroy** [comment]
@ovflowd 
I understand what you're saying, it's not stupid to see what other people think.
Thank you for your opinion

**Comment by Trott** [comment]
> as nodejs.dev is supposed to replace it in the future

For technical reasons, it is unlikely that nodejs.dev will replace nodejs.org. A piece-by-piece import of relevant/important changes is far more likely. If the goal here is to incrementally/iteratively migrate closer to the nodejs.dev style, that's a decent reason to do it, in my opinion. Also, I'm delighted to see nodejs-dev folks get involved on the nodejs.org side of things. It was really weird (and is probably going to result in a lot of extra work) that there were basically two parallel websites going on for years and basically nobody in the two initiatives was talking to each other. (Not trying to criticize anyone for that. I was one of those people who was active on one side and mostly-not on the other, so I was as much or even more a part of that problem than anyone.)

@joesepi @richardlau

**Review by Trott — APPROVED** [review]
If this is a tiny step toward reducing the gap between nodejs.org and nodejs.dev, then great.

**Comment by ovflowd** [comment]
@Trott I’m genuinely confused 😅 isn’t the idea behind the website redesign initiative to actually become the new website 🤔 (No sarcasm here, I’m just honestly lost here 😅)

I believe we’re working on migrating the content that is here to the nodejs.dev website, including all docs and latest page updates, because then the new website would contain all the current content of the nodejs.org website 👀 (it also supports redirects from old nodejs.org links to the new nodejs.dev link format). 

One of the few remaining questions are, for example, if we want to migrate all the current blog posts or let them be on something like archive.nodejs.org 🤔

Having two completely different websites being maintained at the same time seems like a lot of work 😅

And yes, at least I, definitely pretend on migrating current features requests from nodejs.org to the new website and also help here with current things such as bugs and et cetera.

**Comment by ovflowd** [comment]
Also, sorry for my off-topic here. Would happily move this to Slack, or GitHub Discussions so that we don’t pollute this PR 🙏

**Comment by Trott** [comment]
> @Trott I’m genuinely confused 😅 isn’t the idea behind a website redesign yo actually become the new website 🤔

Yes, that was definitely the idea when it was launched. And maybe it can still happen. However, last I understood it, there were technical reasons that made it unlikely. However, it's possible I've misunderstood or those issues have been addressed. This is definitely a conversation to be had by a reasonable combination of current website folks + .dev website folks + Build WG + TSC. This is something @joesepi and I have been working on getting together, but we haven't gotten very far yet. (There were a bunch of things he and I have been and continue to work on, in terms of consolidating things that the Community Committee used to do. Another one is the Crowdin stuff.)

**Comment by Trott** [comment]
(I'll also add that I have not been following the .dev stuff closely for the last year or three, so it's entirely likely that I am completely misinformed about where things stand with it and how they work. So yeah, take what I say with a grain of salt, by all means!)

**Comment by ovflowd** [comment]
I see! I believe indeed there were some technicalities, at least for docs, and the blogs content but pretty much in the last meetings we created plans and found neat solutions for addressing them 👀

There might be more technicalities about other topics I'm just not aware of, I am after all a fairly new contributor just busting my way in 🙈

Having that said, I'm more than confident we're getting things done on an incredible speed and we can overcome those issues ✨

Yet, I honestly don't mind that we take appropriate time on working on these issues in a sustainable and efficient/planned matter.

Also, definitely would love to have a chat with the Build WG and the TSC folks and the current Website team to see what are the remaining blockers and wishes. But if you give a check on the .dev repository, we have a plan of remaining big bets to be done, and we're getting them addressed on s timely matter 🌈

**Comment by ovflowd** [comment]
> (I'll also add that I have not been following the .dev stuff closely for the last year or three, so it's entirely likely that I am completely misinformed about where things stand with it and how they work. So yeah, take what I say with a grain of salt, by all means!)

Thanks, @Trott! I truly appreciate the openness here and the support 🙏

Hopefully we're closer than you imagine, but same applies to me, take my statements with some 🧂 

Now for this PR, I still personally believe that this little change would break the current UI "philosophy or whatever you name it" of nodejs.org. Last thing I want is a Frankenstein on nodejs.org because we're trying to imitate the design of nodejs.dev here 🙈

But if you're fine and we don't have more objections in the following hours, I'm then fine with this change ✨

**Comment by joesepi** [comment]
Hi @ovflowd and others. As I stated in Slack (pasted below), there has been some concern that the website redesign effort may end up making the maintenance of the node.js website more burdensome. As @Trott stated above, we should collectively discuss as a group what the status is, what is outstanding, what the maintenance costs would be (not $ but time/effort) and what we think the new website should and shouldn't be (for example, should "Learn" be a part of the site?)

I hope @Trott and I can organize a meeting on this discussion soon.

image

**Comment by ovflowd** [comment]
Gotcha, thanks @joesepi definitely having a meeting to catch-up and sync these items would be great 🙃

**Comment by AugustinMauroy** [comment]
merge it or wait for other people are ok?

**Comment by ovflowd** [comment]
> merge it or wait for other people are ok?

Usually, 48 hours without other objections 👀

**Comment by AugustinMauroy** [comment]
> 

ok

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
