### PR TITLE
fix: download button icon

### LINKED ISSUE #6392: Confusing "Download Node.js" button on homepage
### Enter your suggestions in details:

Screenshot 2024-03-02 at 09 06 39 (Arc)

This button has a sideways arrow (->), implying that it will bring you to the downloads page ([https://beta-node-js-org.vercel.app/en/download](https://t.co/dXms7U0ziX)) but instead it downloads a file (I know this is explained by the text below but it isn't immediate apparent).  I would either change the link to go to the download page or change the icon to a download icon.

### PR DESCRIPTION
**Pull request by heygsc**
## Description

Before the download button, it was pointed to the right, but changed to downward, which is in line with the meaning of downloading.

## Related Issues

fix: #6392 

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
I'm not fan of this icon we should use same icon as download page.
```tsx
import { CloudArrowDownIcon } from '@heroicons/react/24/outline';
```

**Comment by heygsc** [comment]
> I'm not fan of this icon we should use same icon as download page.
> 
> ```tsx
> import { CloudArrowDownIcon } from '@heroicons/react/24/outline';
> ```

It makes sense. 
At first, when I saw several download buttons on the tailwind, I didn't know which one to choose. 
The download page was indeed suitable. I updated it again.

**Review by AugustinMauroy — APPROVED** [review]
SGTM ! Thanks for your first contribution 🎉

**Comment by heygsc** [comment]
> SGTM ! Thanks for your first contribution 🎉

Thank you!

**Comment by uncenter** [comment]
FYI if you add "closes #6392" to the PR description it will show up as a relevant PR in the issue itself and automatically close the issue when the PR is merged. (Prevents confusion like this: https://github.com/nodejs/nodejs.org/issues/6392#issuecomment-1974860349.)

**Comment by ovflowd** [comment]
FYI, can we swap the icon to before the text? For the arrow, it made sense to be on the right, not for this icon anymore.

**Comment by uncenter** [comment]
I kinda think on the right makes sense?

**Comment by ovflowd** [comment]
> I kinda think on the right makes sense?

Why so? (Out of curiosity)

**Comment by heygsc** [comment]
> FYI if you add "closes #6392" to the PR description it will show up as a relevant PR in the issue itself and automatically close the issue when the PR is merged. (Prevents confusion like this: [#6392 (comment)](https://github.com/nodejs/nodejs.org/issues/6392#issuecomment-1974860349).)

Okay, I didn't carefully check the issue before, but now it has been added to the description.

**Comment by heygsc** [comment]
> FYI, can we swap the icon to before the text? For the arrow, it made sense to be on the right, not for this icon anymore.

To the right, is it to point to the "download" text?
Haha, maybe it can be discussed again.

**Comment by uncenter** [comment]
> > I kinda think on the right makes sense?
> 
> Why so? (Out of curiosity)

It just feels right 😅 

| Right | Left |
| ----- | ---- |
| Capture-2024-03-02-131119 | image |

**Comment by ovflowd** [comment]
> > > I kinda think on the right makes sense?
> > 
> > 
> > Why so? (Out of curiosity)
> 
> It just feels right 😅
> 
> Right	Left
> Capture-2024-03-02-131119	image

Indeed it looks right. (Ba dum ts)

**Comment by ovflowd** [comment]
I'm fast-tracking this since it's a minor fix. Thank you for your first contribution, @heygsc and thank you for reporting this issue, @uncenter

**Comment by shanpriyan** [comment]
LGTM! Thanks for the PR 🌟

**Review by shanpriyan — APPROVED** [review]
LGTM! Thanks for the PR 🌟

**Pull request merged**
