### PR TITLE
Merge logos files

### LINKED ISSUE #6768: Refactor the nodejs logo component
I'm thinking we get this released sooner rather than later, even if we aren't in complete alignment on the approach. 

_Originally posted by @bmuenzenmeyer in https://github.com/nodejs/nodejs.org/pull/6734#issuecomment-2143461166_

### PR DESCRIPTION
**Pull request by araujogui**
## Description

Merge logos 

## Related Issues

Fixes #6768

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by ovflowd** [comment]
:eyes:

**Review by AugustinMauroy — APPROVED** [review]
LGTM !

**Review by canerakdas — APPROVED** [review]
LGTM! ✨

**Comment by bmuenzenmeyer** [comment]
This PR will need to be rebased or recreated now that https://github.com/nodejs/nodejs.org/pull/6850 merged.

**Pull request closed without merging**
