### PR TITLE
Update the packages for some bugs' fixtures

### PR DESCRIPTION
**Pull request by ghost**
1) IMPORTANT Fix：Update the 'marked' package, because there's an existing BUG
reported by @rvagg, and this is already fixed in its v0.6.2.
Ref：https://github.com/nodejs/nodejs.org/issues/2119.
Fixture：https://github.com/markedjs/marked/issues/1434.

2) A general upgration of the two packages:
a) require-dir: 1.0.0 => 1.2.0
b) semver: 5.6.0 => 6.0.0 (Fix a technical bug).
---
All syntaxes passed with unit tests

### CODE REVIEW

**Comment by fhemberger** [comment]
The `marked` fix seems to work. However, I have a strange effect on my local build (the live version is fine).

The current master with `DEFAULT_LOCALE=en npm run build` produces the following output for me (example: `locale/en/about/index.md`):

```
<p><code>`</code>javascript
const http = require(&#39;http&#39;);</p>
<p>const hostname = &#39;127.0.0.1&#39;;
const port = 3000;</p>
<p>const server = http.createServer((req, res) =&gt; {
  res.statusCode = 200;
  res.setHeader(&#39;Content-Type&#39;, &#39;text/plain&#39;);
  res.end(&#39;Hello World\n&#39;);
});</p>
<p>server.listen(port, hostname, () =&gt; {
  console.log(<code>Server running at http://${hostname}:${port}/</code>);
});
<code>`</code></p>
```

**After checking out the PR**, running the same command again (I've renamed the previous `build` directory for diffing):

```
<p>```javascript
const http = require(&#39;http&#39;);</p>
<p>const hostname = &#39;127.0.0.1&#39;;
const port = 3000;</p>
<p>const server = http.createServer((req, res) =&gt; {
  res.statusCode = 200;
  res.setHeader(&#39;Content-Type&#39;, &#39;text/plain&#39;);
  res.end(&#39;Hello World\n&#39;);
});</p>
<p>server.listen(port, hostname, () =&gt; {
  console.log(<code>Server running at http://${hostname}:${port}/</code>);
});
```</p>
```

I don't know if just something on my local build is borked, so PTAL before merging.

**Comment by ghost** [comment]
@fhemberger：This seems a little odd……Here's my index page when running `npm run build`：
image

Here's the result after `npm run serve`：
image

So when you remove all the things in "node_modules" and try to run with `npm i`, is this still happening?

**Comment by ghost** [comment]
Now I've removed the 'package-lock.json' and reinstall all the packages, you can have a try :)

**Comment by fhemberger** [comment]
Hmm, still the same for me, even with

```
rm -rf node_modules
rm package-lock.json
npm i
npm run build
```
🤔

If someone else can confirm the changes are working for them, I'm fine with merging this PR.

**Comment by ghost** [comment]
So @fhemberger , when running `npm run serve`, is everything going with you well? What's up with your local preview page of en/about？

I'm now digging to find what's the matter with that……I'm on Windows 10 (x86, the lastest version of Nodejs, the OS is 17134.648).

**Comment by fhemberger** [comment]
@Maledong `npm run serve` works fine. WTF … 🤔 
Seems to be some local oddities, +1 for merging it.

**Comment by Trott** [comment]
The `nodejs/node` repo stopped using `marked` (which is RegExp based) started using (I think) `remark` last year some time. Might be a good idea in this repo too. But also a lot of work. @rubys did most of the heavy-lifting in the core repo, and may have some wisdom to offer.

**Comment by fhemberger** [comment]
Not sure it's worth it with the upcoming relaunch just around the corner.

**Pull request merged**
