### PR TITLE
Fix typos in GitHub issue templates

### PR DESCRIPTION
**Pull request by andersk**

### CODE REVIEW

**Review by AugustinMauroy — APPROVED** [review]
LGTM!

**Review by ovflowd — APPROVED** [review]
Thanks for the first contribution :)

**Review by anonrig — APPROVED** [review]

**Review by ghost — APPROVED** [review]
@andersk：Just help to remove the duplicated ":"  :D

**Review by benhalverson — APPROVED** [review]
Cookie Monster

**Pull request merged**
