### PR TITLE
ru: correction of an obvious error in the translation

### PR DESCRIPTION
**Pull request by Artem13327**
Option is not the best, but corrects the wrong translation

### CODE REVIEW

**Comment by ovflowd** [comment]
cc @nodejs/nodejs-ru

**Comment by Artem13327** [comment]
So would anyone consider this pull request?

**Comment by ovflowd** [comment]
We need another translator to proof check your translation 🙃

**Comment by Trott** [comment]
Maybe @ChALkeR? I'll rubber-stamp it for now and we can land it if no one else approves in....I don't know, let's say another 48 hours? Sooner if you want.

**Review by Trott — APPROVED** [review]
Rubber-stamp LGTM, would be better if we had someone who knows the language reviewing it....

**Comment by ovflowd** [comment]
No one seemed to be able to review this. Merging for now.

**Pull request merged**
