### PR TITLE
Convert more posts to Markdown.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
We are getting close with this PR.

To make review easier, check the rich diff.

**Review by 3imed-jaberi — APPROVED** [review]

**Comment by nschonni** [comment]
Might be able to remove some of the `allowed_elements` in MD033, but maybe you're waiting for the conversions to be finished first

**Comment by XhmikosR** [comment]
Actually only one post is left AFAICT, but yeah, the next step is to adapt MD033.

**Comment by XhmikosR** [comment]
BTW this fixes many cases of wrong generated HTML. Someone had mixed Markdown into HTML which didn't work. This fixes the cases I hit, there are probably even more.

We need #2466 for sure.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
@XhmikosR, maybe you can forcely push because there're some conflicts with your changes ;)

**Comment by XhmikosR** [comment]
@MaledongGit done

**Pull request merged**
