### PR TITLE
optimize png images losslessly using zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Lossless compression using Google's zopflipng, to save the bandwidth to transfer the images.
 static/apple-touch-icon.png                                           | Bin 5823 -> 5695 bytes
 static/documents/2016-survey-infographic.png                          | Bin 328156 -> 321488 bytes
 static/favicon.png                                                    | Bin 1594 -> 1345 bytes
 static/images/foundation/NewRelic.png                                 | Bin 90306 -> 88889 bytes
 static/images/foundation/appdynamics.png                              | Bin 3441 -> 3423 bytes
 static/images/foundation/codefreshLogo.png                            | Bin 15043 -> 14052 bytes
 static/images/foundation/codefreshLogo2.png                           | Bin 14419 -> 13118 bytes
 static/images/foundation/digitaloceanLogo.png                         | Bin 8238 -> 7554 bytes
 static/images/foundation/famousLogo.png                               | Bin 8423 -> 4702 bytes
 static/images/foundation/fidelityLogo.png                             | Bin 3565 -> 2384 bytes
 static/images/foundation/godaddyLogo.png                              | Bin 24130 -> 22861 bytes
 static/images/foundation/googleLogo.png                               | Bin 7747 -> 7084 bytes
 static/images/foundation/grouponLogo.png                              | Bin 2149 -> 1056 bytes
 static/images/foundation/ibmLogo.png                                  | Bin 20144 -> 10021 bytes
 static/images/foundation/intelLogo.png                                | Bin 13637 -> 7438 bytes
 static/images/foundation/microsoftLogo.png                            | Bin 20910 -> 9388 bytes
 static/images/foundation/microsoftLogo2.png                           | Bin 17791 -> 8112 bytes
 static/images/foundation/modulusLogo.png                              | Bin 22947 -> 20765 bytes
 static/images/foundation/nearformLogo.png                             | Bin 31657 -> 28329 bytes
 static/images/foundation/nodesourceLogo.png                           | Bin 3387 -> 2136 bytes
 static/images/foundation/npmLogo.png                                  | Bin 7404 -> 2757 bytes
 static/images/foundation/opbeat.png                                   | Bin 40592 -> 36301 bytes
 static/images/foundation/paypalLogo.png                               | Bin 23218 -> 17786 bytes
 static/images/foundation/redhatLogo.png                               | Bin 31414 -> 27476 bytes
 static/images/foundation/risingstack_logo.png                         | Bin 64745 -> 61618 bytes
 static/images/foundation/sapLogo.png                                  | Bin 32686 -> 30301 bytes
 static/images/foundation/saucelabsLogo.png                            | Bin 18252 -> 10161 bytes
 static/images/foundation/saucelabsLogo2.png                           | Bin 16376 -> 9795 bytes
 static/images/foundation/strongloopLogo.png                           | Bin 15111 -> 13438 bytes
 static/images/foundation/yahoo.png                                    | Bin 54967 -> 54831 bytes
 static/images/foundation/yldLogo.png                                  | Bin 27229 -> 26681 bytes
 static/images/interactive/background.png                              | Bin 388026 -> 386389 bytes
 static/images/interactive/nodejs-interactive-hero-banner-left-eu.png  | Bin 3522 -> 3494 bytes
 static/images/interactive/nodejs-interactive-hero-banner-right-na.png | Bin 3758 -> 3737 bytes
 static/images/interactive/nodejs-interactive-logo-center.png          | Bin 10502 -> 10464 bytes
 static/images/logo-light.png                                          | Bin 1303 -> 1295 bytes
 static/images/logos/monitor.png                                       | Bin 114250 -> 103620 bytes
 static/images/logos/node-favicon.png                                  | Bin 212 -> 173 bytes
 static/images/logos/nodejs-1024x768.png                               | Bin 475952 -> 443069 bytes
 static/images/logos/nodejs-1280x1024.png                              | Bin 870469 -> 813746 bytes
 static/images/logos/nodejs-1440x900.png                               | Bin 756423 -> 704558 bytes
 static/images/logos/nodejs-1920x1200.png                              | Bin 1321365 -> 1231640 bytes
 static/images/logos/nodejs-2560x1440.png                              | Bin 1832488 -> 1699460 bytes
 static/images/logos/nodejs-black.png                                  | Bin 3282 -> 1978 bytes
 static/images/logos/nodejs-dark.png                                   | Bin 4492 -> 1905 bytes
 static/images/logos/nodejs-green.png                                  | Bin 4483 -> 1905 bytes
 static/images/logos/nodejs-new-black.png                              | Bin 58948 -> 45699 bytes
 static/images/logos/nodejs-new-pantone-black.png                      | Bin 65128 -> 46753 bytes
 static/images/logos/nodejs-new-pantone-white.png                      | Bin 63681 -> 47647 bytes
 static/images/logos/nodejs-new-white-pantone.png                      | Bin 23609 -> 23466 bytes
 static/images/logos/nodejs-new-white.png                              | Bin 55870 -> 45368 bytes
 static/images/logos/nodejs.png                                        | Bin 5109 -> 2262 bytes
 static/legacy/images/anchor.png                                       | Bin 426 -> 420 bytes
 static/legacy/images/close-downloads.png                              | Bin 307 -> 303 bytes
 static/legacy/images/community-icons.png                              | Bin 4547 -> 4544 bytes
 static/legacy/images/download-logo.png                                | Bin 4306 -> 4287 bytes
 static/legacy/images/ebay-logo.png                                    | Bin 1133 -> 1114 bytes
 static/legacy/images/footer-logo-alt.png                              | Bin 1078 -> 1061 bytes
 static/legacy/images/forkme.png                                       | Bin 877 -> 876 bytes
 static/legacy/images/icons-interior.png                               | Bin 3794 -> 3789 bytes
 static/legacy/images/joyent-logo_orange_nodeorg-01.png                | Bin 1036 -> 1032 bytes
 static/legacy/images/logo-light.png                                   | Bin 1303 -> 1295 bytes
 static/legacy/images/logo.png                                         | Bin 3081 -> 3071 bytes
 static/legacy/images/microsoft-logo.png                               | Bin 1600 -> 1593 bytes
 static/legacy/images/not-invented-here.png                            | Bin 172194 -> 172135 bytes
 static/legacy/images/sponsored.png                                    | Bin 2926 -> 2917 bytes
 static/legacy/images/twitter-bird.png                                 | Bin 243 -> 242 bytes

```
```

### CODE REVIEW

**Comment by lpinca** [comment]
LGTM.

**Comment by detailyang** [comment]
LGTM
check by my eyes. just a little difference :grin:

**Comment by lpinca** [comment]
The GoDaddy logo green seems indeed a different green.

**Comment by PeterDaveHello** [comment]
> The GoDaddy logo green seems indeed a different green.

Oops, that's odd, I'll take a look at it, thanks.

**Comment by PeterDaveHello** [comment]
I opened an issue to zopfli, from its help message, I don't think there should be any difference, I use parameter like this `--iterations=500 --lossy_transparent -m`.

This is part of the help message:

> -m: compress more: use more iterations (depending on file size)
> --lossy_transparent: remove colors behind alpha channel 0. **No visual difference**, removes hidden information.

**Comment by jyrkialakuijala** [comment]
Could it be a problem in github? When I downloaded both of the images they looked the same (but had different sizes).

**Comment by PeterDaveHello** [comment]
@jyrkialakuijala the problem is that I'm not saying that this is a lossy compression.
If you want to say it can be lossy since the size looks very different, yes, it could be, but it'll need more discussion, but lossless compression won't need that much.

**Comment by lpinca** [comment]
The difference is very visible. Compare the [current](https://nodejs.org/static/images/foundation/godaddyLogo.png) one to the [new](https://raw.githubusercontent.com/PeterDaveHelloKitchen/nodejs.org/026322d4c197978f2937ae77c11440325eae6000/static/images/foundation/godaddyLogo.png) one.
The same is also valid for codefresh logo.

**Comment by jyrkialakuijala** [comment]
Ok, it was because I viewed the images with ImageMagick 'display'. That tool looks at the pixels and disregards the iCCP segment. With a browser the images look different. We will look into this.

**Comment by PeterDaveHello** [comment]
https://github.com/google/zopfli/issues/113#issuecomment-219704950

**Comment by lpinca** [comment]
@PeterDaveHello nice, are you going to update this pr with `--keepchunks=iCCP`?

**Comment by PeterDaveHello** [comment]
@lpinca sure!

**Comment by PeterDaveHello** [comment]
Updated!

**Comment by lpinca** [comment]
Much better, LGTM.

**Comment by hiroppy** [comment]
LGTM.

**Pull request merged**
