### PR TITLE
update code & lean page

### PR DESCRIPTION
**Pull request by gireeshpunathil**
- add upcoming code & learn event
 - qualify past code & learn events as such

thanks in advance.

### CODE REVIEW

**Comment by fhemberger** [comment]
Could you please update the file in `fa`, `uk`, `zh-cn` and `zh-tw` as well?

**Comment by gireeshpunathil** [comment]
@fhemberger - thanks, added - ptal.

**Review by fhemberger — APPROVED** [review]

**Comment by fhemberger** [comment]
@gireeshpunathil Cool, thanks!

**Comment by gireeshpunathil** [comment]
thanks @fhemberger - that was super fast!

**Pull request merged**
