### PR TITLE
doc: releases avail for oct DOS sec vuln

### PR DESCRIPTION
**Pull request by mhdawson**
@nodejs/website please review.  Will be sending out security announcement on mailing list in parallel

### CODE REVIEW

**Review by bnb — APPROVED** [review]
LGTM

**Review by watilde — APPROVED** [review]

**Review by chris--young — APPROVED** [review]

**Comment by mhdawson** [comment]
Going to land

**Review by lpinca — APPROVED** [review]
LGTM with conflicts resolved.

**Comment by lpinca** [comment]
Maybe me and @aqrln should have included more people when we discussed how to fix the issue 😉.

https://github.com/nodejs/node/issues/13082
https://github.com/nodejs/node/pull/13098#issuecomment-302370463

**Comment by lpinca** [comment]
Looks like this is already merged, closing.

**Pull request closed without merging**
