### PR TITLE
adding a --force flag to update a release blog post

### PR DESCRIPTION
**Pull request by italoacasas**
Adding a flag to allow update a specific **release blog post** without the need of removing the file first

cc: @nodejs/release

### CODE REVIEW

**Comment by phillipj** [comment]
Seems like a good addition, have been annoyed by this myself once in a while..

**Review by phillipj — APPROVED** [review]

**Comment by MylesBorins** [comment]
So the only thing I would maybe enjoy seeing is that if the force tag is given perhaps we can use the original date of the article? This may also be completely unnecessary. Thoughts?

**Comment by mikeal** [comment]
I don't know enough about this process to give an up or down, but I will note that no matter what we do for updating the content we are still sitting behind a CloudFlare CDN and as a result there will be some time between a new deploy and cache invalidation of content we update.

**Comment by italoacasas** [comment]
> we can use the original date of the article? 

@MylesBorins Is that the desired behavior?

IMO, the difference is going to be a few hours, I don't think is going to affect.

**Comment by MylesBorins** [comment]
@italoacasas lets do the simple implementation, easy enough to drop a specific change with git

**Comment by italoacasas** [comment]
@MylesBorins can you explain me what you mean with:

> easy enough to drop a specific change with git

**Pull request merged**
