### PR TITLE
smooth sentence to fit Korean grammar

### PR DESCRIPTION
**Pull request by hallazzang**
previous sentence was grammatically incorrect in Korean.

### CODE REVIEW

**Review by yous — APPROVED** [review]
"Epitaph" means 비문(碑文), not 비문(非文). How about saying "grammatically incorrect" or something in the commit message?

**Comment by hallazzang** [comment]
@yous What a shame, thank you for the correction. I'll change it ASAP.

**Comment by hallazzang** [comment]
Done. Please check it again.

**Comment by yous** [comment]
LGTM. :+1:

**Review by outsideris — APPROVED** [review]

**Comment by fhemberger** [comment]
Thank you!

**Pull request merged**
