### PR TITLE
Lowercase `doctype`.

### PR DESCRIPTION
**Pull request by XhmikosR**
It has the same effect but compresses slightly better.

### CODE REVIEW

**Comment by aymen94** [comment]
Thanks for contributing @XhmikosR, but HTML is Case insensitive, The DOCTYPEs can be either upper or lower case
for more info see: [w3c HTML](https://w3c.github.io/html-reference/documents.html#case-insensitivity)

**Comment by XhmikosR** [comment]
I'm aware of that hence this patch. There's no reason to use the uppercased `doctype` especially since the lowercase one should compress (slightly ofc) better.

**Comment by aymen94** [comment]
let's see what they think  @nodejs/website

**Comment by 3imed-jaberi** [comment]
Thanks for your contribution @XhmikosR , I think there's no need to change it to lowercase. 
I don't find a need to keep this PR open ....

**Comment by Trott** [comment]
If we have places where it is already lowercase, I'd be in favor of this for consistency although I'd want a lint rule to enforce it going forward.

**Comment by XhmikosR** [comment]
I don't mind not landing this, although I really don't see any gain from using an uppercase doctype.

For reference https://github.com/h5bp/html5-boilerplate/blob/master/dist/index.html#L1

And even google is using the lowercase doctype nowadays.

**Comment by Trott** [comment]
@nodejs/website Anyone feel like this is a generally-accepted best practice and therefore something we should do?

**Comment by XhmikosR** [comment]
https://github.com/h5bp/html5-boilerplate/issues/1522#issuecomment-39315391 about the small giz gain.

Personally, I say just lowercase it and be done with it. It's a leftover from the old days.

**Comment by silverwind** [comment]
Is doctype even necessary any more in a modern browser? MDN says 

> its sole purpose is to prevent a browser from switching into so-called "quirks mode"

Given that no current browser except maybe Edge feature such a "quirks mode", is it even necessary?

**Comment by XhmikosR** [comment]
I'd keep it for backwards compatibility. This patch proposes a simple change only.

**Comment by silverwind** [comment]
Yeah I guess the spec saying "A DOCTYPE is a required preamble." should be honored. Anyways, I'm fine with lowercasing it to shave off a few bytes.

**Comment by XhmikosR** [comment]
Can you reopen the PR or should I make a new one? I'm not sure if re-opening will work since I had deleted the branch.

**Review by aymen94 — APPROVED** [review]

**Comment by aymen94** [comment]
LGTM

**Comment by pierreneter** [comment]
`DOCTYPE` should be uppercase.

**Comment by XhmikosR** [comment]
@pierreneter: the spec does not say that.

**Comment by pierreneter** [comment]
So, why we need lowercase?

**Comment by XhmikosR** [comment]
Because it has the same effect plus it compresses slightly better. See the previous links/discussion.

**Comment by pierreneter** [comment]
> Because it has the same effect plus it compresses slightly better. See the previous links/discussion.

I don't think so; so, I will give some ideas on why Uppercase is better.

1. > Note that if you don’t uppercase DOCTYPE in an XHTML document, the XML parser will return a syntax error.
  From: http://mathiasbynens.be/notes/xhtml5#doctype
2. Most style guides and lint recommend DOCTYPE uppercase.
  From: https://google.github.io/styleguide/htmlcssguide.html#Document_Type
  So, if you use editor with any auto formatter tool, it will auto change to `<!DOCTYPE html>`, and this PR (#2389) will be useless.

**Comment by XhmikosR** [comment]
1. We don't use XHTML so that's moot
2. Check out google.com own source code

Anyway, I think this is discussed a lot more than it should be. Feel free to drop it or merge it.

**Comment by Trott** [comment]
> > Because it has the same effect plus it compresses slightly better. See the previous links/discussion.
> 
> I don't think so; so, I will give some ideas on why Uppercase is better.
> 
> 1. > Note that if you don’t uppercase DOCTYPE in an XHTML document, the XML parser will return a syntax error.
>    > From: http://mathiasbynens.be/notes/xhtml5#doctype
> 2. Most style guides and lint recommend DOCTYPE uppercase.
>    From: https://google.github.io/styleguide/htmlcssguide.html#Document_Type
>    So, if you use editor with any auto formatter tool, it will auto change to `<!DOCTYPE html>`, and this PR (#2389) will be useless.

XHTML compatibility (number 1 above) is a non-issue. We do not and should not conform to XHTML. Even the link provided to argue that `doctype` should be capitalized says, basically, don't bother in its very first sentence: "You know, I’ll always prefer HTML over XHTML because it’s much less verbose and I like to keep things simple."

As for the guide/lint thing (number 2 above): The linked style guide does not require capitalization. It uses capitalization in its example. It does not say "Don't use lowercase." Other sections have "not recommended" examples. That one does not. However, what that guide DOES say is to use HTML5 (where lowercase `doctype` is permitted) and to avoid XHTML. 

AFAICT, the only persuasive reason for doing this is that it will (probably) shave a small number of bytes off some or all transfers. And the only persuasive reasons for not doing it are that it is unnecessary churn and that the bytes saved are insignificant.

For me, it's a coin toss. I can go either way.

**Comment by pierreneter** [comment]
@Trott Ok, I agree with you.
Be honest, I prefer `<!DOCTYPE html>`, so, it's just about style and hobby.
But, if we must use `<!doctype html>`, we need to create PRs for all repositories which use `<!DOCTYPE html>` and convert it to `<!doctype html>` on Github?
If that's not necessary, why don't we keep the existing ones now? If this PR was merged, I will create PR with "Uppercase `doctype`." and discuss again?

@XhmikosR can you create PRs for all repositories which use `<!DOCTYPE html>` and convert it to `<!doctype html>` on Github? Let me know if you can. Because we can save 6B per data move time. 
We can significantly reduce the data moving on the Internet if that is a large number of repositories changed and can save the resource for the Internet. Save the World. It can be. But need a lot of PRs. When creating PRs and comments, we move data. Maybe we can create a movement and call everyone to use `<!doctype html>` instead of `<!DOCTYPE html>` and add it to the spec? Do you agree?

**Comment by XhmikosR** [comment]
What does it have to do what others do? I simply decided to contribute to a project which I use daily, here.

Like I said, we are discussing this a lot more than we should. For me it's standard to use lowercase `doctype` for years now. Others have a different opinion and that's OK.

**Comment by Trott** [comment]
I'm going to close this because it is indeed low-stakes.

@XhmikosR Note that there is a website-redesign initiative (no idea how far along they are), so for longevity of the change, you may want to see about implementing over there instead anyway. Not sure where they do their work these days (or if it's stalled? I hope not....)  /ping @nodejs/website-redesign  (I know they also manage the nodejs.dev repo/site but I think that's kind of a stop-gap measure and not a model for the new site.)

**Comment by XhmikosR** [comment]
@Trott for what it's worth, the core docs do use a lowercase `doctype`.

https://github.com/nodejs/node/blob/775048d54c6f190cbc8c0b55c0b53d2ba9d4d028/doc/template.html#L1

**Comment by XhmikosR** [comment]
@Trott can you reopen this? IMO this totally makes sense especially given that a lowercase doctype is used in core.

**Comment by alexandrtovmach** [comment]
I think it's just personal experience preferences... and we can't argue with something one for 100% sure, so we need to just vote. For me personally uppercase is more comfortable, but I had an experience with HTML pages optimization and used lowercase to reduce page size.

@nodejs/website-redesign @nodejs/website Let's vote on this post:
- lowercase :thumbsup:
- uppercase :thumbsdown:

**Comment by XhmikosR** [comment]
My point here is that this is how it is in core. https://github.com/nodejs/node/blob/master/doc/template.html#L1

**Comment by Trott** [comment]
> @Trott can you reopen this?

The Reopen button is disabled, probably because the branch was deleted.

**Comment by XhmikosR** [comment]
Alright I'll make a new PR.

**Comment by alexandrtovmach** [comment]
Let's wait 48 hours for everyone able to vote

**Comment by XhmikosR** [comment]
You should also uppercase it upstream then. Hence why lowercasing it here
is the best solution IMO

**Pull request closed without merging**
