### PR TITLE
meta: remove non-useful bundle analysis generation 

### PR DESCRIPTION
**Pull request by ovflowd**
## Description

This PR removes bundle analysis generation and report as it has been mostly non-useful for us. It doesn't seem to suport dynamically generated pages, nor ISR.

Hence we truly don't need a CI step that uses a lot of resources, time and at best it's just annoying.

## Validation

The Analysis Step is removed and the PR checks are OK.

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by ovflowd** [comment]
cc @nodejs/website as I want y'all opinions on this. This should be trivial and I pretty much believe that this was not bringing any benefits. LMK your thoughts.

**Comment by AugustinMauroy** [comment]
I'm not in website team but I approve this pr. 👍🏼

**Comment by ovflowd** [comment]
Also, cc @nodejs/website, I updated these checks to run if the `github_actions:pull-request` label is added. This is useful for PRs from people not part of the Website Team, as we can easily add a label that will trigger a run of those Workflows.

As by default the `pull_request_target` checks will fail on PRs coming from forks. You can simply add this label and it will automatically approve the Workflows and re-run the Target ones too.

**Comment by ovflowd** [comment]
I've merged for now, for the sake of it. As I doubt anyone would reject this, but lmk if anyone has objections and I'll revert.

**Pull request merged**
