### PR TITLE
docs(learn): Migrate "Anatomy of an http transaction" guide to the learn section

### LINKED ISSUE #6226: Migrate the legacy guide "Anatomy of an HTTP Transaction" to the learn section
Migrate the content currently at [Anatomy of an HTTP Transaction](https://nodejs.org/en/guides/anatomy-of-an-http-transaction/) to a new page under the "learn" section found at https://github.com/nodejs/nodejs.org/tree/main/pages/en/learn.

- [ ] Use your judgement about what existing or new folder the content should go in. Ask in a draft PR if you are unsure. 
- [ ] Review the content during migration, please do not simply copy/paste the content. Similar to #6140, the content may need edits to account for the latest Node.js features.
- [ ] Run your content through a spell-checker in the editor, like https://github.com/streetsidesoftware/vscode-spell-checker, Word/Google Docs, Grammarly, or https://alexjs.com/

### PR DESCRIPTION
**Pull request by mwenku**
## Description

This PR migrates the `Anatomy of an http transaction` guide to the learn section

## Validation

image
image

## Related Issues

Fixes #6226 

### Check List

- [X] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [X] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [X] I have run `npx turbo format` to ensure the code follows the style guide.
- [X] I have run `npx turbo test` to check if all tests are passing.
- [X] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by ShogunPanda — APPROVED** [review]

**Review by AugustinMauroy — COMMENTED** [review]
General review:

- on code block we should use `js` instead of `javascript` for language définition
- when a code snippet import a nodejs internal package we should use the `node:` like in api docs

**Comment by AugustinMauroy** [comment]
Just a question: should you put the contents in the `/learn/module` directory, why not put it under `/learn/http` or `/learn/networking`?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mwelwankuta** [comment]
> General review:
> 
> * on code block we should use `js` instead of `javascript` for language définition
> * when a code snippet import a nodejs internal package we should use the `node:` like in api docs

could you explain more on the second point, i do not fully understand it.

**Comment by mwenku** [comment]
> General review:
> 
> * on code block we should use `js` instead of `javascript` for language définition

i noticed more than 45 files use `js` for language definitions can this be a separate issue ?

**Comment by mwenku** [comment]
> General review:
> 
> * when a code snippet import a nodejs internal package we should use the `node:` like in api docs

i make a change on the snippets to import from `node:theModule` am i right?

**Comment by AugustinMauroy** [comment]
> i noticed more than 45 files use js for language definitions can this be a separate issue ?

I think just making the file you're on would be great. 

> i make a change on the snippets to import from node:http am i right?

Right ! FYI all internal node module can be import with `node:theModule`  to avoid confusion with npm packages. The docs is written with this prefix so we should write it like this

**Comment by mwenku** [comment]
> > i noticed more than 45 files use js for language definitions can this be a separate issue ?
> 
> I think just making the file you're on would be great.
> 
> > i make a change on the snippets to import from node:http am i right?
> 
> Right ! FYI all internal node module can be import with `node:theModule` to avoid confusion with npm packages. The docs is written with this prefix so we should write it like this

awesome, worked on the issues

**Review by AugustinMauroy — APPROVED** [review]
LGTM !

**Review by mikeesto — APPROVED** [review]

**Review by shanpriyan — APPROVED** [review]
LGTM!

**Review by aymen94 — APPROVED** [review]

**Comment by AugustinMauroy** [comment]
@bmuenzenmeyer you would review this pr because it was you who opened the issue

**Review by himself65 — APPROVED** [review]

**Review by bmuenzenmeyer — APPROVED** [review]

**Comment by bmuenzenmeyer** [comment]
i wouldnt be surprised if we moved some of these modules around after we see the full picture

**Pull request merged**
