### PR TITLE
Add v8.x branch link to releases download page

### PR DESCRIPTION
**Pull request by watson**

### CODE REVIEW

**Review by lpinca — APPROVED** [review]

**Comment by watson** [comment]
I'm not sure how I18n works in this repo. Should I add this to all the other languages as well as part of this commit?

**Comment by lpinca** [comment]
@watson yes, that would be great.

Ref: https://github.com/nodejs/nodejs.org/pull/1108

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by watson** [comment]
Will this be squashed when merged, or should I do it my self? (Used the github web editor, otherwise I would have amended)

**Comment by lpinca** [comment]
Yes it will be squashed.

**Review by daxlab — APPROVED** [review]

**Pull request merged**
