### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by OtabekVaxobov**
add Uzbekistan developers group)

### CODE REVIEW

**Comment by OtabekVaxobov** [comment]
something

**Comment by MaledongGit** [comment]
Ping @nodejs/nodejs-uk, Please have a review, thanks!

**Review by ghost — COMMENTED** [review]
IMO: This link doesn't appear in the other version languages, so can you give us the English version?

**Comment by sudodoki** [comment]
@MaledongGit it says 'Uzbekistan group for Node.js' which is slightly different wording from other links that have 'community' or 'developer group' in it, but it could be as this. Also, this is Russian, so maybe @nodejs/nodejs-ru should be pinged instead.

**Review by alexandrtovmach — APPROVED** [review]
yep, looks fine

**Comment by ghost** [comment]
> @MaledongGit it says 'Uzbekistan group for Node.js' which is slightly different wording from other links that have 'community' or 'developer group' in it, but it could be as this. Also, this is Russian, so maybe @nodejs/nodejs-ru should be pinged instead.

Sorry, I thought the content is something related to ur. Now It seems this Can be merged first, and I'll add an English version link later, just like others.

**Pull request merged**
