### PR TITLE
update TC with TSC

### PR DESCRIPTION
**Pull request by thefourtheye**

### CODE REVIEW

**Comment by bnb** [comment]
Other than the above, LGTM.

**Comment by thefourtheye** [comment]
@bnb I fixed it now. PTAL. Also, I feel that it would be better if we got an LGTM from @nodejs/tsc on this.

**Comment by bnoordhuis** [comment]
LGTM

**Comment by ghost** [comment]
yeah, LGTM

**Comment by thefourtheye** [comment]
Thanks for the review people :-) Landed the patch in 0dd684cf21d278ba8aa178db0a20ebc6d587c58e

**Pull request merged**
