### PR TITLE
Blog: v20.10.0 release post

### PR DESCRIPTION
**Pull request by targos**
Refs: https://github.com/nodejs/node/pull/50682

### CODE REVIEW

**Review by richardlau — APPROVED** [review]

**Comment by targos** [comment]
I have no idea what's making the build fail.

Error:
```
- info (blog-posts-data.json) and (node-releases-data.json) got generated.
  undefined:710
  {"version":"v0.1.18","date":"2011-08-26",
  
  SyntaxError: Expected double-quoted property name in JSON at position 263[21](https://github.com/nodejs/nodejs.org/actions/runs/6959448441/job/18936701109?pr=6135#step:7:22)6
      at JSON.parse (<anonymous>)
      at parseJSONFromBytes (node:internal/deps/undici/undici:4553:19)
      at successSteps (node:internal/deps/undici/undici:4527:27)
      at fullyReadBody (node:internal/deps/undici/undici:1307:9)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async specConsumeBody (node:internal/deps/undici/undici:4536:7)
      at async core (/home/runner/work/nodejs.org/nodejs.org/node_modules/@nodevu/core/index.js:18:20)
      at async Module.generateNodeReleasesJson (file:///home/runner/work/nodejs.org/nodejs.org/next-data/generateNodeReleasesJson.mjs:33:[24](https://github.com/nodejs/nodejs.org/actions/runs/6959448441/job/18936701109?pr=6135#step:7:25))
      at async file:///home/runner/work/nodejs.org/nodejs.org/scripts/generate-next-data/index.mjs:11:1
  
  Node.js v20.9.0
```

**Comment by richardlau** [comment]
> I have no idea what's making the build fail.
> 

I [reran the failing build and it passed](https://github.com/nodejs/nodejs.org/actions/runs/6959448441/job/18936901186?pr=6135). I assume it downloads index.json and hit an issue while the download server is overwhelmed.

**Review by ruyadorno — APPROVED** [review]

**Comment by richardlau** [comment]
> > I have no idea what's making the build fail.
> 
> I [reran the failing build and it passed](https://github.com/nodejs/nodejs.org/actions/runs/6959448441/job/18936901186?pr=6135). I assume it downloads index.json and hit an issue while the download server is overwhelmed.

Looks like it's failing when run for the merge queue as well 😞.

**Comment by AugustinMauroy** [comment]
I'm looking into the build error but it's can from #6136 . I'm testing on my machine
EDIT: yes it's form that

**Comment by ovflowd** [comment]
> I'm looking into the build error but it's can from #6136 . I'm testing on my machine

There's nothing wrong, Augustin. Just the DO server being overwhelmed.

**Pull request merged**
