### PR TITLE
Add njs download link to blm layout at the bottom

### PR DESCRIPTION
**Pull request by Jisagi**
This adds a link to the downloads where the docs are linked. This will help people find them. I am fully open to changes if it doesn't fit the wording or location where to link to them.

### CODE REVIEW

**Comment by Trott** [comment]
This is going to conflict with https://github.com/nodejs/nodejs.org/pull/3218. I'm happy to add a link to downloads to that PR, or we can land that one and rebase this one. I think adding the downloads link is a good idea.

**Comment by Jisagi** [comment]
@Trott I'd be fine to close this one and let you add the links to yours. Just let me know which you'd prefer.

**Review by addaleax — APPROVED** [review]

**Comment by Trott** [comment]
> @Trott I'd be fine to close this one and let you add the links to yours. Just let me know which you'd prefer.

I've added a downloads link. PTAL. https://github.com/nodejs/nodejs.org/pull/3218

Thanks for the pull request, by the way!

**Comment by Jisagi** [comment]
> I've added a downloads link. PTAL. #3218
> Thanks for the pull request, by the way!

Thanks for adding them to your pr and no problem :smile:
I will close mine then

**Pull request closed without merging**
