### PR TITLE
chore: remove unmaintained metalsmith plugins

### PR DESCRIPTION
**Pull request by Trott**
Replace with inline equivalents. This addresses some security warnings
in the GitHub interface and in `npm audit`. (The warnings are relevant
to our build tooling, not to the site.)

### CODE REVIEW

**Comment by nschonni** [comment]
Note sure if the windows failure is related to glob v8 vs. v7. Saw some other Windows failures on other repos that tried bumping glob to v8

**Comment by Trott** [comment]
Anyone on a Windows machine want to take a look and see what I'm doing wrong for that platform? @nodejs/platform-windows @nodejs/website

**Comment by Trott** [comment]
> Note sure if the windows failure is related to glob v8 vs. v7. Saw some other Windows failures on other repos that tried bumping glob to v8

Downgraded to glob@7 to see if it fixes anything....

**Comment by Trott** [comment]
> Downgraded to glob@7 to see if it fixes anything....

That seems to have fixed it. Thanks, @nschonni!

**Review by nschonni — APPROVED** [review]

**Review by WaleedAshraf — APPROVED** [review]

**Pull request merged**
