### PR TITLE
AR:  Translate file - docs/guides/anatomy-of-an-http-transaction.md 

### PR DESCRIPTION
**Pull request by Aissaoui-Ahmed**
hello !
translate file `anatomy-of-an-http-transaction.md`
there are many different terms in domain Computer and Programing 
Languages, we trying to get exact meaning in Arabic.  I need help?

@celyes @InterstellarClub

### CODE REVIEW

**Comment by ghost** [comment]
@nodejs/nodejs-ar：Would you mind helping or having a review of this? Thanks for your suggestions if possible.

**Comment by ram-you** [comment]
@Maledong It looks like it's written by a robot, there are so many mistakes that we lose the meaning of the text.

**Review by celyes — CHANGES_REQUESTED** [review]
This file may need a total re-write to make it more " human-readable".
@Aissaoui-Ahmed I suggest reading this web page: https://bit.ly/2MmPTDn as it has an Arabic translation for almost all of the CS Terms in general, including the most used one in the Node.js 's context

**Comment by Aissaoui-Ahmed** [comment]
thank you all !

direction of changes is LTR to fix it copied in text editor and change direction RTL

**Review by celyes — APPROVED** [review]
LGTM

**Pull request merged**
