### PR TITLE
Add gitconnected.com crowd-sourced tutorials to learning

### PR DESCRIPTION
**Pull request by treyhuffine**
Add an additional learning resource. It is a crowd-sourced list of tutorials that are submitted, upvoted, and reviewed by Node developers.

https://gitconnected.com/learn/node-js

Screen Shot 2019-12-09 at 7 12 00 AM

### CODE REVIEW

**Comment by Trott** [comment]
Hi, @treyhuffine. Welcome and thanks for the pull request.

My personal opinion only. Others on @nodejs/website may have the opposite opinion:

Personally, I am resistant to expanding this list and would hold any new resource to a very high bar. I prefer fewer resources. The danger of this list (again) becoming a laundry list of mixed quality is always high.

Rather than add a new resource which, however good it might be, is wholly unneeded in this list, I'd prefer to see it be narrowed. I'd be in favor, for example, of removing Nodeiflux. No criticism of Nodeiflux or the people who run it. But once we're offering more than two or three options, we're probably doing people more of a disservice than a service.

I wouldn't mind this list being removed entirely. Except perhaps if they are seeking an official tutorial, people don't come to nodejs.org looking for ways to learn Node.js. They're far more likely to type "Node.js tutorial" into Google or something like that. We have far too much content on the site of varying curatorial quality, and it would be better for both us and end-users if there was less stuff.

**Comment by treyhuffine** [comment]
Hi @Trott, I really appreciate the feedback and totally understand your concern. I think the value of the resource I submitted is that it does address some of the issues that you mentioned in that instead of Node.js developers needing to sort through the laundry list of mixed quality content, they are able to use the aggregated ratings/feedback from other developers and filters to discover the right tutorial for them.

I understand the issue with the site being overcrowded, so whatever you do decide, I appreciate you taking the time to review the PR and provide detailed feedback.

**Comment by Chasdaspaz** [comment]
pull request

**Comment by Chasdaspaz** [comment]
pull request

**Comment by bnb** [comment]
I am generally -1 on this mostly because it does not introduce value in itself but rather points to others content dynamically. There are a bunch of other sites like this - HashNode, EchoJS, JSFeeds, BestOfJS, r/JavaScript, and so on. At present, I don’t think this particular addition to the website adds a significant amount of value.

**Comment by treyhuffine** [comment]
Those sites are ephemeral news feeds more similar to dev.to/t/node which is already in the learning section. They aggregate links to share the most recently published blog posts.

The resource I'm submitting is a persistent list of tutorials/guides/books/etc focused on answering questions like "How do I learn Node" or "What's the best advanced tutorial to build Node web apps".

I totally understand the points and concerns raised, but in terms of comparisons, I think it provides an entirely different value than the time-based news aggregation feeds.

**Comment by nschonni** [comment]
Going to close this off since it's been awhile and there didn't appear to be any approvals for merging this

**Pull request closed without merging**
