### PR TITLE
chore: normalize spacing + fix erroneous space

### PR DESCRIPTION
**Pull request by bnb**
normalizes spacing on a change made last night + fixes a erroneous double space

### CODE REVIEW

**Review by MylesBorins — APPROVED** [review]
LGTM

**Comment by Trott** [comment]
Not objecting, but I added the line-wrapping because it makes diffs much easier to deal with, and I have a feeling there's going to be a lot of tweaking to this doc.

**Comment by bnb** [comment]
@Trott I'm not opposed to it, I'd just like to see consistency either way. Reverting this section to the way the rest of the doc was structured was easier than converting the rest of the doc to this.

**Comment by Trott** [comment]
> @Trott I'm not opposed to it, I'd just like to see consistency either way. Reverting this section to the way the rest of the doc was structured was easier than converting the rest of the doc to this.

If we land the rest of my PRs, then the word-wrapping will be almost everywhere. :-D

We can then open a separate PR to create consistency.

That said, I'm not opposed to doing it this way either. I *prefer* the other way, but we both have bigger things to worry about right now, so whatevs.

**Comment by Trott** [comment]
> I'd just like to see consistency either way.

Friendly alternative: https://github.com/nodejs/nodejs.org/pull/3234

**Comment by MylesBorins** [comment]
I landed alternative, closing this

**Pull request closed without merging**
