### PR TITLE
docs: previous releases list update

### PR DESCRIPTION
**Pull request by ghost**
I've updated the list of previous releases in all languages. Some languages were missing version **11** or **12** and all of them were missing version **13**. This will improve navigation on the website.

Now it looks like this.
pr

### CODE REVIEW

**Comment by ghost** [comment]
@Trott please take a look.

**Comment by oleksiipotiekhin** [comment]
@Trott @nschonni

**Comment by ghost** [comment]
> @Trott please take a look.

@nschonni or maybe you can.

**Review by nschonni — APPROVED** [review]
LGTM, but I think we may need to at v14 and v15 as well. I think those are missing from the English page too

**Comment by ghost** [comment]
> LGTM, but I think we may need to at v14 and v15 as well. I think those are missing from the English page too

Since v14 and v15 are available on the main page I assumed they are not needed in this section.

image

**Comment by ghost** [comment]
@nschonni please merge this changes.

**Review by marsonya — APPROVED** [review]

**Pull request merged**
