### PR TITLE
about/releases: corrected some grammar and rewrote portions for readability

### PR DESCRIPTION
**Pull request by boneskull**
Hi,

Hope this can be used.  I saw a couple issues I had intended to fix, but just kept going...

### CODE REVIEW

**Comment by fhemberger** [comment]
Nice, LGTM.

**Comment by bnb** [comment]
Are all pages written with hard line breaks? If so, you're good - if not, you should remove all the hard line breaks in your document.

**Comment by boneskull** [comment]
made some updates.

**Comment by boneskull** [comment]
> Are all pages written with hard line breaks? If so, you're good - if not, you should remove all the hard line breaks in your document.

Other pages use hard line breaks

**Comment by bnb** [comment]
@boneskull Links? All the ones I looked at randomly don't used hard line breaks.

Ref:
https://github.com/nodejs/new.nodejs.org/blob/master/locale/en/blog/announcements/interactive-2015-programming.md
https://github.com/nodejs/new.nodejs.org/blob/master/locale/en/blog/release/v4.2.1.md
https://github.com/nodejs/new.nodejs.org/blob/master/locale/en/blog/weekly-updates/weekly-update.2015-10-16.md
https://github.com/nodejs/new.nodejs.org/blob/master/locale/en/blog/feature/streams2.md

**Comment by boneskull** [comment]
@bnb any file in locale/en/about

**Comment by boneskull** [comment]
looks like the `.md` files need to be normalized one way or another.  but that's not part of this PR

**Comment by boneskull** [comment]
should I try to resolve the merge conflicts ..?

**Comment by fhemberger** [comment]
@boneskull Yes, please. I'd like to merge this regardless of line breaks.

We don't have a policy for this yet and some pages use hard breaks and some don't. And as long as the page renders properly, I really don't mind. :smile:

**Comment by boneskull** [comment]
@fhemberger I've resolved the conflicts.  sorry took me awhile :smile:

**Comment by fhemberger** [comment]
Sorry, took a while to merge this. Thanks!

**Pull request merged**
