### PR TITLE
trademark: made translation from english version

### PR DESCRIPTION
**Pull request by ErnestoSalazar**
Hi, i just made a spanish translation from the english version of trademark.md

### CODE REVIEW

**Comment by fhemberger** [comment]
Thanks for translating! AFAIK only the english version of the trademark will be legally binding, just as a side note.

**Comment by ErnestoSalazar** [comment]
Thanks for your reply, so how should we proceed with this PR?

**Comment by vrunoa** [comment]
LGTM

**Review by ghost — APPROVED** [review]

**Comment by fhemberger** [comment]
@ErnestoSalazar I'm just waiting for possible further feedback from @nodejs/nodejs-es, and then we'll merge it. ;)

**Comment by ErnestoSalazar** [comment]
Okay ;D

**Review by vrunoa — APPROVED** [review]

**Pull request merged**
