### PR TITLE
fix: open docs links in the same tab closes #6927

### LINKED ISSUE #6927: Open docs link in same window
### Enter your suggestions in details:

I searched for related discussions but could not find them, is there a good reason I am not aware of to force a new window for that link? For me personally I find it unexpected even with the icon, and since it forces the behavior I as a user have no way to control it and open in the same tab. I didn't look, but I believe this was not the case with the old version, so just wanted to open an issue to discuss this new behavior and if folks are open to removing `target="_blank"`?

### PR DESCRIPTION
**Pull request by wesleytodd**
## Description

Open Docs link in the same tab

## Validation

Open the docs link in the header, should not have the icon and should open in the same tab.

Fixes https://github.com/nodejs/nodejs.org/issues/6927

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [ ] I have run `npm run format` to ensure the code follows the style guide.
- [ ] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
I'm getting a 404 on this current approach. 

https://nodejs-org-git-fork-wesleytodd-docs-in-tab-openjs.vercel.app/en/docs/latest/api/

It may need to be the absolute url to account for the way the site is built and/or requests are routed by CF

**Review by Jay-Karia — COMMENTED** [review]
Even the icon in the navbar should be removed.

https://github.com/nodejs/nodejs.org/issues/6927#issuecomment-2232810823

**Comment by Jay-Karia** [comment]
> I'm getting a 404 on this current approach.
> 
> https://nodejs-org-git-fork-wesleytodd-docs-in-tab-openjs.vercel.app/en/docs/latest/api/
> 
> It may need to be the absolute url to account for the way the site is built and/or requests are routed by CF

@wesleytodd Does it work locally ?

**Comment by Jay-Karia** [comment]
This works,
```json
"docs": {
  "link": "https://nodejs.org/docs/latest/api/",
  "label": "components.containers.navBar.links.docs"
},
```

But, the icon in navbar renders.

**Comment by ovflowd** [comment]
> I'm getting a 404 on this current approach.
> 
> [nodejs-org-git-fork-wesleytodd-docs-in-tab-openjs.vercel.app/en/docs/latest/api](https://nodejs-org-git-fork-wesleytodd-docs-in-tab-openjs.vercel.app/en/docs/latest/api/)
> 
> It may need to be the absolute url to account for the way the site is built and/or requests are routed by CF

With absolute paths, it will always use i18n routing. That's why we use the full path. We can use the full DN (https://nodejs.org/api...), but the external icon will render it, although it will not open on a blank tab, which is what this PR intends to fix.

**Comment by wesleytodd** [comment]
Well IMO the icon should also not render if it is not opening in a new tab. @ovflowd, am I understanding this last comment that the current setup would need a change to exclude this route from the i18n treatment which adds in the `/en`? What if instead we remove the check for `type === 'nav' && href.startsWith('http')`? Is this component used for more than just the nav bar?

**Comment by wesleytodd** [comment]
Figured it was just easier to push a change to this and see what y'all wanted to do.

**Review by bmuenzenmeyer — APPROVED** [review]
I'm fine with this. From a user perspective I wouldn't imagine anyone sees these as two different sites, and someone can always middle click or "open in new tab/window" contextually.

**Review by AugustinMauroy — APPROVED** [review]
LGMT !
I prefer this behavior

**Review by canerakdas — APPROVED** [review]

**Review by juanarbol — APPROVED** [review]
Thanks!

**Review by mikeesto — APPROVED** [review]
LGTM, let's land this

**Pull request merged**
