### PR TITLE
Split npm scripts and run them in parallel

### LINKED ISSUE #2463: Split npm test scripts
I had made #2405, but my patch wasn't accepted as it was.

That being said, I find the current situation inconvenient. We can't run just `standard` without running the whole batch of scripts in `npm run test:lint`.

I believe this should be addressed.

### PR DESCRIPTION
**Pull request by XhmikosR**
This is a first approach at addressing #2463.

Other changes:

1. removed `--fix` from `standard` because on CI this didn't make the build fail. One can still do `npm run test:lint:js -- --fix` locally if they want to
2. runs `test:lint` scripts in parallel

I still think we should move `npm run build` outside of tape and just run this before test. Build warnings aren't shown in [tape](https://github.com/nodejs/nodejs.org/issues/2442#issue-483485909)

Fixes #2463

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by Trott** [comment]
Seems fine to me.

**Comment by XhmikosR** [comment]
@Trott how about moving `build` in scripts and not in tape? See https://github.com/nodejs/nodejs.org/issues/2442#issue-483485909

**Comment by Trott** [comment]
> @Trott how about moving `build` in scripts and not in tape? See [#2442 (comment)](https://github.com/nodejs/nodejs.org/issues/2442#issue-483485909)

👍

**Comment by XhmikosR** [comment]
Cool, I'll make this change in another PR.

**Pull request merged**
