### PR TITLE
Update Node.js Everywhere copy from weekly to monthly

### LINKED ISSUE #1745: Update to Node.js Newsletter
Nothing urgent, but I noticed on the home tab that it states Node.js Everywhere is a weekly newsletter, but we've changed it to monthly. I don't think I have access to the home tab to make this fix. Happy to follow someone's directions on this, but don't want to mess anything up.

Thanks in advance for any help here :)

### PR DESCRIPTION
**Pull request by sonicdoe**
Resolves #1745. The copy is updated on both the [home page](https://nodejs.org/en/) and the [“Get Involved” page](https://nodejs.org/en/get-involved/).

### CODE REVIEW

**Review by daxlab — APPROVED** [review]

**Comment by daxlab** [comment]
👍

**Review by ckotzbauer — APPROVED** [review]

**Comment by fhemberger** [comment]
Great, now we need someone to check the other translations as well ... ;)

**Comment by sonicdoe** [comment]
As an overview, the following strings would need to be updated:

`newsletter-postfix` in [`index.md`](https://github.com/nodejs/nodejs.org/blob/monthly-newsletter/locale/en/index.md):

- [x] Arabic (`ar`): ` , القائمة البريدية الأسبوعية الرسمية ل  Node.js `
- [x] Italian (`it`): `, la newsletter settimanale di Node.js`
- [x] Simplified Chinese (`zh-cn`): `，Node.js 官方的新闻周报。`
- [x] Traditional Chinese (`zh-tw`): `：Node.js 官方的新聞週報。`

In [`get-involved/index.md`](https://github.com/nodejs/nodejs.org/blob/monthly-newsletter/locale/en/get-involved/index.md):

- [x] French (`fr`): `[Node.js Everywhere](https://newsletter.nodejs.org) est la newsletter hebdomadaire officielle de Node.js [en].`
- [x] Traditional Chinese (`zh-tw`): `[Node.js Everywhere](https://newsletter.nodejs.org) 是 Node.js 官方的週報。`

**Review by lpinca — APPROVED** [review]

**Comment by lpinca** [comment]
For the Italian translation above you can use "la newsletter mensile di Node.js"

**Review by marswong — APPROVED** [review]

**Comment by sonicdoe** [comment]
@lpinca Thank you 👍 I’ve changed it.

@fhemberger Should I mention the respective localization teams or should we just merge this as is and update the other languages as we go along?

**Comment by ghost** [comment]
Thanks @sonicdoe，Please add this :)

【For zh-CN】
index.md：Node.js 官方的新闻月报。

【For zh-TW】
index.md：Node.js 官方的新聞月報。
get-involved/index.md：是 Node.js 官方的月報。

/cc：
@nodejs/nodejs-ja 
@nodejs/nodejs-ar 
@nodejs/nodejs-fr 

I've also called these related translators to help to contribute their language translations here, you can copy and paste them when they are free to contribute.

**Comment by fhemberger** [comment]
@sonicdoe Japanese version doesn't use the term "weekly" in their description at all as far as I can tell.

French should be "hebdomadaire" -> "mensuel".

**Comment by sonicdoe** [comment]
@fhemberger Thanks, done 👍 Only Arabic left.

**Comment by thom4parisot** [comment]
@sonicdoe actually in French it should be `mensuelle` instead of `mensuel`, because the term newsletter is a feminine term (hence the `le` suffix).

**Comment by fhemberger** [comment]
@oncletom Ahhhh, sorry for that!

**Comment by thom4parisot** [comment]
@fhemberger no probs at all! Thank you for taking care of this PR with @sonicdoe 🙂

**Comment by mermi** [comment]
For the Arabic version if you need to say weekly newsletter about Node.js it should be:
الرسالة الإخبارية الأسبوعية عن Node.js
If you wanna say monthly newsletter about Node.js it should be:
الرسالة الإخبارية الشّهريّة عن  Node.js

Let me know if you need further help 😃

**Comment by fhemberger** [comment]
@mermi Awesome, thank you so much! 😍

**Pull request merged**
