### PR TITLE
Add dark theme style

### PR DESCRIPTION
**Pull request by NriotHrreion**
issue #3507 

I've added the dark theme style.
It will look more comfortable for the dark theme user (like me).

### CODE REVIEW

**Comment by NriotHrreion** [comment]
So why it can't pass the check?? It can work on my computer.

**Comment by Trott** [comment]
> So why it can't pass the check?? It can work on my computer.

https://github.com/nodejs/nodejs.org/pull/4139/checks?check_run_id=3758405453

```
layouts/css/layout/_dark-theme.scss
  1:6   ✖  Expected single space after at-rule name "@media"   at-rule-name-space-after         
  2:5   ✖  Expected indentation of 2 spaces                    indentation                      
  3:9   ✖  Expected indentation of 4 spaces                    indentation                      
  4:9   ✖  Expected indentation of 4 spaces                    indentation                      
  5:9   ✖  Expected indentation of 4 spaces                    indentation                      
  5:10  ✖  Expected newline after ","                          selector-list-comma-newline-after
  5:14  ✖  Expected newline after ","                          selector-list-comma-newline-after
  5:18  ✖  Expected newline after ","                          selector-list-comma-newline-after
  6:13  ✖  Expected indentation of 6 spaces                    indentation                      
  7:9   ✖  Expected indentation of 4 spaces                    indentation                      
  8:5   ✖  Expected indentation of 2 spaces                    indentation                      
 10:5   ✖  Expected indentation of 2 spaces                    indentation                      
 11:9   ✖  Expected indentation of 4 spaces                    indentation                      
 12:13  ✖  Expected indentation of 6 spaces                    indentation                      
 13:9   ✖  Expected indentation of 4 spaces                    indentation                      
 15:9   ✖  Expected indentation of 4 spaces                    indentation                      
 16:13  ✖  Expected indentation of 6 spaces                    indentation                      
 17:9   ✖  Expected indentation of 4 spaces                    indentation                      
 19:9   ✖  Expected indentation of 4 spaces                    indentation                      
 20:13  ✖  Expected indentation of 6 spaces                    indentation                      
 21:13  ✖  Expected indentation of 6 spaces                    indentation                      
 22:9   ✖  Expected indentation of 4 spaces                    indentation                      
 24:9   ✖  Expected indentation of 4 spaces                    indentation                      
 25:13  ✖  Expected indentation of 6 spaces                    indentation                      
 26:17  ✖  Expected indentation of 8 spaces                    indentation                      
 27:13  ✖  Expected indentation of 6 spaces                    indentation                      
 28:13  ✖  Expected indentation of 6 spaces                    indentation                      
 29:17  ✖  Expected indentation of 8 spaces                    indentation                      
 30:17  ✖  Expected indentation of 8 spaces                    indentation                      
 31:13  ✖  Expected indentation of 6 spaces                    indentation                      
 32:9   ✖  Expected indentation of 4 spaces                    indentation                      
 34:9   ✖  Expected indentation of 4 spaces                    indentation                      
 35:13  ✖  Expected indentation of 6 spaces                    indentation                      
 36:9   ✖  Expected indentation of 4 spaces                    indentation                      
 37:5   ✖  Expected indentation of 2 spaces                    indentation                      
 39:5   ✖  Expected indentation of 2 spaces                    indentation                      
 40:9   ✖  Expected indentation of 4 spaces                    indentation                      
 41:5   ✖  Expected indentation of 2 spaces                    indentation
```

**Comment by ghost** [comment]
> issue #3507
> 
> I've added the dark theme style. It will look more comfortable for the dark theme user (like me).

@NriotHrreion: Just run 'test:lint:stylelint -- --fix' to fix the formation problems and resubmit again :)
But still say a big THANK YOU for your 1st contribution!

**Comment by NriotHrreion** [comment]
I've resubmitted my code.

**Comment by ghost** [comment]
@NriotHrreion: Sorry but I only see the scss there... so anywhere to apply it by a switch to Dark mode or....? Can you offer us a screenshot by running locally with "npm run server"?

**Comment by NriotHrreion** [comment]
Here you are.
And it can change to the dark theme when it detected the user's browser is dark mode. By the way, I'm working on the 
dark theme switcher.

image

**Comment by ghost** [comment]
@NriotHrreion: Waiting for your nice contribution!

**Comment by NriotHrreion** [comment]
I wonder why it can't pass the check again... I've run the tests on my computer and it didn't return any wrong.

**Comment by ghost** [comment]
@NriotHrreion: There're some errors happening when checking:

1) "svg" should have a new line better (Fixed by me).
2) The fetal error is: Plz make sure that your "aria-controls="dark-theme-switcher"——Have you got an element whose ID is "dark-theme-switcher"? (For more, plz see: https://rocketvalidator.com/html-validation/the-aria-controls-attribute-must-point-to-an-element-in-the-same-document).

I suspect whether you've missed something like 'div' or something with the ID = "dark-theme-switcher" so as to let the js dynamically cope with it in the same header.hbs file?

Notice how "lang-picker" is made....they have the same ID in the same document (header.hbs).

image

****
image

**Comment by MaledongGit** [comment]
If everything is OK, a gif or mp4 video is welcomed for us to see what's happening, expecting your job XD

**Comment by NriotHrreion** [comment]
Thank you, I'll check my code.

**Comment by NriotHrreion** [comment]
> @NriotHrreion: There're some errors happening when checking:
> 
> 1. "svg" should have a new line better (Fixed by me).
> 2. The fetal error is: Plz make sure that your "aria-controls="dark-theme-switcher"——Have you got an element whose ID is "dark-theme-switcher"? (For more, plz see: https://rocketvalidator.com/html-validation/the-aria-controls-attribute-must-point-to-an-element-in-the-same-document).
> 
> I suspect whether you've missed something like 'div' or something with the ID = "dark-theme-switcher" so as to let the js dynamically cope with it in the same header.hbs file?
> 
> Notice how "lang-picker" is made....they have the same ID in the same document (header.hbs).
> 
> image
> 
> image

Haha, it's true that I didn't notice that :smile:

**Review by ghost — APPROVED** [review]
LGTM
*****
Demo

**Comment by ghost** [comment]
@Trott: Any comments?

**Comment by NriotHrreion** [comment]
May I ask when it will merge?

**Comment by MaledongGit** [comment]
> May I ask when it will merge?

I'll wait for 2 people to approve at least, and yours will be merged quickly ;)

**Review by Trott — DISMISSED** [review]
Welcome, @NriotHrreion, and thanks for the pull request.

This introduces a few accessibility issues that need to be addressed.

* The theme-switching button element is empty. See how it's done on the doc pages for an example of how to do it in a way that won't be puzzling for users of assistive technology.
*  In dark mode, the link text contrasts insufficiently with the dark background. These colors should be the same as in the docs anyway, where the color contrast meets WCAG AA guidelines. So it's probably best to copy the colors used there.

Thanks for making this happen!

**Comment by Trott** [comment]
@nodejs/website This is a pretty significant feature and could use some reviews.

**Comment by NriotHrreion** [comment]
> Welcome, @NriotHrreion, and thanks for the pull request.
> 
> This introduces a few accessibility issues that need to be addressed.
> 
> * The theme-switching button element is empty. See how it's done on the doc pages for an example of how to do it in a way that won't be puzzling for users of assistive technology.
> * In dark mode, the link text contrasts insufficiently with the dark background. These colors should be the same as in the docs anyway, where the color contrast meets WCAG AA guidelines. So it's probably best to copy the colors used there.
> 
> Thanks for making this happen!

Yes, I'll try my best.

**Comment by ghost** [comment]
@NriotHrreion: You can refer the doc's icon sytle: https://nodejs.org/dist/latest-v16.x/docs/api/

1. Notice the icon has its own tooltip when moving your mouse there.
image

2. Notice the dark mode's color is a bit different from what it is in white (F12 to see what's happening):
image

**Comment by NriotHrreion** [comment]
OK, thanks.

**Comment by NriotHrreion** [comment]
...I forgot to run test...

**Comment by NriotHrreion** [comment]
Why no one replies me?
I've submitted my code for a long time.

**Review by ghost — APPROVED** [review]
Still fine with me with the changed colors of links...ect.
Waiting for other's review results in case of something missing....

****
Demo

**Comment by Trott** [comment]
Seems OK to me, although I'll defer to the more website-focused people. One thing I've noticed is that the pointer that indicates what section you're in is no longer as visible. I don't think this is a blocker. I think this can land and we can either live with it or improve it later. But in case someone feels differently and/or you want to improve it now:

The downward-pointing triangle tells me I'm in the Get Involved section:

image

But in dark mode, it's harder to see:

image

**Comment by NriotHrreion** [comment]
So I made the color of the upper part brighter to make the difference between the two parts more obvious. If it's still not enough, I will continue to modify that.

**Comment by NriotHrreion** [comment]
But I think it's enough.

**Comment by Trott** [comment]
> But I think it's enough.

I think it's fine for now and we can always iterate and modify the colors incrementally later.

**Comment by NriotHrreion** [comment]
> > But I think it's enough.
> 
> I think it's fine for now and we can always iterate and modify the colors incrementally later.

I think so. You're right.

**Comment by NriotHrreion** [comment]
And I'm waiting your review. @Trott

**Review by Trott — COMMENTED** [review]
LGTM.

**Comment by NriotHrreion** [comment]
When will this PR be merged? :thinking: @MaledongGit @Trott

**Comment by ghost** [comment]
@NriotHrreion: It seems you're in a hot temper XD who wants to be merged quickly......Consider this is a big change so I want to confirm from other suggestions for several days, if no obvious againsts, yours will be merged :)

**Comment by NriotHrreion** [comment]
Um.. OK. I'll be patient.

**Comment by Trott** [comment]
@nodejs/website It would be good to get some more reviews of this. Anyone?

**Comment by ghost** [comment]
Considering this has been lasting for a period of long time and there's no obvious againsts to it, I merge it now

**Comment by XhmikosR** [comment]
This was a little poorly implemented IMHO.

1. loading the SVG file in CSS is bad, like pretty bad. The browser needs to download the CSS to start downloading the SVG. We should do what we do with the language toggle icon instead
2. the dark theme doesn't look too good IMHO. Dark != black. And the blue color that was chosen for the navbar doesn't make any sense to me...
3. I don't see why we need a new `data` attribute? I mean, can't we just add a class in the `html` instead?

**Pull request merged**
