### PR TITLE
docs: move and update inspector help

### PR DESCRIPTION
**Pull request by joshgav**
Per feedback in https://github.com/nodejs/node/pull/11207, copying Inspector guide to a simpler path and removing background info.

### CODE REVIEW

**Comment by joshgav** [comment]
cc @nodejs/diagnostics

**Review by hybrist — APPROVED** [review]

**Review by lpinca — APPROVED** [review]

**Comment by joshgav** [comment]
Landed in https://github.com/nodejs/nodejs.org/commit/13eaf4c0fa678aa08fe5a241e8fa8b875a045c43. Thanks!

**Comment by ofrobots** [comment]
I am concerned this landed without review from folks from the DevTools team. /cc @eugeneo @pavelfeldman.

**Comment by hybrist** [comment]
Sorry, didn't fully realize that we now have 2 copies of the "same" guide:

* https://github.com/nodejs/nodejs.org/blob/master/locale/en/docs/guides/debugging-getting-started.md
* https://github.com/nodejs/nodejs.org/blob/master/locale/en/docs/inspector.md

There's also overlap with the debugger docs page, specifically the ["Advanced Usage" section](https://github.com/nodejs/node/blob/master/doc/api/debugger.md#advanced-usage). It might be good to do another pass to unify & cross-link to make sure each of the URLs provides value and we don't duplicate information. Imo iterating on the docs shouldn't have to block the node PR though as long as it points to a valid URL.

**Comment by joshgav** [comment]
@jkrems I left the old version up since it contains more detail in the first section which perhaps we can transition into a more complete guide. Such a guide could also include upcoming JS APIs (cc @eugeneo) and the Advanced usage you mentioned. Let's keep working on that and submit PRs with suggested updates.

The doc in this PR is meant to be as short as possible and focus primarily on available tools per [earlier feedback](https://github.com/nodejs/node/pull/11207#issuecomment-295331471), to help users get started if they specify --inspect manually. In some ways it's a replacement for the chrome-devtools URL originally provided.

Also it's to engender conversation about how to make this experience as good as possible for users, so thanks for the feedback 😄 

@ofrobots would be great to get more feedback and suggestions from the DevTools and Chromium teams, please make follow-on PRs and we can get them merged quickly. Thank you!

**Pull request closed without merging**
