### PR TITLE
Remove the unused metalsmith-metadata dependency

### PR DESCRIPTION
**Pull request by XhmikosR**
Needs another pair of eyes for sure, but it seems this was unused. It might have been used at some point in the past.

### CODE REVIEW

**Comment by Aissaoui-Ahmed** [comment]
I am using [depcheck](https://www.npmjs.com/package/depcheck) to check unused packages
$> depcheck

Unused dependencies
  * jstransformer-handlebars
  * metalsmith-metadata

Unused devDependencies
  * remark-frontmatter
  * remark-gfm
  * remark-preset-lint-node
  * stylelint-config-twbs-bootstrap

Missing dependencies
  * eslint-config-standard: .\.eslintrc 
  * eslint-plugin-import: .\.eslintrc
  * eslint-plugin-node: .\.eslintrc
  * eslint-plugin-promise: .\.eslintrc
  * utf-8: .\layouts\css\styles.scss
  * variables: .\layouts\css\styles.scss
  * base: .\layouts\css\styles.scss
  * utils: .\layouts\css\styles.scss
  * layout: .\layouts\css\styles.scss
  * page-modules: .\layouts\css\styles.scss
  * vendor: .\layouts\css\styles.scss
  * screen: .\layouts\css\styles.scss
  * padded-link: .\layouts\css\_base.scss
  * spinner-border: .\layouts\css\page-modules\spinner.scss

>Update : `$> depcheck --ignores="eslint*" --ignore-dirs="layouts"`

**Comment by XhmikosR** [comment]
Those aren't unused, though. The only unused package is the one I removed here.

**Comment by Aissaoui-Ahmed** [comment]
What about `jstransformer-handlebars` ?

**Comment by XhmikosR** [comment]
It is needed. Generally, don't trust depcheck too much because it can't cover all the use cases out there.

**Comment by Aissaoui-Ahmed** [comment]
You can ignore director and packages
```bash
depcheck --ignores="eslint*,stylelint-*,remark-*" --ignore-dirs="layouts"
```

**Comment by XhmikosR** [comment]
Sure, but it's unrelated to this PR ;)

**Review by Aissaoui-Ahmed — APPROVED** [review]

**Pull request merged**
