### PR TITLE
Remove English commented out code from the Korean files.

### PR DESCRIPTION
**Pull request by XhmikosR**
This is too much duplication and slows down the build.

### CODE REVIEW

**Review by Aissaoui-Ahmed — APPROVED** [review]

**Comment by yous** [comment]
Don't remove the comments. It's for making diffs by translators when the original (en) articles are updated.

**Comment by XhmikosR** [comment]
It's useless and you should use the original files doe this purpose. See
how many lines there are which slow down the builds and/or introduce false
markdown errors.

**Comment by yous** [comment]
Translators make diffs of the original files and the comments. So they can update the translation where it needs update. Re-translating the whole file is time wasting, and translations are not updated real-time to reflect changes of every single commit on `locale/en` directory.

Using HTML comments are [valid](https://daringfireball.net/projects/markdown/syntax#html) in Markdown. Also I see that [every build of master branch](https://travis-ci.com/nodejs/nodejs.org/builds) runs around just one minute. I don't think HTML comments slow down the builds dozens of seconds.

**Comment by XhmikosR** [comment]
You do know there is git available?

Anyway I don't want to engage in this. I'll let the maintainers decide.

To me it's totally useless and bloats the source code with so much
duplication.

**Comment by yous** [comment]
There are translators not used to git.

**Comment by ghost** [comment]
@XhmikosR, I know what you mean, but since there are still some people loving to keep the original content to match what they've translated. So there's no need to remove them.

**Pull request closed without merging**
