### PR TITLE
Added border bottom to Sideabar of about page

### LINKED ISSUE #6677: Seperating the title with the subcontent in about (Sidebar)
### URL:

https://nodejs.org/en/about

### Browser Name:

brave

### Browser Version:

1.65.123

### Operating System:

Windows 11

### How to reproduce the issue:

1. Go the about 
the current visual looks like this 
image
image

i notice a visual dissatisfaction with the title and the subpart of it . i feel like there should be more separation between them  (not only making the font small we can try the below idea ) 
solution:
1. either darken out the title a little bit to show a contrast to it
2. or we can add a padding left to the subpart to show seperation

### PR DESCRIPTION
**Pull request by TenzDelek**
Fixes #6677 

## Description
- as discuss in the issue, the separation of the title and the sub content done with the adding a border bottom to the title

## Validation
image

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
Maybe use `border-neutral-200` for light and `border-neutral-800` for dark, to make it less aggressive

**Comment by TenzDelek** [comment]
> Maybe use `border-neutral-200` for light and `border-neutral-800` for dark, to make it less aggressive

sure

**Review by AugustinMauroy — APPROVED** [review]
IMHO, it's good !
Thanks for this first contribution.

**Comment by TenzDelek** [comment]
> IMHO, it's good ! Thanks for this first contribution.

my pleasure, looking forward to do more!!

**Review by ovflowd — CHANGES_REQUESTED** [review]
It genuinely looks weird and doesn't fit our design system. Sorry, I'm against this change (but appreciate the time you've put into this).

**Comment by TenzDelek** [comment]
> It genuinely looks weird and doesn't fit our design system. Sorry, I'm against this change (but appreciate the time you've put into this).

appreciate your input on this, but i still believe we need some sort of a visual distinction between them. one way I thought is darken out the title a little. if this still feels unnecessary , i will close this pr.. @ovflowd

**Comment by TenzDelek** [comment]
> > It genuinely looks weird and doesn't fit our design system. Sorry, I'm against this change (but appreciate the time you've put into this).
> 
> appreciate your input on this, but i still believe we need some sort of a visual distinction between them. one way I thought is darken out the title a little. if this still feels unnecessary , i will close this pr.. @ovflowd

**Comment by ovflowd** [comment]
Let me mutter a bit about variants we could create, and Ill come back to you :)

**Comment by TenzDelek** [comment]
> Let me mutter a bit about variants we could create, and Ill come back to you :)

sure :smiley:

**Comment by TenzDelek** [comment]
> Let me mutter a bit about variants we could create, and Ill come back to you :)

 @ovflowd  any thought on this ?

**Comment by ovflowd** [comment]
> > Let me mutter a bit about variants we could create, and Ill come back to you :)
> 
> @ovflowd any thought on this ?

Unfortunately haven't putten time into this yet, something I was cogitating/thinking was in line of this:

image

OR this:

image

**Comment by TenzDelek** [comment]
> > > Let me mutter a bit about variants we could create, and Ill come back to you :)
> > 
> > 
> > @ovflowd any thought on this ?
> 
> Unfortunately haven't putten time into this yet, something I was cogitating/thinking was in line of this:
> 
> image
> 
> OR this:
> 
> image

@ovflowd  seeing the reaction of the team, I believe it is a no sign. what about this, i added a visual + and darken the header a little. what do you say?  
image

**Comment by TenzDelek** [comment]
@ovflowd , seeing the reaction of the team , i dont think the above design is feasible for now.  for these pass days , i came up with a design that maybe suitable enough. (added a + sign and darken the header for better seperation). what do you think? :)
image

**Comment by AugustinMauroy** [comment]
maybe without the + it's can be ok

**Comment by TenzDelek** [comment]
> maybe without the + it's can be ok

sure will remove that !!

**Review by mikeesto — APPROVED** [review]
I think this is an improvement over what we currently have so +1 from me

**Review by AugustinMauroy — APPROVED** [review]
LGTM ! Lighthouse contrast ratio is passing 🎉

**Review by aymen94 — APPROVED** [review]

**Comment by ovflowd** [comment]
The headers being dark is definitely a nimble and good solution :)

**Comment by ovflowd** [comment]
> @ovflowd , seeing the reaction of the team , i dont think the above design is feasible for now.  for these pass days , i came up with a design that maybe suitable enough. (added a + sign and darken the header for better seperation). what do you think? :)
> 
> image
> 
> 

It is important to mention those are just random ideas Ive come up in 5 minutes.

**Review by ovflowd — APPROVED** [review]
LGTM. Thank you for your first contribution ;)

**Pull request merged**
