### PR TITLE
Initiate Persian language into Doc

### PR DESCRIPTION
**Pull request by armanatory**

### CODE REVIEW

**Comment by ghost** [comment]
@armanatory：
The build failed, I suggest you copying the `en`'s structure with all of its files into the `locale` and do translations to your own language , don't forget to change the folder name to `fa`.  And plz DO NOT translate anything in the `blog` folder under `locale`.

But still want to say "Thanks first for your contributions~"

**Comment by armanatory** [comment]
@Maledong I did the same, and I'll do it again more precisely. Also appreciate your time and consideration.

**Comment by Maledong** [comment]
No problem.

1. I've checked your issue and it seems that because of your duplicated generated files by Visual Studio, Node cannot recognize these files, this cause your problem.

2. Now I've started a new PR for your lang, so you can update your own local Persian language and based on this, you can do any changes carefully and continue your PRs :)

**Comment by ghost** [comment]
@armanatory：

No problem.

1. I've checked your issue and it seems that because of your duplicated generated files by Visual Studio, Node cannot recognize these files, this cause your problem.

2. Now I've started a new PR for your lang, so you can update your own local Persian language and based on this, you can do any changes carefully and continue your PRs  (See the Persian PR at: https://github.com/nodejs/nodejs.org/pull/1866).

3. Everytime when you do a submit, please DO NOT forget to run "npm run test" and then "npm run serve" to see the result (if there's something you haven't translated yet, this will be still directed to English).

Now this is the result when visiting in your local PC, you can have a view for that：http://localhost:8080/fa/

persian

**Pull request closed without merging**
