### PR TITLE
Fa locale

### PR DESCRIPTION
**Pull request by faeztgh**
### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
We handle translation by crowdin. So please read `TRANSLATION.md`

**Comment by faeztgh** [comment]
> We handle translation by crowdin. So please read `TRANSLATION.md`

I sent join request there.
Also website need to handle new font for fa/ar languages.

**Comment by AugustinMauroy** [comment]
> I sent join request there.
 
Perfect !

> Also website need to handle new font for fa/ar languages.

Why ? could you give more information for that ?

**Comment by faeztgh** [comment]
> > Also website need to handle new font for fa/ar languages.
> 
> Why ? could you give more information for that ?

Because current fonts not fit with `fa/ar` languages very well. I can recommend `Vazirmatn` font for that.

**Comment by AugustinMauroy** [comment]
> Because current fonts not fit with fa/ar languages very well. I can recommend Vazirmatn font for that.

I'm not really in favour of that. But if you feel you need to add another font. Open an issues.

**Pull request closed without merging**
