### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by sh9temp**

### CODE REVIEW

**Comment by nschonni** [comment]
Ping @nodejs/nodejs-ja

**Review by okuryu — APPROVED** [review]
:+1:

**Comment by nschonni** [comment]
@sh9temp can you provide a little description of what this changes? It will just make it easier for the commit message

**Comment by ghost** [comment]
@nodejs/nodejs-ja：If anyone is glad to help, and I'll do changes to this post with the commit.

**Comment by okuryu** [comment]
I created a new PR with description: https://github.com/nodejs/nodejs.org/pull/3063

**Comment by hiroppy** [comment]
We can modify the commit message before merging.

**Comment by alexandrtovmach** [comment]
@nodejs/nodejs-ja Please review this PR

**Pull request closed without merging**
