### PR TITLE
website redesign - fix(ignore): es-lint + git + prettier

### PR DESCRIPTION
**Pull request by AugustinMauroy**
Add storybook to ignore config file

### CODE REVIEW

**Review by rodion-arr — APPROVED** [review]

**Review by ovflowd — APPROVED** [review]
Do we also need a `.storybook` on Gitignore?

Anyhow, thanks!

**Comment by AugustinMauroy** [comment]
> Do we also need a .storybook on Gitignore?

Not they are configuration inside.

**Review by shanpriyan — APPROVED** [review]

**Comment by ovflowd** [comment]
I am requesting fast-tracking of this PR! cc @nodejs/website

**Comment by ovflowd** [comment]
@AugustinMauroy can you rebase the PR or simply recreate it? Had to rebase the branch and now your branch got detached from the branch (different commit hashes)

**Review by anonrig — APPROVED** [review]

**Comment by AugustinMauroy** [comment]
@ovflowd yep i will try to fix this.

**Review by manishprivet — APPROVED** [review]
LGTM 🚀 

We can merge this after the conflicts are resolved

**Review by aymen94 — APPROVED** [review]

**Comment by ovflowd** [comment]
@AugustinMauroy could you remove the `package-lock` changes?

**Comment by AugustinMauroy** [comment]
I am closing this PR because there is a lot of conflict.
But don't worry I'll open it again.

**Pull request closed without merging**
