### PR TITLE
[Docs] Fix a style error

### PR DESCRIPTION
**Pull request by ghost**
Make the extra explain the same size as `<sup>1</sup>` as a footnote.
And now the font size isn't in a good line, they are not the same size. It doesn't look nice.

Compare with the two screenshots:

[Now]
wrong

[After Changes]
right

### CODE REVIEW

**Review by fhemberger — CHANGES_REQUESTED** [review]
Having a entire paragraph in superscript is typographically incorrect, so I'd recommend a different approach. There's no need for a footnote here anyway, as it's only one comment. We can drop it entirely and add the note directly in the line below:



For a simple `<br>` in Markdown, add a double white space at the end of the line.

**Comment by Maledong** [comment]
OK, I'll change by the way, please wait for a moment.

**Comment by ghost** [comment]
CC to those who have translated this article to notify them as well：
@nodejs/nodejs-tw
@nodejs/nodejs-ko
@nodejs/nodejs-ja

**Comment by Maledong** [comment]
Fixed it, @fhemberger

**Comment by fhemberger** [comment]
@Maledong Not entirely:

```
 - **openSUSE Leap 42.2**: `nodejs4`
 - **openSUSE Leap 42.3**: `nodejs4`, `nodejs6`
 - **openSUSE Tumbleweed**: `nodejs4`, `nodejs6`, `nodejs8`
 - **SUSE Linux Enterprise Server (SLES) 12**: `nodejs4`, `nodejs6`

(The "Web and Scripting Module" must be [added before installing](https://www.suse.com/documentation/sles-12/book_sle_deployment/data/sec_add-ons_extensions.html).)
```

Should be

```
* **openSUSE Leap 42.2**: `nodejs4`
* **openSUSE Leap 42.3**: `nodejs4`, `nodejs6`
* **openSUSE Tumbleweed**: `nodejs4`, `nodejs6`, `nodejs8`
* **SUSE Linux Enterprise Server (SLES) 12**: `nodejs4`, `nodejs6`  
  (The "Web and Scripting Module" must be [added before installing](https://www.suse.com/documentation/sles-12/book_sle_deployment/data/sec_add-ons_extensions.html).)
```

1. Using `* ` list for consistency (only a little nit)
2. The "Web and Scripting Module" comment only belongs to the last item.  
Mind the double space after `nodejs6` for line break.

**Comment by ghost** [comment]
OK. Fixed @fhemberger

**Review by fhemberger — APPROVED** [review]

**Comment by fhemberger** [comment]
Thank you!

**Pull request merged**
