### PR TITLE
Update oct members 2017

### PR DESCRIPTION
**Pull request by hackygolucky**
We've been busy! This updates a few missing member logos and adds a few recent. Updated on the English and Ukrainian pages.

### CODE REVIEW

**Review by daxlab — APPROVED** [review]
LGTM

**Review by lpinca — APPROVED** [review]

**Comment by lpinca** [comment]
Are there better images for Chef and Lift logos? They are kinda small, less than 200px wide which is what we use in our CSS:

```stylus
img.memberlogo
  display inherit
  vertical-align middle
  width 200px
  padding-right 20px
  padding-left 20px
  padding-bottom 20px
```

**Review by fhemberger — CHANGES_REQUESTED** [review]
Again, please compress the images using ImageAlpha/ImageOptim before putting them on the website. File size is usually ~70% smaller, which is critical for page load time.

**Comment by hackygolucky** [comment]
Thanks for the reminder @fhemberger! Done.

**Comment by fhemberger** [comment]
@hackygolucky Great, thank you. Merging!

**Pull request merged**
