### PR TITLE
Remove the weekly updates script and the unused collection

### LINKED ISSUE #2682: Remove `utm_source` params?
I notice we have some links with tracking params. Should we remove those or keep them?

```
C:\Users\xmr\Desktop\nodejs.org>git grep -n --column "utm_"
locale/en/blog/weekly-updates/weekly-update.2015-02-27.md:56:285:* **Semaphore**, a hosted continuous integrations service, [tweeted](https://twitter.com/semaphoreapp/status/570987355005431809) about added io.js support in their [Platform update on February 24th, 2015](https://semaphoreapp.com/blog/2015/02/17/platform-update-on-february-24th.html?utm_source=twitter&utm_medium=social&utm_content=platform_update_launch&utm_campaign=platformupdate).                              locale/en/blog/weekly-updates/weekly-update.2015-06-26.md:36:96:* Device Atlas API now [supports Node.js](https://deviceatlas.com/blog/deviceatlas-api-node-js?utm_source=twitter&utm_medium=update&utm_campaign=node%20js%20support)           locale/en/blog/weekly-updates/weekly-update.2015-07-31.md:37:224:* [Milo Mordaunt](https://twitter.com/bananaoomarang) has written about [extending IFTTT with Webtask.io running Node.js code](https://auth0.com/blog/2015/07/28/if-this-then-node-dot-js-extending-ifttt-with-webtask-dot-io/?utm_source=io.js+and+Node.js+News&utm_medium=article) over on [Auth0](https://auth0.com/blog).                                                                                                  locale/en/blog/weekly-updates/weekly-update.2015-07-31.md:38:206:* [Hemanth.HM](https://twitter.com/gnumanth), an author and contributor of more than 200 modules on npm, has written about [authoring Node modules](http://h3manth.com/new/blog/2015/authoring-node-modules/?utm_source=io.js+and+Node.js+News&utm_medium=article).                                    locale/en/blog/weekly-updates/weekly-update.2015-08-07.md:80:219:* [webkid.io](http://webkid.io) co-founder [Moritz Klack](http://twitter.com/moklick) has written about [creating a REST API with Hapi, Dogwater and Bedwetter](http://blog.webkid.io/how-to-create-a-rest-api-with-hapi/?utm_source=io.js+and+Node.js+News&utm_medium=article).                       locale/en/blog/weekly-updates/weekly-update.2015-08-07.md:81:222:* [RisingStack](http://risingstack.com) CEO [Gergely Nemeth](http://twitter.com/nthgergo) has a post in the company blog about [using GraphQL with Graffiti](https://blog.risingstack.com/start-using-graphql-with-graffiti/?utm_source=io.js+and+Node.js+News&utm_medium=article).                    locale/en/blog/weekly-updates/weekly-update.2015-08-07.md:82:151:* [Samsung banks on JavaScript, Node.js for IoT](http://www.infoworld.com/article/2953719/javascript/samsung-banks-on-javascript-node-js-for-iot.html?utm_source=io.js+and+Node.js+News&utm_medium=article), as reported by [Paul Krill](https://twitter.com/pjkrill), editor at large at [InfoWorld](http://www.infoworld.com/).                                                                                              locale/en/blog/weekly-updates/weekly-update.2015-08-14.md:34:170:* [David Walsh](https://twitter.com/davidwalshblog) has written about [using yargs to get Node.js command line arguments](http://davidwalsh.name/nodejs-arguments-yargs/?utm_source=io.js+and+Node.js+News&utm_medium=article).                                                                        locale/en/blog/weekly-updates/weekly-update.2015-08-14.md:35:37:* [Reindex](https://www.reindex.io/?utm_source=io.js+and+Node.js+News&utm_medium=article) has a post about [building a GraphQL server with Node.js and SQL](https://www.reindex.io/blog/building-a-graphql-server-with-node-js-and-sql/?utm_source=io.js+and+Node.js+News&utm_medium=article)
locale/en/blog/weekly-updates/weekly-update.2015-08-14.md:36:131:* [Amine Kabab](https://twitter.com/aminekabab) made [a QR code generator library for Node.js](https://github.com/kabab/qr-cairo/?utm_source=io.js+and+Node.js+News&utm_medium=article)
locale/en/blog/weekly-updates/weekly-update.2015-08-14.md:46:39:* [Nodevember](http://nodevember.org/?utm_source=io.js+and+Node.js+News&utm_medium=article), November 14th - 15th at Nashville, Tennessee, US.
locale/en/blog/weekly-updates/weekly-update.2015-08-21.md:60:39:* [Nodevember](http://nodevember.org/?utm_source=io.js+and+Node.js+News&utm_medium=article), November 14th - 15th at Nashville, Tennessee, US.
locale/en/blog/weekly-updates/weekly-update.2015-08-28.md:88:39:* [Nodevember](http://nodevember.org/?utm_source=io.js+and+Node.js+News&utm_medium=article), November 14th - 15th at Nashville, Tennessee, US.
locale/en/blog/weekly-updates/weekly-update.2015-09-04.md:68:39:* [Nodevember](http://nodevember.org/?utm_source=io.js+and+Node.js+News&utm_medium=article), November 14th - 15th at Nashville, Tennessee, US.
locale/en/blog/weekly-updates/weekly-update.2015-09-11.md:76:39:* [Nodevember](http://nodevember.org/?utm_source=io.js+and+Node.js+News&utm_medium=article), November 14th - 15th at Nashville, Tennessee, US.
locale/en/blog/weekly-updates/weekly-update.2015-09-18.md:51:39:* [Nodevember](http://nodevember.org/?utm_source=io.js+and+Node.js+News&utm_medium=article), November 14th - 15th at Nashville, Tennessee, US.
locale/en/blog/weekly-updates/weekly-update.2015-10-02.md:64:39:* [Nodevember](http://nodevember.org/?utm_source=io.js+and+Node.js+News&utm_medium=article), November 14th - 15th at Nashville, Tennessee, US.
locale/en/blog/weekly-updates/weekly-update.2015-10-09.md:56:39:* [Nodevember](http://nodevember.org/?utm_source=io.js+and+Node.js+News&utm_medium=article), November 14th - 15th at Nashville, Tennessee, US.
locale/en/blog/weekly-updates/weekly-update.2015-10-16.md:46:39:* [Nodevember](http://nodevember.org/?utm_source=io.js+and+Node.js+News&utm_medium=article), November 14th - 15th at Nashville, Tennessee, US.
locale/en/blog/weekly-updates/weekly-update.2015-10-23.md:64:39:* [Nodevember](http://nodevember.org/?utm_source=io.js+and+Node.js+News&utm_medium=article), November 14th - 15th at Nashville, Tennessee, US.
locale/en/blog/weekly-updates/weekly-update.2015-10-30.md:45:39:* [Nodevember](http://nodevember.org/?utm_source=io.js+and+Node.js+News&utm_medium=article), November 14th - 15th at Nashville, Tennessee, US.
locale/en/blog/weekly-updates/weekly-update.2015-11-06.md:43:39:* [Nodevember](http://nodevember.org/?utm_source=io.js+and+Node.js+News&utm_medium=article), November 14th - 15th at Nashville, Tennessee, US.
```

### PR DESCRIPTION
**Pull request by XhmikosR**
Refs #2682 

Needs a PR in nodejs/build to redirect these. Maybe to the blog index page?

### CODE REVIEW

**Comment by nschonni** [comment]
I'm wondering if these should remain (but removed from the site map) or even collapsed down to a single archive page

**Comment by bnb** [comment]
I am a hard -1 on removing content from the site. Having historical context is important for reference.

**Comment by Trott** [comment]
> I am a hard -1 on removing content from the site. Having historical context is important for reference.

@bnb I'd be closer to that position if we weren't so liberal about adding things to the website all the time. It's a sprawling mess and keeping low-quality content around makes the site seem less credible, and can make it harder to find the high-quality content.

Still, there's something to be said about making sure that URLs don't break, etc. This will be a lot of work, but how would you feel about it if we did this:

Replace each page with some boilerplate text along the lines of "This content is unmaintained. It may be out-of-date or otherwise incorrect. To view this content, please use the following URL: " And then provide a link/URL to the content at the Internet Archive. By linking to the Internet Archive, it sends the clear message of "This is how the content appeared on a certain date in the past and we are not updating it." That also helps reduce the maintenance burden on content. For example, if we introduce a new markdown lint rule, we don't have to update these 70+ markdown files anymore.

**Comment by Trott** [comment]
> Replace each page with some boilerplate text along the lines of "This content is unmaintained. It may be out-of-date or otherwise incorrect. To view this content, please use the following URL: " And then provide a link/URL to the content at the Internet Archive. By linking to the Internet Archive, it sends the clear message of "This is how the content appeared on a certain date in the past and we are not updating it." That also helps reduce the maintenance burden on content. For example, if we introduce a new markdown lint rule, we don't have to update these 70+ markdown files anymore.

It also means the removal of tedious translation tasks, allowing people to focus on translating the higher-value material.

There are probably several other benefits I'm not thinking of. But let's summarize that in this case, maybe less is more?

**Comment by Trott** [comment]
Oh, one more thing: I don't know for a fact, but I strongly suspect that content like this is very likely to be eliminated if the website redesign ever finishes. (Did that thing totally stall and I should stop feeling like it's ever going to happen?)

**Comment by bnb** [comment]
@trott If we are going to approach removing old / stale content, I’d prefer that we do so in a way that is consistent across all content - i.e. once things are a year old move them into this state of archival.

Moving that stale content into to a directory where we’re expressly not going to lint or maintain it and then doing the same dynamic linking that we’d need to do with the solution you proposed with the internet archive would be a reasonable solution to me.

Perhaps another similar alternative is that we do the same thing with the slugs and internet archive link, but also include the original markdown source - without rendering it - as a pre+code block.

The thing I would really want to see is for us to retain this content in some meaningful, first-party format - even if it’s completely unmaintained and that state is expressly asserted.

**Comment by XhmikosR** [comment]
How about we just remove the script and keep the content for now? Although it's outdated.

**Comment by XhmikosR** [comment]
@Trott @bnb how about https://github.com/nodejs/nodejs.org/pull/2688#issuecomment-565763619?

**Comment by Trott** [comment]
> How about we just remove the script and keep the content for now? Although it's outdated.

You mean download.js? Yeah, I'd be fine with that. We can revisit what to do with the content here. Hey, @nodejs/website-redesign! Are you folks still active? If so, what's the plan for these old io.js-era newsletter-y things on the new site? They're not going to exist there, are they?

**Comment by XhmikosR** [comment]
Cool, I'll just remove the script and keep the content for now. I'll open a new issue to track this after this is merged.

**Review by Trott — APPROVED** [review]

**Pull request merged**
