### PR TITLE
ko: update translation of 'nodejs-docker-webapp.md'

### PR DESCRIPTION
**Pull request by yous**
Ref #1476, #2080.

You may want to view the whole file because the comments have been updated without the updates of translation.

@nodejs/nodejs-ko Review please.

### CODE REVIEW

**Comment by yous** [comment]
I can't assign `@nodejs/nodejs-ko` as reviewers, are there some limitations?

**Comment by Maledong** [comment]
@nodejs/nodejs-ko：Please have a review, thanks!

**Comment by Maledong** [comment]
@nodejs/nodejs-ko：Would you mind adding @yous into the team so that he can refer you successfully ?

**Comment by yous** [comment]
Actually I’m in the team now, but I’m not available to assign them as reviewers when I make a new PR.

**Review by outsideris — APPROVED** [review]

**Comment by taggon** [comment]
Can we use ‘작업 디렉터리’  instead of ‘워킹 디렉터리’?

**Comment by yous** [comment]
Sure, I've updated.

**Comment by ghost** [comment]
@taggon：Can you confirm whether it's OK? You can merge it if possible :)

**Review by taggon — APPROVED** [review]
LGTM 👍 Thanks!

**Comment by yous** [comment]
Thanks all!

**Pull request merged**
