### PR TITLE
Deleted Forrester report

### PR DESCRIPTION
**Pull request by ZibbyKeaton**
I thought I had deleted the Forrester report before, but it doesn't appear that it went through. The report is no longer available, so I would like to eliminate any reference of it on the Foundation tab.

### CODE REVIEW

**Review by refack — APPROVED** [review]

**Review by daxlab — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by maclover7 — APPROVED** [review]

**Comment by fhemberger** [comment]
Please, everyone: If on or two contributors approve a change and there's no further discussion, just go ahead and merge it.

**Comment by refack** [comment]
> Please, everyone: If on or two contributors approve a change and there's no further discussion, just go ahead and merge it.

Is the code auto promoted to the site?

**Comment by fhemberger** [comment]
@refack Yes, might take a few minutes due to CDN caching.

**Pull request merged**
