### PR TITLE
Remove Fidelity logo

### PR DESCRIPTION
**Pull request by lpinca**
This removes Fidelity Logo.
Ref: https://github.com/nodejs/nodejs.org/commit/ae8c9dc5ed8f53d36eb5f56c5dda6e52bce7bda7

### CODE REVIEW

**Comment by lpinca** [comment]
@nodejs/website ping.

**Comment by mikeal** [comment]
Hold off on this, we're pretty sure that it will end up going back up.

**Comment by williamkapke** [comment]
It was removed almost a month ago. I say delete it- it's easy to put it back.

Or, if we really want to just hold off, then lets say "Hold off for 2 weeks"... just to time box it and avoid PRs sitting endlessly without any way to know a potential completion date.

**Comment by zlatanvasovic** [comment]
Any news on this?

**Comment by mikeal** [comment]
We need to put their logo back up now, the background legal stuff has been resolved.

**Pull request closed without merging**
