### PR TITLE
testing nodejs-github-bot please ignore

### PR DESCRIPTION
**Pull request by Fishrock123**

### CODE REVIEW

**Comment by Fishrock123** [comment]
Ok something is not working right with the travis config on this repo in particular. I'm going to totally disable travis here and re-configure it.

**Comment by Fishrock123** [comment]
🎉 🎉 🎉 🎉 🎉

**Comment by Fishrock123** [comment]
Nada, commit statuses from the bot still aren't working here because there's some odd discrepancy in how travis works on this repo. :/

**Comment by stevemao** [comment]
Since when it stopped working?

**Comment by phillipj** [comment]
@stevemao we tried to indicate build status via github PR statuses, just like Travis CI normally would do. It work perfectly in the nodejs/citgm repo, but not here :( Ended up going back to the bot creating comments again til we figure it out

**Comment by stevemao** [comment]
Sorry, I should stop asking about travis...

**Comment by Fishrock123** [comment]
I tried to contact travis support last night, we'll see if they respond I guess.

**Pull request closed without merging**
