### PR TITLE
README: fixed git clone link

### PR DESCRIPTION
**Pull request by Knighton910**
The old one wasn't working.

### CODE REVIEW

**Comment by stevemao** [comment]
@lordKnighton Why is it not working? Did you setup your ssh properly?

**Comment by fhemberger** [comment]
@stevemao Old link was also working fine.

@lordKnighton Please don't PR+merge in one step, give others the time to comment and give feedback as well.

**Comment by stevemao** [comment]
Hm... I prefer to use ssh as I have two factor enabled. But it could just simply say "clone the repo" here.

**Comment by ghost** [comment]
@stevemao i think it's better as setting up ssh is harder than just cloning it from https. it lowers the entry barrier by a bit

**Comment by lpinca** [comment]
It's really subjective and I also prefer to use ssh but @hg has a point here.

**Pull request merged**
