### PR TITLE
Added Nodenv to package-manager list

### PR DESCRIPTION
**Pull request by monarchwadia**
Nodenv is an alternative to NVM, and is used fairly widely. See https://github.com/nodenv/nodenv. Would like to have it added to the package-managers list as per https://github.com/nodenv/nodenv/issues/157

### CODE REVIEW

**Comment by Trott** [comment]
An entry needs to be added to the table of contents.

**Comment by monarchwadia** [comment]
Done @Trott

**Comment by Trott** [comment]
Is Nodeenv represented on @nodejs/version-management? Is that team still active?

Oh, hi, @nodejs/version-management, you can probably review this PR, yeah?

**Review by ljharb — APPROVED** [review]
The team is very much still active.

id dispute that nodenv is used “widely” but i also don’t think popularity has any bearing on this list, once above a threshold that nodenv has objectively surpassed.

**Review by Trott — APPROVED** [review]

**Comment by Trott** [comment]
Aside: The list here is almost-but-not-quite in alphabetical/lexical order. If someone wants to submit a PR to get it in exactly alphabetical/lexical order, that would be great.

**Comment by jasonkarns** [comment]
> Is Nodeenv represented on @nodejs/version-management?

We (nodenv) are now! 😸  https://github.com/nodejs/version-management/pull/23

**Pull request merged**
