### PR TITLE
Tweak language toggler

### LINKED ISSUE #2545: Switch lang-picker-toggler to a button
Should be better for accessibility and we will probably simplify a few things.

I'll take a stab at it in the next days.

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #2545

### CODE REVIEW

**Comment by XhmikosR** [comment]
@moshfeu please try this branch. Live preview: <https://affectionate-almeida-a9f620.netlify.com/en/>

It might need some further styling tweaks, but I think it's a big improvement already. In order for <kbd>ESC</kbd> to close the menu, well need more JS to handle this, but let's leave it for later.

/CC @nodejs/website (not sure if I can CC you guys, probably not)

**Review by moshfeu — APPROVED** [review]
Looking very good to me.
If they will take that PR (I hope so), it will worth to keep improve this component.

**Comment by XhmikosR** [comment]
Maybe I should wrap the `ul` in a `nav`?

**Comment by moshfeu** [comment]
It's very opinion based but I spoke with accessibility expert some time ago and he actually didn't recommended to use `nav` because it's not a navigation action but sort of setting a configuration action. It's not a **different** page but the **same** page with different view.

The code also says something like that. Navigation will keep a record in the history, while the code **replace** the record:

https://github.com/nodejs/nodejs.org/blob/2026c6ab726e839b3a4f5be16fe837ed99956673/layouts/partials/header.hbs#L61

**Comment by XhmikosR** [comment]
That's something that needs to change BTW, see #2541.

**Comment by XhmikosR** [comment]
Anyway, I'll freeze the changes for now so that this can be reviewed. I also dropped one data attribute and used `textContent` which works for IE9+.

**Comment by moshfeu** [comment]
> That's something that needs to change BTW, see #2541.

I'm not sure :) But let's see what they will decide..

**Comment by Trott** [comment]
@nodejs/website Reviews?

**Review by 3imed-jaberi — COMMENTED** [review]
Thank you @XhmikosR, 
I understand that you want to simplify the code but I think that these chnages aren't necessary, they are simple by nature ...

**Comment by XhmikosR** [comment]
Please try and understand the changes. This makes the language toggler way more accessible and keyboard navigateable.

**Comment by moshfeu** [comment]
@3imed-jaberi try to switch a language without the mouse, only keyboard.

**Review by 3imed-jaberi — APPROVED** [review]
For accessibility 👍

**Comment by alexandrtovmach** [comment]
Looks good to me

**Review by alexandrtovmach — APPROVED** [review]

**Review by osk2 — APPROVED** [review]
LGTM

**Review by Aissaoui-Ahmed — APPROVED** [review]
Great 💯

**Pull request merged**
