### PR TITLE
Use a smaller image for the header logo

### PR DESCRIPTION
**Pull request by lpinca**
This reduces the size of the logo used in the header.
The new size is 245 x 150 which is 2x (for retina displays) the maximum size the image can be.
The image has been compressed with ImageOptim.

### CODE REVIEW

**Comment by ghost** [comment]
LGTM

**Comment by fhemberger** [comment]
Compressed the image … LGTM

**Comment by lpinca** [comment]
I think it's possible to shave some more bytes with zopflipng 😄.

**Comment by silverwind** [comment]
LGTM. It'd be awesome if it were a SVG, but I don't suppose a vector source image is available?

**Comment by lpinca** [comment]
@silverwind there is a vectorial version (`nodejs-new-pantone-white.ai`) which could serve the purpose.

**Comment by lpinca** [comment]
I tried to convert `nodejs-new-pantone-white.ai` to SVG with Inkscape but the colors look different. Here is the result https://dl.dropboxusercontent.com/u/58444696/nodejs-new-pantone-white.svg.

Can someone try with Illustrator?

**Comment by silverwind** [comment]
I too only have inkscape available, but it seems the dull colors are there in the source .ai as well. Below is an attempt at conversion, I'd wager the gradient `<stop>`s could be removed completely, so it's a WIP at best.

**Comment by silverwind** [comment]
https://github.com/nodejs/nodejs.org/pull/884 for my version of the logo.

**Pull request merged**
