### PR TITLE
Added Travis build status badge in readme

### PR DESCRIPTION
**Pull request by phillipj**
Needed sooner or later as someone hopefully writes the first set of tests + addresses the enforcing part of the codestyle linting discussed in #157.

### CODE REVIEW

**Comment by phillipj** [comment]
@nodejs/website shipable or a bad idea?

**Comment by fhemberger** [comment]
Well, at the moment, we don't have any code to test on Travis CI, and linting may soon be replaced by JS "standard".

**Comment by phillipj** [comment]
So we dont want to run standard linting with Travis?

**Comment by fhemberger** [comment]
I think [pre-commit](https://npmjs.org/package/pre-commit) is a better way to handle this.

**Comment by phillipj** [comment]
Hmmm, got to admit I'm no hooks-fan as it will always leave room for someone to not have them in place, even with that pre-commit dependency in place since we cant enforce `$ npm install` on people.

I would be more than happy to have non-critical things run as a hook, such as **only** code style checking. standard does more than that though, checking for undefined variables etc which could cause serious issues.

**Comment by fhemberger** [comment]
Well, if you want to build and test your changes, you have to `npm install` at one point. Even if someone doesn't do this and their PR gets accepted, the following commit (hopefully) will trigger `standard`. I have created a PR for that: #172. 

At the moment, the site is deployed on commit. So even if you have a "failing" travis badge, this would not stop the site from being deployed, unless we use the deploy hook on Travis CI (@rvagg is it possible to use that for the site without much of a hassle?)

So ideally, we could also combine our two PRs.

**Comment by phillipj** [comment]
Good point about any commit triggering a deploy anyway. Possibly using Travis webhooks would be great :+1:

**Comment by rvagg** [comment]
uh, I've never tried, I have [github-webhook](https://github.com/rvagg/github-webhook) that we're using for nodejs.org and iojs.org but don't have anything similar for travis

**Comment by fhemberger** [comment]
We could use the `after_success` step (http://docs.travis-ci.com/user/customizing-the-build/) to trigger `github-webhook` in this case. Necessary secrets can be stored encrypted in `.travis.yml`: http://docs.travis-ci.com/user/encryption-keys/

**Comment by phillipj** [comment]
FYI keeping this open as I'm writing some tests for `./scripts/release-post.js` ATM which could benefit from this.

**Comment by fhemberger** [comment]
Cool. If you're done with the tests, can you take a look at the merge conflict, so we can get this merged?

**Comment by phillipj** [comment]
Absolutely! Will fix it as soon as #193 lands :)

**Comment by phillipj** [comment]
> Absolutely! Will fix it as soon as #193 lands :)

On second thought, I pushed a fix now as we dont need to alter `package.json` anymore, which avoids further conflicts.

**Comment by fhemberger** [comment]
As #193 gives us tests to run for the first time (yay!), I'm merging this as well. Thanks!

**Comment by phillipj** [comment]
🎉

@mikeal does the nodejs org have Travis CI credentials to hook this up?

**Comment by mikeal** [comment]
@phillipj it would be the @nodejs/build WG that would have those credentials.

**Comment by phillipj** [comment]
Awesome! Could anyone in @nodejs/build with permission to this repo, please enable the Travis CI service?

**Comment by rvagg** [comment]
doesn't need @nodejs/build afaik, everyone here with "Owner" should be able to do this if you just log in to Travis. I've done it now, see if it works.

**Pull request merged**
