### PR TITLE
Make dark scroll bar in dark theme

### PR DESCRIPTION
**Pull request by rakleed**
Make dark scroll bar in dark theme

### CODE REVIEW

**Comment by Trott** [comment]
I'm not seeing anything different with this change. Can you share a screenshot showing the before/after and indicate what browser/OS you're using?

**Comment by rakleed** [comment]
I'm new to SCSS, but I've built it, fixed it, and now it works.

You need a Chromium-based browser and that the scroll bar is always displayed (there should be such an option in the system settings).

<details>
<summary>Before</summary>

image

</details>

<details>
<summary>After</summary>

image

</details>

**Review by ovflowd — APPROVED** [review]
LGTM!

**Comment by ghost** [comment]
Thank @rakleed for your contribution to UI, it looks nicer.

**Pull request merged**
