### PR TITLE
doc: Add the missing versions of Nodejs APIs' links

### PR DESCRIPTION
**Pull request by ghost**
1) Missing the v8, v9 links of doc.
2) Fix the site.json in `fa`, add `rtl` and `locale` attributes.

### CODE REVIEW

**Comment by ghost** [comment]
Notice: This can be postponed until Nodejs 8.x is retired from LTS in maintance state, because I've
added Nodejs 8.x as a previous version.

**Review by lpinca — APPROVED** [review]

**Review by ZYSzys — COMMENTED** [review]
How about adding v10 too ?

**Comment by ghost** [comment]
@ZYSzys：

Good question!

Nodejs v10.X will be the active LTS since 2018-10-30 (See：https://github.com/nodejs/Release#release-schedule). So it shoudn't be a previous version in my mind.

But what confuses me is：Since 2018-10-30 v10 will take place of v8.X, will v8.X be the previous version? I have to put it there but as you know, v8 at that time is still in Active LTS……So how to cope with two versions of Nodejs (both v8 and v10 will be ACTIVE LTS after Oct 2018)?

together

**Comment by lpinca** [comment]
Node.js 10 will be shown on the left side so it doesn't make sense to add it.

There will be 11 and 10 here:

screen shot 2018-10-28 at 11 19 18

**Comment by Maledong** [comment]
@Ipinca：Thanks! do you mean both v8.X and v10.X will be shown together at `doc`?
image
If yes, there's no need to add 8.x or 10.x, but just 9.x :)

**Comment by Maledong** [comment]
@lpinca : OK, I'll do changes and submit after v10.x becomes to the active LTS. Thanks again!

**Comment by lpinca** [comment]
@Maledong keep it as is. It's how it should be as soon as 10 will be tagged as LTS.

**Comment by ghost** [comment]
@lpinca：OK, So now I'll keep v8 in the previous list :)

**Comment by ghost** [comment]
Since the latest release of Nodejs 10.x has come. So I'll push this PR :)

new

**Pull request merged**
