### PR TITLE
Add to learning

### PR DESCRIPTION
**Pull request by weg2g**
Adding high school technology services

### CODE REVIEW

**Review by Trott — CHANGES_REQUESTED** [review]
Thanks for the pull request! This list of resources should not be a laundry list. It should be the top 3-5 resources available. (Actually, in my opinion, it should just be removed, but I'm probably in the minority on that.) I'm disinclined to see anything added that isn't already well-established.

**Comment by weg2g** [comment]
Thanks for your response and I understand your concerns and my org is an Associate member of The Linux Foundation, OSI, Python foundation, and more. We are also authorized trainer providers with The Linux Foundation. I also spoke with head of Node foundation on incorporating Node certification in our training and they are going to discuss it in BOD in this fall for partnering with my org. No worry, I list my org there after BOD meeting in fall anyway.

**Comment by MylesBorins** [comment]
@weg2g can you expand on who specifically you talked to and what the outcome was?

**Comment by weg2g** [comment]
@MylesBorins I talked with Rick Trott. I told him that my org is a member of The Linux Foundation. Also, I told him that I am in talk with NodeJS Foundation top management for offering NodeJS certification classes. Anyway, It seems that my request is still on hold.

Also, we submitted a project for custom RESTful API with Node.JS for your showcase page, yet I did not email confirmation or response. I can not see it on https://foundation.nodejs.org/resources/app-showcase
Can you double check? Thx, Matt

**Comment by MylesBorins** [comment]
@weg2g the Node.js Foundation merged with the js foundation and is now known as the OpenJS foundation. We have had changes in leadership in the last year. Who specifically were you talking to so I can follow up with them (fwiw I sit on the board).

**Comment by weg2g** [comment]
@MylesBorins I spoke with Brian Warner for joining my NodeJS foundation as a member. He said that the NodeJS certification will be released in this Fall. He said that if BOD agree on offering training for Node certification, then there is a possibility that my org will provide training for your foundation as an independent contractor. 

My discussion with Brian has nothing to do this Pull Request, so pls remove my pull request. I also add u in my LI connection. Thx

**Pull request closed without merging**
