### PR TITLE
downloads: add macOS ARM64 link for current version.

### LINKED ISSUE #3811: Missing link for Apple Silicon (arm64) on download page
Starting with v16.0.0, we have official Apple Silicon tarballs.
It should be available on https://nodejs.org/en/download/current/

### PR DESCRIPTION
**Pull request by XhmikosR**
image

Fixes #3811

---

I used `versionTypeCurrent` so this will only show up for Node.js 16.x.

### CODE REVIEW

**Comment by richardlau** [comment]
Might it look more compact to have a single "macOS Binary (.tar.gz)" row with two columns ("x64" and "ARM64" (or even "Apple Silicon" as that is what Apple call it))?

**Comment by XhmikosR** [comment]
Yeah, I'm not sure about naming so let me know what you prefer.

As for using a row with two columns, it doesn't sound bad. I could switch
to that if everyone agrees.

**Review by MylesBorins — APPROVED** [review]
LGTM

**Comment by targos** [comment]
I'd prefer two columns

**Comment by XhmikosR** [comment]
I switched to a two-column row.

Let me know about the text. I went with ARM64 but I'm not very familiar with macOS myself.

**Review by richardlau — APPROVED** [review]
I fine with either "ARM64" or "Apple Silicon".

**Pull request merged**
