### PR TITLE
header.hbs: Fix wrong logo width

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Can we get this merged?

**Comment by Trott** [comment]
@nodejs/website

**Comment by phillipj** [comment]
@XhmikosR mind elaborating a bit? Wrong, how/why?

**Comment by XhmikosR** [comment]
The SVG has these:

```
width="589.827" height="361.238" viewBox="0 0 442.37 270.929"
```

So a ratio of 1.6327. 180/75 = 2.4.

If you notice the current image, it has blanks to the right and left; it's due to this.

So, this just makes sure we use the right width.

**Comment by phillipj** [comment]
Great explanation, much appreciated 👏

**Review by phillipj — APPROVED** [review]
LGTM

**Review by alexandrtovmach — APPROVED** [review]

**Comment by phillipj** [comment]
@XhmikosR you want to get in sync with master by rebasing and force push? Based on my previous experience with your PRs, I'm assuming you want as clean git commit history as possible. If not, give me a wink and I'll use GitHub's UI to merge the latest changes from master into this branch.

**Comment by XhmikosR** [comment]
@phillipj: now the option for branches to be up to date is enabled for the repo, so this is no longer an issue :)

When I have one commit I usually prefer squash and merge so that the PR number is included in the commit.

**Comment by phillipj** [comment]
> now the option for branches to be up to date is enabled for the repo, so this is no longer an issue

And as clicking that button on the GitHub UI which "updates" the branch, will cause a merge-commit from master into this branch, there will be more commits than you've created yourself. Since you've been _very explicit_ multiple times about collaborators not squashing your commits before merging, I asked you beforehand.

Also would much rather prefer if we came to a consensus about squashing, rebasing etc and documented in [COLLABORATOR_GUIDE.md](https://github.com/nodejs/nodejs.org/blob/master/COLLABORATOR_GUIDE.md), similar to what is found in [nodejs/node/COLLABORATOR_GUIDE.md](https://github.com/nodejs/node/blob/master/COLLABORATOR_GUIDE.md#landing-pull-requests).

**Comment by XhmikosR** [comment]
@phillipj that's correct, but if you choose "Rebase and Merge" there will be no merge commits.

Personally, I have the Merge option disabled in the repo settings.

**Pull request merged**
