### PR TITLE
Add "Node.js • Apprendre par la pratique" French book

### PR DESCRIPTION
**Pull request by thom4parisot**
This is a proposition to add a new resource, available only in French, which is free online (on the web and on npm) but paid as a print and ebook copy.

I guess it calls 2 discussions, one with the @nodejs/nodejs-fr team for the content and @nodejs/website for the legitimacy of the content. Here is its meaning in English:

> [Node.js • Learning by doing](https://oncletom.io/node.js/) is a book to learn Node.js step by step, published by Éditions Eyrolles. Its source code is open; it is free to read online; the paper and ebook copies are paid.

_Disclaimer_: I have written the book.

### CODE REVIEW

**Review by abenhamdine — APPROVED** [review]

**Comment by thom4parisot** [comment]
Okay.

I'm also happy to reference more french-specific materials, in this PR or another one (as long as they are free content? What are the criterias to list a resource on this page, actually?).

**Comment by fhemberger** [comment]
@oncletom Regarding "what are the criteria", I'm linking this issue here as well:
https://github.com/nodejs/nodejs.org/pull/1964#issue-241194608

(i.e. Yes, we need to define which content should be listed on that page.)

**Comment by ghost** [comment]
@fhemberger: Can this be merged?

**Comment by fhemberger** [comment]
@Maledong Yes, sure.

**Pull request merged**
