### PR TITLE
Change "Discussion" to "Community Discussion"

### PR DESCRIPTION
**Pull request by bnb**
Per a discussion in the Moderation team meeting today, changing "Discussion" to "Community Discussion" enables a little bit more of a permissive and clear definition to what is included in this section.

cc @hackygolucky @nodejs/moderation

### CODE REVIEW

**Review by fhemberger — APPROVED** [review]

**Comment by fhemberger** [comment]
/cc
@nodejs/nodejs-es - Discusión comunidad
@nodejs/nodejs-fr - Discussion communauté
@nodejs/nodejs-uk - спільноти Обговорення
Catalan - Discussió comunitat

Can you please confirm my Google Translate powers? 😉

**Comment by yoannmoinet** [comment]
For the French one I'd say something like "Discussion de la communauté". 

Or "Discussion communautaire" that I like a little less though. 

I'll let my fellow French friends have another opinion on this.

**Comment by cedced19** [comment]
Yes "Discussion de la communauté" seems to be good after a little reflection.

**Comment by academo** [comment]
For Spanish I would go for something like "Discusiones de la comunidad" or "Discusión de la comunidad". The last one (singular) sounds a bit weird for me because sounds like only one discussion is going on.

Other Spanish speakers may as well confirm if they agree with it.

**Comment by bithavoc** [comment]
@academo how about `Discusión Comunitaria` for Spanish

**Comment by academo** [comment]
@bithavoc that sounds very good indeed.

**Comment by Tsuna-mi** [comment]
For spanish seems good to me 'Discusión de la comunidad' 
and for catalan 'Discussió de la comunitat'

**Comment by hackygolucky** [comment]
Will approve once the other language markdown is added!

**Comment by fhemberger** [comment]
@bnb Can you please update the PR with the translations?

**Comment by fhemberger** [comment]
Updated the translations, @bnb @hackygolucky, can this be merged now?
(BTW: I didn't change the Ukrainian translation, leave this to @nodejs/nodejs-uk.)

**Comment by vsemozhetbyt** [comment]
As for Ukrainian translation: `## Обговорення` -> `## Громадське обговорення` seems OK.

**Comment by fhemberger** [comment]
@vsemozhetbyt Thanks, added!

**Review by vsemozhetbyt — APPROVED** [review]

**Comment by bnb** [comment]
Looks like this can be updated, apologies for not getting back to this sooner @fhemberger!

**Comment by fhemberger** [comment]
Ok, merged.

**Pull request merged**
