### PR TITLE
style: make sidebars sticky

### PR DESCRIPTION
**Pull request by arthurjdam**
## Description

Make sidebars "sticky" to the browser top, making it accessible when scrolled partially or entirely down the page

## Validation

When scrolling down the page, sidebars should remain visible:
image

On mobile, layout should be unaffected:
image

## Related Issues

Addresses #7122 

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by mikeesto** [comment]
I'm not sure that I like how the left sidebar is also sticky. It means we need to scroll down to the bottom of every page to see the Modules/Diagnostics/Test Runner pages. Would be interested to hear others thoughts

**Review by ovflowd — CHANGES_REQUESTED** [review]
I don't think this is a good change, sorry. The current layout is more suited for our needs. Thanks for the contribution tho!

**Comment by AugustinMauroy** [comment]
> I don't think this is a good change, sorry. The current layout is more suited for our needs. Thanks for the contribution tho!

the original issue was just to put the ToC in sticky so that it's always handy in the desktop. Which I don't think is too bad, but I don't think the lef nav should be stiky.

**Comment by arthurjdam** [comment]
That's fair. Updated to only make the Metabar sticky, but not the other bars

**Review by ovflowd — APPROVED** [review]

**Comment by ovflowd** [comment]
Thanks for the contribution ✨ -- appreciate your time!

**Pull request merged**
