### PR TITLE
Update board.md

### PR DESCRIPTION
**Pull request by gtewallace**
remove Gianugo as Secretary, add Colleen Evans as Director from Microsoft

### CODE REVIEW

**Comment by lpinca** [comment]
LGTM, maybe we can use a more descriptive commit message when landing.

**Comment by ghost** [comment]
LGTM, i agree with @lpinca. @gtewallace could you amend or rebase this commit to make the commit message more descriptive?

**Comment by lpinca** [comment]
@Lac does "Remove Gianugo Rabellino and add Colleen Evans to board.md" sounds good to you?

**Comment by ghost** [comment]
@lpinca yep, that'll do

**Comment by lpinca** [comment]
Ok, I guess we can squash merge and edit the message so @gtewallace doesn't have to do this.

**Comment by ghost** [comment]
go ahead!

**Comment by gtewallace** [comment]
Hi All,

thank you so much for getting on this so quickly - I'm just getting online this saturday morning and seeing your comments - I'll be sure to do a better job with my commit notes in the future.

thanks again!

**Pull request merged**
