### PR TITLE
translations: fix missing header ID `enabling-remote-debugging-scenar…

### PR DESCRIPTION
**Pull request by XhmikosR**
…ios`.

Note that I didn't update the files I have open PRs to remove. Also, there are probably more cases like this, I just happened to stumble upon this one.

### CODE REVIEW

**Review by Aissaoui-Ahmed — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by Trott** [comment]
HTML comments become header ids for linking? How did I not already know this??!!

**Comment by ghost** [comment]
@Trott, This is a feature done by me, because as you know, non-English characters WON'T generate any id in English alphabets, so we should support non-English characters to generate their IDs.
Here's the link：https://github.com/nodejs/nodejs.org/pull/2045, Maybe you have forgotten ;)

**Comment by Trott** [comment]
Now I'm curious: What was the reason for processing HTML comments rather than putting `a` tags directly in the markup? `<a name="foo"></a>`

**Comment by Trott** [comment]
> Now I'm curious: What was the reason for processing HTML comments rather than putting `a` tags directly in the markup? `<a name="foo"></a>`

Answering my own question: Maybe it's to generate `id` attributes in the header elements rather than using `a` elements.

**Comment by XhmikosR** [comment]
For what is worth name is deprecated. An ID should be used.

That being said, my guess would be so that the anchor targets directly the
header element and not add empty elemements for this purpose.

**Pull request merged**
