### PR TITLE
Add DEV Community link to get involved page [EN/PT-BR]

### PR DESCRIPTION
**Pull request by fernandomaia**
This PR expands the International community sites and projects section on Get involved page (both EN and PT-BR) by adding [Node.js tag on DEV](https://dev.to/t/node). DEV is a platform for software developers to share articles and participate in discussions regarding software topics, and it's a good resource for Node.js related topics.

Some great posts examples can be checked below:

[Bulletproof node.js project architecture 🛡️](https://dev.to/santypk4/bulletproof-node-js-project-architecture-4epf)
[Everything you need to know about Node.js](https://dev.to/jorge_rockr/everything-you-need-to-know-about-node-js-lnc)

### CODE REVIEW

**Comment by XhmikosR** [comment]
Shouldn't this be added in all translated `get-involved/index.md` files?

**Comment by Trott** [comment]
This link already exists on the page under Learning.

**Comment by Trott** [comment]
Although it looks like the pt-br page can/should be synched up.

**Comment by fernandomaia** [comment]
Sorry @Trott, I didn't see it there and I though it would be more of a fit on the community section instead, so I just looked up there. It seems that the PT-BR version already has the same information regarding DEV Community.

**Comment by Trott** [comment]
> Sorry @Trott, I didn't see it there and I though it would be more of a fit on the community section instead, so I just looked up there. It seems that the PT-BR version already has the same information regarding DEV Community.

Oh, you're right, it's there too! Cool.

Thanks!

**Pull request closed without merging**
