### PR TITLE
adding additional information. sorting first, as we're active monthly and other meetup is no longer active.

### PR DESCRIPTION
**Pull request by mateodelnorte**

### CODE REVIEW

**Comment by Trott** [comment]
Could use some reviews. @nodejs/website

**Comment by MylesBorins** [comment]
Both meetups appear active on meetup.com, seems odd to change the order to me

**Comment by mateodelnorte** [comment]
Their last event was September 14, 2017. 

image

image

image

**Review by MylesBorins — APPROVED** [review]
LGTM

**Review by MylesBorins — APPROVED** [review]
LGTM

**Comment by MylesBorins** [comment]
Didn't click through to see year, thanks for your patience.

**Pull request merged**
