### PR TITLE
Add commitizen to repo to make it easy to follow conventional-commits

### PR DESCRIPTION
**Pull request by rikhall1515**
## Description
This makes it so that you only need to run 'git commit' in order to get conventional-commit compliant commits.

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by rikhall1515** [comment]
This is a re-open of [#6659](https://github.com/nodejs/nodejs.org/pull/6659) so I'm just currently waiting on this getting approved. Now this PR just has one single commit.

**Review by ovflowd — APPROVED** [review]
LGTM!

**Comment by ovflowd** [comment]
Thanks for your patience here and for iterating on this PR!

**Comment by bmuenzenmeyer** [comment]
The most critical workflow I want to ensure we don't change is the blog post release process. Has anyone tested that yet?

edit: Marco said this would not affect him

**Review by aymen94 — APPROVED** [review]

**Comment by ovflowd** [comment]
Alrighty, I believe we can merge this. If issues eventually rise, we can just revert and investigate :)

**Pull request merged**
