### PR TITLE
style(scss): Remove outline border from button

### PR DESCRIPTION
**Pull request by heithemmoumni**

### CODE REVIEW

**Comment by nschonni** [comment]
I'm not seeing what this would be used for. Usually you don't want to remove outlines for accessibility reasons, but I don't see a difference in the rendering when trying this with the dev tools in Firefox

**Comment by heithemmoumni** [comment]
cool, ok

**Comment by XhmikosR** [comment]
Yeah, definitely a bad practice to remove the outline unless the effect is replaced with something else.

I'll try to have a look in the next days.

FYI Firefox handles this differently hence why the issue is only visible on Chromium based browsers AFAICT.

**Comment by XhmikosR** [comment]
Alright, I tested this and like I said above, it's bad practice to do this.

**Pull request closed without merging**
