### PR TITLE
chore(build): use workers for less intensive memory usage

### PR DESCRIPTION
**Pull request by ovflowd**
This PR updates the build config to use a new experimental functionality of Next.js that parallelises the build process, reducing the max memory heap of Node.js.

### CODE REVIEW

**Comment by ovflowd** [comment]
Hey @nodejs/website, requesting `fast-tracking` of this PR. Please thumbs up for approval!

**Comment by mikeesto** [comment]
I think this is only available in 13.2.5-canary?

**Review by ghost — COMMENTED** [review]
Well……I tend to postpone this PR, because this is an experimental function and we don't know what will happen to it. Just like we don't suggestion using experimental functions directly in production mode.

My suggestion：**Hold it and release until this is to production:)**

PS: +1, it will be very nice function for Windows, for I'll wait for more than 10 mins to build the whole app with the help of building tools....

**Comment by ovflowd** [comment]
> I think this is only available in 13.2.5-canary?

Nope, it is on stable versions already.

**Comment by ovflowd** [comment]
> Well……I tend to postpone this PR, because this is an experimental function and we don't know what will happen to it. Just like we don't suggestion using experimental functions directly in production mode.

We know what's going to happen with it, or at least I do. Vercel directly recommended us to use this functionality to ease our memory pain. It is Experimental, but to be fair, this doesn't affect us (in the sense that by even being an experimental feature, there are no real risks involved here).

Note that this not necessarily improves build speed for now, but has good memory benefits.

**Comment by ovflowd** [comment]
> PS: +1, it will be very nice function for Windows, for I'll wait for more than 10 mins to build the whole app with the help of building tools....

Windows indeed takes longer, but shouldn't be more than 10 minutes. On our CI it takes 3 minutes. Don't forget, that Next.js has cached builds.

**Review by ghost — APPROVED** [review]
> Nope, it is on stable versions already.

Ok, it's fine for a stable version.

BTW: package-lock.json is changed, will 'package.json' is also changed?

**Comment by ghost** [comment]
> > PS: +1, it will be very nice function for Windows, for I'll wait for more than 10 mins to build the whole app with the help of building tools....
> 
> Windows indeed takes longer, but shouldn't be more than 10 minutes. On our CI it takes 3 minutes. Don't forget, that Next.js has cached builds.

Maybe my PC is too old....when I use 'npm build', it always takes me 6-10 minutes....
Hope your changes bring a new life for me XD

**Comment by ovflowd** [comment]
package-lock was updated because I've run "npm update" to update some of the dependencies.

**Comment by ovflowd** [comment]
Not sure if the change will speed the process up on windows but crossing fingers for you!

**Review by aymen94 — APPROVED** [review]

**Review by manishprivet — APPROVED** [review]

**Review by shanpriyan — APPROVED** [review]

**Pull request merged**
