### PR TITLE
Update how-to-use-crypto-module.md

### PR DESCRIPTION
**Pull request by Yash-Handa**
Hey @chowdhurian and @fhemberger,
In accordance with issue #1977, I have updated the Article **how-to-use-crypto-module** with the following changes:

*  Updates all links to the nodejs.org API`.
* Updated to `crypto.createCipheriv()` and `crypto.createDecipheriv()`.
* Updated the last example for `iv` support.
*  Changed `optimist` package with `yargs`.
* some other miscellaneous updates and refactors.

If there are any **suggestion/enhancement/tips** please feel free to tell me, I would love to incorporate those changes in this Article 😄

### CODE REVIEW

**Review by fhemberger — CHANGES_REQUESTED** [review]
I think instead of MD5 we should advocate SHA256 for hashing, and AES256 instead of 128. Just in case someone simply copies & pastes this code for something that needs to be secured properly. 😉

**Comment by fhemberger** [comment]
Otherwise, great work as always!

I'd love to have a second person reviewing the crypto code example, as I'm not very familiar with it in Node.js.

**Comment by Yash-Handa** [comment]
> I think instead of MD5 we should advocate SHA256 for hashing, and AES256 instead of 128. Just in case someone simply copies & pastes this code for something that needs to be secured properly. 😉

Fair enough, if we are providing an example it should be full-proof in every aspect.
Will update the example with `SHA256` and `AES256` 😎

**Review by ghost — APPROVED** [review]
LGTM

**Review by fhemberger — APPROVED** [review]

**Comment by fhemberger** [comment]
Thanks!

**Pull request merged**
