### PR TITLE
style: remove `\n` from “Hello World”

### PR DESCRIPTION
**Pull request by j9t**
Optimistic edit removing the line break from the sample text. Can edit this for other locales. Curious to learn more if this is deemed important here.

### CODE REVIEW

**Review by Trott — APPROVED** [review]

**Comment by Trott** [comment]
@nodejs/http

**Review by trivikr — APPROVED** [review]

**Comment by XhmikosR** [comment]
This would need to be backported to the translations. But I wonder, was there any reason for the newline in the first place?

**Comment by j9t** [comment]
> This would need to be backported to the translations.

Prepared with https://github.com/nodejs/nodejs.org/pull/2881.

**Comment by XhmikosR** [comment]
There's no need for a new PR... you can just make the changes to the same branch.

**Comment by j9t** [comment]
Good to go?

**Pull request merged**
