### PR TITLE
add one more code and learn event

### PR DESCRIPTION
**Pull request by watilde**
Hello!

We had a Code + Learn event at Tokyo Node Festival 2016. Let me add it to the list.

Merged commits:
```
$ git log --oneline --grep 'https://github.com/nodejs/code-and-learn/issues/58'
9927795 test: use setImmediate() in test of stream2
30bf123 doc: fix typo in doc/repl.md line: 6
63e889a test: add test case of PassThrough
195989d doc: fix typo e.g., => e.g.
8a78fcb test: change from setTimeout to setImmediate
a3dd943 doc: fix typo about cluster doc, (eg. -> e.g.)
9428854 doc: fix typo in doc/tls.md
8ca322d test: improve test-stream2-objects.js
7030f09 doc: fix e.g., to e.g. in doc/http.md
```

Related sources:
+ https://github.com/nodejs/code-and-learn/issues/58
+ http://nodefest.jp/2016/schedule.html
+ https://medium.com/@watilde/cheers-to-a-node-js-conference-in-japan-b9e6e90acd46

### CODE REVIEW

**Review by lpinca — APPROVED** [review]

**Comment by lpinca** [comment]
Can anyone from @nodejs/website give another LGTM?

**Review by Trott — APPROVED** [review]
LGTM. 

Strictly speaking, the Code & Learn event in Austin was on December 1, so not November 2016 but December. And the Tokyo event occurred before that, so if we're keeping them in chronological order, then it should be after Amsterdam and before Austin. I'm not sure if the Tokyo Code & Learn was sponsored by the Foundation, but I'm also not sure that Foundation-endorsement is needed for something to be considered Code & Learn. (/cc @mikeal, I guess)  But these are all nit picks that can be sorted out later. This change looks fine to me.

**Comment by lpinca** [comment]
@watilde can you please move the Tokyo event before the Austin one and update the month as suggested by @Trott?

Thanks.

**Comment by watilde** [comment]
@Trott @lpinca Thanks for your comments, and sure thing! I've updated :)

**Comment by lpinca** [comment]
Thanks!

**Pull request merged**
