### PR TITLE
add release post for v6.3.1

### PR DESCRIPTION
**Pull request by evanlucas**

### CODE REVIEW

**Comment by vsemozhetbyt** [comment]
@evanlucas The main page still is not updated with 6.3.1:

**Comment by evanlucas** [comment]
yea, I'm seeing it also. We had some issues with invalidating the cache when the release was actually completed yesterday. I am not sure what is going on here. /cc @nodejs/website

**Comment by lpinca** [comment]
Everything is ok when running the site locally, so I think this [script](https://github.com/nodejs/nodejs.org/blob/master/scripts/load-versions.js) failed to pick up the latest version. Maybe https://nodejs.org/download/release/index.json wasn't ready?

We can try to deploy again and see if this fixes the issue.

**Comment by evanlucas** [comment]
@lpinca yea, index.json was cached with 6.3.0 as the latest version. Do you have access to deploy again?

**Comment by lpinca** [comment]
No but I'll send a pr with a dep update and once merged it should be deployed again.

**Comment by evanlucas** [comment]
ok, cool. Thanks!!!

**Comment by lpinca** [comment]
Here we go https://github.com/nodejs/nodejs.org/pull/836.

**Comment by lpinca** [comment]
It worked.

**Pull request merged**
