### PR TITLE
fix: use rehype-shikiji

### PR DESCRIPTION
**Pull request by ovflowd**
## Description

This PR temporarily moves from `rehype-pretty-code` to `rehype-shikiji`, since right now, `rehype-pretty-code` would need `shikiji-compat` to work with `rehype-pretty-code,` and unfortunately, that uses Node.js specific APIs.

The functionality of rehype-shikiji is slightly different; hence let's keep an 👀 once `rehype-pretty-code` moves to `shikiji`.

## Validation

All syntax highlighting should still work. Keep in mind empty lines will have a different effect for the meantime.

### CODE REVIEW

**Comment by canerakdas** [comment]
Hey @ovflowd,
Empty lines look like deleted in the preview. Is this an expected situation? I read the validation but didn't get whether this effect is expected or not 🤔

[Vercel preview](https://nodejs-2xppw7dbu-openjs.vercel.app/en/docs/guides/anatomy-of-an-http-transaction#put-it-all-together)

[nodejs.org](https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction#put-it-all-together)

[Markdown file](https://github.com/nodejs/nodejs.org/blob/main/pages/en/docs/guides/anatomy-of-an-http-transaction.md?plain=1#L257-L295)

**Comment by ovflowd** [comment]
> Hey @ovflowd,
> 
> Empty lines look like deleted in the preview. Is this an expected situation? I read the validation but didn't get whether this effect is expected or not 🤔
> 
> 
> 
> [Vercel preview](https://nodejs-2xppw7dbu-openjs.vercel.app/en/docs/guides/anatomy-of-an-http-transaction#put-it-all-together)
> 
> 
> 
> [nodejs.org](https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction#put-it-all-together)
> 
> 
> 
> [Markdown file](https://github.com/nodejs/nodejs.org/blob/main/pages/en/docs/guides/anatomy-of-an-http-transaction.md?plain=1#L257-L295)
> 
> 

Right, it is expected. Sorta. We can always make a css fix on a follow up PRs. The empty lines are still there, but just have no styling.

I have the feeling thats what rehype-pretty-code was doing + a bunch of other things like the line numbers.

So either we abandon rehype-pretty-code and implement these things by ourselves or eventually we move back to that library once they moved to shikiji

**Comment by ovflowd** [comment]
Also @canerakdas feel free to tackle the style empty line issue if you want :) (at least as a hot fix on the legacy css)

**Review by canerakdas — APPROVED** [review]
LGTM!

**Comment by ovflowd** [comment]
Also @devjvao as this might be interesting for your Codebox PR, i.e., line numbers and empty line spacing/padding

**Pull request merged**
