### PR TITLE
id,zh-CN: update translations

### PR DESCRIPTION
**Pull request by ovflowd**
Update and add some new translations for Indonesian and the simplified Chinese.

### CODE REVIEW

**Comment by ovflowd** [comment]
These MDX discrepancies are annoying. I wonder why the `lint` (or `prettier`) step didn't fail because technically those are... not prettied.

**Comment by ovflowd** [comment]
@bmuenzenmeyer maybe our prettier is not "prettying/checking" MDX files?

**Comment by bmuenzenmeyer** [comment]
> @bmuenzenmeyer maybe our prettier is not "prettying/checking" MDX files?

it should according to https://prettier.io/blog/2021/11/25/2.5.0.html
you added this locally and had lint-staged try to format them, I am guessing?

**Comment by ovflowd** [comment]
> > @bmuenzenmeyer maybe our prettier is not "prettying/checking" MDX files?
> 
> it should according to [prettier.io/blog/2021/11/25/2.5.0.html](https://prettier.io/blog/2021/11/25/2.5.0.html) you added this locally and had lint-staged try to format them, I am guessing?

Okay, it should be, but is it? Can you mess a MDX file and check if it complains?

Because on regular Markdown it would probably complain about that, no?

**Comment by bmuenzenmeyer** [comment]
A quick and dirty test revealed mdx files getting prettified.  I used `pages/en/docs/index.mdx`

I intentionally left list items as asterisks and on commit it changed them to hyphens. 

I had some other strageness happening on commit though, with eslint not being aware of the MDXProvider and therefore stating that `<NodeApiVersionLinks />` was not defined. I... don't really expect eslint to know about that, so I'm confusing myself as to how it hasn't tripped sooner.

**Comment by ovflowd** [comment]
> I had some other strageness happening on commit though, with eslint not being aware of the MDXProvider and therefore stating that <NodeApiVersionLinks /> was not defined. I... don't really expect eslint to know about that, so I'm confusing myself as to how it hasn't tripped sooner.

So how did ESLint complain? Was it within the IDE? Or when you ran `eslint`?

**Comment by bmuenzenmeyer** [comment]
> So how did ESLint complain? Was it within the IDE? Or when you ran `eslint`?

image

```
git commit -m "testing change to mdx file"
[STARTED] Preparing lint-staged...
[SUCCESS] Preparing lint-staged...
[STARTED] Running tasks for staged files...
[STARTED] .lintstagedrc — 1 file
[STARTED] **/* — 1 file
[STARTED] eslint --fix
[FAILED] eslint --fix [FAILED]
[FAILED] eslint --fix [FAILED]
[FAILED] eslint --fix [FAILED]
[STARTED] Applying modifications from tasks...
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Reverting to original state because of errors...
[SUCCESS] Reverting to original state because of errors...
[STARTED] Cleaning up temporary files...
[SUCCESS] Cleaning up temporary files...

✖ eslint --fix:

C:\src\nodejsorg-3\pages\en\docs\index.mdx
  27:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

✖ 1 problem (1 error, 0 warnings)

husky - pre-commit hook exited with code 1 (error)
```

**Comment by ovflowd** [comment]
And it never complained about that file before? Is eslint somehow ignoring old files that were not updated recently? What if you touch the same file from another language?

We can disable the react/jsx-no-undef for MDX files, because that makes sense, inho. (We had it on the nodejs.dev eslint rules)

What I'm really confused is about why it is not linting all MDX/Markdown files and only the files that were modified?

**Comment by bmuenzenmeyer** [comment]
> What I'm really confused is about why it is not linting all MDX/Markdown files and only the files that were modified?

lint-staged only lints what is changed. it does so by taking the specified command(s)... eslint, and appending the staged files as args

if you meant in general, I think I found an actual difference between `next lint` and `eslint`

### next lint

```
npx next lint
(node:7272) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
- warn You have enabled experimental features (largePageDataBytes, outputFileTracingExcludes) in next.config.mjs.
- warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

✔ No ESLint warnings or errors
```

### eslint

```
npx eslint .

C:\src\nodejsorg-3\CONTRIBUTING.md
   14:1   warning  Don’t use multiple top level headings (1:1)  remark-lint-no-multiple-toplevel-headings
   36:11  warning  Remove trailing whitespace                   remark-lint-no-trailing-spaces
   53:1   warning  Don’t use multiple top level headings (1:1)  remark-lint-no-multiple-toplevel-headings
  124:11  warning  Remove trailing whitespace                   remark-lint-no-trailing-spaces
  135:11  warning  Remove trailing whitespace                   remark-lint-no-trailing-spaces
  137:3   warning  Remove trailing whitespace                   remark-lint-no-trailing-spaces
  153:1   warning  Don’t use multiple top level headings (1:1)  remark-lint-no-multiple-toplevel-headings
  171:1   warning  Don’t use multiple top level headings (1:1)  remark-lint-no-multiple-toplevel-headings
  202:1   warning  Don’t use multiple top level headings (1:1)  remark-lint-no-multiple-toplevel-headings

C:\src\nodejsorg-3\pages\ar\docs\index.mdx
  26:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\ca\docs\index.mdx
  28:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\de\docs\index.mdx
  31:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\en\docs\index.mdx
  27:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\es\docs\index.mdx
  26:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\fr\docs\index.mdx
  26:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\id\docs\index.mdx
  26:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\ja\docs\index.mdx
  25:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\ka\docs\index.mdx
  26:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\ko\docs\index.mdx
  28:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\nl\docs\index.mdx
  26:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\pt-br\docs\index.mdx
  26:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\ro\docs\index.mdx
  26:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\ru\docs\index.mdx
  29:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\tr\docs\index.mdx
  26:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\uk\docs\index.mdx
  26:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\zh-cn\docs\index.mdx
  26:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

C:\src\nodejsorg-3\pages\zh-tw\docs\index.mdx
  26:2  error  'NodeApiVersionLinks' is not defined  react/jsx-no-undef

✖ 27 problems (18 errors, 9 warnings)
  0 errors and 1 warning potentially fixable with the `--fix` option.
```

---

- CI uses `npx turbo lint` which calls `next lint`
- lint-staged is using `eslint` (we've previously established than running `next lint` here doesn't work)

Apologies for all this confusion! A short-term fix would be to add the rule, but I don't think I am happy with the incongruence in our linting approach

**Comment by ovflowd** [comment]
> lint-staged only lints what is changed. it does so by taking the specified command(s)... eslint, and appending the staged files as args

if you meant in general, I think I found an actual difference between next lint and eslint

Yes, that's what I'm saying. Something must be wrong on `next lint`

**Comment by ovflowd** [comment]
@bmuenzenmeyer let's open a PR and ditch `next lint` for our lint command. We already disabled next linting features during build time as we validate ourselves. Can we do the following?:

- Open a PR
- This PR removes the usage of `next lint` on our `lint` commands, and uses `eslint` with the same globs
  - Pretty much same globs but remove the `--files` argument, as eslint files glob is an unamed argument
- Ensure to configure eslint caching (https://eslint.org/docs/latest/use/command-line-interface#--cache)
  - Separate files for caching Markdown (`.eslintmdcache`)
  - Separate files for caching JavaScript (`.eslintjscache`)
  - Add these files to our .gitignore
- Update Eslint configuration (`.eslintrc`) to disable `react/jsx-no-undef` on `mdx`

**Review by bmuenzenmeyer — APPROVED** [review]
LGTM

**Review by ghost — APPROVED** [review]
Approved for the Simplified Chinese

**Pull request merged**
