### PR TITLE
Update Walmart Case Study

### PR DESCRIPTION
**Pull request by ZibbyKeaton**
Hey All - I'm trying to track downloads to our case studies. I'm doing a little test with Walmart to make sure it works. LMK if I did this correctly. cc: @phillipj

### CODE REVIEW

**Comment by phillipj** [comment]
Please remove the `[Read the full case study.]` preceding the `<a ...>` you've added

**Comment by phillipj** [comment]
Linking with https://github.com/nodejs/nodejs.org/issues/1121

**Comment by ZibbyKeaton** [comment]
@phillipj I just did this. Let me know if this works for you.

**Review by phillipj — APPROVED** [review]

**Comment by phillipj** [comment]
It is live and seems to be working. Hopefully you see these events in GA as well?

**Comment by ZibbyKeaton** [comment]
@phillipj it is working. Thank you, thank you, thank you for helping me with this. You were an awesome help with this and really patient with me. I really appreciate it.

**Comment by phillipj** [comment]
@ZibbyKeaton no problem! Feel free to open a new PRs if you want to do the same with more links.

**Pull request merged**
