### PR TITLE
fix:  Pop-up Menu cannot close when clicking outside it

### LINKED ISSUE #3907: Navbar Issue
I have found issue in the top of navbar.
We see the translation button. It's working fine.
But when we click outside the translation div it is not disappearing it remain still there when i again tap on the translation icon
Fix this issue

### PR DESCRIPTION
**Pull request by Medialo**
Fix the bug when click outside the menu, it doesn't close.
Ref: https://github.com/nodejs/nodejs.org/issues/3907

### CODE REVIEW

**Comment by MaledongGit** [comment]
@Medialo：Plz use 'test:lint:js --fix' to fix formation first, and thanks for your 1st contribution!

**Review by ghost — CHANGES_REQUESTED** [review]
@Medialo：Code is fine with me, however plz use 'standard--fix' to fix formation first, and thanks for your 1st contribution!

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
@Medialo：Now I've helped you to re-format your codes and everything seems fine with me.

**Comment by Medialo** [comment]
> @Medialo：Now I've helped you to re-format your codes and everything seems fine with me.

@MaledongGit  Thanks a lot and sorry for the mistake, I will use your advice next time to fix formation.

**Comment by ghost** [comment]
> > @Medialo：Now I've helped you to re-format your codes and everything seems fine with me.
> 
> @MaledongGit Thanks a lot and sorry for the mistake, I will use your advice next time to fix formation.

Haha, nothing...

BTW：Considering there're some new comers like you, who don't know how to begin. I submitted another PR for you by offering you two commands to check your syntaxes before submitting. Notice README.md before submitting is always right ;)

See：
image

**Pull request merged**
