### PR TITLE
Remove events page

### PR DESCRIPTION
**Pull request by lpinca**
This removes the event pages as per #1031.
The diff is big but it should be easy to review :)

### CODE REVIEW

**Comment by fhemberger** [comment]
Thought we would keep the page (for conferences and Nodeschool events) and just remove the Meetups?

**Comment by amandeepmittal** [comment]
I agree with @fhemberger with removing the meetups and keeping the page.

**Comment by lpinca** [comment]
I'm fine with that but then we should update them regularly. I agree with what @Trott wrote here: https://github.com/nodejs/nodejs.org/issues/1031#issuecomment-307207622.

**Review by Trott — APPROVED** [review]
LGTM

**Comment by bnb** [comment]
Saw this issue, and logged it in https://github.com/nodejs/community-events/issues/2. That issue there shouldn't be a blocker to this PR, but did want to raise the potential there for people to start getting involved at a future date, should they be interested 👍

**Comment by Trott** [comment]
Not sure how exactly the process works here these days. Can this land? Or is this blocked by objections?

**Comment by fhemberger** [comment]
@Trott We are thinking about keeping some kind of events list, but without the map and the list from meetup.com. Sorry, didn't have time to look into it yet.

**Comment by Trott** [comment]
> @Trott We are thinking about keeping some kind of events list, but without the map and the list from meetup.com. Sorry, didn't have time to look into it yet.

👍 Thanks.

<sup>I'll just note such a thing could always be added back later. Leaving the current not-useful events page up while that gets sorted probably isn't doing a service to website users. OK, I'll stop now.</sup>

**Comment by fhemberger** [comment]
@Trott Okay, we can come up later with a better solution.

**Pull request merged**
