### PR TITLE
Translate into French doc (Index.md)

### PR DESCRIPTION
**Pull request by AugustinMauroy**
Translate into French
(index.md)

### CODE REVIEW

**Review by ACT-team-ytb — APPROVED** [review]

**Review by ACT-team-ytb — COMMENTED** [review]
Nickel mais reste le reste je pense qu'il faudras faire plusieurs pr pour le reste

**Comment by AugustinMauroy** [comment]
@ACT-team-ytb  genre?

**Comment by AugustinMauroy** [comment]
@ACT-team-ytb ça change rien du coup non désolé mais merci de la proposition

**Comment by ACT-team-ytb** [comment]
OK ca marche

**Comment by ghost** [comment]
@nodejs/nodejs-fr : Plz have a final review and if everything is OK, this can be merged.

**Comment by AugustinMauroy** [comment]
@MaledongGit It can be merged. The rest will come after my exams.

**Comment by AugustinMauroy** [comment]
@MaledongGit all its ok you can merge this pr.

**Review by ghost — APPROVED** [review]
Rubber stamps on me. Merge it first if anything changed later, we can still push a PR here.

**Comment by ghost** [comment]
@AugustinMauroy : Thanks for your 1st contribution to French translations.
@ACT-team-ytb : Thanks for your free time reviewing.

**Pull request merged**
