### PR TITLE
chore: strengthen commitment to mentoring on Black Lives Matter page

### PR DESCRIPTION
**Pull request by Trott**

### CODE REVIEW

**Comment by Trott** [comment]
/ping @bnb @MylesBorins since this something I believe you two would be specifically committed to?

**Comment by benjamingr** [comment]
Hey, I didn't speak to Tierney or Myles about this but I would be comfortable with my (personal) email being there as someone who is willing to engage and mentor (1 - 2) under-priviledged individuals interested in mentorship (I am not in a US timezone). I have (some) experience locally through [tech career](https://www.facebook.com/tech.career) and [magshimim](https://www.magshimim.cyber.org.il/about) as well as several remote programs working with under-privileged people in some more remote places.

Honestly a bit part of willing to do this is whenever I did this - the results were overwhelmingly positive because the people being mentored ended up being _very_ hard-working compared to the norm I'm used to.

**Review by MylesBorins — APPROVED** [review]
LGTM

I am ok with this commitment

**Comment by Trott** [comment]
@benjamingr I think the thing to do would be to open a pull request adding yourself to the list of people that folks can reach out to? But that assumes you're on Twitter.... So maybe the thing to do is reach out to Myles and Tierney via email or some other mechanism and see what to do?

**Pull request merged**
