### PR TITLE
Add CVE for constant hash seeds to annoucement

### PR DESCRIPTION
**Pull request by mhdawson**

### CODE REVIEW

**Comment by fhemberger** [comment]
Hmm, the CVE is only listed as "reserved", but not yet as published. Should we update the post anyway?

**Comment by mhdawson** [comment]
I've submitted the request to publish and already added the CVE to the mailing list.  The goal is to have the CVE number made public close to the time the CVE details are available, but as I understand it we will generally distribute the CVE in advance of the details being available from Mitre.

**Comment by fhemberger** [comment]
Okay, thanks for the clarification. 👍 
Merged.

**Comment by mhdawson** [comment]
Also just checked and details have been published :).  Thanks for landing.

**Pull request merged**
