### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by nodejs-crowdin-zz**

### CODE REVIEW

**Comment by nschonni** [comment]
@nodejs/nodejs-es @nodejs/crowdin-managers this looks like it just reverts some translated text back to English.
Unless there is a reason for this, I'll close and delete the branch

**Comment by nschonni** [comment]
@nodejs/crowdin-managers it looks like there has been a bunch of activity over on that side https://crowdin.com/project/nodejs-website/activity_stream but we're not seeing anything here except this PR

**Comment by alexandrtovmach** [comment]
@nschonni As much as I remember, PR creates only for approved translations, that's why not all activities shown here

**Comment by nschonni** [comment]
The last PR before this one was back in April https://github.com/nodejs/nodejs.org/pull/3112

**Comment by ghost** [comment]
It seems the problem is now solved, I closed it.

**Pull request closed without merging**
