### PR TITLE
Language picker implemented

### PR DESCRIPTION
**Pull request by alexandrtovmach**
Implemented simple language picker #806, to make better UX on the website

How it looks you can check here:
https://www.loom.com/share/9022dba48c1d42a486df212e4acabbdf

### CODE REVIEW

**Comment by ZYSzys** [comment]
@alexandrtovmach Thanks, this is great!👍

A little suggestion: can we avoid always redirecting to the home page when we change the default language ?

**Comment by alexandrtovmach** [comment]
@ZYSzys it's kind of "overcomplexity".

Of course, I can write this, but this website very simple, and trying to avoid scripts as much as possible, so I decided to go with the same way.

**Comment by alexandrtovmach** [comment]
@ZYSzys added:
https://www.loom.com/share/1cff103b50b14f0ba7d5c586f2d963f5

**Review by ZYSzys — APPROVED** [review]
Cool, LGTM👍

**Comment by zeke** [comment]
Looking good!

Drive-by comment: is it possible to also display the English name of each language?

For example: `简体中文 (Simplified Chinese)`

**Comment by alexandrtovmach** [comment]
@zeke Thanks for proposition. Do you think that's good idea? I'm agreed with [this comment](https://github.com/nodejs/nodejs.org/issues/806#issuecomment-505086687), because when user looking for his language he don't need English version. In the same time if we'd add English name, it will make string longer.

I think optimal way is to use `title` attribute, to show English name on hover. For example:
image

**Comment by zeke** [comment]
> use title attribute, to show English name on hover.

👍

**Comment by alexandrtovmach** [comment]
@zeke added. Thanks for help

**Comment by ghost** [comment]
@nodejs/website-redesign：This is due to a web design function, so any other ideas about that? I agree with this :)

**Comment by keywordnew** [comment]
This is looking good to me! Thanks for the PR @alexandrtovmach 💯

**Comment by alexandrtovmach** [comment]
Thanks everyone for a review 🤗.

@MaledongGit What do you think about merge?

**Comment by srl295** [comment]
I missed the original PR. 
- make sure `en` is a variable and not assumed
- you can get localized names for languages from CLDR, loadable from JSON via https://www.npmjs.com/package/cldr-data

**Pull request merged**
