### PR TITLE
Change Tracing WG to Diagnostics WG

### PR DESCRIPTION
**Pull request by ryanmurakami**
The Tracing working group has become the Diagnostics working group and expanded their scope.
This PR updates the group's information on the working groups page. 

This change would need to be updated for other localized sites that include the same page:
@nodejs/nodejs-ko 
@nodejs/nodejs-uk

### CODE REVIEW

**Review by fhemberger — APPROVED** [review]

**Review by lpinca — APPROVED** [review]

**Comment by williamkapke** [comment]
Hm. Pls hold off on merging this for a few min while I review.

**Comment by williamkapke** [comment]
I guess I'm late to the game on this topic unfortunately.

@joshgav was this expansion of the WG's charter approved by the CTC?

I see these PRs:
https://github.com/nodejs/diagnostics/pull/47
https://github.com/nodejs/node/pull/9329

But I don't see a discussion with the CTC requesting to expand the official charter. I feel confident that the CTC would approve it- but I just want to make sure we take the steps to ensure documentation and process.

Maybe this was done and I just wasn't able to find it?

**Review by williamkapke — CHANGES_REQUESTED** [review]
I'm not a fan of mixing off-topic formatting changes in a PR.

**Comment by joshgav** [comment]
@williamkapke discussion and conclusion are in https://github.com/nodejs/diagnostics/issues/46, we made this change around when v8_inspector first came in in spring 2016 but missed propagating it in various docs.

Do you think we should have had a more official measure then?

@ryanmurakami - thanks for updating this!

**Comment by ryanmurakami** [comment]
@williamkapke I hear you on mixing changes. I backed out everything except the tracing->diagnostics change and will open a separate PR for that. Thanks!

**Review by williamkapke — APPROVED** [review]

**Comment by williamkapke** [comment]
@joshgav I had seen that post- but missed how old it was!

yeah- I would have pushed for a more formal process of approval at the time but it is really too far in the past to bring it up now! As I said- I'd find it really hard to believe the CTC would NOT approve it anyhow. There certain hasn't been any objections since the change :P 

Hopefully, this thread can serve to help document it even more and some future person will understand how it all went down. heh. Thanks.

LGTM. Let's merge it in!

**Pull request merged**
