### PR TITLE
Russian locale: remove untranslated files.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Review by ghost — APPROVED** [review]
If there's no-one translating these files, no need to be kept here.

**Comment by Trott** [comment]
@nodejs/nodejs-ru

**Comment by Trott** [comment]
(I agree these can be removed if there is no translation going on. The ping was in case anyone wanted to translate one or more of these--in case they didn't realize there was lots of untranslated content.)

**Comment by XhmikosR** [comment]
I'm just trying to clean up the locales. When a page has been translated, then it should be added, not before.

**Comment by XhmikosR** [comment]
I see one ongoing translation in #2473. I can exclude the removal of this file assuming that PR will land.

**Comment by XhmikosR** [comment]
So, how should we proceed with this?

**Comment by ghost** [comment]
Until  #2473 is merged

**Comment by XhmikosR** [comment]
I don't follow? I can just skip this file from this PR, if #2473 is going to be merged.

Note that this removes obsolete/old files too.

**Comment by ghost** [comment]
@XhmikosR , What I mean is you can revert ONLY this file 'locale/ru/docs/guides/simple-profiling.md' but just remove the others. But I still see your file is in the state of remove.
image

**Pull request merged**
