### PR TITLE
Anchor links

### PR DESCRIPTION
**Pull request by fabiosantoscode**
Okay, this implements anchor links in headings from markdown text!

I love anchor links, so I really had to do this one.

### CODE REVIEW

**Comment by fabiosantoscode** [comment]
(Fixes #52)

**Comment by fhemberger** [comment]
Great idea, still needs some fine tuning (see the link on the bottom right):

https://nodejs.org/en/about/working-groups/#website
bildschirmfoto 2015-09-14 um 18 40 23

Also a little bit of padding would be nice, so the hash doesn't touch the headline. Maybe also a more subtile hover style for those links without the green background?

**Comment by fabiosantoscode** [comment]
Yes, good idea. The font might be too bold too.

**Comment by phillipj** [comment]
Nice, looking forward to this landing 👍

**Comment by mrkiffie** [comment]
I've forked @fabiosantoscode's branch [here](https://github.com/mrkiffie/new.nodejs.org/tree/feature/anchor-links), resolved conflicts and extended the renderer function to support markdown headings that contain links. Here is the [comparison with master](https://github.com/nodejs/new.nodejs.org/compare/master...mrkiffie:feature/anchor-links). Any thoughts?

**Comment by phillipj** [comment]
Nice refactoring w/tests @mrkiffie :+1: Maybe you could address the styling issues @fhemberger pointed out aswell while you're at it?

> Also a little bit of padding would be nice, so the hash doesn't touch the headline. Maybe also a more subtile hover style for those links without the green background?

**Comment by mrkiffie** [comment]
Ok, I'll have a look at those style tweaks

**Comment by mrkiffie** [comment]
@phillipj, I've updated the styles to be similar to those of the attachment in #52.
I also simplified the markup that was being generated as it doesn't appear to serve a purpose.

**Comment by phillipj** [comment]
Very nice @mrkiffie! I would say your branch looks mergeable after squashing your commits into one and opening a PR from your fork.

**Comment by phillipj** [comment]
Fixed with 294af4f, thanks to both of you :+1:

**Pull request closed without merging**
