### PR TITLE
fix(minor): Bash script on downloads page uses a command that is not installed on Mac

### LINKED ISSUE #3758: Bash script on downloads page uses a command that is not installed on Mac
* **URL**: [https://nodejs.org/en/download/package-manager/#macos](https://nodejs.org/en/download/package-manager/#macos)
* **Browser version**: Google Chrome 88.0.4324.192
* **Operating system**: Mac OSX 10.15.7

By going to [the link above](https://nodejs.org/en/download/package-manager/#macos), you can see the following code:

```bash
curl "https://nodejs.org/dist/latest/node-${VERSION:-$(wget -qO- https://nodejs.org/dist/latest/ | sed -nE 's|.*>node-(.*)\.pkg</a>.*|\1|p')}.pkg"
```

This bash script uses the command `wget`. However, Mac OS does not come with `wget`, meaning that this cannot be used.

### PR DESCRIPTION
**Pull request by focarroll**
## Description

I made this issue (#3758) about three years ago and then forgot about it. Not knowing how to fix it, I left the solution as a comment and hoped someone would figure it out. Today, I received two emails about comments reminding me about this minor issue. Now knowing a bit more about Git, I've decided that it's finally time to put this issue to rest.
So long...
(this description is longer than the fix lol)

## Validation

The package was downloaded and successfully installed to /usr/local/bin. Running node -v confirmed that v21.6.2 was installed.

## Related Issues

Fixes #3758

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [X] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [X] I have run `npx turbo format` to ensure the code follows the style guide.
- [X] I have run `npx turbo test` to check if all tests are passing.
- [X] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
any reasons why this pr is on draft ?

**Comment by focarroll** [comment]
> any reasons why this pr is on draft ?

First PR on a major repository (not first PR overall) so I didn't want to make a dumb mistake. Gonna hit the "Ready for review" button.

**Review by AugustinMauroy — APPROVED** [review]
LGTM ! Thanks for your first contribution 🎉

**Review by aymen94 — APPROVED** [review]

**Comment by focarroll** [comment]
That's embarrassing... I made a minor edit to the command when running it on my computer, but never changed the file before pushing.

**Comment by focarroll** [comment]
...
And now I know not to merge the upstream branch into the issue branch
So sorry to whoever's dealing with my nonsense

**Comment by ovflowd** [comment]
All good :)

**Review by ovflowd — APPROVED** [review]
The changes look good to me!

Thank you for your first contribution 🎉

**Pull request merged**
