### PR TITLE
test: Added test for codebox

### LINKED ISSUE #5526: Flaky Test on `Codebox` for Storybook
### The Issue

The Codebox component currently holds a flaky test that often passes and often does not. It also causes PRs that run `test:storybook:snapshot` often to update this flaky Storybook test with unrelated changes.

#### Cause

This is mainly caused due to `Prismsjs` being client-side and modifying the DOM-tree on-the-fly for the Codebox. This is the current approach instead of running Prismjs, setting the content on a state, and then injecting through a `dangerouslyInnerHtml` React option.

The new approach does indeed modify the contents, and it is a side-effect out of the bounds of React.

### Solution

Since this change on the DOM-tree is caused by Prismjs, we can wait for the `tabindex` field to be present. (Wait until `pre[tabindex="0"]` renders)

### PR DESCRIPTION
**Pull request by vrinda-mahajan**
## Description

This PR addresses the flaky test in the Codebox component, caused by Prismjs modifying the DOM tree on-the-fly and leading to unpredictable test results.
As a solution suggested by @ovflowd in issue #5526 
I have added a test on top in `components/Article/Codebox/__tests__/index.test.tsx` which waits for the `tabindex` field of the `pre` element to be equal to `0`

Please let me know if any changes are required.

## Related Issues
This PR Fixes #5526 

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing, and/or `npx turbo test:snapshot` to update snapshots if I created and/or updated React Components.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by ovflowd — APPROVED** [review]
Hey there, I appreciate the PR, this PR introduces a new test, and that's great!

Sadly it does not fix the flakiness. ([this](https://github.com/nodejs/nodejs.org/pull/5530) PR fixes the flakiness by adding a timeout)

I'm approving this PR because, regardless, it is an excellent addition! Tbank you!

**Review by mikeesto — APPROVED** [review]
Thanks for your first contribution

**Comment by vrinda-mahajan** [comment]
> Hey there, I appreciate the PR, this PR introduces a new test, and that's great!
> 
> Sadly it does not fix the flakiness. ([this](https://github.com/nodejs/nodejs.org/pull/5530) PR fixes the flakiness by adding a timeout)
> 
> I'm approving this PR because, regardless, it is an excellent addition! Tbank you!


Thank you for the feedback! After looking at your PR,  I now understand the approach you've taken to solve the problem. Your support is appreciated!

**Review by aymen94 — APPROVED** [review]

**Review by bmuenzenmeyer — APPROVED** [review]
flakiness resolved via #5530 - thanks for contributing. per the [guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#before-merging), this needs to sit for 48 hours

**Review by ovflowd — APPROVED** [review]
Again, thank you for your contribution :)

**Pull request merged**
