### PR TITLE
chore: Add Swedish locale in i18n config

### PR DESCRIPTION
**Pull request by dinkelspiel**
## Description

Added swedish localization to the i18n/config.json so that translation work for swedish can begin.

## Validation

Git diff shows added locale

## Related Issues

No related issues

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by dinkelspiel** [comment]
Is there anything required that i'm missing for this to get committed?

**Comment by ovflowd** [comment]
FYI we're not adding new languages at the moment until we fix our Crowdin issues 🙇

**Review by bmuenzenmeyer — APPROVED** [review]
This work is now unblocked.

**Comment by bmuenzenmeyer** [comment]
added in crowdin

**Pull request merged**
