### PR TITLE
Add missing pt-br translations

### PR DESCRIPTION
**Pull request by joemaffei**
Native speaker here. I was looking at the source code and noticed some of the translations were missing. Confirmed on nodejs.org

### CODE REVIEW

**Comment by Trott** [comment]
@ovflowd Are pull requests directly to this repo OK for translations or do we need to direct everything through Crowdin first?

**Comment by ovflowd** [comment]
Crowdin would be the way forward. We need to update the README and TRANSLATING.md with these instructions.

**Comment by ovflowd** [comment]
I actually see our `TRANSLATION.md` is correctly explaining translation steps: https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md

**Comment by joemaffei** [comment]
Sorry, I didn't see the guidelines in TRANSLATION.md. I'll try Crowdin.

**Pull request closed without merging**
