### PR TITLE
Fixed cursor flickering on nav menu

### PR DESCRIPTION
**Pull request by eckerdj7**
## Nav Cursor Update
* Added a rule to make the cursor stop flickering between the default, hand, and text-selection cursor when hovering over the nav menu items.
* The rule causes the cursor to stay default unless directly on an anchor element, in which case it follows normal behavior over a link.

### CODE REVIEW

**Comment by lpinca** [comment]
SGTM, can you please use a more descriptive commit message?

**Comment by eckerdj7** [comment]
Sure, how so? This is my first time ever making a contribution to any Github project. So I'm not exactly sure what the standard is for commit messages.

**Comment by lpinca** [comment]
There are no strict rules for this repo take a look at the previous commits.
I'd just use something that describe the change like, I don't know, "Fix cursor flickering on nav menu".

**Comment by eckerdj7** [comment]
Ah, sorry, I thought you meant the comment. I see now you meant the commit title. Better?

**Comment by lpinca** [comment]
@eckerdj7 you updated the PR title and that's fine, I was referring to the commit message:

```
git commit --amend
# Update the commit message and then force push
git push -f origin feature/consistent-nav-cursor
```

We can also change it before merging the PR so no problem!

**Comment by eckerdj7** [comment]
@lpinca - Hmmm, I'm only using the online features right now. Is there a way to do that on here? If so, I could not find it.

Sorry for the newb questions, btw. What's the best place for me to learn this stuff? I read through the initial tutorial pages but I obviously have a lot to learn still.

**Comment by fhemberger** [comment]
@eckerdj7 It's fine, we can fix that on merge. You can post your description in a comment.

**Comment by eckerdj7** [comment]
@fhemberger Alright sounds good. At least now I'll know for next time. 

And thanks for the help, @lpinca

**Review by eckerdj7 — COMMENTED** [review]
Fixed cursor flickering on nav menu.

**Review by lpinca — APPROVED** [review]

**Comment by fhemberger** [comment]
@eckerdj7 Cool, thank you!

**Pull request merged**
