### PR TITLE
change "persian language" to "persian" & adding other indexes

### PR DESCRIPTION
**Pull request by AliSawari**
the language list contains "Farsi Language" which does not make sense here, we need only the name of the language here, you won't see something like "English Language", "French Language"
@nodejs/nodejs-fa

### CODE REVIEW

**Comment by nschonni** [comment]
Ping @nodejs/nodejs-fa

**Review by ghost — COMMENTED** [review]
@AliSawari:
Make sure that you've translated this file (locale/fa/get-involved/index.md) into Persian (I mean the titles such as "## Learning"?

Perhaps the "##Learning" content can also be translated into Persian, if possible?

**Comment by brandt2891** [comment]
[16 Feb 2020 817 pm.txt](https://github.com/nodejs/nodejs.org/files/4209729/16.Feb.2020.817.pm.txt)

**Comment by alexandrtovmach** [comment]
@nodejs/nodejs-fa @AliSawari @brandt2891

**Comment by ebraminio** [comment]
@alexandrtovmach Thanks for the ping, as they are out-of-date and needs minor style, am working on a patch that resolves this and #2775

**Comment by alexandrtovmach** [comment]
@ebraminio Thanks for a quick response and your help. Could you make all of your updates on [Crowdin project](https://crowdin.com/project/nodejs-website), and don't create new PR on GitHub

**Comment by ebraminio** [comment]
> @ebraminio Thanks for a quick response and your help. Could you make all of your updates on Crowdin project, and don't create new PR on GitHub

No problem, I have an old account there but there is no Persian for nodejs-website apparently https://crowdin.com/project/nodejs-website

**Comment by alexandrtovmach** [comment]
@ebraminio I will add Persian language to Crowdin project for you

**Comment by alexandrtovmach** [comment]
@ebraminio Added:
https://crowdin.com/project/nodejs-website/fa

**Pull request closed without merging**
