### PR TITLE
Chore: remove obsolete package repository

### PR DESCRIPTION
**Pull request by Trott**
## Description

Software Collections does not contain a version of Node.js newer than 12.x. Remove it from the documentation on installing Node.js with a package manager.

## Related Issues

n/a

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [ ] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [ ] I have run `npx turbo format` to ensure the code follows the style guide.
- [ ] I have run `npx turbo test` to check if all tests are passing, and/or `npx turbo test:snapshot` to update snapshots if I created and/or updated React Components.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by Trott** [comment]
`npx turbo` exits with errors on my laptop so I skipped it for this, but hopefully there's a low probability of that causing issues with a small change like this.

**Comment by AugustinMauroy** [comment]
@Trott don't worry all test pass.

**Review by ovflowd — APPROVED** [review]
Changes sound legit.

**Comment by ovflowd** [comment]
FYI @Trott if you want to share your error logs over Slack that'd be fine.

**Comment by mhdawson** [comment]
RHEL 7 is still supported for another year and I suspect Node.js 14 is installed the same way as was described (its still supported by RH for RHEL7)

I'm not sure this should have landed.

**Comment by ovflowd** [comment]
@mhdawson the change only removes the installation method through "Software Collections", there are still other methods mentioned there for RHEL7 (yum/rpm)

**Comment by Trott** [comment]
@mhdawson There is no supported version of Node.js in Software Collections as far as I can tell. 12.x is the most recent. (Or is this one of those cases where Red Hat backports security fixes from supported release lines? I kind of doubt it in this case.....)

@ovflowd I think the remaining CentOS text is for CentOS 8 only. So it won't work for CentOS 7 users.

I think CentOS 7 users need to use installation methods like NodeSource's packages or snaps or `nvm`/`n` or....seems to be lots of options, but it seems that Software Collections would get them an old, insecure, unsupported version of Node.js. (If I'm wrong about that, it's easy enough to revert this and we can/should do so quickly. I should have commented that this probably shouldn't land until someone from Red Hat reviews it.)

**Comment by Trott** [comment]
> FYI @Trott if you want to share your error logs over Slack that'd be fine.

The problem is that `npx turbo lint` expects to find `concurrently` and I didn't do any troubleshooting after that.

```
lint: sh: concurrently: command not found
lint: ERROR: command finished with error: command (/Users/trott/temp/nodejs.org) npm run lint exited (127)
command (/Users/trott/temp/nodejs.org) npm run lint exited (127)
```

This is on macOS.

**Comment by ovflowd** [comment]
> This is on macOS.

Did you run `npm ci` (this sounds stupid for me from asking) but concurrently is a `devDependency` so it requires all the packages to be installed 🤔 

> @ovflowd I think the remaining CentOS text is for CentOS 8 only. So it won't work for CentOS 7 users.

Oh! My bad 😅

**Comment by Trott** [comment]
> Did you run `npm ci` (this sounds stupid for me from asking) but concurrently is a `devDependency` so it requires all the packages to be installed 🤔

No...uh, I did not. My mistake (obviously).

**Comment by Trott** [comment]
> > @ovflowd I think the remaining CentOS text is for CentOS 8 only. So it won't work for CentOS 7 users.
> 
> Oh! My bad 😅

I could be wrong. The NodeSource RPMs and the snaps might work on CentOS 7. I don't...actually...know.

**Pull request merged**
