### PR TITLE
Add Chinese website

### PR DESCRIPTION
**Pull request by h7lin**

### CODE REVIEW

**Comment by fhemberger** [comment]
We were planning to add localization to the nodejs.org website as we had on iojs.org - how about adding your translation under `content/cn`, so releases, template and css fixes always stay up to date for the Chinese version as well? nodejs.cn could redirect to nodejs.org/cn/ as well.

**Comment by fhemberger** [comment]
Pinging @nodejs/iojs-cn as well.

**Comment by XadillaX** [comment]
@fhemberger +1

**Comment by fengmk2** [comment]
Yep, follow the iojs.org way.

**Comment by laosb** [comment]
Good point.

**Pull request closed without merging**
