### PR TITLE
docs: make note formatting more consistent

### PR DESCRIPTION
**Pull request by GeorgeSapkin**
The note formatting seems to differ among various parts of the docs, so I've tried to normalize it a bit. I've only touched the English bits for now. I've picked the style that seems to be the most popular:

> ~~**Note:**~~ Details here.

### CODE REVIEW

**Comment by Trott** [comment]
Looks fine to me, although I wonder if the thing to do is remove `Note:` entirely.

**Comment by GeorgeSapkin** [comment]
What are you suggesting? Just leave the note text without the word `Note:`?

> ~~**Note:**~~ Details here.

I don't have a strong opinion. I'm updating the event loop guide and this irks me somewhat.

**Comment by Trott** [comment]
> What are you suggesting? Just leave the note text without the word `Note:`?
> 
> > ~**Note:**~ Details here.
> 
> I don't have a strong opinion. I'm updating the event loop guide and this irks me somewhat.

Yes, that's what I'm suggesting, but like you, I don't have a particularly strong opinion. The change here is 👍 by me, as would getting rid of `Note:` entirely. Maybe let's see what @nodejs/website folks thing.

**Review by phillipj — APPROVED** [review]
LGTM either way, with or without *Note:*.

If I'd have to choose, I'd lean slightly towards getting rid of *Note:*, primarily because the text that follows it has now been updated to be markdown quotes, which I'm assuming will highlight it a bit compared to other non-quote parts of these guides.

**Comment by GeorgeSapkin** [comment]
I removed `Note:` and rebased.

**Comment by sonicdoe** [comment]
To support removing “Note:” completely, we’ve made the same change two years ago in https://github.com/nodejs/node/pull/18592.

**Pull request merged**
