### PR TITLE
Remove Node.js Interactive banner from frontpage

### PR DESCRIPTION
**Pull request by phillipj**
It's time to remove the Node.js Interactive banner on the frontpage?

/cc @mikeal

### CODE REVIEW

**Comment by mikeal** [comment]
+1 :)

**Comment by ghost** [comment]
+1, it's time

**Comment by ghost** [comment]
also, do we have some kind of recap blog post we can put up?

**Comment by mikeal** [comment]
@nodejs/evangelism ^ wrapup blog post.

**Pull request merged**
