### PR TITLE
Blog: v20.17.0 release post

### PR DESCRIPTION
**Pull request by marco-ippolito**
Refs: https://github.com/nodejs/node/pull/54447

cc @nodejs/releasers @nodejs/nodejs-website

### CODE REVIEW

**Comment by marco-ippolito** [comment]
missing shasum

**Review by UlisesGascon — APPROVED** [review]
LGTM!

**Review by AugustinMauroy — APPROVED** [review]

**Comment by marco-ippolito** [comment]
https://nodejs.org/en/blog/release/v20.17.0 its oddly taking a while to go up :skull:

**Comment by ovflowd** [comment]
> https://nodejs.org/en/blog/release/v20.17.0 its oddly taking a while to go up :skull:

Weird, is the build on main passing?

**Comment by ovflowd** [comment]
Redeploying. Build in progress.

**Comment by ovflowd** [comment]
Deployed!

**Pull request merged**
