### PR TITLE
Add Vietnamese language

### PR DESCRIPTION
**Pull request by datlechin**
Hi,
If you want a Vietnamese translator for nodejs.org, I'd be happy to

### CODE REVIEW

**Comment by nschonni** [comment]
Ping @nodejs/nodejs-vi

**Comment by nschonni** [comment]
@datlechin thanks! You can leave out files that are just copies of the English, since those fall back to English if they are not found. It's also better since any changes to the English are picked up, instead of having an old copy in the `vi` folder

**Comment by datlechin** [comment]
do i have to delete untranslated files from vi directory?

**Comment by pierreneter** [comment]
> do i have to delete untranslated files from vi directory?

yes

**Comment by MaledongGit** [comment]
@datlechin: Hi, you don't need to delete these files but just to make your own language translations and re-submit by rebase your changes....Just leave translated files and do changes to your title.

**Comment by ghost** [comment]
> Hi, If you want a Vietnamese translator for nodejs.org, I'd be happy to

@datlechin:

Hi, First say a BIG THANK YOU to you if you're glad to make contributions to Nodejs.org.
And what's more: You can only leave translated files here by rebasing and submitting forcely to the same PR branch and change your title such as:

`vi: translations for ....`

Notice that you DON'T need to join in the language group when contributing by translating the English files, maybe with more and more files are translated, you'll be involved soon ;)

**Comment by datlechin** [comment]
> @MaledongGit 

> so i can update the translations by committing to this PR, right? (Or do I have to submit a new PR)

Welcome :)

**Pull request merged**
