### PR TITLE
feat(ignore): add storyBook

### PR DESCRIPTION
**Pull request by AugustinMauroy**

### CODE REVIEW

**Comment by ovflowd** [comment]
Note: It's just Storybook not StoryBook xD

**Review by ovflowd — APPROVED** [review]
LGTM!

**Review by rodion-arr — APPROVED** [review]

**Review by shanpriyan — APPROVED** [review]
LGTM

**Review by aymen94 — APPROVED** [review]

**Comment by aymen94** [comment]
LGTM

**Pull request merged**
