### PR TITLE
Revert the Windows slashes workaround

### PR DESCRIPTION
**Pull request by XhmikosR**
I open this as a draft.

I've finally pinpointed and [submitted patches](https://github.com/segmentio/metalsmith-permalinks/pulls/XhmikosR) to metalsmith-permalinks to fix the Windows backslashes issues.

When there's a new metalsmith-permalinks release with the fixes, I'm gonna update to it, rebase this and drop the Windows addition in CI (unless you guys think we should keep it).

TODO:

- [x] Waiting for a new release from metlsmith/permalinks
- [x] Confirm if `replace` is still needed here: https://github.com/nodejs/nodejs.org/blob/baaf63179d1b1ecc69901c62600fe7fbf0bf2515/scripts/plugins/githubLinks.js#L16
- [x] Revert the lockfile-lint changes if/when we have an npm package
- [ ] Revert the Windows CI addition?
- [x] Rebase the patches and clean up the branch

### CODE REVIEW

**Comment by XhmikosR** [comment]
It's too bad that we don't have a patch released with the Windows fixes...

It would save us from the hacks to get things right on Windows.

Oh, well, I'll keep this open and rebase it when we have a new metalsmith-permalinks version.

**Comment by XhmikosR** [comment]
If anyone is in touch with the metalsmith-permalinks people, it would help if they took care of the remaining open PRs I have and releasing a new version. I've done my best to bug them to release a new version without success. 🙁

Otherwise, we could switch to using a specific commit from master, similarly to what this branch does which works on all OS'es.

**Comment by XhmikosR** [comment]
> If anyone is in touch with the metalsmith-permalinks people, it would help if they took care of the remaining open PRs I have and releasing a new version. I've done my best to bug them to release a new version without success. 🙁
> 
> Otherwise, we could switch to using a specific commit from master, similarly to what this branch does which works on all OS'es.

@Trott @MylesBorins any thoughts? I think at this point the best solution would be to just use a specific commit from master since I think the project is sort of dead.

**Comment by Trott** [comment]
The package is explicitly deprecated with this message:

> No longer maintained; Migrate to the following package: @metalsmith/permalinks

Any chance that's a viable option?

**Comment by XhmikosR** [comment]
Oh, I wasn't aware of that, I'll give that a go then and update the PR
tomorrow or so

**Comment by XhmikosR** [comment]
Apparently [`@metalsmith/permalinks`](https://github.com/metalsmith/permalinks/releases) doesn't have a new version published either.

**Comment by Trott** [comment]
> @metalsmith/permalinks

https://www.npmjs.com/package/@metalsmith/permalinks says it last published 22 days ago. Judging from https://github.com/metalsmith/permalinks, it's a pretty recent fork--only a few weeks old. So it may be worth it to see what happens if you open an issue asking them to publish a new version?

**Comment by XhmikosR** [comment]
@Trott @MylesBorins how to you think we should proceed? It's a pity having to keep the legacy workarounds especially since I have submitted fixes upstream, but they haven't released a new version. The new package doesn't have a new version either. Would it be OK to pin to a specific repo commit?

I can drop the Windows CI addition, I just did it to ensure everything is still fine.

**Comment by Trott** [comment]
I just opened https://github.com/metalsmith/permalinks/issues/4 to hopefully prompt publishing of a new version. 

> Would it be OK to pin to a specific repo commit?

I'm OK with that.

**Comment by webketje** [comment]
Hi @XhmikosR @Trott, 

Thank you for your patience.
Following the reporting of https://github.com/metalsmith/permalinks/issues/4, I would like to give some extra info on the status of Metalsmith: a year ago the project was in a difficult situation with segmentio no longer allocating resources to the project and leaving the maintainers with insufficient control to manage it independently. We started migrating some repo's and NPM packages, including permalinks (original plan was outlined in https://github.com/segmentio/metalsmith/issues/339), however we reached out to segment and are in the process of a legal ownership transfer (still ongoing) which will be followed by a repo transfer to the GH metalsmith org.

That is the reason substantial updates to the "temporary" repositories have been put off, while we wait for the segmentio repo ownership (including permalinks) to be transferred.

Feel free to join the relatively recent https://gitter.im/metalsmith/community for updates.

**Comment by webketje** [comment]
@metalsmith/permalinks@2.3.0 released yesterday

**Comment by Trott** [comment]
@XhmikosR Are you able to pick this one up again?

**Comment by XhmikosR** [comment]
@webketje thanks!

@Trott done. Please check the OP TODO, not sure if we want the Windows CI or not, but it's the only way to make sure this works. That being said, I'd be OK without it since no one else seems to have noticed the issues apart from me and the slowdown maybe isn't something we want to introduce.

**Comment by Trott** [comment]
@XhmikosR Can you convert this from a Draft PR to want that is read for review?

I'm inclined to keep the Windows CI for now and if it ends up being slow enough to bother anyone, we can remove it at that time.

**Review by Trott — APPROVED** [review]

**Comment by XhmikosR** [comment]
@Trott SGTM. Just remember to adapt the branch protection rules.

**Comment by Trott** [comment]
> Just remember to adapt the branch protection rules.

Preemptively updated them so nothing else can land until this does (because the windows test doesn't exist anywhere else yet).

**Pull request merged**
