### PR TITLE
Remove doc and testing WGs

### LINKED ISSUE #1240: Remove Docs WG and Test WG link
After [meta: decharter the Docs and Testing Working Groups #121](https://github.com/nodejs/CTC/pull/121) was merged, we need to remove Docs WG and Test WG links. 

- [ ] https://nodejs.org/en/foundation/education/

### PR DESCRIPTION
**Pull request by sotayamashita**
According to https://github.com/nodejs/nodejs.org/issues/1240#issuecomment-304767680 and nodejs/CTC#121

### CODE REVIEW

**Comment by lpinca** [comment]
@sotayamashita I think those WGs should also be removed from https://nodejs.org/en/about/working-groups.

See for example https://github.com/nodejs/nodejs.org/pull/1213 which removed the inclusivity WG.

**Comment by sotayamashita** [comment]
@lpinca Thanks, I removed

**Comment by lpinca** [comment]
If I'm not wrong the testing WG should also be removed.

**Comment by sotayamashita** [comment]
@lpinca That's right... :cry:

**Review by lpinca — APPROVED** [review]

**Comment by sotayamashita** [comment]
@lpinca I appreciate you reviewing. :bow:

**Pull request merged**
