### PR TITLE
Added browser detection notification

### PR DESCRIPTION
**Pull request by NriotHrreion**
issue: #3960

I think it's very important for the users who are using old browser. So I added and committed it.

### CODE REVIEW

**Comment by NriotHrreion** [comment]
@MaledongGit @Trott Can you have a review?

**Comment by Trott** [comment]
I'll defer to others, but I'm not sure this is useful in 2021. My impression is that if someone is browsing the internet with IE9, then they are used to half the internet being completely broken for them and they know they are running an old browser.

**Comment by NriotHrreion** [comment]
> I'll defer to others, but I'm not sure this is useful in 2021. My impression is that if someone is browsing the internet with IE9, then they are used to half the internet being completely broken for them and they know they are running an old browser.

I'm sure that there must be some people still using IE9. Not all are using Chromium. It's necessary to add this.

**Comment by XhmikosR** [comment]
I don't think it's worth adding this, either. It's totally useless nowadays.

**Comment by NriotHrreion** [comment]
well.

**Pull request closed without merging**
