### PR TITLE
fix: layout word break

### LINKED ISSUE #6711: Blog Word Break
### URL:

https://nodejs.org/en/blog/announcements/v22-release-announce

### Browser Name:

Arc

### Browser Version:

1.41.0 (49440)

### Operating System:

MacOS 14.4.1 (23E224)

### How to reproduce the issue:

The blog currently uses `word-break: break-all` for the body text. This seems like a bug to me. It makes it difficult to read the posts. I would recommend changing it to `word-break: normal`.

1. Go to https://nodejs.org/en/blog/announcements/v22-release-announce
2. Look at the end of each line of text. Many words will be chopped off, not even hyphenated.

It looks like it was introduced in #6680. I think that change was only supposed to affect small screens, like phones, but I am using a full desktop browser on a large screen and having the issue.

## Before
Notice the way that every line ends in a broken word.

image

## After (`word-break: normal`)
image

### PR DESCRIPTION
**Pull request by araujogui**
## Description

Change layout's word break to normal

## Validation

image

## Related Issues

Fixes #6711

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by AugustinMauroy — APPROVED** [review]

**Review by mikeesto — APPROVED** [review]

**Review by aymen94 — APPROVED** [review]

**Comment by canerakdas** [comment]
It seems to overflow content for low-resolution mobile browsers, for example;

https://nodejs-jow7mncue-openjs.vercel.app/en/blog/release/v20.12.0

IMO it might be better to use `xs:break-words` for mobile resolution

**Comment by bmuenzenmeyer** [comment]
yeah - we have dueling solutions here now and we need to slow down and consider our use cases and options

**Review by canerakdas — APPROVED** [review]
LGTM

**Review by shanpriyan — APPROVED** [review]

**Comment by NiedziolkaMichal** [comment]
You guys may consider `text-align: justify`:
image

**Comment by krave1986** [comment]
I would suggest try

```
word-break: normal;
overflow-wrap: anywhere;
hyphens: auto;
```
This will both keep the result closest to the current design and bring hyphens to broken words at the end of the lines.

Another benefit would be that we don't need to concern media query for such cases further.

**Comment by ovflowd** [comment]
Look we also already tried the hyphens approach. Each approach has its own cons and pros and different side effects.

I think is worth going over git history to see what was already attempted and what not and if whatever proposed works well on all scenarios

**Comment by tniessen** [comment]
I came across this PR after running into this odd issue and trying to fix it myself. For me, personally, justified alignment and normal word break work fine in combination.

**Comment by ovflowd** [comment]
@araujogui could you go over the considerations that both me, Caner and Brian mentioned? 👀

**Comment by araujogui** [comment]
Found out that word-break was introduced in #6680, so I think we can assume that until then it was the browsers defaults (normal). The issue solved in #6680 didn't come back with this PR.

**Pull request merged**
