### PR TITLE
chore(content): use as 100% new codebox

### PR DESCRIPTION
**Pull request by AugustinMauroy**
## Description

Adding possibility to switch between `cjs`/`esm` on new codeBox

## Related Issues

No related Issues

### Check List

- [X] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [X] I have run `npx turbo format` to ensure the code follows the style guide.
- [X] I have run `npx turbo test` to check if all tests are passing.
- [X] I have run `npx turbo build` to check if the website builds without errors.
- **NA** I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by ovflowd** [comment]
Can you attach a screenshot of an example?

**Comment by AugustinMauroy** [comment]
@ovflowd  here you have a record. don't forget you have the preview ;) 

https://github.com/nodejs/nodejs.org/assets/97875033/fe888e28-92ab-4fc3-91c4-942b634a97b6

**Review by ovflowd — APPROVED** [review]

**Review by mikeesto — APPROVED** [review]
I wouldn't mind the second tab being "ESM" instead - perhaps more recognisable?

**Review by aymen94 — APPROVED** [review]

**Comment by ovflowd** [comment]
> I wouldn't mind the second tab being "ESM" instead - perhaps more recognisable?

I guess it's because on our docs we write "MJS", but I guess ESM would be more friendly for newcomers indeed

**Pull request merged**
