### PR TITLE
Chore(events): Proposal add content for nodejs events

### PR DESCRIPTION
**Pull request by AugustinMauroy**
## Description of **Proposal**

I propose to add area/section for our past/upcoming events.

Feat add:

- Component for home page (old design)
- Component to display something about new events (new design follow Figma design system)

TODO:

- new component need to support small screen

Thing we can add :

- JSON with `date`, `title`, `description`, `link`. 
Do using `JsonLink` component
- Events page, should contain futur event + link for summit repo + link for travel fund

IF we want to provide more picture we can take here:

- [OpenJS Collab Summit 2023](https://www.flickr.com/photos/linuxfoundation/albums/72177720307939302)
- [Node+JS Interactive 2019](https://www.flickr.com/photos/linuxfoundation/albums/72157712187942248)
- [Node+JS Interactive 2018](https://www.flickr.com/photos/linuxfoundation/albums/72157702447591635)

## Related Issues

No related issue _(if it's need to talk about this idea I will open one)_

### Check List

- [X] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [X] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [X] I have run `npx turbo format` to ensure the code follows the style guide.
- [X] I have run `npx turbo test` to check if all tests are passing, and/or `npx turbo test:snapshot` to update snapshots if I created and/or updated React Components.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by ovflowd — CHANGES_REQUESTED** [review]
I would have appreciated if you could have opened a feature request issue beforehand so we could discuss about this feature before simply opening a PR. Since this is a considerable change on what sort of content we show on our website.

Honestly, I don't think the Node.js Website should have information about past events that are **related** to Node.js, even if organised by the Foundation. It makes more sense for the Foundation to have their past events. The LF Events Website will already show past events.

I'm against the change of adding these new "Events" section because this is not the scope of the Website and does not bring any sort of value, IMHO.

- Yet, I think if you open a separate PR updating only the content of the existing "Collab Summit" page with some changes like past editions and some of the promotional content, that might be fitting.
- Note that I don't think that adding an embed video of the Collab Summit Welcome session is fitting here.
- I also believe an Issue should be opened here before a PR as we don't want to add more content to the legacy website layout.

**Comment by ovflowd** [comment]
I'm closing this PR as we've stated already that drastic content/design changes are not permitted during this period of website redesign transition.

@AugustinMauroy please open an issue with your ideas. I appreciate your contribution, but it is misplaced and non-communicative.

**Comment by AugustinMauroy** [comment]
i will open issue.

**Comment by ovflowd** [comment]
Thanks!

**Pull request closed without merging**
