### PR TITLE
feat(mastodon.tsx): replace old mastodon icon with new icon

### PR DESCRIPTION
**Pull request by liberaldev**
## Description

Replace the old logo of the mastodon with the new logo.

## Validation

스크린샷 2024-06-23 225129

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by mikeesto — APPROVED** [review]
LGTM, thank you

**Review by aymen94 — APPROVED** [review]

**Comment by AugustinMauroy** [comment]
For your information https://joinmastodon.org/en/branding

**Review by AugustinMauroy — APPROVED** [review]
LGMT !
Thanks for your first contribution !

**Review by shanpriyan — APPROVED** [review]

**Comment by bmuenzenmeyer** [comment]
This PR will need to be rebased or recreated now that https://github.com/nodejs/nodejs.org/pull/6850 merged.

**Comment by mikeesto** [comment]
I've rebased this in the interests of getting it merged soon

It looks like the UI change will need to be approved in Chromatic

**Pull request merged**
