### PR TITLE
fix: Correct redirect for security

### LINKED ISSUE #5621: Wrong redirect for https://nodejs.org/en/security/
### URL:

https://nodejs.org/en/security/

### Browser Name:

Edge

### Browser Version:

115.0.1901.200

### Operating System:

Windows 11 22H2 22621.2134

### How to reproduce the issue:

Go to https://nodejs.org/en/security/, either directly or via the link in e.g. https://nodejs.org/en/blog/vulnerability/august-2023-security-releases. 

This is currently redirecting to https://github.com/nodejs/release#release-schedule which is incorrect and it should instead redirect to https://github.com/nodejs/node/blob/HEAD/SECURITY.md#security. See previous discussion in https://github.com/nodejs/nodejs.org/issues/5601.

### PR DESCRIPTION
**Pull request by richardlau**
## Description

Corrected where https://nodejs.org/en/security/ gets redirected to.

## Related Issues

Fixes: https://github.com/nodejs/nodejs.org/issues/5621
Refs: https://github.com/nodejs/nodejs.org/issues/5601

### Check List

- [ ] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [ ] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [ ] I have run `npx turbo format` to ensure the code follows the style guide.
- [ ] I have run `npx turbo test` to check if all tests are passing, and/or `npx turbo test:snapshot` to update snapshots if I created and/or updated React Components.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by ovflowd — APPROVED** [review]
LGTM! I did a little typo over here.

**Comment by ovflowd** [comment]
@richardlau prettier is complaining about the file, can you run `npm run prettier:fix` locally?

**Comment by richardlau** [comment]
> @richardlau prettier is complaining about the file, can you run `npm run prettier:fix` locally?

Not right now -- I did this PR in a web browser and not on my work computer.

**Comment by ovflowd** [comment]
> > @richardlau prettier is complaining about the file, can you run `npm run prettier:fix` locally?
> 
> Not right now -- I did this PR in a web browser and not on my work computer.

You can use Codespaces, or simply https://github.dev/nodejs/nodejs.org/tree/richardlau-fix-security-rewrite (I've just done that for you!)

**Comment by bmuenzenmeyer** [comment]
merging this as a hotfix

**Pull request merged**
