### PR TITLE
chore: remove engines field from package.json

### PR DESCRIPTION
**Pull request by TKDev7**
Is this required?

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [ ] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [ ] I have run `npx turbo format` to ensure the code follows the style guide.
- [ ] I have run `npx turbo test` to check if all tests are passing.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by AugustinMauroy — APPROVED** [review]
LGTM thanks for you first contribution 🎉

**Comment by AugustinMauroy** [comment]
@ovflowd have you access to see what is the problème with Vercel ?

**Comment by ovflowd** [comment]
Why you dont check Vercel Status Website? :)

**Comment by TKDev7** [comment]
Looks like Vercel is having issues https://www.vercel-status.com/

**Comment by AugustinMauroy** [comment]
> Why you dont check Vercel Status Website? :)

oh I just discovered that 😅

and my first idea is "what why it's fail? Vercel take care about this ?"

**Comment by ljharb** [comment]
I'm confused; why would you want to remove this? the `engines` field makes it explicit what versions of node the project can run on.

**Comment by ovflowd** [comment]
> I'm confused; why would you want to remove this? the `engines` field makes it explicit what versions of node the project can run on.

Now I noticed what this PR is about. Wholeheartedly agree with @ljharb. We added the engines field exactly because we only support said versions.

**Comment by TKDev7** [comment]
@ljharb Doesn’t it only work when you have engine-strict set to true in your .npmrc?

**Comment by ljharb** [comment]
@MrHBS it gives you a warning regardless, and either way it's human documentation. No package.json should *ever* omit `engines`, ever.

**Comment by TKDev7** [comment]
Well I saw this project lacked the flag in their .npmrc so I found this field redundant. Closing this since you all happen to disagree.

**Comment by TKDev7** [comment]
Btw, I could be mistaken, shouldn’t it be >=18 without the v?

**Comment by ljharb** [comment]
Both are valid; see `npx semver -c '>= v18'` vs `npx semver -c '>= 18'`

**Comment by TKDev7** [comment]
@ljharb Since it is simple enough, would you want me to open a PR to add the engine-strict flag?

**Comment by ljharb** [comment]
That will break installs if anything in the graph has mis-set its engines field, so no. It’s best to treat the engines field as advisory for your graph.

**Pull request closed without merging**
