### PR TITLE
Update previous-releases.mdx

### LINKED ISSUE #6669: Release schedule too difficult to find
Every time I try to find the release schedule page on the current site I get frustrated and give up. It used to be prominent on the homepage. Now, I haven't a clue where to find it.

Monosnap Node js - Vivaldi 2024-04-23 21-58-13

### PR DESCRIPTION
**Pull request by srl295**
## Description

per [discussion](https://openjs-foundation.slack.com/archives/C019Y2T6STH/p1714147592632439?thread_ts=1714146718.007219&cid=C019Y2T6STH)

> We can update the title of the "Previous Releases" to be "Node.js Releases"

## Validation

verify titles are changed

## Related Issues

- none yet

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npm run format` to ensure the code follows the style guide.
- [x] I have run `npm run test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by srl295** [comment]
image

**Comment by theoludwig** [comment]
Related issue #6669

**Review by theoludwig — COMMENTED** [review]
Mostly LGTM.

Except, if we rename it to "Node.js Releases", we should probably also rename the page? From `/about/previous-releases` to `/about/releases` (or similar).

**Comment by ovflowd** [comment]
> Mostly LGTM.
> 
> 
> 
> Except, if we rename it to "Node.js Releases", we should probably also rename the page? From `/about/previous-releases` to `/about/releases` (or similar).

If we rename the link we break a lot of pages. Im fine renaming it although we need a redirect ;)

**Comment by srl295** [comment]
> > Mostly LGTM.
> > 
> > 
> > 
> > Except, if we rename it to "Node.js Releases", we should probably also rename the page? From `/about/previous-releases` to `/about/releases` (or similar).
> 
> If we rename the link we break a lot of pages. Im fine renaming it although we need a redirect ;)

I'm not sure how to redirect best. Could one of you update the pr? Or have that as a follow on? This already improved things.

**Comment by AugustinMauroy** [comment]
IMHO [package-manager](https://github.com/nodejs/nodejs.org/tree/main/pages/en/download/package-manager), [prebuilt-binaries](https://github.com/nodejs/nodejs.org/tree/main/pages/en/download/prebuilt-binaries) and [source-code](https://github.com/nodejs/nodejs.org/tree/main/pages/en/download/source-code) can receive mention of "previous releases"

**Comment by srl295** [comment]
> IMHO [package-manager](https://github.com/nodejs/nodejs.org/tree/main/pages/en/download/package-manager), [prebuilt-binaries](https://github.com/nodejs/nodejs.org/tree/main/pages/en/download/prebuilt-binaries) and [source-code](https://github.com/nodejs/nodejs.org/tree/main/pages/en/download/source-code) can receive mention of "previous releases"

sounds like it should become a component?

**Comment by AugustinMauroy** [comment]
> sounds like it should become a component?

I didn't get what you want to do.

**Review by bmuenzenmeyer — DISMISSED** [review]
blocking this explicitly until a redirect is in place - i can guarantee it will break stuff without

**Comment by srl295** [comment]
> blocking this explicitly until a redirect is in place - i can guarantee it will break stuff without

How does this break? It doesn't rename pages.

**Comment by theoludwig** [comment]
The renaming can be done on a follow up PR.

**Review by ovflowd — APPROVED** [review]
LGTM!

**Review by AugustinMauroy — APPROVED** [review]
LGTM !

**Comment by AugustinMauroy** [comment]
if you can change heading level it's can be cool 

Capture d’écran 2024-04-30 à 11 36 36

**Comment by ovflowd** [comment]
> if you can change heading level it's can be cool
> 
> Capture d’écran 2024-04-30 à 11 36 36

Not related to this PR let's do it as a follow-up

**Pull request merged**
