### PR TITLE
chore: Use ES6 to write functions

### PR DESCRIPTION
**Pull request by ghost**
~~The 'json.js' file isn't referred, so remove it.~~

Use ES6 to write functions for 'm.read' and 'Object.keys.forEach' in 'build.js'.

### CODE REVIEW

**Review by ZYSzys — COMMENTED** [review]
Not sure exactly, maybe it's used to replace this 
https://github.com/nodejs/nodejs.org/commit/bee3f0da3c8cb2e31bd50c2cb20bdceac991fc7c#diff-efd59cd1bdc5c9ac6d0eaa368f1e149fL164 ?

**Comment by fhemberger** [comment]
@ZYSzys Yes, you're right. But I can't remember where we needed the `json` Markdown helper in the first place … 🤔

**Comment by ghost** [comment]
So this file shouldn't be removed? Well……I didn't find anywhere to refer…… XD

**Comment by richardlau** [comment]
> 
> 
> So this file shouldn't be removed? Well……I didn't find anywhere to refer…… XD

It's indirectly referenced: 
https://github.com/nodejs/nodejs.org/blob/2ca6decd1312eb2a4b99e701bf328747ffbed082/build.js#L158-L161

**Comment by ghost** [comment]
Thanks all! I've changed the topic to another submit :)

**Review by ZYSzys — APPROVED** [review]

**Pull request merged**
