### PR TITLE
Remove source/schedule.json

### LINKED ISSUE #2767: Remove source/schedule.json?
@Trott @rvagg since the deployment command always runs this, is there any reason for us to keep the file in the repository?

### PR DESCRIPTION
**Pull request by XhmikosR**
This file is grabbed on build time for production.

Just add a `preserve` script for local development.

Fixes #2767 

@nodejs/website 

BTW we could probably remove the `serve` script and use `npm start` only, since right now `npm start` just calls `serve`. It just needs some doc updates to reflect this later.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Hmm, actually we need the same script for `build` and `build:deploy`

**Comment by XhmikosR** [comment]
Alright, I added 2 approaches. Let me know which one you prefer. I also changed `build:deploy` to call the `build` script to reduce duplication.

The only thing that we might need to do is document that `curl` is needed to be installed and in `PATH`. Even Windows 10 has it, and *nix should also have it.

**Comment by AyushG3112** [comment]
Note that this does impact offline `serve`s.

**Comment by XhmikosR** [comment]
Well, of course :)

But as far as I see it

1. either we keep updating the file manually
2. have it as a prehook or something
3. this patch
4. live with it being outdated

The same applies for source/versions.json, but versions.json isn't used in build time AFAICT.

**Review by aymen94 — APPROVED** [review]

**Comment by Trott** [comment]
@XhmikosR Is this ready to land in your opinion?

**Comment by XhmikosR** [comment]
It is ready AFAICT, we just need to decide which of the two ways to go with.

Also do keep in mind that this will require an internet connection to develop. I don't consider this an issue, but there might be cases this could cause trouble for some people.

**Review by 3imed-jaberi — APPROVED** [review]

**Comment by XhmikosR** [comment]
I'm gonna close this since we haven't come to an agreement. I will push my fork's branch to the upstream repo in case we need it later.

**Pull request closed without merging**
