### PR TITLE
tools: remove PPC BE from release blog template

### PR DESCRIPTION
**Pull request by MylesBorins**
It is no longer an officially supported binary type

/cc @mhdawson

### CODE REVIEW

**Review by refack — APPROVED** [review]

**Review by daxlab — APPROVED** [review]

**Comment by mhdawson** [comment]
My one concern is that this will mean it does not show up for 4.X and 6.X LTS releases where it is still supported.  Is there a way we can have it only apply to versions 8.X and higher ?

**Comment by fhemberger** [comment]
Agreeing with @mdawson, different approach:

```diff
--- a/scripts/helpers/downloads.js
+++ b/scripts/helpers/downloads.js
@@ -77,6 +77,8 @@ const postMergeDownloads = [
   }
 ]

+const latestDownloads = postMergeDownloads.filter(download => download.title !== 'Linux PPC BE 64-bit Binary')
+
 // v0.x of Node.js
 const legacyDownloads = [
   {
@@ -135,6 +137,12 @@ function resolveUrl (item, version) {
 }

 module.exports = (version) => {
-  const downloads = semver.satisfies(version, '>= 1.0.0') ? postMergeDownloads : legacyDownloads
+  let downloads = latestDownloads
+  if (semver.satisfies(version, '< 8.0.0')) {
+    downloads = postMergeDownloads
+  }
+  if (semver.satisfies(version, '< 1.0.0')) {
+    downloads = legacyDownloads
+  }
   return downloads.map((item) => resolveUrl(item, version))
 }
```

**Comment by gibfahn** [comment]
@fhemberger 's version LGTM.

**Comment by MylesBorins** [comment]
I'm on vacation until the 7th, please feel free to update this PR or close it and open a new one

New version lgtm

**Comment by fhemberger** [comment]
Landed with changes, thanks everybody!

**Comment by mhdawson** [comment]
@fhemberger thanks :).  Just catching up after the holidays and this looks good.

**Pull request merged**
