### PR TITLE
fix typo in simple-profiling.md

### PR DESCRIPTION
**Pull request by meixg**
Check if the username exists, "400" will be back.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by MaledongGit** [comment]
@meixg: Thanks for your 1st great contribution!

**Comment by ghost** [comment]
@meixg: Sorry by mistake, I found the real logic is: If the user name Exists, a 400 error will be back. So this cannot be as a commit and I've reverted it back to what it used to be.

**Comment by meixg** [comment]
> @meixg: Sorry by mistake, I found the real logic is: If the user name Exists, a 400 error will be back. So this cannot be as a commit and I've reverted it back to what it used to be.

there are two api, newUser and auth.

newUser should be 'If the user name Exists, a 400 error will be back.'

auth should be 'if the user name **not** exists, a 400 error will be back.'

**Comment by ghost** [comment]
@meixg: Ah....Thanks!

And it seems you've missed the other files of translations...I've fixed them totally.

**Comment by ghost** [comment]
@meixg : Thanks for your good catch, and here's my fix for it, you can approve it if free to have a review.

**Pull request merged**
