### PR TITLE
Fix sed command line in "Diagnostics - Flame Graphs" guide

### PR DESCRIPTION
**Pull request by kazarmy**
This pr fixes the sed command line used for perf file cleanup by enabling Extended Regular Expressions (ERE) syntax, so that the first sed script (that deletes lines containing "` __libc_start`", "` LazyCompile `" etc.) works. The alternative to enabling ERE syntax is to escape `(`, `|`, `)` and `?` which is less elegant.

### CODE REVIEW

**Comment by nschonni** [comment]
Ping @nodejs/diagnostics

**Comment by kazarmy** [comment]
Hi, it's been more than a week. You can verify this fix yourself using `diff -u` on before/after perf files to see whether lines containing ` __libc_start| LazyCompile | v8::internal::| Builtin:| Stub:| LoadIC:|\[unknown\]| LoadPolymorphicIC:` are actually deleted.

**Comment by ovflowd** [comment]
I can confirm that this works as intended. @kazarmy sorry for the extremely slow reply, feel free to rebase this PR and I would more than happy approve and merge it :)

But yet, @nodejs/diagnostics if y'all want to have a word here

**Comment by ovflowd** [comment]
I can confirm that this works as intended. @kazarmy sorry for the extremely slow reply, feel free to rebase this PR and I would more than happy approve and merge it :)

But yet, @nodejs/diagnostics if y'all want to have a word here

**Comment by kazarmy** [comment]
> @kazarmy sorry for the extremely slow reply

No problem ... better late than never :)

> feel free to rebase this PR

Ok done

**Comment by tony-go** [comment]
I didn't have time to test it at the moment. I'll try to do it this week.

**Review by RafaelGSS — APPROVED** [review]

**Pull request merged**
