### PR TITLE
Add localization resources

### PR DESCRIPTION
**Pull request by ghost**
I'll just start adding localization stuff to make this happen. The file I added is an altered version of the one found in the nodejs/iojs.org repo, which is changed to reflect the new localization repos and accommodate to the new file structure.

If I missed anything, let me know, since I still need to actually look at how the website itself works :smile:

### CODE REVIEW

**Comment by bnb** [comment]
Are you still working on this? If so, I think we should restart the list on the base translation file - I don't think we want/need all the io.js ones (correct me if I'm wrong!).

**Comment by bnb** [comment]
Do you want me to modify this once it is accepted, or do you want me to comment on it as-is? The former would probably be better in terms of modularity of issues.

**Comment by mikeal** [comment]
I say we merge it, although we're going to have to update most of those links soon since the locale groups are going through name changes.

**Comment by ghost** [comment]
@mikeal Fair enough, I wasn't too sure on how to include those there.

**Comment by outsideris** [comment]
You missed some repos for localization.

```
[iojs-ar](https://github.com/nodejs/iojs-ar)
[iojs-bg](https://github.com/nodejs/iojs-bg)
[nodejs-ko](https://github.com/nodejs/nodejs-ko)
[iojs-ms](https://github.com/nodejs/iojs-ms)
[nodejs-ta](https://github.com/nodejs/nodejs-ta)
```

**Comment by fhemberger** [comment]
LGTM, please add the groups @outsideris mentioned and we're good to go.

**Comment by ghost** [comment]
Real quick, what country exactly is `nodejs-ta`? I couldn't find anything.

**Comment by fhemberger** [comment]
@sup: Not a country, it's the language Tamil: https://en.wikipedia.org/wiki/Tamil_language

**Comment by ghost** [comment]
Alright, it should be good.

**Comment by fhemberger** [comment]
Great, thanks!

**Pull request merged**
