### PR TITLE
id, zh-CN: localize some files

### PR DESCRIPTION
**Pull request by ovflowd**
Update and add new translations for Indonesian, the Simplified Chinese.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Approved for the Simplified Chinese

**Comment by ovflowd** [comment]
Sadly issue with MDX is still happening 😢 

@MaledongGit could you fix the MDX issues directly on this branch if you don't mind? 🙇

**Comment by ghost** [comment]
@ovflowd : This is a protected version, I cannot sign in and submit.....:(

**Comment by ovflowd** [comment]
@MaledongGit afaik you should be able to bypass the "rules", but I can also fix it myself.

**Comment by ghost** [comment]
> @MaledongGit afaik you should be able to bypass the "rules", but I can also fix it myself.

For more: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#about-branch-protection-rules

According to the Docs, it seems I'm not the owner of the branch unless someone adds me to the **[custom rules](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-peoples-access-to-your-organization-with-roles/managing-custom-repository-roles-for-an-organization)** to avoid the "protected version" so that I can submit into the branch directly.

Can u help me to add me there, or any other ways I didn't find out?

**Pull request merged**
