### PR TITLE
Updated bylaws

### PR DESCRIPTION
**Pull request by mikeal**
The board voted last week to guarantee a Gold Level director if there are Gold Members.

This PR has the new bylaws. I'm keeping it in docx because that's how our lawyer manages it and it will be easier to reconcile and find diffs than exporting it to PDF before we publish it.

### CODE REVIEW

**Review by ryanmurakami — APPROVED** [review]
LGTM

**Comment by williamkapke** [comment]
How about we offer a link in both formats then? It is far easier to pop it open in the browser (PDF) than download it and open it.

Truly- I'd rather things were converted to markdown and committed to git for history diffs.
... which is what I'll be doing to diff this anyhow.

**Comment by mikeal** [comment]
@williamkapke If we could get the lawyers to use GitHub I'd be the happiest person in the world. Unfortunately I don't see that happening any time soon :(

**Comment by Fishrock123** [comment]
I'd prefer to also keep a `.pdf`. Docx seems less accessible.

**Comment by williamkapke** [comment]
This will fix #1051

**Comment by fhemberger** [comment]
-1 on DOCX.

Please provide a PDF version as well. We can check in both formats, but the PDF should be linked on the page.

**Review by fhemberger — CHANGES_REQUESTED** [review]
-1 on DOCX.

Please provide a PDF version as well. We can check in both formats, but the PDF should be linked on the page.

**Review by fhemberger — APPROVED** [review]

**Comment by fhemberger** [comment]
@williamkapke @mikeal I converted the .docx to .pdf - if you're okay with the change, this PR can be merged.

**Review by williamkapke — CHANGES_REQUESTED** [review]
These need more updates.

**Comment by williamkapke** [comment]
Sorry- I forgot this PR was open still.

See: https://github.com/nodejs/board/issues/53

**Comment by ghost** [comment]
I'd prefer to also keep a .pdf.

**Comment by williamkapke** [comment]
A markdown version now exists that is identical to the PDF version currently linked on the website. PRs have been opened to bring this MD version up-to-date.

https://github.com/nodejs/board/blob/master/by-laws.md

Ya'll can consider if we want to point to that instead of a PDF version.

**Comment by mikeal** [comment]
> Ya'll can consider if we want to point to that instead of a PDF version.

Yes Please!!!

**Comment by fhemberger** [comment]
Should we link directly to https://github.com/nodejs/board/blob/master/by-laws.md to avoid having two copies, or add the Markdown file to the website?

**Comment by williamkapke** [comment]
@fhemberger I think we should just link to the markdown file in the board repo.

**Comment by fhemberger** [comment]
@williamkapke @mikeal Updated the link, I think we're good to go.

**Review by williamkapke — APPROVED** [review]
Excellent!

**Review by amandeepmittal — APPROVED** [review]

**Pull request merged**
