### PR TITLE
Add WSL to list of install options

### PR DESCRIPTION
**Pull request by mattwojo**
Discussion about this here: #2684

### CODE REVIEW

**Comment by mattwojo** [comment]
Discussion about this here: https://github.com/nodejs/nodejs.org/issues/2684

**Review by MylesBorins — APPROVED** [review]
LGTM

**Comment by MylesBorins** [comment]
One though... the instructions listed here show how to setup Windows Subsystem Linux and then point towards using nvm

https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2#install-nvm-nodejs-and-npm

Do we want to include this documentation when it is a bit of a duplication?

**Comment by Trott** [comment]
@nodejs/platform-windows @nodejs/website This could use a few more eyes. It's a pretty simple change, but I don't have any WSL expertise so someone else indicating that this is a good idea (or that it's not a good idea) would be great.

**Comment by XhmikosR** [comment]
I'm on Windows but I don't use WSL so I don't have a personal opinion. But since the link points to Microsoft's own article, it should be OK.

**Comment by nschonni** [comment]
:-1: for the reasons on the linked issue. I'm also not sure where this link would show up when being added to the JSON file.

**Comment by Trott** [comment]
Yeah, without a corresponding string in a layout file somewhere, I'm not sure what this accomplishes.

**Comment by Trott** [comment]
Thanks for the PR, @mattwojo! I'm going to close this, but feel free to comment or re-open if you think that's being hasty.

**Comment by mattwojo** [comment]
re-open

**Pull request closed without merging**
