### PR TITLE
Node.js 10.0.0 Release Post

### PR DESCRIPTION
**Pull request by jasnell**
PR-URL: https://github.com/nodejs/node/pull/19091

### CODE REVIEW

**Comment by tniessen** [comment]
Was the removal of `package-lock.json` intentional?

**Comment by jasnell** [comment]
I'm editing the package-lock update out of the commit

**Comment by jasnell** [comment]
typed the wrong command when adding ;-)

**Comment by jasnell** [comment]
Fixed :-)

**Pull request merged**
