### PR TITLE
update schedule.json

### PR DESCRIPTION
**Pull request by ghost**
1. According to our plan in https://nodejs.org/en/about/releases/, we've now published the 13th version of Nodejs, add this to the schedule for the maintance.

2. Add the missing coding name for v12.

### CODE REVIEW

**Review by csabapalfi — APPROVED** [review]

**Review by osk2 — APPROVED** [review]

**Comment by Trott** [comment]
Looks good to me but I never even noticed this file before (that I can remember anyway) so I'll leave the actual approving to others (which has already happened anyway).

**Comment by XhmikosR** [comment]
IMO this should be autogenerated somehow. Unfortunately, I don't have the time to do it myself.

**Comment by Trott** [comment]
> IMO this should be autogenerated somehow. Unfortunately, I don't have the time to do it myself.

Maybe open an issue and label it appropriately as `help wanted` and/or `good first contribution`? Then we can land this as-is but not lose the recommendation you're making.

**Comment by XhmikosR** [comment]
Oops sorry, I meant it for #2758

**Comment by nschonni** [comment]
Should the build just curl this file from https://github.com/nodejs/Release/blob/master/schedule.json instead of keeping a separate copy?

**Comment by ghost** [comment]
@nschonni: Not sure yet, but according to your description, it seems this file here is duplicated?
@nodejs/release: It seems this file has been defined in the https://github.com/nodejs/Release/blob/master/schedule.json, so do we have to maintain this copy here? Just for a confirm.
If you think this file can be removed, I'll remove it.

**Comment by richardlau** [comment]
I think the file in the repository is a placeholder that gets overridden during build by `load-schedule` (called by `deploy`):
https://github.com/nodejs/nodejs.org/blob/575a47ec75132585404c2f19bd80a084405f723a/package.json#L12-L14 (see https://github.com/nodejs/nodejs.org/pull/1890)

**Comment by XhmikosR** [comment]
Can't we remove the folder and the file completely?

**Comment by ghost** [comment]
> I think the file in the repository is a placeholder that gets overridden during build by `load-schedule` (called by `deploy`):
> https://github.com/nodejs/nodejs.org/blob/575a47ec75132585404c2f19bd80a084405f723a/package.json#L12-L14
> 
> (see #1890)

So this file should be totally removed, or just run the script to update the file, just like what I submitted?

**Review by aymen94 — APPROVED** [review]

**Comment by XhmikosR** [comment]
This patch is moot since this is overwritten on build time. We should instead see if we can just remove the folder and the file.

**Pull request closed without merging**
