### PR TITLE
Add CodeQL Action

### PR DESCRIPTION
**Pull request by XhmikosR**
- [ ] See if everyone's OK with the cron job
- [ ] Tackle the errors

About this error: https://github.com/nodejs/nodejs.org/security/code-scanning/1?query=ref%3Arefs%2Fpull%2F4315%2Fmerge, I still do not get why we need this client side. I'm pretty sure I expressed my objection in the relevant PR, but due to lack of time, I couldn't spend more time then.

Does anybody recall why we need this client side and why we don't generate the Edit on GitHub links on build time?

EDIT: I see now it was done #3971. I still don't quite get what the issue was and why we can't fix it on build time...

### CODE REVIEW

**Comment by Trott** [comment]
> Does anybody recall why we need this client side and why we don't generate the Edit on GitHub links on build time?

I agree that there's no evident reason for it to be client side and not done at build time. If you want to move it to a build step, I'd 👍 that.

**Comment by XhmikosR** [comment]
TBH I was hoping someone else would make the changes since I didn't really follow them and I don't have a lot of time this period :/

**Comment by mohammadjnoor** [comment]
@mohammadnoor

**Comment by mohammadjnoor** [comment]
> @mohammadjnoor @XhmikosR []()
```

**Comment by mohammadjnoor** [comment]
@mohammadjnoor @XhmikosR @

**Comment by mohammadjnoor** [comment]
> - [ ] See if everyone's OK with the cron job
> - [ ] Tackle the errors
> 
> About this error: https://github.com/nodejs/nodejs.org/security/code-scanning/1?query=ref%3Arefs%2Fpull%2F4315%2Fmerge, I still do not get why we need this client side. I'm pretty sure I expressed my objection in the relevant PR, but due to lack of time, I couldn't spend more time then.
> 
> Does anybody recall why we need this client side and why we don't generate the Edit on GitHub links on build time?
> 
> EDIT: I see now it was done #3971. I still don't quite get what the issue was and why we can't fix it on build time...

@mohammadjnoor

**Comment by mohammadjnoor** [comment]
@mohammadjnoor @XhmikosR @@nodejs-crowdin

**Comment by MaledongGit** [comment]
@XhmikosR：Sorry for delaying so much and here's the fix for you to have a review.

**Comment by MaledongGit** [comment]
For the 1st HTML invalid error：This isn't checking HTML's safety, so should we ignore it?

**Review by ghost — APPROVED** [review]
LGTM for me

**Comment by ghost** [comment]
This alert won't accept the input from the browser, and anyway, it will convert each word splitted by '-', so it cannot be a risk here. I ignored it and merge it.

**Comment by Trott** [comment]
> This alert won't accept the input from the browser, and anyway, it will convert each word splitted by '-', so it cannot be a risk here. I ignored it and merge it.

We're now going to get that alert on every pull request, aren't we?

**Comment by XhmikosR** [comment]
Not if it's ignored in the repository security tab.

**Pull request merged**
