### PR TITLE
remove summaries

### PR DESCRIPTION
**Pull request by Trott**
Because our blog posts are mostly only release announcements trying
to have summaries probably isn't that useful. The summaries also
sometimes get misrendered in small ways (as is the case for the
latest-as-of-this-writing summary for the 17.6.0 release).

### CODE REVIEW

**Comment by Trott** [comment]
Before: 
image

After: 
image

**Comment by Trott** [comment]
I'm on the fence with this one. I like that it simplifies our build pipeline a bit. I think the pages *look* better with the summaries, but I'm not sure they are any better functionally. Maybe they are.

**Comment by DerekNonGeneric** [comment]
Please leave the commit hashes.

**Comment by Trott** [comment]
> Please leave the commit hashes.

Why?

**Comment by DerekNonGeneric** [comment]
They look better imo, but do as you wish.

It seems nicer for people who want to see what went on, but if that's also in the individual blog posts themselves, then I don't really see a problem.

**Review by nschonni — APPROVED** [review]
This will also be able to fix https://github.com/nodejs/nodejs.org/issues/4361

**Comment by DerekNonGeneric** [comment]
> This will also be able to fix https://github.com/nodejs/nodejs.org/issues/4361

Welp, maybe @Trott wants to add [fixes syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to the commit message? Or is that bug more complicated?

**Comment by Trott** [comment]
> Welp, maybe @Trott wants to add [fixes syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to the commit message? Or is that bug more complicated?

This won't quite fix it. Once this lands, it can be fixed with a subsequent PR that re-enables link-checking.

**Comment by DerekNonGeneric** [comment]
> Once this lands, it can be fixed with a subsequent PR that re-enables link-checking.

I must have missed when link-checking was disabled/removed (guess that was being handled by [`vnu-jar`](https://www.npmjs.com/package/vnu-jar)), but would imagine that that would not be too difficult to add as a follow-on PR and would gladly make such a PR to help move this along.

<details>

As you likely know, nowadays, there are so many ways people do link-checking, but not sure what would be ideal for this particular repository. I have seen some really good ways of doing it, and the way that I liked the most would probably not be appropriate for this repository since it involves using [Perl](https://www.perl.org/) for pre-deployment checking or the links [w3c/link-checker](https://github.com/w3c/link-checker) &mdash; feel free to read up more about it at on [their documentation page](https://dev.w3.org/perl/modules/W3C/LinkChecker/docs/checklink).

I have not done extensive research into its usage, but maybe its online service version may be a potentially good solution (it seems to not be functional at the moment).

A cursory look at other issues in this repo regarding link-checking only turned up #2865 &mdash; I also found a [Metalsmith Plugin](https://www.npmjs.com/package/@fidian/metalsmith-broken-link-checker) recently published to npm that could be a viable solution.

</details>

I wonder how it should be done here? Are there better ideas that have been discussed in the past that would help move this PR along? I have not found any others.

**Comment by Trott** [comment]
> I wonder how it should be done here? Are there better ideas that have been discussed in the past that would help move this PR along? I have not found any others.

I believe we used linkinator in a GitHub Action workflow.

**Pull request merged**
