### PR TITLE
fix: merged js logos and fixed svgs

### PR DESCRIPTION
**Pull request by ovflowd**
This PR merges all the Node.js Logo variants in one file (and differentiates them by using different exports).

This PR also standardized the "Design System" Storybook Paths.

Finally, this PR fixes numerous SVGs by making them one-liners to avoid using extra network with line breaks.

### CODE REVIEW

**Comment by ovflowd** [comment]
cc @nodejs/nodejs-website for fast-tracking. As these are trivial changes

**Comment by bmuenzenmeyer** [comment]
some of the newer issues reference `components/__design__/text.stories.tsx` - so we will have to resolve where those go. perhap news files for each (list, anchor, inline code...) but `text` seemed convenient there

**Comment by ovflowd** [comment]
> some of the newer issues reference `components/__design__/text.stories.tsx` - so we will have to resolve where those go. perhap news files for each (list, anchor, inline code...) but `text` seemed convenient there

I rather have them all on the same File but as different exports, as I've done with the logos

**Review by bmuenzenmeyer — APPROVED** [review]
makes sense to me. thanks for this cleanup. 

as a retro: we should have synced on how to structure this for GHC, but all in all it worked without too much trouble!

**Comment by ovflowd** [comment]
> makes sense to me. thanks for this cleanup.
> 
> as a retro: we should have synced on how to structure this for GHC, but all in all it worked without too much trouble!

I agree, next time we should better sync this.

**Pull request merged**
