### PR TITLE
Blog: v14.0.0 release post

### PR DESCRIPTION
**Pull request by BethGriggs**
Refs: https://github.com/nodejs/node/pull/32181

### CODE REVIEW

**Comment by BethGriggs** [comment]
Hmm, 15minutes is longer than usual for the website to update - is it possible to check the state or  force a redeploy? @nodejs/build maybe?

**Comment by sam-github** [comment]
Its up now, but IIRC, it used to be just minutes before deploying. It was long enough for the last sec announcement, that I just left and checked the next morning.

I wonder if some of the caching changes recently made it slower? cc: @rvagg

**Comment by richardlau** [comment]
GitHub itself is having issues at the moment which could be a contributing factor.

**Comment by richardlau** [comment]
The tail from the webhook log (https://nodejs.org/github-webhook.log) seems to indicate it hasn't been triggered for/picked up the changes from this PR:

```
Sun Apr 19 2020 15:34:06 GMT+0000 (Coordinated Universal Time)
Took 137643 ms
stdout: build-site.sh already running
event="push", match="ref == "refs/heads/master" && repository.full_name == "nodejs/nodejs.org"", exec="/home/nodejs/build-site.sh nodejs"
Tue Apr 21 2020 15:02:06 GMT+0000 (Coordinated Universal Time)
Took 22 ms
stdout: build-site.sh already running
event="push", match="ref == "refs/heads/master" && repository.full_name == "nodejs/nodejs.org"", exec="/home/nodejs/build-site.sh nodejs"
Tue Apr 21 2020 15:02:06 GMT+0000 (Coordinated Universal Time)
Took 11 ms
```

**Comment by richardlau** [comment]
The tail from the webhook log (https://nodejs.org/github-webhook.log) seems to indicate it hasn't been triggered for/picked up the changes from this PR:

```
Sun Apr 19 2020 15:34:06 GMT+0000 (Coordinated Universal Time)
Took 137643 ms
stdout: build-site.sh already running
event="push", match="ref == "refs/heads/master" && repository.full_name == "nodejs/nodejs.org"", exec="/home/nodejs/build-site.sh nodejs"
Tue Apr 21 2020 15:02:06 GMT+0000 (Coordinated Universal Time)
Took 22 ms
stdout: build-site.sh already running
event="push", match="ref == "refs/heads/master" && repository.full_name == "nodejs/nodejs.org"", exec="/home/nodejs/build-site.sh nodejs"
Tue Apr 21 2020 15:02:06 GMT+0000 (Coordinated Universal Time)
Took 11 ms
```

**Comment by nschonni** [comment]
If you have access to the box, you can try restarting the hook https://github.com/nodejs/build/issues/2123#issuecomment-570987532

**Comment by nschonni** [comment]
There is also https://github.com/nodejs/nodejs.org/issues/3018 if anyone is feeling ambitious

**Comment by rvagg** [comment]
We have extended the CDN purge from job so that could be a partial explanation for the slower deploy. I think you can expect up to 30 minutes now for cloudflare to refresh.
Although the webhook log should still be showing an update. I guess this got sorted out since the post is visible now?

**Pull request merged**
