### PR TITLE
Added green hex logo svg

### LINKED ISSUE #25: Add Green Hex Logo SVG
Add the green Hex Logo to the site assets. 

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

image

> from the [Figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=337-7897&mode=dev)

> displaying all. This issue only adds the green one.

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

Make sure that `npm ci` completes for you in a terminal pointing to your fork. If it doesn't or you aren't sure, ask a mentor.

---

#### Where to add the file

Site assets are found at https://github.com/nodejs/nodejs.org/tree/main/public/static/images/logos. 

- Add the file into this directory _on your fork_

#### Adding the file

This file is an SVG, which means it is represented as text.

Create a new file in the `public/static/images/logos` directory, called `hex-green.svg`

Paste the below contents into the new file and save.

```
<svg width="63" height="77" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_337_7895)"><path d="M33.31 6.401a3.366 3.366 0 0 0-3.332 0L2.476 22.28C1.43 22.866.843 23.977.843 25.152v31.82c0 1.176.653 2.287 1.633 2.875l27.502 15.877a3.367 3.367 0 0 0 3.331 0l27.503-15.877c1.045-.588 1.633-1.7 1.633-2.875v-31.82a3.404 3.404 0 0 0-1.633-2.874L33.31 6.4Z" fill="url(#paint0_linear_337_7895)"/><path d="M60.877 22.279 33.244 6.4a4.533 4.533 0 0 0-.85-.326L1.5 59c.261.327.673.804 1 1l27.478 15.725c.784.457 1.698.588 2.548.327l29.07-53.186a2.043 2.043 0 0 0-.72-.587Z" fill="url(#paint1_linear_337_7895)"/><path d="m29.063.586-.392.196h.523l-.13-.196Z" fill="url(#paint2_linear_337_7895)"/><path d="M60.809 59.848c.784-.458 1.491-1.315 1.491-2.348L32.196 6.01c-.784-.131-1.633-.066-2.352.391L2.408 22.213 32 76.183c.392-.066.85-.197 1.241-.393L60.81 59.848Z" fill="url(#paint3_linear_337_7895)"/></g><defs><linearGradient id="paint0_linear_337_7895" x1="42.844" y1="18.226" x2="17.971" y2="68.959" gradientUnits="userSpaceOnUse"><stop stop-color="#3F873F"/><stop offset=".33" stop-color="#3F8B3D"/><stop offset=".637" stop-color="#3E9638"/><stop offset=".934" stop-color="#3DA92E"/><stop offset="1" stop-color="#3DAE2B"/></linearGradient><linearGradient id="paint1_linear_337_7895" x1="27.464" y1="44.779" x2="97.246" y2="-6.77" gradientUnits="userSpaceOnUse"><stop offset=".138" stop-color="#3F873F"/><stop offset=".402" stop-color="#52A044"/><stop offset=".713" stop-color="#64B749"/><stop offset=".908" stop-color="#6ABF4B"/></linearGradient><linearGradient id="paint2_linear_337_7895" x1="-.166" y1=".663" x2="63.473" y2=".663" gradientUnits="userSpaceOnUse"><stop offset=".092" stop-color="#6ABF4B"/><stop offset=".287" stop-color="#64B749"/><stop offset=".598" stop-color="#52A044"/><stop offset=".862" stop-color="#3F873F"/></linearGradient><linearGradient id="paint3_linear_337_7895" x1="-.165" y1="41.053" x2="63.473" y2="41.053" gradientUnits="userSpaceOnUse"><stop offset=".092" stop-color="#6ABF4B"/><stop offset=".287" stop-color="#64B749"/><stop offset=".598" stop-color="#52A044"/><stop offset=".862" stop-color="#3F873F"/></linearGradient><clipPath id="clip0_337_7895"><path fill="#fff" d="M0 .5h63v76H0z"/></clipPath></defs></svg>
```

#### Adding a Storybook story to preview the file

Use [Storybook](https://storybook.js.org/) to preview the new logo.

Add a file called `hex-logos.stories.tsx` to the `components/__design__` directory. If this file already exists, open it instead.

We want to create a file that looks like this, eventually, for this and the other logos (separate stories)

```tsx
import Image from 'next/image';
import type { Meta as MetaObj, StoryObj } from '@storybook/react';

export const HexLogos: StoryObj = {};

export default {
  title: 'Design System/Logos',
  component: () => {
    return (
    <div>
      <div>
        <Image
            src={`/static/images/logos/hex-white.svg`}
            alt="Node.js"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src={`/static/images/logos/hex-green.svg`}
            alt="Node.js"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src={`/static/images/logos/hex-black.svg`}
            alt="Node.js"
            width={64}
            height={64}
          />
      </div>
    </div>
  )},
} as MetaObj;
```

> Only add the `Image` for the logo you added.

#### Running Storybook

In a terminal, run `npm run storybook`.

Then, in a browser, go to http://localhost:6006/?path=/story/design-system-logos--hex-logos and you should see the file you added.

<details><summary>Preview</summary>

</details>

#### Submitting the changes

[Submit a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) back to the main repository.

### PR DESCRIPTION
**Pull request by Pooja-Codes**
## Description

Added the Green Hex SVG logo file and added a Storybook story to preview the file.

## Validation

Varified via `npm run storybook`  and previewed the added Green Hex Logo SVG.

## Related Issues

Fixes [#25](https://github.com/bmuenzenmeyer/nodejs.org/issues/25)

### Check List

Followed the below checklist.

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
Good job 👍. But you forgot/not yet added the other hexagons.

**Comment by Pooja-Codes** [comment]
> Good job 👍. But you forgot/not yet added the other hexagons.

Correct! I am responsible for green and black hex logos only! There is another PR [#5864](https://github.com/nodejs/nodejs.org/pull/5864) for the black hex logo by me!

**Review by AugustinMauroy — APPROVED** [review]
Ok, LGMT thanks for your first contribution !

**Review by ovflowd — COMMENTED** [review]
I have the feeling some of the changes of this PR belong to this PR? https://github.com/nodejs/nodejs.org/pull/5857 (Maybe we should split the changes?)

**Comment by Pooja-Codes** [comment]
> I have the feeling some of the changes of this PR belong to this PR? #5857 (Maybe we should split the changes?)

I agree! I fixed that and now this PR includes only two required file modifications!

Please review it again. Thank you! @ovflowd 😊

**Comment by bmuenzenmeyer** [comment]
changing the target branch to a feature, instead of `main`, so i can resolve some merge conflicts

**Pull request merged**
