### PR TITLE
Remove unused Prism CSS files.

### PR DESCRIPTION
**Pull request by XhmikosR**
These aren't used, probably left for historical reasons?

### CODE REVIEW

**Comment by XhmikosR** [comment]
Can we get this and some of the other CSS PRs moving?

https://github.com/nodejs/nodejs.org/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+author%3AXhmikosR+css

and

https://github.com/nodejs/nodejs.org/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+author%3AXhmikosR+stylus

I'd like to clean up the CSS and finish with the Sass move.

**Comment by XhmikosR** [comment]
Ping

**Review by Trott — APPROVED** [review]
LGTM but wouldn't mind a few more sets of eyes to make sure I'm not missing anything. @nodejs/website

**Review by bnb — APPROVED** [review]
Served the site locally, everything seemed to work to me. Relatively trivial revert if something is actually broken. :shipit:

**Review by csabapalfi — APPROVED** [review]

**Review by aymen94 — APPROVED** [review]

**Pull request merged**
