### PR TITLE
Blog: add #28630 to "notable" section of v12.7.0 release

### PR DESCRIPTION
**Pull request by boneskull**
@targos I don't know if it's typical to update this after-the-fact, but here it is in case you want to merge it.  I think it's worth drawing attention to, anyway, because it will break people using the experimental "reports" API.

### CODE REVIEW

**Comment by targos** [comment]
Could you revert the other changes? LGTM otherwise

**Comment by boneskull** [comment]
oops. blame prettier

**Comment by boneskull** [comment]
@targos this is updated

**Comment by Trott** [comment]
LGTM but maybe include what it used to be? It's returning an object instead of....

**Review by Trott — APPROVED** [review]

**Comment by targos** [comment]
I updated the release entry: https://github.com/nodejs/node/releases/tag/v12.7.0
I modified the text to "Modify process.report.getReport() to return an Object instead of a JSON string"

**Comment by boneskull** [comment]
LGTM

**Review by lpinca — APPROVED** [review]

**Pull request merged**
