### PR TITLE
Translate file 'security.md' to Arabic

### PR DESCRIPTION
**Pull request by celyes**
Translated the file `security.md` to Arabic.

@InterstellarClub

### CODE REVIEW

**Review by ouadie-lahdioui — APPROVED** [review]
LGTM 👍

**Review by Aissaoui-Ahmed — APPROVED** [review]
great !

**Comment by ghost** [comment]
@celyes：Thanks for your new contribution!

**Comment by celyes** [comment]
Thank you, everyone!
@Maledong @Aissaoui-Ahmed @ouadie-lahdioui

**Pull request merged**
