### PR TITLE
Fix FR about page

### PR DESCRIPTION
**Pull request by ghost**
Remove repetitions and change a couple of words to use the technical idiom in French.

## Description
I am French (so a native french speaker)
Reading the About page in French, I found a lot of repetitions, maybe due to a commit/merge issue. I also took the freedom to change a couple of words for their more appropriate french technical idiom (child process > processus fils).

## Validation

This only a text update so I assume it should not break anything. Not knowing how the whole NPM stuff works, and not having it installed, I could not run all the tests of the checklist.

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [ ] I have run `npm run format` to ensure the code follows the style guide.
- [ ] I have run `npm run test` to check if all tests are passing.
- [ ] I have run `npx turbo build` to check if the website builds without errors.
- [ ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by TenzDelek** [comment]
i dont think we are suppose to make changes in localization here. it is done through crowdin

**Comment by ghost** [comment]
> i dont think we are suppose to make changes in localization here. it is done through crowdin

I clicked the link "Edit this page" from the website... and ended on the GitHub editor from where I made my edits.
You may want to remove the link if it's not the correct method to update the page.

**Comment by ghost** [comment]
The french about page still needs to be fixed.

**Comment by AugustinMauroy** [comment]
> The french about page still needs to be fixed.

First of all, it's not the term “fix” that should be used, but “correct”, because fix is the term for a bug and correct for typography/grammar.

As mentioned above and on the `translation.md` document, all questions concerning translation are answered on crowdin. So if you think there's something to revise, say so there.

**Pull request closed without merging**
