### PR TITLE
remove Node Interactive banner from home

### PR DESCRIPTION
**Pull request by edsadr**
Removing Node Interactive banner, this change revert the home page state to: https://web.archive.org/web/20160316165108/https://nodejs.org/en/

### CODE REVIEW

**Comment by lpinca** [comment]
You might also want to remove https://github.com/nodejs/nodejs.org/blob/master/layouts/css/page-modules/_interactive-banner.styl and https://github.com/nodejs/nodejs.org/blob/master/layouts/css/base.styl#L83

**Comment by edsadr** [comment]
@lpinca sorry forgot about those, just updated the PR

**Review by lpinca — APPROVED** [review]

**Comment by lpinca** [comment]
👍

**Comment by lpinca** [comment]
Maybe also the relevant images under /static/images can be removed, not sure.

**Comment by edsadr** [comment]
I was thinking about that too, but images could be indexed and this will generate a 404... so I would say let's keep them...

**Comment by lpinca** [comment]
Yup but we already removed the old ones, like the old Amsterdam background etc. ¯\_(ツ)_/¯

**Comment by edsadr** [comment]
@lpinca images removed then, still looks like a policy about deleting assets should be set

**Comment by lpinca** [comment]
@edsadr I agree.

**Comment by outsideris** [comment]
LGTM

**Pull request merged**
