### PR TITLE
Update code-and-learn.md

### PR DESCRIPTION
**Pull request by hari-govind**
Move completed Code + Learn event from upcoming section to past

### CODE REVIEW

**Comment by fhemberger** [comment]
Thanks, could you please also update the page in the other languages as well?

**Comment by hari-govind** [comment]
Sure!

**Comment by hari-govind** [comment]
I've updated the page in other languages(for which the page was available) as well.

**Review by willin — APPROVED** [review]
LGTM

**Review by ZYSzys — APPROVED** [review]

**Comment by fhemberger** [comment]
Great, thank you!

**Pull request merged**
