### PR TITLE
Fix the links for non-English alphabets when anchors generated

### PR DESCRIPTION
**Pull request by ghost**
Consider that some special characters (not included in the 26 English alphabets) are ignored by md file's anchor when generated. We have to change the anchor link.

Take this as an example：'SmartOS 和 illumos', the '和' doesn't belong to an English character, so it's ignored and the generated anchor would be '#smartos-illumos' instead of '#smartos-and-illumos'.

This is the HOT fix for that. What I did now is to use the pure HTML instead of md's "##" to force the "a href"'s link to keep it the same as that in English version.

PS：For Japanese, it seems they've noticed the anchor problem so their anchor name isn't the same as the English version. What I do is just to change the title to make it the same as what we can see in the category.

【Before Fix】
image

### CODE REVIEW

**Comment by ghost** [comment]
@nodejs/nodejs-cn：Please have a review for that.

**Comment by ghost** [comment]
@nodejs/localization：Kindly tip, please notice whether your own specific language has the same problem :)

**Comment by Maledong** [comment]
If this fix is OK, I'll try to fix other languages.

**Comment by yous** [comment]
Did these commits disappear from master? The commits of #2026 are also gone.

**Comment by Maledong** [comment]
Yes, two are missing. And there's another submit, it doesn't show in the history of "Pull Requests" but in the "Comments":

[cid:955c3764-1497-4023-9356-aecc761f2df0]

In the history of Pull Request:
[cid:c1a35dad-941c-4936-86bb-26df57118dcf]

So can you fix this? I don't think it is related to the forcely push, because it used to be good with me. And what's more——the latest submission also missed, and it's NOT a forcely submit 😃
________________________________
发件人: Chayoung You <notifications@github.com>
发送时间: 2019年2月3日 18:02
收件人: nodejs/nodejs.org
抄送: Maledong; State change
主题: Re: [nodejs/nodejs.org] Fix the links for non-English alphabets when anchors generated (#2028)


Did these commits disappeared from master? The commits of #2026<https://github.com/nodejs/nodejs.org/pull/2026> are also gone.

**Comment by yous** [comment]
I don't see the images, they only show `[cid:...]`. Can you re-post them on GitHub?

**Comment by ghost** [comment]
@yous：No problem, I've re-submitted and everything goes fine !

**Pull request merged**
