### PR TITLE
Translate in French the guides (index and getting started)

### PR DESCRIPTION
**Pull request by tisma95**
### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing, and/or `npx turbo test:snapshot` to update snapshots if I created and/or updated React Components.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by mikeesto — CHANGES_REQUESTED** [review]
Hi! Appreciate you taking the time to contribute and translate. However, the translations for this site happen on 
Crowdin. You are welcome to join and be part of that process there - please see here: https://github.com/nodejs/nodejs.org/blob/main/TRANSLATION.md

**Comment by ovflowd** [comment]
Closing as this work should be done on Crowdin. Please read `TRANSLATING.md`

**Comment by tisma95** [comment]
Hi @ovflowd , @mikeesto,

I requested on Crowdin to join the translation team for French but I didn't receive the approval it is why I translated on GitHub. Could you accept my request if you have the right ?

Thanks 😊

**Comment by ovflowd** [comment]
@tisma95 could you request it again? And what username did you use there?

**Comment by tisma95** [comment]
Hi @ovflowd,

On Crowdin my username is tisma95 (Ismaël Maurice).
See in following images the view which I had
Capture d’écran 202
![Capture d’écran 2023-07-18 à 17 59 09
3-07-18 à 17 59 01](https://github.com/nodejs/nodejs.org/assets/55036198/e127b1c6-13c5-4830-b5f2-c5854cc5a141)

Thanks

**Comment by AugustinMauroy** [comment]
Hey 👋 ! 
I’m augustin the French proofreader. If you need any help contact me.
Also i will proofread your job.
Thanks for joining French translation.

**Comment by ovflowd** [comment]
@AugustinMauroy I didn't approve their invitation yet.

> Also i will proofread your job.

Not sure this sounds correct.... I guess you meant "Also I will proofread your work/translations"

**Comment by tisma95** [comment]
Hi @ovflowd,
My request to join the translation has been accepted for nodes-website. The translation of api-docs is it in the same project I   guess the translation of APIs is in another project api-docs should you also accept my request there.

Thanks

**Comment by ovflowd** [comment]
Sorry, API docs are not translatable. And will not be.

**Comment by tisma95** [comment]
Ok Thanks I will remove remove it in my request.

**Pull request closed without merging**
