### PR TITLE
fix: Replace implicit blockquotes

### PR DESCRIPTION
**Pull request by nschonni**
This render correctly, but are flagged by remark-lint.
Sometimes they may be unitentional

### CODE REVIEW

**Comment by XhmikosR** [comment]
I assume this rule is enabled in the upcoming remark-lint config and also upstream?

**Comment by XhmikosR** [comment]
Also, is there any markdownlint rule we should have enabled? Maybe https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md027---multiple-spaces-after-blockquote-symbol or md0028?

**Comment by nschonni** [comment]
No, and that's already enabled

**Comment by XhmikosR** [comment]
We should really stick to one base config until we make the switch. It gets too complicated.

**Review by XhmikosR — APPROVED** [review]

**Review by alexandrtovmach — APPROVED** [review]

**Pull request merged**
