### PR TITLE
docs(learn): Migrate diagnostics user journey from guide to learn section

### PR DESCRIPTION
**Pull request by paulobelucci**
## Description

This PR migrates the legacy guide "Diagnostics User Journey" to the learn section, it also remove the link [Diagnostics - User Journey] from the guide section and finally it fix some broken links.
- link removed -> https://github.com/v8/sampling-heap-profiler - `error 404`

## Validation
Navigation
image

Section
User Journey
image

User Jouney -> Memory
image

User Jouney -> Live Debugging
image

User Jouney -> Poor Performance
image

## Related Issues

#6222 

### Check List

- [X] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [X] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [X] I have run `npx turbo format` to ensure the code follows the style guide.
- [X] I have run `npx turbo test` to check if all tests are passing.
- [X] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
[this part](https://github.com/nodejs/nodejs.org/blob/e92aa8ae7b4b12eadf31ce8fd5eda1120c937247/pages/en/learn/diagnostics/live-debugging/index.md?plain=1#L8-L11) can be remove because on new design we have ToC 

> to run website with new design use `turbo serve:redesign`
**BTW** redesign isn't finish so it's why it's not default dev env

we should also try to put everything in the nav bar to make it easier to navigate.  

**Importante Note:** [on guides link](https://nodejs-org-git-fork-paulobelucci-migrate-diagnost-426d10-openjs.vercel.app/en/guides/diagnostics/poor-performance) we have 404 we need to do something

in a couple of places I've seen snipet code in the files you're migrating, you'd have to change the language from `javascript` to `js` to simplify all that.

**Comment by AugustinMauroy** [comment]
Note for website team before validating we should ask review nodejs/diagnostics 'cause it's original writer and "expert"

**Comment by paulobelucci** [comment]
> [this part](https://github.com/nodejs/nodejs.org/blob/e92aa8ae7b4b12eadf31ce8fd5eda1120c937247/pages/en/learn/diagnostics/live-debugging/index.md?plain=1#L8-L11) can be remove because on new design we have ToC
> 
> > to run website with new design use `turbo serve:redesign`
> > **BTW** redesign isn't finish so it's why it's not default dev env
> 
> we should also try to put everything in the nav bar to make it easier to navigate.
> 
> **Importante Note:** [on guides link](https://nodejs-org-git-fork-paulobelucci-migrate-diagnost-426d10-openjs.vercel.app/en/guides/diagnostics/poor-performance) we have 404 we need to do something
> 
> in a couple of places I've seen snipet code in the files you're migrating, you'd have to change the language from `javascript` to `js` to simplify all that.

Hi there! thank you for the feedback. 😃 

**I made some changes:**

- move the internal links at the user journey section to the navigation bar.

image

- redirect the call for the /guide -> /en/guide to avoid the 404 error

Ps.: I didn't find the snippet codes you mentioned in the files I migrated in this PR. Can you please give the name of the files, so I can make the fix. 👍 

Again thank you so much for the support. 😃

**Comment by paulobelucci** [comment]
> Note for website team before validating we should ask review nodejs/diagnostics 'cause it's original writer and "expert"

Can you please help me on how to ask for review to a specific team?
It seens that I have no access to ask for it.
image

Thank you 😃

**Comment by AugustinMauroy** [comment]
> Ps.: I didn't find the snippet codes you mentioned in the files I migrated in this PR. Can you please give the name of the files, so I can make the fix. 👍

my bad, these files you have modified for links but not migrated sorry

**Comment by AugustinMauroy** [comment]
On "Memory" and "Poor Performance" there are an kind of toc written in the markdown you can remove it 'cause it's on layout.

**Comment by paulobelucci** [comment]
> On "Memory" and "Poor Performance" there are an kind of toc written in the markdown you can remove it 'cause it's on layout.

done ✅ 

image

image

**Comment by AugustinMauroy** [comment]
@paulobelucci you are not obligated to send image we have [preview link](https://github.com/nodejs/nodejs.org/pull/6291#issuecomment-1931120363)

**Review by AugustinMauroy — APPROVED** [review]
LGTM ! I have nothing more to say.

**Review by ovflowd — APPROVED** [review]
Let's get this merged :)

Thanks for the awesome amount of work put in here!

**Comment by paulobelucci** [comment]
> Let's get this merged :)
> 
> Thanks for the awesome amount of work put in here!

Nice! Thank you @AugustinMauroy for the help. 👍

**Pull request merged**
