### PR TITLE
it: translation locale/it/get-involved/node-meetups.md

### PR DESCRIPTION
**Pull request by alepolidori**

### CODE REVIEW

**Comment by nschonni** [comment]
Ping @nodejs/nodejs-it

**Review by aymen94 — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Approved.

Just want to know whether we need to translate "node-meetups.md"? Because this is always changing, and maybe different kinds of people will add dynamically information into the page...?

@nodejs/community-committee @nodejs/website

**Comment by nschonni** [comment]
@alepolidori sorry about the delay, it looks like I can't update the branch and I can't merge without it. Can you rebase or pull the latest changes into your branch?

**Comment by XhmikosR** [comment]
@alepolidori closing as per @nschonni's comment above; feel free to make a new PR after you rebase.

**Pull request closed without merging**
