### PR TITLE
moved events into its own page due to the growing list

### PR DESCRIPTION
**Pull request by iancrowther**
- created event page
- added documentation outlining how it was done

### CODE REVIEW

**Comment by fhemberger** [comment]
Can you please have a look at the merge conflicts? I think it's because of #140.

**Comment by iancrowther** [comment]
Yep np

**Comment by fhemberger** [comment]
@iancrowther Can you please look into this? I'd like to merge it as soon as the conflicts are resolved.

**Comment by fhemberger** [comment]
Conflicts resolved and merged through #243.

**Pull request closed without merging**
