### PR TITLE
Fix: use MDX format to render tables

### LINKED ISSUE #6002: Table is not rendered
### URL:

https://nodejs.org/en/docs/guides/debugging-getting-started#command-line-options

### Browser Name:

Mozilla Firefox

### Browser Version:

118.0.1

### Operating System:

Fedora Linux 37 (Workstation Edition)

### How to reproduce the issue:

1. What I did.

I opened the documentation page at "https://nodejs.org/en/docs/guides/debugging-getting-started#command-line-options".

2. What I expected to get.

The options table properly rendered.

3. What I actually got.

The options table was missing.

### PR DESCRIPTION
**Pull request by victorsptt**
## Description

Changed file extensions to enable processing in the MDX format with the remark-gfm plugin. This is required to render the HTML tables.
Adapted the Markdown comments and HTML attributes to match the MDX format.
The tbody and thead HTML elements were added explicitly to make the HTML in the server match the one in the client.
No documentaton text was changed.

## Validation

I checked that the pages are rendering properly.

Screenshot from 2023-10-15 15-50-14

## Related Issues

Fixes #6002

### Check List

- [ x ] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [ x ] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [ x ] I have run `npx turbo format` to ensure the code follows the style guide.
- [ x ] I have run `npx turbo test` to check if all tests are passing.
- [ x ] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by ovflowd** [comment]
> Changed file extensions to enable processing in the MDX format with the remark-gfm plugin. This is required to render the HTML tables.

This doesn't make any sense. We don't use `remark-gfm`. The table rendering was probably not rendering with default Markdown because it probably had invalid HTML tables.

Neverthless, table should be done with Markdown Tables

I would recommend actually instead of changing these files to MDX to use https://tableconvert.com/html-to-markdown, if possible.

**Comment by ovflowd** [comment]
(Also honestly speaking these pages are all going to be deleted soon and replaced)

**Comment by ovflowd** [comment]
@victorspt are you still interested in fixing this?

**Comment by victorsptt** [comment]
Hi Claudio,
Yes, I am interested.
I will try to finish the fix today.
I will follow your advice to convert the tables from HTML to Markdown.

Em qua., 18 de out. de 2023 12:02, Claudio W ***@***.***>
escreveu:

**Comment by victorsptt** [comment]
From #6002:

> I tried to convert the tables from HTML to Markdown, but they are not rendered.
> 
> Pipe tables are a syntax extension included in GFM, they are not a CommonMark syntax, and @mdx-js/mdx only supports CommonMark by default.

I submitted a new PR with an alternative fix, #6027.

**Pull request closed without merging**
