### PR TITLE
fix: fix example code

### PR DESCRIPTION
**Pull request by ExIxIxS**
## Description

Fixed a mistake in code example on the [page](https://nodejs.org/en/learn/asynchronous-work/understanding-processnexttick)

## Validation
image

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I have run `npx turbo build` to check if the website builds without errors.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Review by araujogui — APPROVED** [review]
LGTM

**Comment by ovflowd** [comment]
People keep making PRs to this specific example, because the output result at times will be different. This is probably the 5th time this example is updated having the output 4 and 3 swapped.

**Comment by ovflowd** [comment]
Closing this, as to be honest, the discrepancy is expected at times. cc @nodejs/collaborators as I'd really like to know the origin of why this happens.

**Comment by lemire** [comment]
@ovflowd The output varies from run to run. You can just add it as a remark (`The exact output may differ.`)


Screenshot 2024-04-03 at 2 00 09 PM

**Comment by ovflowd** [comment]
> @ovflowd The output varies from run to run. You can just add it as a remark (`The exact output may differ.`)
> 
> 
> 
> 
> 
> Screenshot 2024-04-03 at 2 00 09 PM
> 
> 

Mind making a tiny PR? 🙃

**Comment by lemire** [comment]
Sure. I will.

**Pull request closed without merging**
