### PR TITLE
chore: install Storybook addon themes

### PR DESCRIPTION
**Pull request by HinataKah0**
## Description

Install Storybook's addon `@storybook/addon-themes` and setup light & dark mode in Storybook

Followed [this](https://github.com/storybookjs/storybook/blob/next/code/addons/themes/docs/getting-started/tailwind.md) guide
See [this](https://github.com/nodejs/nodejs.org/pull/5781#discussion_r1321595086) comment for context

## Validation

Tested locally using `CrossLink` component

```js
export const Prev: Story = {
  args: {
    direction: 'left',
    text: 'How to install Node.js',
    url: 'https://nodejs.dev/en/learn/how-to-install-nodejs/',
  },
  decorators: [
    Story => (
      <div className="w-[305px]">
        <Story />
      </div>
    ),
  ],
};
```

Screenshot 2023-09-12 at 8 42 16 PM
Screenshot 2023-09-12 at 8 42 33 PM

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `npx turbo lint` to ensure the code follows the style guide. And run `npx turbo lint:fix` to fix the style errors if necessary.
- [x] I have run `npx turbo format` to ensure the code follows the style guide.
- [x] I have run `npx turbo test` to check if all tests are passing.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
should try not to use decorators in stories. And personally theme switch doesn't work on preview.

**Comment by HinataKah0** [comment]
> About decorator usage

It is based on the [collaborator guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#general-guidelines-for-storybooks)
```
If you need to decorate/wrap your Component/Story with a Container/Provider, please use [Storybook Decorators](https://storybook.js.org/docs/react/writing-stories/decorators)
```

> And personally theme switch doesn't work on preview.

Sorry, I don't get it. Which preview are you referring to?
Edit: Are you saying that theme switcher (the component that we will create later) won't work in Storybook preview?

**Review by ovflowd — APPROVED** [review]
LGTM! Clean implementation :)

**Comment by ovflowd** [comment]
I'd like to fast-track this as other PRs would definitely benefit from this trivial change. cc @nodejs/nodejs-website

**Comment by AugustinMauroy** [comment]
I mean we should use theme switching on all stories.

**Review by aymen94 — APPROVED** [review]

**Comment by ovflowd** [comment]
> I mean we should use theme switching on all stories.

This is already what this changeset does. Or so I believe

**Comment by HinataKah0** [comment]
Yes, it changes all stories. You can switch between stories and the themes are the same.

**Comment by ovflowd** [comment]
@HinataKah0 can you run the CI? :)

**Comment by HinataKah0** [comment]
I usually let some time passes before merging
@ovflowd If you think we can merge soon, I am fine with it

**Comment by ovflowd** [comment]
@HinataKah0 Im just asking for you to run the CI pipelines... not to merge the PR

**Comment by HinataKah0** [comment]
My bad :)

**Comment by ovflowd** [comment]
No worries. But if you can please run the CI lol (add the PR label) 😅

**Review by rodion-arr — APPROVED** [review]

**Pull request merged**
