### PR TITLE
fix(i18n): fix typo in translation keys

### LINKED ISSUE #5091: Typo: Translation Keys
### URL:

https://nodejs.org

### Browser Name:

Arc

### Browser Version:

Chromium Engine Version 110.0.5481.177

### Operation System:

MacOS 13.2.1 (22D68)

### How to reproduce the issue:

Hi,

I was looking the new NextJS structure and found two typo issues in translation keys.

1. components.downaloadList.links.shaSums.howToVerify (should be **components.downaloadList.links.shaSums.howToVerify**)
2. componets.header.buttons.toggleLanguage (should be **componets.header.buttons.toggleLanguage**)

### PR DESCRIPTION
**Pull request by EmirBoyaci**
Two i18n keys that includes typo changed

Fixes #5091

### CODE REVIEW

**Review by AugustinMauroy — APPROVED** [review]
LGTM!

**Review by ovflowd — APPROVED** [review]
LGTM! Thank you for your contribution 😄

**Comment by EmirBoyaci** [comment]
> LGTM! Thank you for your contribution 😄

Always! But, do you have any idea why PR checks didn't start? I am asking this because I think you're maintainer, so it should be started.. Isn't it?

**Comment by ovflowd** [comment]
> Always! But, do you have any idea why PR checks didn't start? I am asking this because I think you're maintainer, so it should be started.. Isn't it?

Yeah, sounds like a weird bug. GitHub is not giving me any option to start them 😅 

I wonder why. Let me see if I can force trigger them.

**Comment by ovflowd** [comment]
Hmm, it's not allowing me. Could you re-push the changes? I see that the commit is not verified and we kinda require signed commits.

**Comment by EmirBoyaci** [comment]
> Hmm, it's not allowing me. Could you re-push the changes? I see that the commit is not verified and we kinda require signed commits.

Sure but signed commit requirement is not included in [Contributing Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md). IMHO you should also include it..

**Comment by ovflowd** [comment]
Correct, let me update that.

**Comment by EmirBoyaci** [comment]
@ovflowd could you please check it again? I force pushed signed commit :)

**Comment by EmirBoyaci** [comment]
I was looking for why it is stuck on "Expected — Waiting for status to be reported" stage and found one solution. Unfortunately, the solution did not work. Second force-push was for this trial.

**Comment by EmirBoyaci** [comment]
Ok next solution did not work also. I will not do anything after now XD

**Comment by ovflowd** [comment]
> Ok next solution did not work also. I will not do anything after now XD

Now it worked!

**Comment by EmirBoyaci** [comment]
> > Ok next solution did not work also. I will not do anything after now XD
> 
> 
> 
> Now it worked!
> 
> 

Yea, we got 🟢 also! 🚀

**Pull request merged**
