### PR TITLE
fix(test): dir name

### PR DESCRIPTION
**Pull request by AugustinMauroy**
use `__tests__` not `__test__`

### CODE REVIEW

**Review by ovflowd — APPROVED** [review]

**Review by mikeesto — APPROVED** [review]

**Review by shanpriyan — APPROVED** [review]

**Review by aymen94 — APPROVED** [review]

**Comment by ovflowd** [comment]
@AugustinMauroy your rebase is completely broken, I still recommend you to read docs on how to properly do Git rebasing or I'd recommend you to just cherry-pick commits.

**Comment by AugustinMauroy** [comment]
I will take a look to cherry pick.

**Comment by ovflowd** [comment]
**This PR got accidentally closed because the branch got deleted. Please feel free to reopen the PR.**

**Review by aymen94 — APPROVED** [review]

**Comment by Harkunwar** [comment]
I beleive this test is not needed as it's already captured by storybook.

https://github.com/nodejs/nodejs.org/tree/major/website-redesign/components/Home/NodeFeatures

**Review by Harkunwar — DISMISSED** [review]
Could you please delete the `components/Home/NodeFeatures/__tests__` directory since it's not needed anymore.

**Comment by AugustinMauroy** [comment]
Hey @Harkunwar I don't saw what do you mean.
Can you give more explaining

**Comment by Harkunwar** [comment]
> Hey @Harkunwar I don't saw what do you mean.
> Can you give more explaining

Since we're using Storybook to automatically do Snapshot testing, we don't need to write unit tests in Jest to do them anymore, which is why I said you could delete the test as well as the snapshot. Any component written in storybook will automatically have a snapshot generated instead of a manual test.

**Review by Harkunwar — APPROVED** [review]

**Comment by Harkunwar** [comment]
@ovflowd Are we waiting for anything, should we merge this?

**Comment by AugustinMauroy** [comment]
@Harkunwar I thinks you can merge. Claudio are too busy this week.

**Pull request merged**
