### PR TITLE
Use new logo on website.

### PR DESCRIPTION
**Pull request by mikeal**
Loving this new logo :)

### CODE REVIEW

**Comment by stevemao** [comment]
Related issues: #458 #501 #367
@mikeal Should we update https://github.com/nodejs/nodejs.org/blob/master/static/documents/foundation-visual-guidelines.pdf?

**Comment by rvagg** [comment]
FYI

screen shot 2016-02-19 at 1 56 13 pm

**Comment by fhemberger** [comment]
@mikeal Please use [ImageAlpha](https://pngmini.com/) and [ImageOptim](https://imageoptim.com/) to shrink the file size before adding images. You always tend to add unnecessarily large files to the site.

Updated the image, went from 63KB down to 24KB: 6b49e53.

**Comment by mikeal** [comment]
ya, i always get ahead of myself and checkin giant images. sorry :/

**Comment by silverwind** [comment]
Not sure who updated the org logo on Github, but it has some artifacts which are especially noticeable on dark backgrounds:

artifacts

Also, the hexagon is very slightly cut off at the top.

**Comment by stevemao** [comment]
It looks correct with the default theme. @silverwind are you using https://github.com/StylishThemes/GitHub-Dark? I can see there is a white area on the image though.

**Comment by silverwind** [comment]
Yeah using that style, but the white part is visible on the left too: https://avatars1.githubusercontent.com/u/9950313. I'll see to making fixed version based on the logo in this PR.

**Comment by silverwind** [comment]
Here's a version that's cleanly trimmed and square. Someone please update the org logo!

node-org

By the way, The gradients on the [original source](https://raw.githubusercontent.com/nodejs/nodejs.org/5f3872b4da6a5f429c33e8911fbcc3ee60ce9973/static/images/logos/nodejs-new-white-pantone.png) are not really smooth. Maybe a compression artifact or is it intended?

**Comment by mikeal** [comment]
I just cleaned this up, should look better now.

**Comment by silverwind** [comment]
Looking great, thanks :+1:

f

**Pull request merged**
