### PR TITLE
feat: introduce built-in next.js exports and updated scripts and configs

### PR DESCRIPTION
**Pull request by ovflowd**
This PR simply updates the Next.js configuration/installation and `package.json` scripts to support the new built-in `output: 'exports'` from Next.js

A few other optimizations were done such as:

- `next-sitemap` configuration to be ModuleJS
- `next-istemap` write output to the correct `build` folder for static builds
- updated all `node` imports such as `path` and `fs` to have the `node:` prefix
- updated contribution guidelines and `package.json` scripts

### CODE REVIEW

**Comment by ovflowd** [comment]
FYI @nodejs/website markin this as `fast-track` please give +1 for a quick merge

**Comment by AugustinMauroy** [comment]
Why remove Robot ?

**Comment by ovflowd** [comment]
> Why remove Robot ?

Because it is a generated file. It was committed accidentally a long time ago.

**Comment by AugustinMauroy** [comment]
Ok good, thanks for the clarification !

**Review by Harkunwar — APPROVED** [review]

**Comment by ovflowd** [comment]
We might want to update this PR once https://github.com/iamvishnusankar/next-sitemap/pull/638 gets released on `next-sitemap@4.1.0`

**Pull request merged**
