### PR TITLE
locale/ru: reword phrase about V8 version

### PR DESCRIPTION
**Pull request by mymedia2**

### CODE REVIEW

**Comment by nschonni** [comment]
Ping @nodejs/nodejs-ru

**Review by alexandrtovmach — APPROVED** [review]

**Comment by ghost** [comment]
@mymedia2: Maybe you can update your base branch, otherwise we cannot help to merge your submit.
image

**Comment by mymedia2** [comment]
@MaledongGit rebased to master, thank you for the reminder

**Comment by ghost** [comment]
No. It seems there's no button to click:
I wonder why ....? 
image

**Comment by MaledongGit** [comment]
@mymedia2 : Plz check whether your local project is bad or not. It seems your file cannot work properly :(

image

**Comment by ghost** [comment]
@mymedia2 : Plz check whether you've allowd us to merge or not, and you've allowd us to edit/submit your repository:
image

**Comment by mymedia2** [comment]
@MaledongGit  rebased again.

You were unable to edit that file in my fork, maybe because the "Allow edits by maintainers" checkbox was unset. This was default for me, sorry for that.

"Allow edits by maintainers" is unchecked

**Comment by ghost** [comment]
@mymedia2 : OK, thanks for your contribution!

**Pull request merged**
