### PR TITLE
AR : Fix the bug in debugging-getting-started.md

### PR DESCRIPTION
**Pull request by 3imed-jaberi**

### CODE REVIEW

**Comment by ghost** [comment]
@nodejs/nodejs-ar, Please have a review.

**Comment by ram-you** [comment]
Seems to be correct. For me it's Ok for merge.

**Review by Aissaoui-Ahmed — APPROVED** [review]

**Comment by Aissaoui-Ahmed** [comment]
thank you @3imed-jaberi

**Review by celyes — APPROVED** [review]

**Comment by celyes** [comment]
seems correct. thank you for your contribution @3imed-jaberi

**Pull request merged**
