### PR TITLE
fix: MD004/ul-style

### PR DESCRIPTION
**Pull request by nschonni**
Unordered list style

### CODE REVIEW

**Comment by XhmikosR** [comment]
Is this the same as upstream?

**Comment by nschonni** [comment]
The docs hare primarily asterisks, but it hasn't been normalized on way or the other

**Comment by XhmikosR** [comment]
Alright, it would make sense to make this change upstream and update the remark-lint config too.

**Review by ghost — APPROVED** [review]

**Comment by XhmikosR** [comment]
I'm all for this assuming this is enforced in the upstream Markdown config.

We need to try to be as close to the main repo lint config so that developers coming from there don't need to adapt to yet another config IMO.

**Review by 3imed-jaberi — APPROVED** [review]

**Comment by nschonni** [comment]
Rebased for conflict

**Pull request merged**
