### PR TITLE
chore: point to MDN for arguments object article

### LINKED ISSUE #4384: Formatting mistake at "What is the arguments object?" page
```
myfunc
  .apply(obj, arguments)
  // concat arguments onto the
  .Array.prototype.concat.apply([1, 2, 3], arguments);
```
I think this should be written as:  
```
myfunc.apply(obj, arguments);

// concat arguments onto the
Array.prototype.concat.apply([1, 2, 3], arguments);
```
I don't know what is the meaning of that period on the concat function.

### PR DESCRIPTION
**Pull request by Trott**
Send readers from the arguments object knowledge base article to the MDN
article on the topic. This also removes some sample code that was
broken.

Closes: https://github.com/nodejs/nodejs.org/issues/4384

### CODE REVIEW

**Review by nschonni — APPROVED** [review]

**Comment by lxmarinkovic** [comment]
Hi @Trott , I need to join 18n, but it looks like I need an invite to @nodejs first. Could you help

**Comment by Trott** [comment]
> Hi @Trott , I need to join 18n, but it looks like I need an invite to @nodejs first. Could you help

Why do you say you need to join i18n?

**Comment by lxmarinkovic** [comment]
Hi @Trott  , thank you for the quick reply. I posted an issue
https://github.com/nodejs/i18n/issues/612 with my reasons to join i18n,
and it is mainly because I feel that as a professional  software engineer
that is using this technology for more than ten years,
should use free time to contribute, making it more accessible to the
non-English speaking/writing crowd

Wish you a nice day ahead! :D

**Comment by Trott** [comment]
> Hi @Trott , thank you for the quick reply. I posted an issue [nodejs/i18n#612](https://github.com/nodejs/i18n/issues/612) with my reasons to join i18n, and it is mainly because I feel that as a professional software engineer that is using this technology for more than ten years, should use free time to contribute, making it more accessible to the non-English speaking/writing crowd Wish you a nice day ahead! 🗡️ 

Hi @lxmarinkovic. If you want to create Serbian translations, you can open pull requests against this repository, creating files in `locale/sr`. I'm not sure where things are at with i18n and CrowdIn, but we'll see what people say in that other issue.

**Comment by lxmarinkovic** [comment]
Thank you, @Trott , I'll do that, and also the reason why I would like to become of node.js org is willing to invest some free time in evangelism and education with a Node.js Stockholm meetup group

**Pull request merged**
